### ISSUE TITLE
JavaScript variable not working - issue is due to using old syntax, see new syntax here

### ISSUE THREAD

**Issue by TomAsl50** [kelaberetiv/TagUI#1004]
Hi Ken,

I am new to TagUI. 

I try to test on JS script from the https://www.rpa-sg.org/TagUI-Tips-Techniques/how-to-get-current-date.php and the code as below:

js begin
function formatDate(date) {
    var d = new Date(date),
        mm = '' + (d.getMonth() + 1),
        dd = '' + d.getDate(),
        yy = d.getFullYear();
    return [yy.toString().substr(2,2), (mm>9?'':'0')+mm, (dd>9?'':'0')+dd].join('-');
}
today = formatDate(new Date());
js finish
 
echo "today = "+today

After I run the tagUI, the result does not show the date variable [today], but instead it show "today = "+today

I also try the other reported solution/sample on variables declaration, but turn still the same. One Example below:

js test_number = 456
echo 'test_number - ' test_number

Result: 'test_number - ' test_number

Is my setup wrong? or any parameters need to configure?

Thank you.

**Comment by kensoh** [comment]
Hi @TomAsl50 oh it's because TagUI syntax has changed since then (see below in GitHub home page)
https://github.com/kelaberetiv/TagUI#change-in-syntax-for-echo-dump-write-steps

For better consistency in TagUI steps, you don't need quotation marks now for echo step, and variables are denoted with backticks \`\` - see example below -

```
test_number = 456
echo test_number - `test_number`
```

**Comment by TomAsl50** [comment]
It works now.

Thanks.
