### ISSUE TITLE
Running a database flow within a flow results in file not found error

### ISSUE THREAD

**Issue by whho21** [kelaberetiv/TagUI#1006]
Hi, Sorry if this is not the place to ask this, can you execute a database flow within a flow, e.g.
tagui datatables.tag database.csv
within a .tag file?

When I try to do that, it gets an error as follows:
ERROR - file not found for step tagui datatables.tag database.csv
ERROR - automation aborted due to above

**Comment by ruthtxh** [comment]
Hi @whho21 

Currently we cannot call the datatable directly from a subflow step.

Is your main flow utilising another datatable? If not you can call the datatable when running the main flow, and access the contents of this datatable with your subflow, since subflows can access all variables of the parent flow.

**Comment by whho21** [comment]
Actually, the purpose of not calling the database in the main flow was because I wanted to initialize certain values, like logging in as admin of the website, and then proceeding to handle updating a list of products on the site. That's why I wanted to call the database within a sub flow so it won't have to keep logging in again and again. Is there a way to do this?

**Comment by ruthtxh** [comment]
Hi @whho21 

Yes, you can use the datatable.csv in the mainflow, and do te following so that the login with only be for the first iteration:

```
if `[iteration]` equals to 1
	// login as admin

// url for subsequent steps after login to process individual records
// process individual records
```

Link to some similar use cases:
https://github.com/kelaberetiv/TagUI/issues/1000
https://github.com/aimakerspace/TagUI-Bricks/tree/master/IMDA-ICMS-CITREP#tagui-workflow

**Comment by whho21** [comment]
That's fantastic! Thanks so much!
