### ISSUE TITLE
Using r = some_value in workflow triggers R integration, to ignore 'r =' / 'R =' - done

### ISSUE THREAD

**Issue by Jassherrin** [kelaberetiv/TagUI#1011]
The tagui runs as normal until the excel sheet. There are a bunch of things it needs to copy and it gets stuck coping at the same place. The command prompt shows no error and does not stop the process unless it is ctrl C'ed.

It keeps getting stuck at U15's r = clipboard().

keyboard [ctrl]g

keyboard [ctrl]a[delete]

keyboard U14[enter]

keyboard [ctrl]c

q = clipboard()

keyboard [ctrl]g

keyboard [ctrl]a[delete]

keyboard U15[enter]

keyboard [ctrl]c

r = clipboard()

keyboard [ctrl]g

keyboard [ctrl]a[delete]

keyboard U16[enter]

keyboard [ctrl]c

s = clipboard()

**Comment by kensoh** [comment]
Hi @Jassherrin can you attach the log files in tagui\src\tagui.sikuli here?

The logs will share more info what could have gone wrong. Haven't come across this issue before from users.

**Comment by Jassherrin** [comment]
[tagui.sikuli.zip](https://github.com/kelaberetiv/TagUI/files/6302663/tagui.sikuli.zip)

**Comment by kensoh** [comment]
Hi @Jassherrin from the logs it looks like everything works correctly. It might be [ctrl]c end up killing TagUI because that is the shortcut to kill TagUI if your focus at the moment is on TagUI and not other apps. Will you be able to join the weekly Zoom call this Thursday from 4-5pm? https://github.com/kelaberetiv/TagUI/issues/914 we can look further on the call. I cannot find anything wrong with the logs and your workflow.

```
[tagui] INPUT  - [117] keyboard U15[enter]
[tagui] ACTION - keyboard U15[enter]
[log]  TYPE "U15#ENTER."
[tagui] OUTPUT - [117] SUCCESS

[tagui] INPUT  - [118] keyboard [ctrl]c
[tagui] ACTION - keyboard [ctrl]c
[log] ( Ctrl )  TYPE "c"
[tagui] OUTPUT - [118] SUCCESS

[tagui] FINISH - stopped listening
IDE terminated: returned: 0
```

**Comment by Jassherrin** [comment]
I'll join the zoom call tomorrow. Thanks.

**Comment by Jassherrin** [comment]
Hello could we meet around 4.30 or 5pm?

**Comment by kensoh** [comment]
Hi @Jassherrin 430pm ok, if you join at 445pm ok too.

**Comment by Jassherrin** [comment]
The problem was with the variable r. Changing it fixes the issue.

**Comment by kensoh** [comment]
Thanks Sherrin for closing the issue!

Adding on, yes, `r = some value` will be interpreted by TagUI as trying to run the R integration with `r some commands`

I'll reopen the issue for the time being, and see if we can add some safeguards so that users won't run into this again.

For eg, maybe ignore `r =` or `r=` statements to be R integration commands, since they are more like defining variable.

**Comment by kensoh** [comment]
Above commit fixes this. Users can download the latest copy of TagUI with this fix and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files.

**Comment by kensoh** [comment]
Closing issue, change included in latest packaged release - https://github.com/kelaberetiv/TagUI/releases/tag/v6.46.0
