### ISSUE TITLE
How to get started with TagUI?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1020]
*source - LinkedIn*

**Comment by kensoh** [comment]
My team-mate Ruth is now working on a video course, probably sometime in June she can publish. In the meantime, following are useful resources to get started.

Overview slide deck - https://drive.google.com/file/d/1pltAMzr0MZsttgg1w2ORH3ontR6Q51W9/view

Recent 1h webinar -  https://www.youtube.com/watch?v=hKc4eNBhMws

Usage guide -  https://tagui.readthedocs.io/en/latest/  

Simple examples -  https://github.com/kelaberetiv/TagUI/tree/master/flows/samples

Advance examples - https://github.com/aimakerspace/TagUI-Bricks

Weekly Zoom 1-to-1 (Thursday 4-5pm SGT, UTC+8) -  https://github.com/kelaberetiv/TagUI/issues/914  

Telegram group chat -  https://t.me/rpa_chat

The weekly Zoom meeting and Telegram group chat are especially useful resources if you have any questions to ask. Folks from the community will also share back their experiences. Also, you can also raise an issue on GitHub where so far this year we have been replying within 24h - https://github.com/kelaberetiv/TagUI/issues

**Comment by manuautomatic** [comment]
MacBook-Air-de-Aliro:~ aliro$ ln -sf /Users/aliro/tagui/src/tagui /usr/local/bin/tagui
ln: /usr/local/bin/tagui: Permission denied 
I can't install tagui in Mac  do you help me ?

**Comment by kensoh** [comment]
Hi @manuautomatic can you try with below, maybe need permission to create this shortcut -

```
sudo ln -sf /Users/aliro/tagui/src/tagui /usr/local/bin/tagui
```

**Comment by manuautomatic** [comment]
Gracias por responder. Puse la sintaxis  
sudo ln -sf /Users/aliro/tagui/src/tagui /usr/local/bin/tagui
Aparecio --> Password: 
Puse la contrasena y me sale que no encontro el archivo es extraño porque cuando ejecuto tagui de forma manual sigue la direccion lineas arriba. He logrado instalar y ejecutar la extension de python pero agrega mas texto y quiero poder hacer con el tagui. Estoy intentando automatizar algunos procesos 

Mira cuando hago click manualmente Last login: Thu Jul 22 01:57:58 on ttys000
/Users/aliro/Desktop/tagui/src/tagui ; exit;
MacBook-Air-de-Aliro:~ aliro$ /Users/aliro/Desktop/tagui/src/tagui ; exit;
tagui v5.11: use following options and this syntax to run - ./tagui flow_filename option(s)
.................

**Comment by manuautomatic** [comment]
Thanks for answering. I put the syntax
sudo ln -sf / Users / aliro / tagui / src / tagui / usr / local / bin / tagui
Appeared -> Password:
I put the password and I get that I did not find the file is strange because when I manually execute tagui it follows the direction lines above. I have managed to install and run the python extension but it adds more text and I want to be able to do with the tag. I am trying to automate some processes

Watch when I manually click Last login: Thu Jul 22 01:57:58 on ttys000
/ Users / aliro / Desktop / tagui / src / tagui; exit;
MacBook-Air-de-Aliro: ~ aliro $ / Users / aliro / Desktop / tagui / src / tagui; exit;
tagui v5.11: use following options and this syntax to run - ./tagui flow_filename option (s)
.................

**Comment by manuautomatic** [comment]
I have seen that there is a time when you can have a zoom meeting you have a link

**Comment by manuautomatic** [comment]
Thanks for answering. I put the syntax
sudo ln -sf /Users/aliro/Desktop/tagui/src/ tagui /usr/local/bin/tagui
Appeared -> Password:
I put the password and I get that I did not find the file is strange because when I manually execute tagui it follows the direction lines above. I have managed to install and run the python extension but it adds more text and I want to be able to do with the tag. I am trying to automate some processes

Watch when I manually click Last login: Thu Jul 22 01:57:58 on ttys000
/ Users / aliro / Desktop / tagui / src / tagui; exit;
MacBook-Air-de-Aliro: ~ aliro $ / Users / aliro / Desktop / tagui / src / tagui; exit;
tagui v5.11: use following options and this syntax to run - ./tagui flow_filename option (s) 

I have seen that there is a time when you can have a zoom meeting you have a link

**Comment by manuautomatic** [comment]
then password put   --- > ln: /usr/local/bin/tagui: No such file or directory

**Comment by kensoh** [comment]
Hi @manuautomatic sorry I just saw your message! The Zoom meeting is every Thursday 4-5pm (UTC+8) -

https://github.com/kelaberetiv/TagUI/issues/914

**Comment by kensoh** [comment]
Can you double check your line below? I think you accidentally added an extra space between `/src/` and `tagui`

```
sudo ln -sf /Users/aliro/Desktop/tagui/src/ tagui /usr/local/bin/tagui
```

Try again with -
```
sudo ln -sf /Users/aliro/Desktop/tagui/src/tagui /usr/local/bin/tagui
```

For TagUI in human language version, the download instructions are here. And it should be > v6.46 after you download.

https://tagui.readthedocs.io/en/latest/setup.html

**Comment by kensoh** [comment]
Closing this issue because most of the items in the list are already integrated into the GitHub landing page
