### ISSUE TITLE
Hungarian language issue (broader bug with indentation for other languages) - fixed

### ISSUE THREAD

**Issue by FulopJozsi** [kelaberetiv/TagUI#1030]
[hungarian.csv](https://github.com/kelaberetiv/TagUI/files/6447724/hungarian.csv)

Language (tested in german and hungarian) errors in linux:
tagui 3_conditions.tag 
PHP Notice:  Undefined offset: 2 in tagui/tagui_parse.php on line 104
PHP Notice:  Undefined offset: 3 in tagui/tagui_parse.php on line 104
PHP Notice:  Trying to access array offset on value of type bool in tagui/translate.php on line 53
ERROR - missing indentation for echo animals
ERROR - automation aborted due to above

First 3 line hot fix:
```
sed -i "s/temp_argv2 = \$argv\[2\]/temp_argv2 = isset(\$argv[2]) \? \$argv[2] \: ''/g" tagui/src/tagui_parse.php \
	&& sed -i "s/temp_argv3 = \$argv\[3\]/temp_argv3 = isset(\$argv[3]) \? \$argv[3] \: ''/g" tagui/src/tagui_parse.php \
	&& sed -i "s/language_data\[\$language_count\]\[0\] == ''/language_data\[\$language_count\] === false/g" tagui/src/translate.php
```

But you will need the last two.

**Comment by kensoh** [comment]
Hi @FulopJozsi can you tell me your steps to replicate the error for 3_conditions.tag? It is in English and shouldn't be able to run in another language.

For rclick and dclick these steps are not part of the steps supported for other languages because they are not often used in UI interactions.

**Comment by kensoh** [comment]
Thanks for raising this issue by the way!

**Comment by kensoh** [comment]
Thanks @FulopJozsi, I think you found a bug whether in other languages, when there is indentation it becomes removed during the translation process. I'll work on a fix asap so that you can use it!

Also, the step for echo is not `kiír` but `visszhang` in the Hungarian dictionary file https://github.com/kelaberetiv/TagUI/blob/master/src/languages/hungarian.csv

For `echo` step used for printing output, I used Google translate to provide the `visszhang` translation. Let me know if that should be changed to `kiír`. If yes, let me know if you would like to submit a PR on this change so that you can be added as contributor and be recognised for your contribution for this project. It will show up when people click Contributors on TagUI home page - https://github.com/kelaberetiv/TagUI/graphs/contributors

**Comment by kensoh** [comment]
Hi @FulopJozsi and other users with similar problems using non-English languages, this is now fixed!

Above commit fixes the problem of non-English language workflows that uses indentation for condtions or code blocks etc.

Users can download the latest copy of TagUI from here and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this fix will become part of the packaged zip files.

**Comment by kensoh** [comment]
Adding on, for @FulopJozsi, below is the working Hungarian language workflow. You can change tagui\src\tagui_config.txt the language setting to hungarian (`var tagui_language = 'hungarian';`) and this should work for you. Note that the keywords for echo step and else step that you have typed in your workflow are not valid keywords in the [Hungarian dictionary](https://github.com/kelaberetiv/TagUI/blob/master/src/languages/hungarian.csv) translated by Google. So I have changed below to use the keywords. You can send a PR if you think what you have used is more suitable than the Google translated one. Thank you! 

```
// This flow demonstrates the usage of conditions

// Assign the string 'dog, cat' to the variable 'animals' 
// Assign the number 12 to the variable 'cupcakes'
allatok = 'kutya, macska'
cupcakes = 12

// If the condition is true, then show 'animals' value in the command line output, or else do nothing
ha allatok egyenlő 'kutya, macska'
 visszhang `allatok`

// If the condition is true, then show 'contains dog' and 'another instruction' in command line output
ha allatok tartalmaz 'kutya'
 visszhang tartalmaz kutya
 visszhang másik instrukció

// If the condition is true, then show 'some instructions' in the command line output
// or else check if the second condition is true, then show 'other instructions'
// or else show 'yet other instructions'
some_number = 1
ha some_number egyenlő 1
 visszhang valami instrukció
egyébként ha some_number egyenlő 2
 visszhang más instrukció
más
 visszhang megint valami instrukció

// Other examples of comparisons below work as you expect
// not equals to
// lesser than
// greater than or equals to
```

**Comment by kensoh** [comment]
Also, there is a small translator utility inside tagui\src folder. It can be used to translate any English workflows into another language, or from another language back to English. That means it is possible to translate from 1 language to another language. For eg a Chinese workflow can be translated first into English and then to Hungarian.

Below is general syntax -
`php translate.php filename.tag to/from language`

Below is the example to translate from Chinese to Hungarian - 

```
php translate.php ../flows/samples/8_chineseflow.tag from chinese
php translate.php ../flows/samples/8_chineseflow.tag_translated to hungarian
```

Chinese flow
```
// This flow demonstrates usage of non-English in flows
// To run this, edit tagui/src/tagui_config.txt and
// change the line - var tagui_language = 'english';
// to this line - var tagui_language = 'chinese';

// You can find the full list of translated words for each language in
// tagui/src/languages folder with the language csv files

https://ca.yahoo.com

// Set the output language to chinese
tagui_language = 'chinese'

输入 search-input 为 github
显示 search-input
点击 search-button

等待 2.5秒

回声 完毕
```

Hungarian flow
```
// This flow demonstrates usage of non-English in flows
// To run this, edit tagui/src/tagui_config.txt and
// change the line - var tagui_language = 'english';
// to this line - var tagui_language = 'chinese';

// You can find the full list of translated words for each language in
// tagui/src/languages folder with the language csv files

https://ca.yahoo.com

// Set the output language to chinese
tagui_language = 'chinese'

típus search-input mint github
előadás search-input
kettyenés search-button

várjon 2.5秒

visszhang 完毕

```

Note that only TagUI steps are translated. The actual echo printout of what text to print on the screen will still remain the same as what user specify to print on the screen. For eg above last 2 lines is wait 2.5 seconds and echo finish.

**Comment by FulopJozsi** [comment]
### **Thank you the quick fix!**
So 'visszhang' means 'the sound is reflected', but echo function is to print which means 'kiír' (print out).
Thanks the translator utility, it will be useful.
By the way, I run it in a docker full desktop environment with my own **language correct** https://github.com/kelaberetiv/TagUI/files/6447724/hungarian.csv dictionary. :)
(My native language is the Hungarian)

**Comment by kensoh** [comment]
Thanks @FulopJozsi ! I've updated your Hungarian dictionary into TagUI master. I moved dclick and rclick up in the dictionary so these steps are matched first. Also, your TagUI version doesn't have dclick and rclick in TagUI's main translation engine, above commit adds that. Otherwise I think translating dclick and rclick in Hungarian will not work.

You and other users can download the latest copy of TagUI from here and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

PS - I started working on TagUI project in 2016 and I was staying in Budapest with my wife in Sep-Oct 2016. Some photos of the Impact Hub co-working space which we do our stuffs in the day, home-cooked food, and photos of the beautiful city.

In the next release, this will become part of the packaged zip files. Reopening issue until this gets into the next release.

![20161009_203600](https://user-images.githubusercontent.com/10379601/118079811-6a7a0480-b3eb-11eb-9177-d5dd2ef77f36.jpg)

![20161009_231044](https://user-images.githubusercontent.com/10379601/118079816-6c43c800-b3eb-11eb-82dc-3d03cc0ffab2.jpg)

![20160901_173036](https://user-images.githubusercontent.com/10379601/118079821-6ea62200-b3eb-11eb-8ca2-7e4714622047.jpg)

![20160831_154626](https://user-images.githubusercontent.com/10379601/118079825-6fd74f00-b3eb-11eb-81c9-3f6aca420f47.jpg)

![20160902_213706](https://user-images.githubusercontent.com/10379601/118079829-72d23f80-b3eb-11eb-865f-3e39511f9ca5.jpg)

**Comment by kensoh** [comment]
Closing issue, change included in latest packaged release - https://github.com/kelaberetiv/TagUI/releases/tag/v6.46.0

**Comment by erwinlagu** [comment]
Closed

**Comment by kensoh** [comment]
Yes the change on Hungarian language has been implemented already last year
