### ISSUE TITLE
Read URLs from datatable and open them - see working example using workaround

### ISSUE THREAD

**Issue by camsanjot** [kelaberetiv/TagUI#1031]
When we type in url starting with http in .tag file it opens fine but but if I want to store the urls in .csv file, and open them one after the other how do I do it?

**Comment by kensoh** [comment]
Hi @camsanjot the following link has the solution. Due to a limitation now, there is a need to save the URL to a file and read it and then telling TagUI that your variable is a URL by prefixing with `https://`. Let me know how that goes!

https://github.com/kelaberetiv/TagUI/issues/960#issuecomment-793434201

In the next release, we will try to find a better way for users to do this. I personal find having to use this workaround terrible.
