### ISSUE TITLE
Issue between for and js begin, may be related to the fixed #966 - pending checks

### ISSUE THREAD

**Issue by FooZhiRuiHSC** [kelaberetiv/TagUI#1039]
```
for n from 1 to 100
    some tagui code
js begin
some js code
js finish
```

Above syntax returns an error "mismatch of { and }". Same error occurs even when explicitly declaring curly braces. Was able to get around the issue by parking a wait 1 between the loop and js begin

```
for n from 1 to 100
    some tagui code
wait 1
js begin
some js code
js finish
```

Not sure if issue extends to other scenarios (py begin / py finish, etc). Please check when able.

**Comment by kensoh** [comment]
Hi @FooZhiRuiHSC thanks for raising this! I was not able to replicate and the following works. This may be related to a bug around mismatching {} but has been fixed in issue #966. Can you try if using the patch from https://github.com/kelaberetiv/TagUI/issues/966#issuecomment-798784313 works for you?

This fix will be in the next TagUI release.

```
for n from 1 to 10
    echo `n`
js begin
a = 1
b = 2
c = a + b
js finish
echo `c`
```
```
START - automation started - Tue May 25 2021 09:52:22 GMT+0800 (+08)

1
2
3
4
5
6
7
8
9
10
3

FINISH - automation finished - 0.8s
```
