### ISSUE TITLE
How to attach to an existing Chrome Browser? - not doable unless it's special instance

### ISSUE THREAD

**Issue by DanielCCF** [kelaberetiv/TagUI#1043]

**Comment by DanielCCF** [comment]
> _No description provided._

Hi All! 

I misclicked before, here is the issue:

I am trying to attach to an existing Browser window to do partial automation since the other parts of the process are quite easy to do and 1 time only. To achieve this goal, I need to attach TagUI to an existing Chrome tab, using the DOM to easily do what I need. 

I tried to find a way to do it, but I did not make it. Is this possible to do?

This also refers to an older issue: [https://github.com/kelaberetiv/TagUI/issues/666](https://github.com/kelaberetiv/TagUI/issues/666)

**Comment by kensoh** [comment]
Hi @DanielCCF oh that is not really possible. This is because TagUI needs to open a back door in Chrome through a websocket connection, so that it can control Chrome from backend. And that backdoor can only be opened when the Chrome session is initially launched. So you can't suddenly open the backdoor in an existing Chrome browser.

There are 3 alternative ideas you can consider -

1. try using visual automation to visually automate on the Chrome browser that you are working on. This mode does not require a backdoor to be opened because the automation happens through the frontend of Chrome browser.

2. Add a `live` step in your TagUI script or something like the following, so that you can do all the pre-requisite steps manually before letting the robot take over doing the rest -
```
// set timeout sufficiently long for your manual steps
timeout 900

// wait up to 900 seconds for some element to finally appear as the signal to start the automation
hover element

// set timeout back to default 10 seconds
timeout 10
```
3. There should be a way to launch Chrome with back socket to be used and then let TagUI latch onto it later. But that requires hacking your Chrome shortcut and hacking TagUI runner script. Not recommended unless there are no other ways.

**Comment by DanielCCF** [comment]
Hi @kensoh ! Thanks for your time answering.

The second option is interesting in my case. I'll take a look at it.

Is it possible to create a Chrome Extension that allows us to access the Browser in a mostly secure way? This would be a nice feature.

From my side, this issue can be closed.

**Comment by kensoh** [comment]
Hi Daniel, sure let me know how it goes and if you run into any problem!

Oh I think none of the RPA software companies does it through a Chrome extension. Maybe because of technical limitations or difficulties using that as a good integration channel. So there's no plan for that now in TagUI. However, there is 1 exception of RPA software that is Chrome extension based. Check out https://ui.vision it looks like a great tool and being driven from Chrome extension, though there is a usage limit on the free version.

TagUI has a Chrome extension, but that is mainly for recording web-based workflows and identifying elements -
https://chrome.google.com/webstore/detail/tagui-web-automation/egdllmehgfgjebhlkjmcnhiocfcidnjk?hl=en-GB
