### ISSUE TITLE
How to handle JavaScript alert in TagUI - use computer vision to initiate alert and click

### ISSUE THREAD

**Issue by kalyangadgil** [kelaberetiv/TagUI#1048]
Hello @kensoh 

I am uploading data on website using tagui.
But not able to deal with the javascript alert. Cannot access it using Xpath or any other way.
How can I click button on that alert
please help!!

Thanks
![popupicmr](https://user-images.githubusercontent.com/40426939/120666136-fbec0c00-c4a9-11eb-8af8-2ae970b4ec34.png)

**Comment by kensoh** [comment]
Hi @kalyangadgil oh this is a common scenario, what happens is after clicking a button to trigger this alert, by the website and browser design, the alert will block TagUI from continuing unless user clicks on it. The workaround is to click on the button using computer vision and then click on the OK using computer vision. This way, the automation is done from the OS layer instead of the browser layer, so TagUI will not be blocked from execution until user clicks ok. Something like this -

```
click button_that_will_trigger_the_alert.png
click alert_ok_button.png
```

**Comment by kalyangadgil** [comment]
Hello,

I am trying to use visual automation to check whether alert is present or not on the page.
like this ,

if r.present('images/AlreadyExistSrf_trans.png'):
       print("success")

Following issues I am facing :

1)  even if that alert does not occur , its still going inside IF block and print success.
2)  OR if there is any other alert with different message, still its going inside IF block which is not expected

I tried to implement this 
 https://github.com/kelaberetiv/TagUI/issues/433

![AlreadyExistSrf_trans](https://user-images.githubusercontent.com/40426939/121907619-d8e31700-cd49-11eb-9fe3-f4499620415b.png)

**Comment by kensoh** [comment]
Using present() will do the checking at this instance. If what is you are checking is not there False will be returned.

You may want to try using exist() to check for something up to 10 seconds.

Lastly, the matching is done using computer vision, with some margin of tolerance for noise. If most of the image is the same, it might trigger as True even if it is not exact match. You can try to provided image snapshot as targetted as possible to the text that you are looking for.

**Comment by kensoh** [comment]
Closing for now until further inputs
