### ISSUE TITLE
ERROR - expected token '(' - in live mode, if condition and for loop are not supported

### ISSUE THREAD

**Issue by gilgoldman** [kelaberetiv/TagUI#1050]
Hi Ken!

Any idea why TagUI throws an error when attempting to use an if statement with exist() helper function?
This error appears on live mode as well.
The intended use is to check if an email field exists and if it does exist fill it with the email address.

Happens for other strings as well (if exist("email"), if exist('Log-In'), etc). OS is Ubuntu, TagUI version is the latest (6.14).

Did I misunderstand the syntax, or is there something else going on?

All the best,

Gil

```

if exist(//*[@id="email"])
 type //*[@id="email"] as testy-McTestFace

ERROR - expected token '('


```

**Comment by kensoh** [comment]
Hi Gil,

Above example should be with single quotes like below because it is a function -

```
if exist('//*[@id="email"]')
 type //*[@id="email"] as testy-McTestFace
```

Also, there are a couple of fixes past few months on indentation. You can download the latest copy of TagUI with this and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

Then see if that helps. In the next release, changes in above updated file will become part of the packaged zip files.

PS - lastly, present() can also be used if you don't need to 'test' until the default timeout of 10 seconds but wants a response right away if something is there without waiting for it

**Comment by gilgoldman** [comment]
Hi Ken!

No luck:
```
if exist('//*[@id="email"]')
ERROR - expected token '('
```
Overwriting the old TagUI copy with the latest from master doesn't help.

Thoughts?

PS - isn't it about 01:00 am in Singapore? This is hardly a critical issue and can definitely wait until tomorrow :smile:

**Comment by kensoh** [comment]
Hi @gilgoldman the following works for me, can you try if it works for you?

```
www.google.com
if exist('//*[@name="q"]')
    type //*[@name="q"] as open-source rpa[enter]
wait
```

PS - haha I sometimes sleep very late and work late into the night 🤣

**Comment by kensoh** [comment]
The output I have and using [TagUI v6.42](https://github.com/kelaberetiv/TagUI/issues/1050#issuecomment-855265631) (type tagui command without parameters)
```
START - automation started - Sun Jun 06 2021 10:34:26 GMT+0800 (+08)
https://www.google.com - Google

type //*[@name="q"] as open-source rpa[enter]
wait

https://www.google.com/search?q=open-source+rpa&sxsrf=ALeKk01g5753fWJ3E1X0FhWOT6SIysGyFA%3A1622946866790&source=hp&ei=MjS8YOiwLYPn9QOx6oyQBg&iflsig=AINFCbYAAAAAYLxCQqde-3BxpbIXUgO4d1O1b9JhDx6z&oq=open-source+rpa&gs_lcp=Cgdnd3Mtd2l6EAwyBAgjECcyAggAMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjoFCAAQkQI6CwguELEDEMcBEKMCOgUIABCxAzoLCC4QsQMQxwEQrwE6DgguELEDEIMBEMcBEK8BOggILhDHARCvAVCPCVjvFmDEGGgAcAB4AIABXIgBzwaSAQIxNZgBAKABAaoBB2d3cy13aXo&sclient=gws-wiz&ved=0ahUKEwjoke2b_IHxAhWDc30KHTE1A2IQ4dUDCAc - open-source rpa - Google Search
FINISH - automation finished - 10.0s
```

**Comment by gilgoldman** [comment]
Hi Ken!

No luck - still the same issue. I also have TagUI v6.42 (confirmed by typing tagui without parameters)

Any idea what it might be?

```
www.google.com
if exist('//*[@name="q"]')
ERROR - expected token '('
```
![image](https://user-images.githubusercontent.com/9378905/120933074-c8eb8780-c6f8-11eb-83bd-fc6ebeae4e02.png)

**Comment by kensoh** [comment]
Hi @gilgoldman oh that's right! In live mode there isn't support to do if condition / for loops. This is because it's quite awkward to try to communicate what steps belong to the if condition and for loop.

And for now the live mode compiler runs each line as a single block of JavaScript code instead of building buffer and have some way for user to tell live mode 'hey i have finish entering all the lines i want, now run them'.

**Comment by gilgoldman** [comment]
Ohhhhhhh that makes a lot of sense, actually. Issue resolved, then :smile: 
Thanks again Ken!
