### ISSUE TITLE
How to open new tab or Window to start another automation - use dom window.open()

### ISSUE THREAD

**Issue by macrocks** [kelaberetiv/TagUI#1056]
Hi There,

I am looking for an option to open a new tab or window where another automation will begin.
e.g. I have to login to gmail first and once logged in, i should open another tab to login to outlook/yahoo

I tried popup option but no luck. is there any command or any way we can do this?

**Comment by kensoh** [comment]
Hi @macrocks see working example below. Note that first time you run you have to enable popup to not block, then run again. Otherwise Chrome will block popups if you trigger it. Also, can you tell more why there is a need to run 2 tabs instead of doing everything first on 1st website and then go to 2nd website to do the rest of the automation steps?

```
https://google.com
type //*[@name="q"] as testing 1

dom window.open('https://yahoo.com')
popup yahoo
    type //*[@name="p"] as testing 2
```

**Comment by kensoh** [comment]
Besides using `dom` step, below shows use of keyboard automation to open new tab -

```
https://google.com
type //*[@name="q"] as testing 1

keyboard [cmd]t
keyboard [cmd]l
// either this
keyboard https://yahoo.com[enter]

// or use clipboard
// clipboard('https://yahoo.com')
// keyboard [cmd]v
// keyboard [enter]

popup yahoo
    type //*[@name="p"] as testing 2
```

**Comment by kensoh** [comment]
Closing for now until further inputs
