### ISSUE TITLE
ERROR - number of step { does not tally with with } - inconsistent indents (spaces + tabs)

### ISSUE THREAD

**Issue by lookang** [kelaberetiv/TagUI#1065]
Dear Ken,
I have this working TagUI file
[posttosls3.tag.zip](https://github.com/kelaberetiv/TagUI/files/6731703/posttosls3.tag.zip)

but if i add code 
[posttosls3broken.tag.zip](https://github.com/kelaberetiv/TagUI/files/6731715/posttosls3broken.tag.zip)

else
		{
		click cv-button add-component bx--btn bx--btn--tertiary bx--btn--field
		click Free-Response

        click /html/body/div[1]/main/div/div/div/section[1]/div[2]/div/div/div[`qn_cnt`]/div/div/div/div/div/div/div[2]/div/div/div/div/form/dl[2]/dd/div/div[2]/div
		type paragraph as `qn.question`

        click /html/body/div[1]/main/div/div/div/section[1]/div[2]/div/div/div[`qn_cnt`]/div/div/div/div/div/div/div[2]/div/div/div/div/form/dl[6]/dd/div/div[2]/div[1]/dl/dd/div/div[2]/div
        type paragraph as `qn.answer`

        click //div[@class="input-radio"][`qn.answer`]//span[@class="input-icon"]
		}

the file stops working. Do you know why?
(base) Opens-MacBook-Pro:SLS_assessment_automation lookang$ tagui posttosls3broken.tag
ERROR - number of step { does not tally with with }
ERROR - automation aborted due to above

**Comment by lookang** [comment]
no worries, it is fixed!

**Comment by lookang** [comment]
TagUI code Completed!
https://github.com/lookang/TagUI/blob/main/SLS_assessment_automation/ReadME

YouTube explainer
https://www.youtube.com/watch?v=KTExNaIGDfI

credits:
code written by Shaun Quek and Loo Kang Wee 

If you have 1000 of questions to post to SLS, this automation tool could be for you!

Pre-Conditions:
computer with admin rights, that means WOG and SSOE are not able to do TagUI!
I use a Mac but Windows will work too!
Code editor: Visual Code Studio
Command Prompt: like Terminal
CSV editor: Microsoft Excel

Recommended use
download output.csv
edit output.csv to your own questions
add new rows if needed but keep the rows and columns in the same position ( dont delete or add new columns, only add new rows)
save the file output.csv


Install TagUI if need
https://tagui.readthedocs.io/en/latest/setup.html


run TagUI file by typing in command prompt
tagui /Users/lookang/Desktop/tagui/flows/SLS_assessment_automation/posttosls5.tag
first time prepare the login to SLS and gmail for the otp, means key in your login id and password and the gmail login and password for the OTP, select let Chrome manage the password. So TagUI code will not store the confidential info.
run TagUI again
it should be able to populate the questions now.
Enjoy!

**Comment by kensoh** [comment]
Thanks Lawrence for asking and sharing!

Also spread the word on LinkedIn - https://www.linkedin.com/posts/kensoh_using-tagui-to-automate-posting-of-questions-activity-6815907088426905600-MP_0

And AI Singapore community site - https://community.aisingapore.org/groups/tagui-rpa/forum/discussion/workflows-showcase-from-users/ (to be made publicly accessible in couple of weeks)

PS - I guess you found the cause, I saw from your example above that some lines are using tabs to indent and some lines are using spaces. Visually this may look the same on text editors, but TagUI will be confused because it doesn't know which way is the user's intention. TagUI can work with tabs or a fixed number of spaces (up to user to decide), as long as consistent through the workflow. If you are using newer versions of TagUI, {} are optional too, just indentation is sufficient. For folks who prefer {} instead of indentation, TagUI is backward compatible and works too for scripts written that way.
