### ISSUE TITLE
how to change TagUI downloaded filename prompt to change file name?

### ISSUE THREAD

**Issue by lookang** [kelaberetiv/TagUI#1076]
Dear @kensoh ,

I run these 3 lines in Tagui Live on a google sheet

click File
click Download
click csv

But Tagui chrome didn't offer to save filename prompt so I can change the filename.
It is possible to specific the filename before it downloaded to the flow folder?
![Screenshot 2021-07-15 at 3 13 19 PM](https://user-images.githubusercontent.com/20143558/125745344-0646c6a0-5752-4a25-bd26-c87789b1537c.png)
I even looked it the TagUI Chrome settings, but it doesn't seem to follow the settings.

Any suggestions?
I want to change the google sheet filename to something else.

**Comment by lookang** [comment]
Oh, I also realize I cannot open the *.csv file from TagUI Chrome? Is it an expected behaviour?

That's weird, the behaviour is different from the normal Chrome.

**Comment by kensoh** [comment]
Hi Lawrence, yes TagUI will by default set the downloads location to the folder of the workflow for easier organising.

But I think this setting will make that folder / filename selection window not pop up.

Sure, ping me again if anything! Adding on, you can try using following to rename or move the downloaded files around -

```
run mv /folder/filename /new_folder/new_filename
```

I believe wildcards like * should also be supported. Above make use of OS-level commands to move files around.

Full path is needed because the working folder for run step is in tagui/src folder and not the workflow folder.

**Comment by lookang** [comment]
I change my code to suit the downloaded files names. No worries.

**Comment by fangxy926** [comment]
> Hi Lawrence, yes TagUI will by default set the downloads location to the folder of the workflow for easier organising.
> 
> But I think this setting will make that folder / filename selection window not pop up.
> 
> Sure, ping me again if anything! Adding on, you can try using following to rename or move the downloaded files around -
> 
> ```
> run mv /folder/filename /new_folder/new_filename
> ```
> 
> I believe wildcards like * should also be supported. Above make use of OS-level commands to move files around.
> 
> Full path is needed because the working folder for run step is in tagui/src folder and not the workflow folder.

I use * to match file, but it seems not working.
![image](https://user-images.githubusercontent.com/23739775/141738616-29042366-4612-409e-9135-247e5dc8a2d4.png)

**Comment by kensoh** [comment]
Hi @fangxy926, you are right, it looks like the * with called from run command does not get expanded by the shell to become wildcard selection. One workaround I tested to be working is this way -

1. create a script.sh file with the following line of the file moving, including the full path. For example -
```
mv /Users/xxx/Desktop/test/*.xlsx /Users/xxx/Desktop/test/efg.xlsx
```
2. chmod the script.sh from your terminal, so that it can be executable -
```
chmod 744 script.sh
```
3. use the following line (full path) in TagUI to run that script to do the renaming -
```
run /Users/xxx/Desktop/test/script.sh
```

Alternatively, if you are familiar with JavaScript, you can use the built-in fs module to get a list of files there for processing -
https://phantomjs.org/api/fs/method/list.html

Copying @ruthtxh
