### ISSUE TITLE
Automate Excel files with native integration using Excel formula in TagUI - done

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1081]
First path is trying out embedding sheet.js directly (and credit) to see if that's doable -

https://github.com/sheetjs/sheetjs

**Comment by kensoh** [comment]
It looks like SheetJS does not ensure preservation of formatting and features like pivot tables. And that improved consistency is only for the paid pro version. In that case SheetJS cannot be an option. More details in below posts -
https://github.com/SheetJS/sheetjs/issues/347
https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021

It also looks like PHPSpreadsheet does not preserve formatting -
https://stackoverflow.com/questions/53787637/will-phpspreadsheet-convert-xls-to-xlsx-and-preserve-formatting

Looking further, Python packages such as openpyxl also do not preserve formatting -
https://stackoverflow.com/questions/52878615/how-to-keep-style-format-unchanged-after-writing-data-using-openpyxl-package-in

Looking even further, from Microsoft, they only provide an API for web-based MS Office, which has a limited feature set and not the primary mode of consumption of MS Office documents - 
https://docs.microsoft.com/en-us/javascript/api/overview?view=excel-js-preview

**Comment by kensoh** [comment]
In light of above, will explore doing from UI with keyboard shortcuts + visual automation, but with minimal effort from users.

For example, explore the following syntax -

**1-liners - reading**
```
excel file Sales Report.xlsx
excel sheet June Report
excel cell G20 to total
excel range A1:G20 to data_array
```
**1-liners - writing**
```
excel 99999 to cell H20
excel cell A1 to cell A2
excel data_array to range A1:G20
excel range A1:B2 to range E2:F3
excel save Sales Report.xlsx
```
**excel block - reading**
```
excel begin
file Sales Report.xlsx
sheet June Report
cell G20 to total
range A1:G20 to data_array
excel finish
```
**excel block - writing**
```
excel begin
99999 to cell H20
cell A1 to cell A2
data_array to range A1:G20
range A1:B2 to range E2:F3
save Sales Report.xlsx
excel finish
```

**Comment by kensoh** [comment]
Iterating to VBScript for Windows + AppleScript for Mac -
https://www.faqforge.com/windows/run-vbscript-windows/
https://www.idautomation.com/font-encoders/applescript/

**Comment by kensoh** [comment]
```
excel begin
file --> sheet --> cell/range = variable
variable = file --> sheet --> cell/range
file --> sheet --> cell/range = file --> sheet --> cell/range
excel finish
```

**Comment by kensoh** [comment]
References for macOS applescript -

https://www.idautomation.com/font-encoders/applescript/
https://discussions.apple.com/thread/5298745
http://preserve.mactech.com/articles/mactech/Vol.23/23.02/2302AppleScript/index.html
https://discussions.apple.com/thread/8345854

**Comment by kensoh** [comment]
How the syntax will look like if using Excel standard definition of workbook + sheet + range -
![Screenshot 2021-08-18 at 4 02 45 PM](https://user-images.githubusercontent.com/10379601/129861350-d2bb1498-933a-4862-bb32-f9254ba77d0e.png)

**Comment by kensoh** [comment]
I think I found the ultimate syntax for this feature. This requires learning 0 additional knowledge to use and super powerful.

```
variable = [workbook.xlsx]sheet!range
[workbook.xlsx]sheet!range = variable
[workbook.xlsx]sheet!range = [workbook.xlsx]sheet!range
```

**Comment by kensoh** [comment]
Tests before this feature can be released -
- [ ] [workbook]sheet!range = variable
- [ ] variable = [workbook]sheet!range
- [ ] [workbook]sheet!range = [workbook]sheet!range
- [ ] repeat with absolute & relative workbook path
- [ ] repeat with space in workbook and sheet name
- [ ] repeat with cell, column, row, range for range
- [ ] repeat with string, number, array for variable
- [ ] what if file does not exist or already opened
- [ ] repeat all the above in TagUI live mode
- [ ] repeat all the above on Windows

**Comment by kensoh** [comment]
Thanks Imane for raising these questions, copying @ruthtxh to share her views on these questions.

**Comment by ruthtxh** [comment]
Hi @EmyEtti00 

**1-Does the software contains an orchestrator if yes how it works?**
No, but you can make use of other tools to achieve this For instance:
- Task Scheduler (Windows) to schedule your deployed TagUI workflow
- OpenRPA which has integrations with TagUI

**2- How to manage login and the password?**
You can save to TagUI's Chrome user profile when building your workflow, so that these credentials will be auto populated when you visit the page.

If you want to hide the password you can separate them from your flow file using the concept of object repository in TagUI. See https://tagui.readthedocs.io/en/latest/advanced.html?highlight=object%20repository#object-repositories

You can also use 3rd party password managers.

**3- Does the Robot's settings exist?**
Sorry I don't understand this question, can you elaborate more?

**4- Can I add commands and packages by myself?**
With human language TagUI you can use the following steps - Javascript, Python, R to write code in the respective programming languages. See https://tagui.readthedocs.io/en/latest/reference.html?highlight=custom%20code#custom-code
There's also the following "flavours" of TagUI:
Python: https://github.com/tebelorg/RPA-Python
C#: https://www.nuget.org/packages/tagui
Node-RED: https://flows.nodered.org/node/node-red-contrib-tagui

**5- how does the software manage to lag?**
Sorry I don't understand this question, can you elaborate more?

**6- Does TagUI have interactions with desktop apps and java apps?**
Yes, you can do desktop automations using visual automation, which involves taking snapshots of the controls as identifiers. See this example: https://github.com/aimakerspace/TagUI-Bricks/tree/master/MS-Word-Letter

**7-Any information about the WorkQ**
Sorry I don't understand this question, can you elaborate more? If you are referring to work queues for orchestration, then it would depend on how you orchestrate your flows using the suggestions in point 1.

**Comment by kensoh** [comment]
Thanks @ruthtxh! I have nothing to add other than including OpenFlow and OpenBots into the list of open-source RPA tools that have built-in support to orchestrate TagUI.

**Comment by kensoh** [comment]
References for porting to Windows - 

https://docs.microsoft.com/en-us/previous-versions/office/troubleshoot/office-developer/automate-excel-from-client-side-vbscript
https://www.activexperts.com/admin/vbscript-collection/msoffice/excel/
https://www.softwaretestinghelp.com/vbscript-excel-tutorial-11/
https://www.mrexcel.com/board/threads/vbscript-activating-an-excel-window-already-opened.1076542/
https://www.file.net/process/wscript.exe.html
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cscript
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wscript
https://www.experts-exchange.com/articles/17325/Difference-between-cscript-and-wscript.html
https://isvbscriptdead.com

**Comment by kensoh** [comment]
Excel integration added! [See this link](https://github.com/kelaberetiv/TagUI/issues/1081#issuecomment-902058917) for list of cases tested, known limitations to explore, and user suggestions for review.

Usage guide with various examples - https://tagui.readthedocs.io/en/latest/reference.html#excel

If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. If not, you can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html) before performing the update.

For list of changes since TagUI v.6.46 release in mid-June, see this (link also found at TagUI installation page) -
https://github.com/kelaberetiv/TagUI/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fixed+OR+done+

**Comment by kensoh** [comment]
Closing since this change has made its way into the latest packaged release.

**Comment by Umariqbal6814** [comment]
hello sir 
i am diploma student
sir how we find latest data in a particular format
