### ISSUE TITLE
Is there a way to not refresh page between iterations? - try iterating on .csv directly

### ISSUE THREAD

**Issue by loweaxerium** [kelaberetiv/TagUI#1083]

**Comment by ruthtxh** [comment]
Hi @loweaxerium, datatables will open a new browser session for each iteration. You may try using load step to load the csv into an array then use javascript to split and get each items. This example types each item consecutively into the google search bar without refreshing the page:

flow file:
```
https://google.com
load datatable.csv to datatable
rows = datatable.split('\n')
for (n=1; n<rows.length; n++)
    item = rows[n].split(",")[1]
    type q as `item`
```

datatable.csv:
```
#,item
1,apple
2,orange
3,pear
```

**Comment by loweaxerium** [comment]
You are awesome @ruthtxh, that did the trick, completely sped up my process, thanks a lot!

**Comment by kensoh** [comment]
Hi @loweaxerium, adding on, I've just added a new update to TagUI that preserves the URL state between iterations. In this way, the browser does not refresh with about:blank each time and will continue where it left off. More details at - 

https://github.com/kelaberetiv/TagUI/issues/1087#issuecomment-888050542

You can get this update with `tagui update` command or the Update TagUI button in MS Office plug-ins.

PS - There is still a 3 second delay in between datatable iterations and that is by design, to prevent going too fast and getting blocked by target website for detecting as automation and exceeding access rate limits.
