### ISSUE TITLE
How to check if icon matches specifically with some image - check attribute in this case

### ISSUE THREAD

**Issue by lookang** [kelaberetiv/TagUI#1084]
https://tagui.readthedocs.io/en/latest/reference.html
Is it possible to check if any icon1.png is equal?

The error message is 
ERROR - invalid flags supplied to RegExp constructor.

This is incomplete flow

https://www.moe.gov.sg/private-education/private-schools

total = 858

//read /html/body/main/div[2]/div/div/div/div/div/div[1]/p to title
///html/body/main/div[2]/div/div/div/div/div/div[1]/div/div[1]/i
//read /html/body/main/div[2]/div/div/div/div/div/div[1]/div/div[1]/a to address
//read /html/body/main/div[2]/div/div/div/div/div/div[1]/div/div[2] to phone
//read /html/body/main/div[2]/div/div/div/div/div/div[1]/div/div[3] to fax
//read /html/body/main/div[2]/div/div/div/div/div/div[1]/div/div[3]/a to email

//read /html/body/main/div[2]/div/div/div/div/div/div[2]/p to title
//read /html/body/main/div[2]/div/div/div/div/div/div[2]/div/div[1]/a to address
//read /html/body/main/div[2]/div/div/div/div/div/div[2]/div/div[2] to phone
//read /html/body/main/div[2]/div/div/div/div/div/div[2]/div/div[3]/a to email

// read /html/body/main/div[2]/div/div/div/div/div/div[9]/div/div[1]/i to addressicon

//6
///html/body/main/div[2]/div/div/div/div/div/div[6]/p

rowCnt = 1
pending = []

for rowCnt from 1 to 20
    // trying to break out if total is not found 
    // if title exists
    check /html/body/main/div[2]/div/div/div/div/div/div[9]/div/div[1]/i equals to icon1.png | read /html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/p to title | 
        // if title exists
        read /html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/p to title
    if (exist('/html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/div/div[1]/a')) 
        read /html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/div/div[1]/a to address
    if (exist('/html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/div/div[2] ')) 
        read /html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/div/div[2] to phone
        // to handle missing emails from table
    if (exist('/html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/div/div[3]/a')) 
        read /html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/div/div[3]/a to fax
    if (exist('/html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/div/div[3]/a')) 
        read /html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/div/div[3]/a to email
        js pending.push([rowCnt, title, address, phone, fax, email])
    
    else 
        break
    

// WRITING TO FILE
write `csv_row(["S/N", "Title", "Address", "Phone", "Email"])` to moereview_list.csv
for i from 1 to pending.length
    write `csv_row(pending[i - 1])` to moereview_list.csv
    // to debug and see what is happening in pending 
    js console.log(pending[i-1])

**Comment by ruthtxh** [comment]
Hi @lookang, you may check if the title exists using the if exist() function:

```
if exist('/html/body/main/div[2]/div/div/div/div/div/div[`rowCnt`]/p')
    //do something
```

For the image checking, the website you provided renders the images with icons using classes. You may try to check if the class of the element matches the icon class you are looking for.

```
read /html/body/main/div[2]/div/div/div/div/div/div[9]/div/div[1]/i/@class to icon_class
if (icon_class.indexOf("icon-landmark") !== -1)
	echo matches
```

**Comment by lookang** [comment]
https://weelookang.blogspot.com/2021/07/using-tagui-to-crawl-publicly-available.html

Thank you!
Got it to work.
https://www.youtube.com/watch?v=yYyYhs4I6Vo
https://github.com/lookang/TagUI/tree/main/moepublicdata data is public so it is okay to share.

**Comment by kensoh** [comment]
oh nice! I saw your workflow here - https://github.com/lookang/TagUI/blob/main/moepublicdata/moe3.tag

you are using if exist condition to read the fields if they are in the record. exist() will wait until the default timeout of 10s before returning true or false. if you swap to present(), then there is no delay and TagUI will immediately return true or false. This way, if something is missing, the automation will continue rightaway.

However, in order to make sure that all records have been loaded at https://www.moe.gov.sg/private-education/private-schools , you may want to do a hover step at the last record or if exist at the last record to make sure. otherwise checking with present() may return a false negative while the page is still loading.

i think in Singapore's context the internet speed is fast so this should not be a problem, but just highlighting on best practice. another optimization will be if exist no need brackets. if exist() will do, don't need if (exist()). TagUI will automatically add the outer () during compilation to JavaScript code in the backend

**Comment by lookang** [comment]
Wow! Good tip present() works well.
https://github.com/lookang/TagUI/blob/main/moepublicdata/moe4.tag
updated and a lot faster.
Thanks
