### ISSUE TITLE
Installing on MacOS Big Sur. ln: /usr/local/bin/tagui: No such file or directory - pending clues

### ISSUE THREAD

**Issue by hmtan09** [kelaberetiv/TagUI#1095]
Faced an issue while installing TagUi on MacOS Big Sur (11.4). 

![image](https://user-images.githubusercontent.com/88553245/128544204-eee7b706-11ae-4618-900f-f5b5d6f9c86b.png)

Is there certain user permission settings which i need to change ?

**Comment by kensoh** [comment]
Hi Huimin, I'm also from VJ, 98S44 :wave:

Thanks for trying out this RPA tool. I'm running older Mac Catalina and can't replicate.

Is there a /usr/local/bin folder anymore on your Big Sur Mac? I can't find answers online

**Comment by kensoh** [comment]
If somehow the folder /usr/local/bin is missing, an alternative is you can create an alias by

```
alias tagui=/your_tagui_path/tagui/src/tagui
```

Though this is temporary unless you modify your /Users/hmtan/.profile

The purpose of the above and the sudo ln is to create a shortcut so that you can type tagui in any folder to run TagUI

Without creating a shortcut it will still work alright, just that you have to type the full path everything to run it.

**Comment by hmtan09** [comment]
Thanks Ken! Good to see you are keeping well. We were in the same course during NUS days too. This is great stuff that you are doing. =)

I believe the folder is there. See here.
![image](https://user-images.githubusercontent.com/88553245/128585923-b9dbb1aa-c9ee-435c-ba30-7d4647a33bfa.png)
 
Am also still doing some search on the net to see how to resolve this. Anyway, this is not a deal breaker and thanks for your suggestion on the temporary way to do this.

I am just executing it directly from the folder.

**Comment by kensoh** [comment]
Hi Huimin, thanks for your support and kind words :)

If you are looking further, maybe try this command below to see if the bin folder is there. The path variable only shows where is the search path for commands but may not necessarily confirm that a folder is actually there.

```
ls -l /usr/local
```

Mine will see something like this -

```
drwxrwxr-x  78 kensoh  admin  2496 Aug  7 01:57 bin
```

Why I thought to check this is because the only way I can replicate your error message is when I provide a parameter that is a missing directory, for example when I provide `/usr/local/bin/test/tagui` which there isn't test folder there.
```
sudo ln -sf /your_tagui_path/tagui/src/tagui /usr/local/bin/test/tagui
ln: /usr/local/bin/test/tagui: No such file or directory
```

Sure, lemme know again if you run into any blockers. Below are some other resources to get started, as well as other channels users can post problems to. In particular, Telegram group and weekly Zoom Q&A are useful.

https://github.com/kelaberetiv/TagUI/blob/master/src/media/TagUI%20Technical%20Webinar.md#how-to-get-started

PS - a Macbook Pro (M1) user with missing /usr/local folder, but no solution and reason was mentioned - https://discussions.apple.com/thread/252495484

**Comment by lookang** [comment]
https://weelookang.blogspot.com/2020/12/managed-to-get-tagui-work-on-mac.html?m=1
My blog when I installed tagui may be useful.

**Comment by kensoh** [comment]
closing for time being until further inputs

**Comment by vecinveni** [comment]
Hello community, I am encountering an issue as @hmtan09 , can I check how do I go about solving this issue?

**Comment by ruthtxh** [comment]
Hi @vecinveni you can check if the parent folder is there?
