### ISSUE TITLE
Download the PDF of the link - use visual automation / keyboard step or run step with curl

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#1097]
Hello
I have this script that is not working properly
```
https://www.economiaemdia.com.br/SiteEconomiaEmDia/Monitores/Boletim-de-Investimentos
wait
keyboard [alt]
click //h1[contains(text(),"Última Publicação")]/../a
```
I would like to send a command on mac OS
`keyboard [option]` but together with `click //h1[contains(text(),"Última Publicação")]/../a`
in order to download the pdf of the link
would it be possible?
thanks

**Comment by kensoh** [comment]
Hi Marcelo, is it because with alt key it becomes a download and not opening directly in web browser to view?

Some ideas to explore -

1. the keyboard [alt] only works with some other characters within the same step. you can try doing a rclick (either using visual automation or XPath etc), and then using visual automation or keyboard step to choose the download option you want.

2. you can use `read XPath/@href into link` to form the URL of the PDF. TagUI comes with curl command on Windows and for macOS it already has curl. You can do something like this. It will download the PDF to your desired folder using run step and curl.
```
filename = '/Users/user/Desktop/report.pdf'
link = 'some url'
run curl -k -s -L -o `filename` `link`
```

3. For users using RPA for Python, they can also use r.download(link) to download directly using built-in Python library.

**Comment by marcelocecin** [comment]
hi Ken
I changed the script to:
```
https://www.economiaemdia.com.br/SiteEconomiaEmDia/Monitores/Boletim-de-Investimentos
wait
read //h1[contains(text(),"Última Publicação")]/../a/@href to link
js pdf = link.split( '/' ).pop()
file = '/Users/marcelocecin/Downloads/'+pdf
echo `file`
run curl -k -s -L -o `file` `link`
echo `run_result`
```
the file is not being saved and no error is being returned
when I run the `curl` command in the terminal manually, the file is saved
thanks

**Comment by kensoh** [comment]
I see, that's great! I can see why you have to do the additional steps, in order to control location of downloaded file.

Another option is use the run step with mv command to move the file after downloading. For eg,

```
run mv *.pdf /Users/marcelocecin/Downloads/.
```

Also, the js in front of pdf = ... step is optional because TagUI can detect assignment JS code as JS code and handle it.

**Comment by marcelocecin** [comment]
hi Ken
I created a version using SikuliX:
```
https://www.economiaemdia.com.br/SiteEconomiaEmDia/Monitores/Boletim-de-Investimentos
wait
click (300,300)
wait
keyboard [down][down][down][down]
hover download.png
wait
vision begin
keyDown(Key.ALT)
mouseDown(Button.LEFT)
mouseUp()
keyUp()
vision finish
wait
```

**Comment by kensoh** [comment]
Interesting, thanks for sharing Marcelo! Copying my team-mate Ruth @ruthtxh 

Yes with vision step to control SikuliX directly you can do a whole lot more stuffs.

You can also do something like below to save the series of custom actions in a .tag file to be reused in other workflows.

```
tagui special_click.tag
```
