### ISSUE TITLE
Quotation Marks lose formatting when scraped - see eg, pending replication

### ISSUE THREAD

**Issue by bcpeinhardt** [kelaberetiv/TagUI#1105]
A piece of my code uses the read step to get text from an html element on one tab and then types that text into a field on the original tab. When I do this:
```
popup emp 
{
    read //td[text()="Headline:"]/../td[2] to headline
}
type defaultSubject as `headline`
```
The quotation marks are printed as their unicode characters \u201c and \u201d, so
```
"original text"
```
becomes
```
\201coriginal text\201d
``` 
I could do a quick js step to fix this after the fact, but I'm worried about other characters displaying correctly as well. Any advice on how to solve this?

**Comment by kensoh** [comment]
Hi @bcpeinhardt, TagUI will read the text of an element using the following priority -

textContent, innerText, value and returns blank '' if all 3 properties are blank

I can't replicate the issue using below example. Can you share the website for us to take a look?

The right behaviour for TagUI is to read what the website stores, if it is unicode character then the read step should also return in that form. For type step and other steps, TagUI will already process the unicode characters correctly, since the underlying engine is JavaScript.

See this example, I type using unicode, then read unicode string to variable b, then type it out again. It works correctly.

```
www.google.com
a = '\u201coriginal text\u201d'
echo `a`
type q as `a`

read q to b
echo `b`
type q as `b`
wait
```
![Screenshot 2021-09-04 at 2 25 56 PM](https://user-images.githubusercontent.com/10379601/132085151-6bd63d04-d6e8-4a29-84f1-64664478cdda.png)

![Screenshot 2021-09-04 at 2 28 49 PM](https://user-images.githubusercontent.com/10379601/132085197-37322e9b-6142-44f1-850f-d0ed9a1ecbc8.png)

**Comment by bcpeinhardt** [comment]
Unfortunately, I can't. They're both custom internal sites that require company logins. I can say that I'm reading from a td element and writing to an input of type text.

**Comment by kensoh** [comment]
I see, can you try the example to see if this works on your computer?

```
www.google.com
a = '\u201coriginal text\u201d'
echo `a`
type q as `a`

read q to b
echo `b`
type q as `b`
wait
```

**Comment by bcpeinhardt** [comment]
This fails to write anything to the search on my machine, but I'm not sure what the issue is. I tried removing the Unicode and it still didn't work. It's triggering the I'm feeling lucky animation as though that element is being hovered over. I added the line
```
snap page to testing.png
```
to show this.
![testing](https://user-images.githubusercontent.com/61021968/132277763-e534669c-c7c0-434a-8c5d-fa9a36c24fee.png)

**Comment by bcpeinhardt** [comment]
Terminal output (added live mode line so the terminal would stay up for me to copy it)
```
START - automation started - Mon Sep 06 2021 23:17:03 GMT-0400 (Eastern Daylight Time)
https://www.google.com - Google

original text
type q as original text
read q to b
I'm Feeling Lucky
type q as I'm Feeling Lucky
LIVE MODE - type done to quit
```

**Comment by bcpeinhardt** [comment]
Sorry that was without the unicode quotes here's with them:
```
START - automation started - Mon Sep 06 2021 23:19:47 GMT-0400 (Eastern Daylight Time)
https://www.google.com - Google

ΓÇ£original textΓÇ¥
type q as ΓÇ£original textΓÇ¥
read q to b
I'm Feeling Lucky
type q as I'm Feeling Lucky
```

**Comment by kensoh** [comment]
I see, I think our Google.com renders differently the HTML so q does not match. Can you try below, this should work better -

```
www.google.com
a = '\u201coriginal text\u201d'
echo `a`
type //*[@name = 'q'] as `a`

read //*[@name = 'q'] to b
echo `b`
type //*[@name = 'q'] as `b`
wait
```

**Comment by bcpeinhardt** [comment]
This works as expected! Types "original text""original text" to the search bar. My search input has name="q" so not sure why the previous did not work.

**Comment by kensoh** [comment]
Oh great! Then maybe you can explore along these lines. You see in this example, double quotes were typed in unicode and read as unicode and typed back as unicode successfully.

However, in your company internal website, the same sequence of actions did not work and instead becomes `\201coriginal text\201d`. You can try to compare why this is so, what is different from above example in your company example.

**Comment by bcpeinhardt** [comment]
The difference is trying to read the text from a popup and then write the text inside the original window.

**Comment by kensoh** [comment]
I see, then it sounds like with popup step, unicode characters get returned as normal string without the `\u` being escaped as unicode code. I can imagine why is that so, because of an additional target layer, some info may not come through in the same form as the raw data. My recommendation -

1. don't do as a popup, do directly in that URL, get the data then go on to do what's needed
2. knowing this gap, consider applying some JavaScript function to process the unicode correctly
