### ISSUE TITLE
Iterate Ids from csv file and save data to excel or csv - use datatables and write step

### ISSUE THREAD

**Issue by fjchavez** [kelaberetiv/TagUI#1109]
Hello kensoh,

I am new to using TaGUI and I would like some guidance on how to use the tool to extract information from a system.

I have a list of Booking IDs saved in a ids.csv, for each ID I have to enter the system, search for the ID and extract the first and last name of the client, then save that data in an excel or csv.
Could you guide me in pseudocode and with which functions to perform this procedure with TaGUI?

[ids.csv](https://github.com/kelaberetiv/TagUI/files/7133637/ids.csv)

**Comment by kensoh** [comment]
Hi @fjchavez pinging my team-mate Ruth @ruthtxh

**Comment by ruthtxh** [comment]
Hi @fjchavez here's your pseudocode.

```
if iteration equals to 1
  write ReservationNr, FirstName, LastName to output.csv
https://google.com
type q as `ReservationNr`[enter]
read //*[@id="rso"]/div[1]/div/div/div[1]/a/h3 to firstName
write `ReservationNr`, `firstName` to output.csv
```

This makes use of the concepts of datatables to loop through the dataset provided. Then it types to the google search bar the reservatioNr, and reads the first result title to a variable called firstName. After this, it writes the reservationNr and firstName to a new csv file called output.csv.

See the usage guides here for the steps used:
https://tagui.readthedocs.io/en/latest/advanced.html?highlight=datatable#datatables
https://tagui.readthedocs.io/en/latest/reference.html?highlight=type#type
https://tagui.readthedocs.io/en/latest/reference.html?highlight=read#read
https://tagui.readthedocs.io/en/latest/reference.html?highlight=write#write

Note that the dataset headers were being tweaked to remove blank spaces and special characters. To run the flow, you can run the command:
```
tagui flow.tag ids.csv
```

If you want to write to the same ids file instead of a new output file, it is possible too, but slightly more complicated. My suggestion is to go with the above solution for a start.
[sample.zip](https://github.com/kelaberetiv/TagUI/files/7135799/sample.zip)

**Comment by fjchavez** [comment]
Thank you very much for the answer @kensoh and @ruthtxh, your answer helps me a lot.
I have an additional query.
The process I follow to extract the information is:

1. I enter the URL of the system
2. I enter my username and password
3. I wait for a message to arrive on my mobile to the Authenticator app to approve the login, I approve.
4. I enter the system and search in the options to consult each reservation.
5. I enter the booking id and extract the first and last name, move on to the next id and so on.

If I use datatables, this whole process is repeated for each iteration as I read in the documentation.
Is there a way that this previous process (step 1 to 3) is done only once and apply a "for" to go through the ids and query the names?
I ask this because for 10 ids I can be approving logins on my mobile but for 1000 it is very tedious.
Thank you very much again.

**Comment by ruthtxh** [comment]
Hi @fjchavez, you can access the current iteration with the iteration keyword.

To login only once on the first record, you can do the following. You can modularize your login steps and write them separately in another tag file, then access it like this.
```
if iteration equals to 1
  // tagui login.tag
```

**Comment by kensoh** [comment]
Adding on some thoughts that may be useful in your scenario, as part of your login, you may want to use `timeout 300` to give a large 5-min time window for user to key in 2FA, before continue the automation.

After running the first ID, TagUI will continue next iteration from where it left off. If you need to 'reset the state' by going to some specific starting URL, you can add that outside the if condition above, so that it always go to that URL for every ID.

Lastly, if you are doing with 1000 records, see you turbo mode works for your application. If it works reliably at superhuman speed the automation can run more than 10X faster to complete. More info on caveats and using this option -
https://tagui.readthedocs.io/en/latest/advanced.html#turbo-mode-to-run-10x-faster
