### ISSUE TITLE
Most efficient way to check conditions with exist()? - try for loop and present()

### ISSUE THREAD

**Issue by Dj0672** [kelaberetiv/TagUI#1115]
Hi,

I have a case where I need to check condition like this :

   timeout 100
   if exist('image_1.png) or exist('image_2.png')
        echo text

With the image in the current screen is image_2, it seems tagui will check first the existence of image_1 first until 100 second and then check the second image. It shows no error, however it is not efficient.
Is it the behavior by design ? Is there any workaround for this case ?

Regards

**Comment by kensoh** [comment]
Hi @Dj0672, yes this is by design, the timeout handles 1 element at a time. I believe this is the same for other RPA tools, and not timeout on a combination of conditions. However, you can try something like below to see if that helps. present() immediately give result. I think it has a similar effect of timeout 100 seconds but checking both conditions.

```
for n from 1 to 100
    if present('image_1.png) or present('image_2.png')
        echo text
    wait 1 second
```

**Comment by kensoh** [comment]
copying @ruthtxh on this interesting scenario

**Comment by kensoh** [comment]
Also, for efficiency, you may want to try out the newly added turbo option that can run at 10X the normal speed -
https://tagui.readthedocs.io/en/latest/advanced.html#turbo-mode-to-run-10x-faster

**Comment by Dj0672** [comment]
Hi Kensoh,

It works using present(). Thanks you for the quick respond and solution.
I see that tagui are working toward native integration with Excel. If it is also able to run Excel Macro from Tagui, it will be excellent. Hope to see this in the near future. 
Thanks for keeping on improving Tagui.

**Comment by kensoh** [comment]
Hi @Dj0672, oh there is no plan to add additional Excel functions for now, because Excel has a huge range of functions to add, and there would be more overall value for users if we continue implementing on items on the roadmap.

To run macro now, you can use a combination of computer vision, using OCR, keyboard step, to replicate what you would do manually to run a macro.
