### ISSUE TITLE
Navigate to previous URL - see examples here, use dom step or keyboard step

### ISSUE THREAD

**Issue by bcpeinhardt** [kelaberetiv/TagUI#1117]
How can I navigate to the previous url? I have tried
```
keyboard [alt][left]
``` 
and storing the url in a dom_result
```
dom return window.location.href;

// go do stuff on another page

`dom_result`
```
but neither of these seems to do the trick.
In chrome visible.

**Comment by bcpeinhardt** [comment]
```
report_page = url()
`report_page`
```
also produces the error
```
ERROR - [LINE 21] cannot understand step '+report_page+'
```

**Comment by kensoh** [comment]
1. For keyboard [alt][left], need to make sure Chrome browser is in focus, so that the keyboard shortcut is sent to browser instead of other app that is in focus. This can be done by using computer vision to click on the Chrome icon on the taskbar for eg.

2. To use dom step to send URL back, following works for me (shows URL). See below on visiting variable URLs.
```
www.google.com
dom return window.location.href
echo `dom_result`
``` 

3. You can't visit a URL variable directly because TagUI doesn't know that variable is a URL to visit or some other TagUI steps. You can visit a URL variable by prefixing with https:// and then provide the variable truncated part without https:// -
```
www.google.com
dom return window.location.href
echo `dom_result`
www.yahoo.com
wait
https://`dom_result.split('https://')[1]`
```
