### ISSUE TITLE
How can a combination of image and keyboard automation work - use vision keyDown

### ISSUE THREAD

**Issue by Anujpalu24** [kelaberetiv/TagUI#1138]
Like wanted to open an .exe file with pressing shift Key

and we are planning to use skiulli to open the .exe and we need to press shift key until that application get opens.

**Comment by kensoh** [comment]
Hi @Anujpalu24 you can do it in the following way, by using vision step to send custom instruction to SikuliX engine.

```
vision keyDown(Key.SHIFT)
dclick icon.png
vision keyUp(Key.SHIFT)
wait 10
```

However, press make sure you include the keyUp instruction, and also test your dclick icon.png step of the image snapshot of the .exe icon. Otherwise if your automation does not complete or missing the keyUp action, your keyboard shift key will be permanently pressed down until reboot I believe. CC @ruthtxh
