### ISSUE TITLE
Click first Google result not working for Hugh Jackman - invalid XPath, try this instead

### ISSUE THREAD

**Issue by eienkisu** [kelaberetiv/TagUI#1144]
Basically I'm writing a flow to go to fb and unfollow pages. The flow worked for other pages but when it comes to certain google result like Hugh Jackson, the link is there but it's not clicking.

using windows 10, latest chrome, latest version of tagui.

flow:
```
www.google.com
type  //*[@name="q"] as [clear]site:facebook.com hugh jackman[enter]

if text() contains 'hugh jackman | Facebook'
	click hugh jackman | Facebook

if exist('(//*[@class="g"])[1]//a')
	show  (//*[@class="g"])[1]//a
	click (//*[@class="g"])[1]//a
```

log:
```
START - automation started - Sun Dec 05 2021 09:02:14 GMT+0800 (Malay Peninsula Standard Time)
https://www.google.com - Google

type //*[@name="q"] as [clear]site:facebook.com hugh jackman[enter]
show (//*[@class="g"])[1]//a
Hugh Jackman | Facebookhttps://www.facebook.com › Pages › Public figure
click (//*[@class="g"])[1]//a

https://www.google.com/search?q=site%3Afacebook.com+hugh+jackman&source=hp&ei=lw-sYZLFCoOuqtsP0sufmAg&iflsig=ALs-wAMAAAAAYawdp8ksGtEkbQzVQbn0orzt9OunxVXi&ved=0ahUKEwjS7JGHu8v0AhUDl2oFHdLlB4MQ4dUDCAk&oq=site%3Afacebook.com+hugh+jackman&gs_lcp=Cgdnd3Mtd2l6EAw6CAgAEIAEELEDOgUILhCABDoOCC4QgAQQsQMQxwEQ0QM6EQguEIAEELEDEIMBEMcBEKMCOggIABCxAxCDAToICC4QsQMQgwE6CwguELEDEMcBEKMCOg4ILhCxAxCDARDHARCvAToOCC4QgAQQsQMQxwEQowI6CwgAEIAEELEDEIMBOggILhCABBCxAzoLCC4QgAQQxwEQrwE6BQgAEIAEOgQILhADOgsILhCABBDHARDRA1AAWIccYNAeaABwAHgAgAHgAogB0j6SAQYyLTI3LjKYAQCgAQE&sclient=gws-wiz - site:facebook.com hugh jackman - Google Search
FINISH - automation finished - 9.3s
```

**Comment by eienkisu** [comment]
fixed this by typing google search operator -noimage

`type //*[@name="q"] as [clear]site:facebook.com hugh jackman -noimage[enter]`

**Comment by kensoh** [comment]
Hi @eienkisu this is because the first link the class is not equals to "g" but "g xxxxx". You can double check that by entering (//*[@class="g"])[1]//a in your Chrome inspector and it will not highlight that first link to Facebook but the dropdown question answers here -

![Screenshot 2021-12-06 at 12 19 52 PM](https://user-images.githubusercontent.com/10379601/144787114-ce728b1b-6ef7-4992-b5f7-dc91e648bc8c.png)

I saw that the search results title has the "| Facebook" string. Following works for me - 
```
www.google.com
type  //*[@name="q"] as [clear]site:facebook.com hugh jackman[enter]
click | Facebook
```

Copying @ruthtxh

**Comment by eienkisu** [comment]
thanks it worked.
