### ISSUE TITLE
tagui is not recognized as a command in Terminal on macOS - wrong folder path

### ISSUE THREAD

**Issue by suribeiro** [kelaberetiv/TagUI#1152]
Hi! 
I tried to install TagUI for macOS, following the instructions.
I tried everything I knew in MacOS Catalina, in MacOS Big Sur and in MacOS Monterey, including installing homebrew, changing the names of the directories, but I always get the answer: zsh: command not found: tagui. (first it was bash: command not found)

I tried with different directory flows, but the last attempt I made was with:

sudo ln -sf /Desktop/tagui/src/tagui /usr/local/bin/tagui

tagui /Desktop/tagui/flows/samples/1_google.tag

Anyone with the same problem?

**Comment by pp082** [comment]
When you click on the alias / usr / local / bin / tagui, can it be opened?

The alias may be wrong

**Comment by kensoh** [comment]
Adding on, I have not used ZSH shell. After you run `sudo ln -sf /Desktop/tagui/src/tagui /usr/local/bin/tagui` is there any error message? If not, try running `ls -l /usr/local/bin/tagui` to see if the shortcut has been created.

Also, I think for Mac, the folder you used is wrong. It is probably `/Users/your_username/Desktop/tagui/src/tagui` instead of `/Desktop/tagui/src/tagui`. Maybe that's the reason why the symbolic link is not working.

**Comment by suribeiro** [comment]
Hi! 
Thanks a lot for your help.
I changed the shell to Bash again. Then I tried doing what you told me and this was the result:

MBPSu2020:~ susanaribeiro$  sudo ln -sf /Desktop/tagui/src/tagui /usr/local/bin/tagui
Password:
MBPSu2020:~ susanaribeiro$ ls -l /usr/local/bin/tagui
lrwxr-xr-x  1 root  wheel  24 20 Dez 11:27 /usr/local/bin/tagui -> /Desktop/tagui/src/tagui
MBPSu2020:~ susanaribeiro$ tagui /Desktop/tagui/flows/samples/1_google.tag
-bash: tagui: command not found


Then I tried with the other options of folders and it happened this:

MBPSu2020:~ susanaribeiro$ sudo ln -sf /Users/susanaribeiro/Desktop/tagui/src/tagui /usr/local/bin/tagui
MBPSu2020:~ susanaribeiro$ ls -l /usr/local/bin/tagui
lrwxr-xr-x  1 root  wheel  44 20 Dez 11:32 /usr/local/bin/tagui -> /Users/susanaribeiro/Desktop/tagui/src/tagui
MBPSu2020:~ susanaribeiro$ tagui /Users/susanaribeiro/Desktop/tagui/flows/samples/1_google.tag
/usr/local/bin/tagui: line 300: php: command not found
Unable to open file: /Users/susanaribeiro/Desktop/tagui/flows/samples/1_google.tag.js

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script /Users/susanaribeiro/Desktop/tagui/flows/samples/1_google.tag.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

**Comment by kensoh** [comment]
Hi @suribeiro great! Looks like you found the issue, by including /User/username you are able to map the command correctly. This next error is due to Mac newer version removing a component used by TagUI, the PHP engine.

You can fix this by running below 2 lines to install PHP manually -
https://github.com/kelaberetiv/TagUI/issues/1137#issuecomment-989465983

This issue is recently reported and I have updated the setup guide to include this troubleshooting step.

**Comment by suribeiro** [comment]
Hi @kensoh 
I followed the instructions in #1137 and #1136 and finally it's working!!!
Thank you very much!
