### ISSUE TITLE
Enquiry about running .tag file in terminal on macbook - tagui live, pending more inputs

### ISSUE THREAD

**Issue by AndyHuang1008** [kelaberetiv/TagUI#1155]
Hi,
I'm now trying to run a simple tag. file in the terminal on my Macbook. I followed every step in the YouTube tutorial, I copied the path of the tag. file which is /Users/andyhuang/Desktop/tagui/flows/test>tagui test.tag. And then I pressed enter, it showed zsh: permission denied: /Users/andyhuang/Desktop/tagui/flows/test. 
I also tried to add cd before my code in order to open the file, but at the end when I tried to open test.tag, it still shows the error. 
I wonder what's the reason for this error and how should I solve it? The person in the tutorial used windows to run this code and I did exactly what he did in the tutorial. So I'm not sure why there is an error.

**Comment by kensoh** [comment]
Hi @AndyHuang1008 I have not come across this error before reported by users. What happens if you enter `tagui live`?

This error is likely something related to the OS environment, and probably not easy to troubleshoot. Would you be able to join our Zoom call that happens weekly on Thursday 4-5pm (SGT, UTC+8)? Here the meeting link - https://github.com/kelaberetiv/TagUI/issues/914

Offhand I cannot think of any other causes without trying out stuffs and finding out more info.
