### ISSUE TITLE
[enter] using type() function - use keyboard or visual automation for real keyboard [enter]

### ISSUE THREAD

**Issue by anikalthh** [kelaberetiv/TagUI#1167]
Why does this function output true but it actually doesn't press the enter button on the keyboard? Is there a workaround for this issue without having to use tagui's visual automation? I would like to use the python rpa package on its own. Would love some help as I've been stuck for quite long, thank you!

**Comment by kensoh** [comment]
Hi @anikalthh if you are using Python rpa package, you can raise the issue at https://github.com/tebelorg/RPA-Python/issues because that is still a personal project I support in personal time. If there is `[enter]` string in the type function and you are using web identifiers, then it sends a `\r` key to Chrome, which is the key to mean enter.

For making real keyboard enter keys, you can use keyboard() function with `[enter]`, or use visual automation of type step - `type textbox.png as [enter]`

**Comment by kensoh** [comment]
cc @ruthtxh
