### ISSUE TITLE
Greyed Screen after entering into URL - some idea for this sporadic website issue

### ISSUE THREAD

**Issue by youngyeeer** [kelaberetiv/TagUI#1172]
Hi,

This is something I face when running my TagUI flows. The page is greyed so UI interactions fail, but upon some hovers around the page then it would render. Is there a workaround to handle such a case? This happens sporadically.

![image](https://user-images.githubusercontent.com/64126540/151507028-b4bb2ba6-9431-4853-a598-f97561134db6.png)

**Comment by kensoh** [comment]
Hi, I assume that this happens if you manually browse the website?

Such a case is difficult to automate because of the randomness of when this happens. An idea is you can design your automation to give some signal that it is successfully completed. And then may be schedule it periodically so that it will keep running until the success signal is achieved.

**Comment by youngyeeer** [comment]
Thanks for the response! I'll have to experiment with some approaches to fail-proof the automation.

**Comment by youngyeeer** [comment]
-

**Comment by kensoh** [comment]
Welcome! Let us know more if you run into problems :)
