### ISSUE TITLE
Visual automation not working correctly - see some checks here

### ISSUE THREAD

**Issue by NnamdiG** [kelaberetiv/TagUI#1173]
So I'm trying to use TagUI for a project that I have and I'm testing the visual automation mode. Whenever I'm trying to double click a '.png' image on my desktop, instead it is just double clicking the text in my terminal. Any ideas why this is happening?

Thanks, 
Benn Gin
<img width="563" alt="Screen Shot 2022-01-31 at 2 19 08 PM" src="https://user-images.githubusercontent.com/47512167/151866527-47e557a3-4ad6-4d47-9867-fa5f3ef7fecf.png">

**Comment by ruthtxh** [comment]
Hi @NnamdiG 

For RPA Python questions, please raise issue over at https://github.com/tebelorg/RPA-Python.

You can check if your image exists in the same folder as your flow file when using relative path. Otherwise you have to use an absolute path when calling the image. If the path points to an image file that does not exist, then it will treat the path as a text to be found on the screen.

**Comment by kensoh** [comment]
Adding on some other possibilities, could be to make sure that the desktop is actually visible and not hidden behind the terminal. Visual automation mode works by whatever is displayed on your primary monitor.

But, most likely it sounds like the file may not be at that folder, so the RPA engine resorts to using OCR to click onto the screen which matches the `lebron`word. We'll close this issue here.
