### ISSUE TITLE
使用本地Chrome而非启动调试浏览器的方法

### ISSUE THREAD

**Issue by clovelee** [kelaberetiv/TagUI#1188]
在使用Tagui时，启动的是一个新的调试浏览器。没有日常使用的浏览器插件。想问一下，如何将启动改成一个现存的本地浏览器，而非调试。

**Comment by ruthtxh** [comment]
Hi @clovelee，if you want to do web automation and control the elements using XPath, then you will have to use the special chrome user profile instead of your existing browser. If you want to use your existing chrome browser, you can only do visual automation using OCR because there is no connection established to control the web elements directly. Let me know if you need me to translate this into Chinese I can try.

**Comment by twinyk** [comment]
肯定需要啊。翻译一下呗
















At 2022-03-01 11:40:24, "Ruth" ***@***.***> wrote:

Hi @clovelee，if you want to do web automation and control the elements using XPath, then you will have to use the special chrome user profile instead of your existing browser. If you want to use your existing chrome browser, you can only do visual automation using OCR because there is no connection established to control the web elements directly. Let me know if you need me to translate this into Chinese I can try.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ruthtxh** [comment]
如果您想使用 XPath 来控制网页元素那得使用 TagUI 的调试浏览器。如果您想使日常使用的浏览器，只能用 OCR 进行视觉自动化，因为只有 TagUI 的调试浏览器已建立网络套接字连接

**Comment by clovelee** [comment]
@ruthtxh 谢谢你的回复，不需要翻译的，我的电脑自带了翻译插件。OCR如何使用，我会尝试一下。我另外查到了一种方法：[https://github.com/natkuhn/Chrome-debug。我的设想是：若是造出一个9222的端口作为现有浏览器的复制版，而tagui运行调试窗口时，去这个新的9222的端口，是不是可行。我按步骤操作了，虽然可以造出9222的窗口，但是和tagui仍然不能连接。或者是我少了什么，比如修改--user-data-dir的地址来指定？我不知道应该怎么继续往下走来实现···](https://github.com/natkuhn/Chrome-debug%E3%80%82%E6%88%91%E7%9A%84%E8%AE%BE%E6%83%B3%E6%98%AF%EF%BC%9A%E8%8B%A5%E6%98%AF%E9%80%A0%E5%87%BA%E4%B8%80%E4%B8%AA9222%E7%9A%84%E7%AB%AF%E5%8F%A3%E4%BD%9C%E4%B8%BA%E7%8E%B0%E6%9C%89%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%E5%A4%8D%E5%88%B6%E7%89%88%EF%BC%8C%E8%80%8Ctagui%E8%BF%90%E8%A1%8C%E8%B0%83%E8%AF%95%E7%AA%97%E5%8F%A3%E6%97%B6%EF%BC%8C%E5%8E%BB%E8%BF%99%E4%B8%AA%E6%96%B0%E7%9A%849222%E7%9A%84%E7%AB%AF%E5%8F%A3%EF%BC%8C%E6%98%AF%E4%B8%8D%E6%98%AF%E5%8F%AF%E8%A1%8C%E3%80%82%E6%88%91%E6%8C%89%E6%AD%A5%E9%AA%A4%E6%93%8D%E4%BD%9C%E4%BA%86%EF%BC%8C%E8%99%BD%E7%84%B6%E5%8F%AF%E4%BB%A5%E9%80%A0%E5%87%BA9222%E7%9A%84%E7%AA%97%E5%8F%A3%EF%BC%8C%E4%BD%86%E6%98%AF%E5%92%8Ctagui%E4%BB%8D%E7%84%B6%E4%B8%8D%E8%83%BD%E8%BF%9E%E6%8E%A5%E3%80%82%E6%88%96%E8%80%85%E6%98%AF%E6%88%91%E5%B0%91%E4%BA%86%E4%BB%80%E4%B9%88%EF%BC%8C%E6%AF%94%E5%A6%82%E4%BF%AE%E6%94%B9--user-data-dir%E7%9A%84%E5%9C%B0%E5%9D%80%E6%9D%A5%E6%8C%87%E5%AE%9A%EF%BC%9F%E6%88%91%E4%B8%8D%E7%9F%A5%E9%81%93%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E7%BB%A7%E7%BB%AD%E5%BE%80%E4%B8%8B%E8%B5%B0%E6%9D%A5%E5%AE%9E%E7%8E%B0%C2%B7%C2%B7%C2%B7)

**Comment by ruthtxh** [comment]
Ok thanks @clovelee I don't recommend using visual automation for websites because it is not reliable, and the elements have to be displayed on the screen then it can be found. If it is not scrolled into view, you cannot interact with it.

For visual automation, instead of XPath, you can save a snapshot of the element as an image and do something like this for example
```
click image.png
```
you can use both relative and absolute file paths to the image. If you use relative file path, you can place the image in the same folder as the flow file.

You can reference to an example of visual automation [here](https://github.com/aimakerspace/TagUI-Bricks/tree/master/IRAS-Notice-OCR)

**Comment by clovelee** [comment]
@ruthtxh Thank you for your reply and help.
