### ISSUE TITLE
always crash on windows 11 - pending logs

### ISSUE THREAD

**Issue by hunter-xue** [kelaberetiv/TagUI#1190]
chrome engine quit randomly without any error messages.

**Comment by ruthtxh** [comment]
Hi @hunter-xue what does it show on the command prompt? Does it hang at the last step?

Can you also attach the log in tagui\src\tagui.sikuli for more clues. Thanks!

**Comment by ruthtxh** [comment]
Closing issue due to lack of updates, feel free to reopen.

**Comment by shaozhenzhou** [comment]
I encountered the same problem, the Chrome engine crashes immediately upon startup. When I use the tagui live command, the SikuliX engine opens normally, but the Chrome engine crashes immediately after starting (around 1 second). Please assist in troubleshooting this issue, thank you!

tagui.log
[tagui] START  - listening for inputs

[tagui] FINISH - stopped listening
IDE terminated: returned: 0

tagui_sikuli.in
finish 

tagui_sikuli.out
[0] FINISH

C:\Users\shaoz> python --version
Python 3.12.7

C:\Users\shaoz> java --version
openjdk 23.0.2 2025-01-21
OpenJDK Runtime Environment (build 23.0.2+7-58)
OpenJDK 64-Bit Server VM (build 23.0.2+7-58, mixed mode, sharing)

PS C:\Users\shaoz> tagui
tagui v6.114: use following options and this syntax to run - tagui flow_filename option(s)

tagui live     launch TagUI live mode enabled with visual automation for interactive development
tagui update   download and update to latest TagUI version (please backup your version beforehand)
input(s)       add your own parameter(s) to be used in your automation flow as variables p1 to p8
data.csv       specify a csv file to be used as the datatable for batch automation of many records
-deploy    -d  generate .cmd file which can be double-clicked to run workflow with specific options
-headless  -h  run on invisible Chrome web browser instead of visible as default (first install Chrome)
-nobrowser -n  run without any web browser, for example to perform automation only with visual automation
-report    -r  track run result in tagui\src\tagui_report.csv and save html log of automation execution
-turbo     -t  run automation at 10X the speed of normal human user (read the caveats in usage guide)
-quiet     -q  run without output except for explicit output (echo, show, check steps and errors etc)
-edge      -e  run TagUI using Microsoft Edge instead of Google Chrome (can be used with -headless)

C:\Users\shaoz> systeminfo
主机名:             ALIENWARE
OS 名称:            Microsoft Windows 11 家庭中文版
OS 版本:            10.0.26100 暂缺 Build 26100
OS 制造商:          Microsoft Corporation
OS 配置:            独立工作站
OS 构建类型:        Multiprocessor Free
注册的所有人:       shaozhenzhou@outlook.com
注册的组织:         暂缺
产品 ID:            00326-40000-00000-AAOEM
初始安装日期:       2024/12/18, 18:28:14
系统启动时间:       2025/2/16, 15:57:03
系统制造商:         Alienware
系统型号:           Alienware Aurora R11
系统类型:           x64-based PC
处理器:             安装了 1 个处理器。
                    [01]: Intel64 Family 6 Model 165 Stepping 5 GenuineIntel ~3792 Mhz
BIOS 版本:          Alienware 1.0.24, 2024/4/2
Windows 目录:       C:\WINDOWS
系统目录:           C:\WINDOWS\system32
启动设备:           \Device\HarddiskVolume1
系统区域设置:       zh-cn;中文(中国)
输入法区域设置:     zh-cn;中文(中国)
时区:               (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:       65,305 MB
可用的物理内存:     34,329 MB
虚拟内存: 最大值:   69,401 MB
虚拟内存: 可用:     24,025 MB
虚拟内存: 使用中:   45,376 MB
页面文件位置:       C:\pagefile.sys
域:                 WORKGROUP
登录服务器:         \\ALIENWARE
修补程序:           安装了 3 个修补程序。
                    [01]: KB5050577
                    [02]: KB5051987
                    [03]: KB5052085
网卡:               安装了 3 个 NIC。
                    [01]: Killer E3000 2.5 Gigabit Ethernet Controller
                        连接名:      以太网
                        启用 DHCP:   是
                        DHCP 服务器: 10.0.0.2
                        IP 地址
                          [01]: 10.0.0.10
                    [02]: Killer(R) Wi-Fi 6 AX1650i 160MHz Wireless Network Adapter (201NGW)
                        连接名:      WLAN
                        状态:        媒体连接已中断
                    [03]: Bluetooth Device (Personal Area Network)
                        连接名:      蓝牙网络连接
                        状态:        媒体连接已中断
基于虚拟化的安全性: 状态： 正在运行
                    所需的安全属性:
                    可用的安全属性:
                          基本的虚拟化支持
                          DMA 保护
                          安全内存覆盖
                          UEFI 代码只读
                          基于模式的执行控制
                          APIC 虚拟化
                    Services Configured:
                    Services Running:
                    App Control for Business policy: 强制
                    App Control for Business user mode policy: 关
                    已启用安全功能:
Hyper-V 要求:       已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。

**Comment by kensoh** [comment]
Hi @shaozhenzhou , can you share what is in tagui/src/tagui_chrome.log ?

Furthermore, can you open tagui/src/tagui.cmd look for this line. change `start` to `echo`. This should hopefully show the command to start Chrome browser. So that you can manually run that command in your command prompt to see why Chrome quits immediately on initialisation.

```
start "" "!chrome_command!" --user-data-dir="%~dp0chrome\tagui_user_profile" !chrome_switches! !window_size! !headless_switch! !no_sandbox_switch!
```
