### ISSUE TITLE
vision step hangs - probably wrong SikuliX syntax, try normal click step with visual automation instead

### ISSUE THREAD

**Issue by fjchavez** [kelaberetiv/TagUI#1192]
Hi,

I have a finished flow, the flow has visual automation.
I want to run that flow on an amazon aws server that has windows server installed.
I have tried several times and the flow fails right at the line of sight....
How can I solve this problem?

**Comment by ruthtxh** [comment]
Hi @fjchavez does the problem only occur with visual automation, how about steps that don't require visual automation?

Some factors you can consider is, is the display showing on your server when running the automation? Since it requires a matching of what is displaying on the screen.

What is the error message you are getting upon running the flow?

**Comment by fjchavez** [comment]
Hi @ruthtxh ,

I currently log in via windows remote desktop and run the flow.
The xpath statements 
![2022-03-07_01-15-36](https://user-images.githubusercontent.com/30538191/156978326-ceddc90b-ae17-408d-8df6-9cd20e47c549.png)
work correctly.
When it gets to the vision part it stops.
Attached is a screen shot of the message.

**Comment by ruthtxh** [comment]
Hi @fjchavez perhaps the syntax for SikuliX you are using is incorrect.

If you want to do a visual automation click you can simply use the TagUI click step, like this:
```
click C://somefilepath//image.png
```

note that if you use the forward slash, it has to be double so that the character can be escaped when parsing. Single backslash should be ok.

**Comment by ruthtxh** [comment]
Closing issue due to lack of updates, feel free to reopen.
