### ISSUE TITLE
How to do a "middle mouse" click & keydown + click - use vision step, some suggestions

### ISSUE THREAD

**Issue by pohhian** [kelaberetiv/TagUI#1198]
Wonder how to do a middle mouse click in tagui.
Alternatively how to simulate a hold-down specific Keyboard key while "click" ?

Thanks.

**Comment by marcelocecin** [comment]
hello 
use custom code `vision`

https://tagui.readthedocs.io/en/latest/reference.html?highlight=sikuli#vision

maybe with one of these commands:

https://sikulix-2014.readthedocs.io/en/latest/region.html

or

https://raiman.github.io/SikuliX1/javadocs/org/sikuli/script/Mouse.html

**Comment by ruthtxh** [comment]
Thanks for the suggestion @marcelocecin. Yes indeed you can use the vision step with SikuliX commands directly.

You can try the step here for middle mouse click
https://answers.launchpad.net/sikuli/+question/167430

For mouse hold and click you can do something like
```
vision begin
keyDown(Key.CTRL)
click(Location(200,500))
keyUp()
vision finish
```

**Comment by pohhian** [comment]
Thanks to @ruthtxh @marcelocecin . 
I was trying to avoid using vision so as the automation can run headless.
Nevertheless the recommendation does making sense of a workaround.

[It does not work when i tested it but it is due to fact i do not have admin right when running the process. I saw somehow somewhere that it could be the lacking of admin issue so the vision failed to control the mouse somehow] 
Nevertheless the failure of vision command shall be a totally different topic then. Will check separately. Thanks.

**Comment by kensoh** [comment]
Not sure if this is Ryan? 😄

Adding on, there isn't a middle button because it is rarely used on websites. However, you can explore using below code to see if it helps. Below is the sequence of code within TagUI to do a click, but modified to do a middle button click.

```
chrome.scrollIntoViewIfNeeded(selector);
var xy = chrome.mouse.getXY(selector);
chrome.mouse.action('mouseMoved',xy.x,xy.y,'none',0);
chrome.mouse.action('mousePressed',xy.x,xy.y,'middle',1);
chrome.mouse.action('mouseReleased',xy.x,xy.y,'middle',1);
```

For holding a key down, it might be possible but I have not tried and validate that before. It will probably involve writing some custom Chrome instructions to do, using the following Chrome API and using TagUI's chrome_step() function. Live mode can be use to explore the sequence needed but I don't think it is straightforward.

https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchKeyEvent

**Comment by pohhian** [comment]
Thanks and really appreciate it.  I do manage to have it work by directly using those line of codes.
