### ISSUE TITLE
How to deploy flow that only runs with admin rights? - some suggestions

### ISSUE THREAD

**Issue by Shivang310** [kelaberetiv/TagUI#1210]
hi @ruthtxh I am having problem in deploying the tag file as in the system I am working on the tag file can only run in cmd as admin in normal cmd it is not working and even if I use -d to deploy the tag file and then double click it is not runing can you please help me with this issue

**Comment by ruthtxh** [comment]
Hi @Shivang310 

I think due to some permission issues especially on company pc you are required to run as admin for the flow to work properly (most likely for the SikuliX process to run).

In the meanwhile you can try the following solution which is to create a short cut and set the short cut permission to run as admin. More details here https://stackoverflow.com/questions/30480228/run-command-to-open-command-prompt-as-administrator (see highest score solution)

For the step 2 - Enter Location you can do something like this:
```
%windir%\system32\cmd.exe /k "cd your_flow_folder_location & tagui flow.tag"
```

**Comment by Shivang310** [comment]
@ruthtxh can you please tell me about the second step as i have tried 
%windir%\system32\cmd.exe /k "cd C:\RPA\tagui\src\tagui & tagui filezilla.tag" and 
%windir%\system32\cmd.exe /k "cd C:\RPA\tagui\flows\samples\fileZilla\filezilla.tag & tagui flow.tag"
both are showing me 
The directory name is invalid.
ERROR - cannot find filezilla.tag 
As I have to run the file for crone job in the windows

**Comment by ruthtxh** [comment]
Hi @Shivang310, can you try this? Assuming you have the flow named filezilla.tag inside your C:\RPA\tagui\flows\samples\fileZilla folder.

```
%windir%\system32\cmd.exe /k "cd C:\RPA\tagui\flows\samples\fileZilla & tagui filezilla.tag"
```

**Comment by Shivang310** [comment]
hello @ruthtxh  it worked thank you very much but can I run this as a crone job as everytime I double click it is asking for permission

**Comment by ruthtxh** [comment]
Hi @Shivang310 

You may want to check out the suggestions here if you are using windows task scheduler on how to bypass it for automated tasks. https://www.sevenforums.com/tutorials/11949-elevated-program-shortcut-without-uac-prompt-create.html

Generally, UAC (the prompt for permission) is a setting for your whole computer so whenever you run as admin it will appear.

**Comment by Shivang310** [comment]
@ruthtxh  it worked thank you very much

**Comment by ruthtxh** [comment]
That's great, closing this issue for now, feel free to reopen.
