### ISSUE TITLE
希望可以增加 click http://xxxxx.com/image/button.png - some thoughts

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1213]
Ruth，你好，我把 .tag 放到服务器后，发现点击图片命令还是读的本地图片，

希望可以增加 click http://xxxxx.com/image/button.png

支持点击服务器图片，这样整个流程所需文件都放服务器，运行起来也方便。

**Comment by ruthtxh** [comment]
Hi @kangyiwen for visual automation, it is best if you can take a screenshot of the element in the same machine you are running the automation on. This is because different computers have different screen resolutions, so most of the time your screenshot based on another computer would not work. As such, it is best that the images are saved locally and are specific to that machine's screen resolution.

**Comment by kangyiwen** [comment]
哦 谢谢，理解了。我的使用场景是 N台一模一样的WINDOWS电脑使用，所以会想到这个需求。

**Comment by kensoh** [comment]
This is an interesting question, and asked for the first time by user. Technically this feature can be done, but it feels heavy because the TagUI .tag file will have many long lines of `click https://.....`

Another idea could be TagUI auto-downloading all image files if the .tag file that is executed is hosted online. However, this has problem with the usage scenario where users want to use that own local images with an online .tag file. It will overwrite their local image files, or fail when reading missing online image files.

I don't have a clear idea which way would be good to implement a feature like this. Any thoughts, Ruth and Yi Wen? Also, it might be not a major use case to add, compared to other new TagUI features on your roadmap, Ruth.

In the meantime, something like the following can be done. At the start of your TagUI .tag file, you can configure it to download the images required, using the `curl` tool that is included with TagUI.

```
curl -k -s -L -o image1.png http://xxxxx.com/image/image1.png
curl -k -s -L -o image2.png http://xxxxx.com/image/image2.png
curl -k -s -L -o image3.png http://xxxxx.com/image/image3.png
curl -k -s -L -o image3.png http://xxxxx.com/image/image4.png
```

`-k` to allow insecure connection if the server is not SSL secured
`-s` is to perform the download silently
`-L` is to automatically handle redirection if the link redirects to another URL.
`-o` is to point what file name to save as. Note that by default, without including the path, I think it saves to `tagui/src` folder.

**Comment by kangyiwen** [comment]
我想到的方案：在 .tag 里，增加一个参数，可以有下面2个值：
img_source = 'local'
img_source = 'http://xxxxxx.com/img/'

img_source 如果是带http的，就默认代码内的图片前面带这个URL，例如：
click  button.png  实际运行 click http://xxxxxx.com/img/button.png
这样代码看着就不乱了，同时本地调试和服务器使用切换很方便。


.tag 发现需要点击服务器图片时，可以先建立个零时目录  例如 temp，然后把所有图片先下载到这个目录，然后继续执行，默认图片路径都在 temp 内。

或者，执行 click 时，自动先下载图片，保存为一个随机文件名.png，然后执行 click 随机文件名.png   
接下去还有 click 时，还是这样操作，保存并覆盖 随机文件名.png，然后执行 click 随机文件名.png

**Comment by ruthtxh** [comment]
@kensoh to confirm you're thinking of having the feature only be for hosted online tag files? Why only for online tag files though...

**Comment by kensoh** [comment]
When I created the online .tag feature, I think the only other support is datatable csv file, if it is available in the same URL and same name as the .tag file. Being able to pull image files from online to run locally would be great to have.

But will have to weigh that amongst other items on the roadmap, in terms of the potential userbase benefitting from this feature vs other features in mind. We can explore more on tomorrow's Zoom call.

**Comment by ruthtxh** [comment]
For visual automation most likely it won't be able to completely match an online image or an image screenshot taken on another computer due to resolution issues. I don't see a big use case for this, unless the hosted image can be used for another purpose other than visual automation.

**Comment by kensoh** [comment]
In that case, maybe use the above curl method. Yi Wen can also consider zipping up all the image files so that only 1 line of run curl is needed inside .tag file.

And can combine with some unzip command to do the unzipping.

https://github.com/kelaberetiv/TagUI/issues/1213#issuecomment-1108233807

**Comment by kangyiwen** [comment]
嗯，图片先ZIP，下载解压到本地，是个方法。
