### ISSUE TITLE
.tag 里如何进行多行注释？

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1224]
请问，在.tag 文件里如何进行多行注释？

我尝试用了 ` /*    */ `  但没成功，请问应该怎样进行多行注释？

谢谢

**Comment by ruthtxh** [comment]
Hi @kangyiwen 

You can only make single line comments using // in TagUI.

**Comment by kangyiwen** [comment]
谢谢   我现在选中多行，用 ctrl+q （notepad++快捷键）进行多行注释。

**Comment by kensoh** [comment]
Indeed, because TagUI doesn't have the logic to support /* and */

However, a workaround, if really needed is write in JavaScript
```
js begin
/* some long form comments
some more comments
further comments
end of comment */
js finish
```

Above will work. But I know is very ugly script lol 🤣

**Comment by kensoh** [comment]
fyi @ruthtxh

**Comment by kangyiwen** [comment]
还是希望 .tag 未来可以支持多行注释。

**Comment by kensoh** [comment]
Hi @kangyiwen, and @ruthtxh, I had a close look at the TagUI codebase. Technically supporting `/* */` block comments is doable. However, it slows down execution by a bit. The most reliable way to reduce chance of breaking existing user scripts is to do special parsing before expanding tagui subflows, and parsing again after.

Parsing before tagui step is important because calling a sub-flow within the comment block should not be done. Parsing after tagui step is also important because the feature should also work for comment blocks in subflows. Then change everything between `/* */` to `//`.

However, this strategy means reading .tag files 2 times extra to do the parsing. And this comes at expense of most users who are not going to use the feature. For now, will recommend using js begin / finish workaround or IDE shortcuts. Perhaps when more users raise this again, can relook whether it makes sense to add that additional overhead.

Also, special care must be taken to make sure common XPath strings like `//*`are not accidentally treated as multi-line comments, perhaps only when the line begins with `/*`. This is just one case which can break, but there could be more situations which may break existing user code if not done carefully.

**Comment by kensoh** [comment]
I have some time tonight and was thinking to add in the new feature to support `/* */`. But after reviewing, I believe it is a net negative for TagUI users in general, due to risks of possibly breaking existing scripts, and the small overhead in parsing when running the TagUI scripts. So I just leave just thoughts above for future consideration when users raise this again.
