### ISSUE TITLE
依然还没搞懂，何时改用 JS 语法，何时可以用 TagUI语法

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1227]
@ruthtxh @kensoh 你们好，TagUI 兼容 JS 语法，但2个语法之间切换，真的是非常烧脑的问题，把我弄的有些晕了。

下面这个问题，请问为什么 tagui 语法运行后，结果不正确，正确的TagUi语法如何使用  indexOf()？

```
list = ["aa.mov","bb.mp4"]
echo `list[1]`

//tagui 语法  
指定扩展名="mp4"
字符位置=`list`[1].indexOf(`指定扩展名`)
echo `字符位置` <---------------------------------------结果是 -1  表示没有找到，结果不正确

//JS 语法
js begin
	字符位置=list[1].indexOf(指定扩展名)+1 
js finish
echo `字符位置`  <--------------------------------------结果是4，结果正确
```

谢谢

**Comment by kangyiwen** [comment]
另外使用  echo 时，下面正确的语法是什么？

```
list = ["aa.mov","bb.mp4"]
echo `list[1]`

指定扩展名="mp4"
echo `list`[1].indexOf(`指定扩展名`)
echo `list[1].indexOf(`指定扩展名`)`
echo `list[1].indexOf(指定扩展名)`
```

请问正确的 echo 应该怎么写？
echo 是否支持这种变量里面套变量？
谢谢

**Comment by ruthtxh** [comment]
Hi @kangyiwen
In programming, arrays begin with 0 instead of 1, so in this scenario, to get the first item of the list, you have to have to access the item of index 0:
```
list = ["aa.mov","bb.mp4"]
echo `list[0]`
echo `list[1]`
```

Next, in programming, variables cannot have spaces in them too. You can use an underscore in place of space. Try this.
```
specify_extension="mp4"
echo `list[0].indexOf(specify_extension)`
echo `list[1].indexOf(specify_extension)`
```
the results should return -1 and 3. The first case returns -1 because "aa.mov" does not have the string "mp4". The second case returns 3 because the string "mp4" is found in "bb.mp4" at the index of 3 (counting from 0).

**Comment by kensoh** [comment]
Adding on, the complexity of TagUI language could be a positive. Means lesser pool of developers to serve clients.

Instead of expensive software licenses, charge money for service but $0 for the software.

**Comment by kangyiwen** [comment]
@ruthtxh  谢谢，原来我最后这句 `echo `list[1].indexOf(指定扩展名)``  是对的。

@kensoh TagUI 复杂程度比我想的高不少，很多细节只有做实际流程时，才会想到。
