### ISSUE TITLE
建议增加 tagui -k  参数 to kill processes - method unreliable

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1232]
我在一台闲置电脑上写了一个流程（大概步骤是打开网页，读取数据，关闭网页），然后用计划任务每隔15分钟运行一次，运行一次约2分钟。

目前遇到的问题是：当上一次运行没有正常完成，就会造成后续都无法运行，图：
![image](https://user-images.githubusercontent.com/76672577/168935889-f156b176-3ad8-417d-8041-4e690676c368.png)

我手动运行 end_processes.cmd  后，就可以恢复运行。

我的问题是：如何在 .tag 运行前，执行 end_processes.cmd  ？ 
.....  我想到了，在生产的流程cmd文件里，加上 end_processes.cmd 。

**建议**
是否 tagui 可以增加一个参数，例如  tagui  -k    就是 kill 掉之前的所有相关进程，再运行新进程？
这样会方便不少。

**Comment by kangyiwen** [comment]
还是没实现。。。

我在cmd里添加了 `"D:\TagUI\src\end_processes.cmd"`，但运行后发现残留进程是杀掉了，但后续没有正常运行 tqbotjk.tag，请问要如何处理？

```
@echo off 
"D:\TagUI\src\end_processes.cmd"
cd /d "C:\Users\Administrator\Documents\TagUI\TQbotjk" 
"D:\TagUI\src\tagui" "C:\Users\Administrator\Documents\TagUI\TQbotjk\tqbotjk.tag"         

```

**Comment by kensoh** [comment]
Inside a batch file, when you run another batch or cmd file, have to use call command. Otherwise it does not come back to run the lines after that.

call "D:\TagUI\src\end_processes.cmd"

For adding option to kill before starting, it is hard. Because end_processes.cmd will end up killing TagUI process itself and it will not continue to run after killing itself.

For Python version, it kill existing process by default by calling end processes first, then run tagui command. Similar to the idea you do above.

**Comment by kensoh** [comment]
Copying @ruthtxh for her thoughts

**Comment by kangyiwen** [comment]
哈！  谢谢 @kensoh ，可以了
```
call "D:\TagUI\src\end_processes.cmd"
```

我也记录到中文说明里去。

**Comment by kangyiwen** [comment]
流程cmd里用了 call 后，直接双击运行流程cmd，可以先杀进程后运行流程了。 但放到 计划任务里，就一直报错。

我单独在计划任务里执行 end_processes.cmd  时，会报错，但直接运行不会报错，请问这是为什么？
![image](https://user-images.githubusercontent.com/76672577/169033991-b4c4d8b7-e5a9-461d-b49f-ec2975d5dfc7.png)

**Comment by kangyiwen** [comment]
找到解决方法了，要在计划任务里，填写文件路径就可以。

![image](https://user-images.githubusercontent.com/76672577/169040883-937cc019-b39d-4df1-809e-db20b32fa7de.png)

**Comment by kangyiwen** [comment]
找到方法了，要在这里填写路径才可以在计划任务里正常运行。
![image](https://user-images.githubusercontent.com/76672577/169041338-b0fd0bd6-e96b-4f7b-a9da-ea2a434972db.png)

**Comment by ruthtxh** [comment]
Hi @kangyiwen another way you can explore is to find out what is the line of code that is mostly causing the error on every run and try to handle it within the flow such as calling end_processes when it happens. So instead of calling end_processes before your new run, you call it upon your previous run when you error out.

**Comment by kangyiwen** [comment]
谢谢，我学习下怎么操作。

**Comment by kangyiwen** [comment]
@ruthtxh  我有点不明白，如何让 a.tag 报错后执行 end_processes，然后再继续执行 a.tag，一直到 a.tag 正常运行完毕？或者连续报错5次，退出流程？

能给下例子代码吗？ 谢谢
