### ISSUE TITLE
Can't find the exportToFieldTaggedButton - try using XPath instead

### ISSUE THREAD

**Issue by Xiaojun928** [kelaberetiv/TagUI#1235]
Hi，

I am trying to use TagUI scrape data from [web of science](https://www.webofscience.com/). After open the url, I got the error like this

`click exportToFieldTaggedButton
ERROR - cannot find exportToFieldTaggedButton`

I use TagUI at win10, and the browser is Chrome
Could you please give me some help?
Thanks in advance!

Best,
Xiaojun

**Comment by ruthtxh** [comment]
Hi @Xiaojun928 I am unable to access that website as it requires login.

Perhaps instead of using attribute as an identifier, you may want to use XPath instead. You can copy the XPath by right clicking on the element > Inspect. Then in the the developer tools console right click the element again > Copy > Copy XPath.

**Comment by Xiaojun928** [comment]
Many thanks for your reply! I will try it later to see if it works.


Cheers,
Xiaojun
