### ISSUE TITLE
href on element

### ISSUE THREAD

**Issue by adegard** [kelaberetiv/TagUI#153]
How can I retrieve the href attribut of an element?
Thanks!

**Comment by adegard** [comment]
I found the solution with javascript integration...

element_identifier = '#c_16 > div:nth-child(1) > h3 > a'

js begin
var myurl = this.getElementsAttribute(element_identifier, 'href');
js finish

echo myurl

**Comment by kensoh** [comment]
Hi @adegard, a note is don't use var to define as a local variable. because in upcoming release, this local variable will strictly not be usable in the steps after it. also, TagUI will recognize the line as JS code automatically, so the following can be considered -

element_identifier = '#c_16 > div:nth-child(1) > h3 > a'
myurl = this.getElementsAttribute(element_identifier, 'href')
echo myurl

Lastly, the dom step in TagUI can also be used to run JS code directly in the HTML DOM to retrieve information or make changes to the HTML DOM using the usual JS code.
