### ISSUE TITLE
Any support for proxy?

### ISSUE THREAD

**Issue by pneely412** [kelaberetiv/TagUI#162]
Hello,

I am wondering if there is any support for proxies? If i’m not wrong, setProxy is supported on casperjs. Tried casper.options.setProxy = proxy and setProxy = proxy but both dosnt seem to be working. 

Anyway, loved this project and keep up the good work!

**Comment by kensoh** [comment]
Hi @pneely412 the default mode is running on PhantomJS. So you can do something like below as part of your TagUI script, before accessing the next URL under that proxy. The last 2 parameters are the username and password, if your proxy service provider requires credentials.

`phantom.setProxy('IP', 'port', 'manual', '', '');`

If you are running Chrome mode, the proxy setting has to be done manually, for example in the link below. And perhaps through a Chrome extension for your proxy service provider. You can also consider using the visual automation feature to do that configuration, if you really want to do it programmatically.

https://customers.trustedproxies.com/knowledgebase.php?action=displayarticle&id=10

---

Lastly, depending on your use scenario, something like the following may be applicable, though unlikely because the underlying browser is Chrome instead of Chromium - 

https://blog.apify.com/how-to-make-headless-chrome-and-puppeteer-use-a-proxy-server-with-authentication-249a21a79212

---

Thanks for your encouragement!! I'll close the issue but let us know if any questions..

**Comment by jdvalentini** [comment]
Hello @kensoh , I am working on an automation that needs to work with chrome. My environment is Windows Server 2012R2 and Chrome 75.0.3770.142 (Official Build) (64-bit).

While working with this automation I noticed that it would work with `chrome` but not `headless`. The headless version throws an error. I have been able to debug it to see something like `browser_process_sub_thread.cc(221) waited 5 ms for network service`

Soon enough I found out that Chrome Headless won't take IE proxy settings as Chrome would, and that was the error. Moreover, it will not even take the proxy settings set by [netsh], which should set the proxy system-wide.

Testing chrome with the --headless to hit the correct switch I found out that this command works:
`chrome.exe --headless --disable-gpu --dump-dom https://www.chromestatus.com --enable-logging --proxy-server="http=http://pro.xy.local:3128;https=http://pro.xy.local:3128"`

Effectively Chrome headless handles the proxy well, maybe if tagui could receive the proxy as an argument it could then pass this data through to Chrome somehow.

So far I have not been able to get a workaround for this, and I just had to make firewall exceptions for this host. I am pretty sure that is not a possibility for everyone

[netsh]: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet#configure-the-proxy-server-manually-using-netsh-command

**Comment by kensoh** [comment]
Hi Jorge, thanks very much for raising this and sharing your solution!

As TagUI primary use case is automating UI interactions for process automation, a typical use case will not involve using proxy to mask the traffic. Thus I won't add an option for Chrome to support cases like using proxy. However I'll look out for more use cases where running with special Chrome options make sense and I will review again to see if adding this is more valuable compared to working on other features.

In the meantime, I want to share a workaround which you can use directly from your solution above. Since TagUI is open-source, you can modify the source code to work the way you want. For Windows, tagui\src\tagui.cmd is the part to modify. For macOS / Linux, tagui/src/tagui is the file to modify.

For Windows, inside tagui.cmd there is below line -

```batch
start "" "%chrome_command%" !chrome_switches! !window_size! !headless_switch!
```

Users who want to use proxy for headless Chrome can try something like below -

```batch
start "" "%chrome_command%" !chrome_switches! !window_size! !headless_switch! --proxy-server="http=http://pro.xy.local:3128;https=http://pro.xy.local:3128"
```

What will happen above after appending the proxy setting, is TagUI will launch Chrome with the proxy parameter given by user. This should be able to replicate your success above in using the switch to run headless Chrome with proxy. The limitation would be the hard-coding only works for that proxy and not straightforward to rotate and change different proxies on each iteration.

You're welcome! TagUI becomes better and better over time because of user feedback such as what you shared. I appreciate you taking the time to share your findings! Because in this age, many open-source users would be too busy with work to have time to share back ❤️

**Comment by kensoh** [comment]
Adding on for completeness, for macOS, below is the line in tagui/src/tagui to change - 
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome $chrome_switches $window_size $headless_switch > /dev/null 2>&1 &
```

For Linux, below is the line in tagui/src/tagui to change - 
```
$chrome_command $chrome_switches $window_size $headless_switch > /dev/null 2>&1 &
```

**Comment by jdvalentini** [comment]
Thanks for your quick reply Ken. That is a perfect solution, to me that is good enough.

> As TagUI primary use case is automating UI interactions for process automation, a typical use case will not involve using proxy to mask the traffic. 

Regarding this, I just want to clarify. It does not have to do with traffic masking, it was just a requirement of the network I was in to be able to browse internet sites.

Cheers

**Comment by kensoh** [comment]
Thanks Jorge for clarifying, I'm sorry for assuming on the common use of proxy for masking.

In your professional network, is it common for companies to use proxies in order to access the internet? I'm thinking if this is a common use case in companies (due to network access restriction), then I may have to work out a way for users to provide their preferred proxy instead of hacking the tagui and tagui.cmd.

**Comment by jdvalentini** [comment]
I would not say it is common to use explicit proxy. In cases where direct internet access is not available it might be more frequent to have wpad-configured proxy or even transparent proxy via WCCP in layer 2 (which should work seamlessly). However, I still do see places where proxy is explicitly set.

**Comment by kensoh** [comment]
Thanks Jorge so much for telling me more. I understand now.. Got it, in that case I will hold back from implementing an option to configure proxy for TagUI chrome / headless mode. Workaround will be modifying tagui / tagui.cmd for now. Over the longterm, this will help keep the API set small and easier to use by implementing most often used features.
