### ISSUE TITLE
(suggestion) Able to build from source

### ISSUE THREAD

**Issue by wei3hua2** [kelaberetiv/TagUI#180]
Instead of pre-package and manual set-up. Suggest to be able to build from source. 

Rely on package manager to handle dependencies such as PhantomJS, CasperJS etc.

**Comment by kensoh** [comment]
Thanks @wei3hua2 for raising this idea! At the moment, you can use npm install tagui with all its dependencies - https://github.com/kelaberetiv/TagUI#packaged-installation

Alternatively, by downloading the packaged installation from above link, users can run TagUI directly with all dependencies included for Windows, Linux or macOS. I'll close the issue for now but do tell me more about what you mean by build from source, compared to the setup options above.

There's no need to build from source because TagUI's engine is not a binary but a combination of JS, PHP, Python, Bash, Batch scripts. The [manual setup-up option](https://github.com/kelaberetiv/TagUI#manual-installation) in readme is for users who would like to practise setting up the dependencies manually but is not required.

**Comment by wei3hua2** [comment]
@kensoh apology. I missed the package.json file somehow. Going for eye check tomorrow

**Comment by kensoh** [comment]
No probs James! Appreciate all the different users' feedback.

That was how the tool became better and better with time.

**Comment by wei3hua2** [comment]
By the way I love the tool a lot and given the potential of RPA and current lacking in open source alternative. I wish this project will be great. =)

Still studying the source code though.
