### ISSUE TITLE
How to stop closing chrome browser after flow execution

### ISSUE THREAD

**Issue by ramu-yarru** [kelaberetiv/TagUI#181]
Hi Ken,

Is there any way to stop closing the chrome browser after a flow execution (test)? Because the next flow being executed in my program is in continuation to the previous flow. If I can stop closing the browser, my thought is to check whether the next flow can be started from that point instead of opening a fresh browser and again start from begining, which will give faster response obviously. Here i can't combine the two flows due to limitations in my calling program. Could you please let me know is there any such feature available in TagUI?

Thanks,
Ramu

**Comment by kensoh** [comment]
Hi Ramu, can you tell me more about the limitations why the 2 flows cannot be combined? There is tagui step to run sub-flows and also run step which can be used to run child-flows as a subprocess. You may want to try download the [cutting edge version](https://github.com/kelaberetiv/TagUI/archive/master.zip) to overwrite your local packaged installation. And see if [tagui step](https://github.com/kelaberetiv/TagUI#modules) helps or the run step to run tagui command as a child-process helps.

At the moment, running TagUI with speed option will let batch automation run without restarting Chrome, but running separate flows will still restart Chrome. The reason is a technical limitation which requires starting a fresh Chrome session with websocket connection so that TagUI can talk to it, so the default behavior is killing after execution and starting again.

There is an [open existing issue on Chrome](https://github.com/kelaberetiv/TagUI/issues/164) but that one is to start in a separate process so that user's existing tabs don't get killed on running TagUI automation. I'll close the issue for now but please share more about your use scenario!

**Comment by ramu-yarru** [comment]
My Plan is to invoke/call tagUI webservice flows from a Model based testing tool. As you aware, model based testing tool generate different test paths at runtime and one path may be continuation/dependent on previous path. So I want to retain the chrome session.

Thanks,
Ramu

**Comment by kensoh** [comment]
I see, can you share what will happen if you combine the 2 scripts into 1 script? TagUI will be able to access other URLs halfway during execution to go to some other websites if needed.

Also, adding on, if visible Chrome mode is used, I think the session will remain as it is when the first flow is closed. If headless mode is used I think Chrome does not store the session details.
