### ISSUE TITLE
Can tagui detect the changes in a web application?

### ISSUE THREAD

**Issue by nsahithi** [kelaberetiv/TagUI#209]
Hi,
 Can tagui detect the changes in a web application when the version changes happens or a new feature has added? For example, In a recording, I selected an option from a drop-down field and the recording has played back successfully. After that a new feature(for ex, new drop-down option)  has added in the web application. As tagui detecting the selected element in the number order, can it detect the previously selected option successfully? Can tagui play recording successfully? Please explain.

Thanks & Regards,
Sahithi.

**Comment by kensoh** [comment]
Hi @nsahithi when developing a script you can record or specify the element identifier. If webpage changes and the old identifier is still valid, then the script will still work. However, that identifier may be pointing to the wrong element because it may be some other web element.

If the website changes and the identifier is now invalid, then TagUI will throw error message so that users can check if something has been broken due to website changes. My recommendation is use very strict element identifier (for example accurate XPath), so that breaks are flagged out immediately for investigation. It is better to have false-positive versus having the wrong impression that the automation is still working but it has already been broken.

There is a related option called baseline. If you run an automation script with the baseline option, TagUI will create a folder called baseline to store the execution results. This can be helpful to let you compare a run with a run in the past to check for any difference in execution.

eg below runs the yahoo sample and creates a baseline folder to store a copy of the script and the results + log of the automation -

```
tagui 1_yahoo baseline 
```

**Comment by kensoh** [comment]
fyi @Aussiroth and @lohvht
