### ISSUE TITLE
How to export status of a tagui script to database?

### ISSUE THREAD

**Issue by nsahithi** [kelaberetiv/TagUI#253]
Hi,
    We are working on metadata dash boards. For this, we are trying to push  tagui scripts execution status to database, every-time it runs. Is there any way to do this ? If so, please guide me..

Thanks in advance,
sahithi N.

**Comment by kensoh** [comment]
Hi Sahithi, if your database is exposed through webservice API, you can use the api step to send the info to your database via your webservice API.

If not, check out following issue showing examples of how you can write to your DB. There isn't a generic way to do so because different database needs different commands to write to it, following is mysql DB - https://github.com/kelaberetiv/TagUI/issues/112
