### ISSUE TITLE
Trigger action when error occures

### ISSUE THREAD

**Issue by adegard** [kelaberetiv/TagUI#270]
Hi @kensoh,

Is it possibile to add some trigger if an error succeed in Tagui ?

i.e. when tagui return
"ERROR - cannot find selector" then use API i.e. sending email to administrator...
Can I add some code directly in Tagui 's files to do that?

It could be usefull to control some automatic tasks.

Thanks you and I have a nice weekend!
Arnaud

**Comment by kensoh** [comment]
Hi @adegard the normal recommendation is to use the present() or visible() helper function to check if an element is there or not for parts in the workflow which is likely to have issues. But it can be very difficult if you want to do that for every step of the workflow.

Inside tagui_parse.php, there is a function end_tx and following block of code can be hacked to do other things you want to. For example making an API call with JavaScript to send emails with call_api() function or some other custom functions you can define.

`{this.echo('ERROR - cannot find ".$locator."').exit();}`

The downside will be (if you hack tagui_parse.php), in future releases when you update to new version, you will lose your modifications. This is because tagui_parse.php is a core file. Only tagui_local.js and tagui_global.js are custom files for [user-defined functions](https://github.com/kelaberetiv/TagUI#helper-functions).

Closing the issue but feel free to add on further discussion. Copying @Aussiroth as he is taking over supporting questions and advice on TagUI.
