### ISSUE TITLE
Using NodeJS code in tagui_global.js and inside TagUI scripts

### ISSUE THREAD

**Issue by ramu-yarru** [kelaberetiv/TagUI#297]
Hi,

Will tagui accept writing node JS code in tagui_global.js file. I wanna write a user defined function using node JS which has a require/import statement at the begining of the file. When I run the flow file which is calling this function, the execution is failing. So would like to know  whether tagui accept writing node JS code in tagui_global.js file or not.

Note: I have installed TagUI as a NPM package.

Thanks,
Ramu Y

**Comment by Aussiroth** [comment]
Hi, unfortunately TagUI runs on phantomjs, which does not accept and execute nodeJS code.

**Comment by kensoh** [comment]
Adding on, it is a design choice to build TagUI on PhantomJS versus on Node.js. This is because, with PJS, any user can unzip and run TagUI directly. But with Node.js, business users or companies with strict software installation policies will not be able to have Node.js installed on their laptops, and they will not be able to run TagUI automations.

In future if PJS does not work with a future version of Linux or Windows, may need to migrate TagUI to Node.js, but it comes with a cost that many current users won't be able to use TagUI anymore, unless they have IT department to allow Node.js.

**Comment by ramu-yarru** [comment]
Thank you Ken for the update. But I believe nowadays, Node JS is also available as a ZIP distribution (https://nodejs.org/en/download/). With this, there is absolutely no need for business users and companies to install Node JS. You can ship Node JS distribution along with TagUI zip file like you are doing for PJS.

**Comment by kensoh** [comment]
Hey Ramu @ramu-yarru, this is good information, thanks!

In that case, Alvin @Aussiroth (and copying Ryzal @ryzalk), this limitation may not be a concern when the time comes to migrate to Node.js. I can imagine a big rewrite of TagUI, making use heavily of existing code that talks to Chrome and the current overall automation framework. But anything to do with CasperJS will involve rewriting. For better or worse, that would also mean no execution on Firefox through SlimerJS or PhantomJS headless WebKit browser, and only running web flows on Chrome.

Personally though, I'll think a rewrite of TagUI in Python would open up more impact versus a rewrite for Node.js. A Python-based TagUI will probably make a bigger help to current data science and machine learning related user community, versus potential benefits of a Node.js TagUI over PJS TagUI.
