### ISSUE TITLE
unable to import npm package in tagui_global.js

### ISSUE THREAD

**Issue by tejaswiniarrob** [kelaberetiv/TagUI#299]
tried to require exceljs package in tagui_global.js

it says,
START - automation started - Tue Oct 30 2018 17:38:25 GMT+0530 (IST)
SyntaxError: Use of reserved word 'class'
../src/phantomjs:/platform/promish-class.js:15 in loadModule

ReferenceError: Can't find variable: Promise
..src/phantomjs:/platform/promish.js:5
Error: Cannot find module 'events'
../src/phantomjs:/platform/bootstrap.js:299 in require
..src/phantomjs:/platform/bootstrap.js:263 in require
../src/phantomjs:/platform/zip-stream.js:14
Error: Cannot find module 'stream'
..src/phantomjs:/platform/bootstrap.js:299 in require

Can you please help me with this?

**Comment by Aussiroth** [comment]
Hi, unfortunately since TagUI runs in phantomjs, which does not accept and execute nodeJS code, it is not possible to do stuff like import npm packages as you are trying to do.

**Comment by kensoh** [comment]
Adding on, it is a design choice to build TagUI on PhantomJS versus on Node.js. This is because, with PJS, any user can unzip and run TagUI directly. But with Node.js, business users or companies with strict software installation policies will not be able to have Node.js installed on their laptops, and they will not be able to run TagUI automations.

In future if PJS does not work with a future version of Linux or Windows, may need to migrate TagUI to Node.js, but it comes with a cost that many current users won't be able to use TagUI anymore, unless they have IT department to allow Node.js.

**Comment by kensoh** [comment]
linking this issue to https://github.com/kelaberetiv/TagUI/issues/297 (more info there)
