### ISSUE TITLE
How to switch to new browser window

### ISSUE THREAD

**Issue by Balajiiguru** [kelaberetiv/TagUI#308]
In web sutomation if I want to switch to new tab(browser window) how it is possible in tagui?

**Comment by Aussiroth** [comment]
Hi, to automate a new tab/window that launches due to the automation, you can make use of the popup step. The syntax is like
```
popup <keyword_identifier> {
    <<automation code for new tab/window here>>
}
```
Where the <keyword_identifier> should be some keyword within the url that you want TagUI to automate.
For example, the URL https://github.com/kelaberetiv/TagUI, you can use kelaberetiv or TagUI as keywords if they do not appear in any other URL within the open tabs/windows that session.
