### ISSUE TITLE
demostration for input

### ISSUE THREAD

**Issue by lim-enhui** [kelaberetiv/TagUI#326]
not quite sure on using demo 8 haste bin.

**Comment by lim-enhui** [comment]
do you have a demonstration for user to input their user id and password and thereafter automate the task?

**Comment by Aussiroth** [comment]
Hi, the hastebin demo is a simple TagUI script that automates the uploading of the log files to hastebin. The script is run by TagUI itself whenever the upload option is used in an automation flow. 
For inputing a userid and password, you can see sample 5 for an example of having TagUI directly type in the username and password. However, since the username and password will be stored as plaintext in the script, there may be privacy or security concerns. 
One way around this provided by TagUI is to use the live step instead of the steps to type the username and password. The user can then manually type in the username and password, then continue the automation flow.

**Comment by lim-enhui** [comment]
thanks. I met with another issue that i need to address
