### ISSUE TITLE
is it possible run TagUI on opened chrome window?

### ISSUE THREAD

**Issue by indruin** [kelaberetiv/TagUI#330]

**Comment by Aussiroth** [comment]
Hi, if you mean by a chrome window you currently have open, no. TagUI needs to start a new chrome session with a specific setup to make sure that the chrome browser session can be communicated with to allow TagUI to send commands to the browser to execute for the automation.

**Comment by indruin** [comment]
Ok. I understand it.

Please close the issue.

**Comment by harishweeroda** [comment]
@kensoh how to work on active window of chrome with chrome browser == False in init function , so that another chrome window wont get open . can we do this?

**Comment by kensoh** [comment]
It is not possible to automate through Chrome's backend for an existing Chrome window, because a backdoor needs to be open when Chrome is launched. But you can automate Chrome using computer vision and keyboard() like below -

https://github.com/tebelorg/RPA-Python#visual-automationsee_no_evil
https://github.com/tebelorg/RPA-Python#keyboard-automationmusical_keyboard
