### ISSUE TITLE
for select the css selector doesnt work .

### ISSUE THREAD

**Issue by SreenijaK** [kelaberetiv/TagUI#331]
I'm trying to enter value to dropdown by the following command.  

click (//SELECT[@class="form-control ng-pristine ng-untouched ng-valid"])[2]
select (//SELECT[@class="form-control ng-pristine ng-untouched ng-valid"])[2] as 1

The above is failing to identify the dropdown. 
PS:I don't want to use other ways of selection like xpath, etc.

**Comment by Aussiroth** [comment]
Hi, for this if you use chrome you can try right clicking on the select element you want, and right clicking it -> copy selector for css selector to make sure the selector is correct, or copy xpath for xpath selector. 
 While you mention you want to use a css selector instead of xpath, the selector you provided in the example here is an xpath selector. It should look similar to the screenshot here.
![image](https://user-images.githubusercontent.com/3212014/50683667-c8dd8e00-104d-11e9-978e-53070ace812a.png)

For doing the select, you need to provide the second argument (after the 'as') to be the value of the option you want selected. For an example of how it should be, check the issue here https://github.com/kelaberetiv/TagUI/issues/305

I hope these help you!
