### ISSUE TITLE
How do I open chrome browser halfway during automation?

### ISSUE THREAD

**Issue by lim-enhui** [kelaberetiv/TagUI#337]
hi there is html element that i cannot select so i'd like to open chrome after execute some script and let the user self input the data to the elements. But i do not find any section to provide support to open chrome command.

**Comment by kensoh** [comment]
hi Enhui, you can try to run normally with Chrome, ask for user input, then send that input to Chrome, for eg by running on command line `tagui demo chrome` to invoke below demo script.

**demo**
```
https://www.google.com/
ask Enter element identifier
element_id = ask_result

ask Enter text to search
search_text = ask_result

type `element_id` as `search_text`
type `element_id` as [enter]

wait 10 seconds
```

You can use `run` step to invoke Chrome or visual automation to click Chrome icon to open, but using that way you can only use visual automation to automate, because there won't be a special web socket connection between TagUI to that instance of Chrome in order to control it via Chrome's backend.

**Comment by kensoh** [comment]
In the above example, I enter q for first input as the identifier name for the google search box is 'q'. I enter some search string for the second popup input window. Then TagUI performs the search and shows results.
