### ISSUE TITLE
How to use dom step to pass variables to be used in web browser DOM environment?

### ISSUE THREAD

**Issue by Scipionh** [kelaberetiv/TagUI#343]
Hi,

I tried using variables into a dom selector using backquote but it didn't work.

```
 for y from 1 to 3
 {
    dom alert(document.querySelectorAll('#blah')[`y`].querySelector('#foo').innerHTML)
 }
```

I read the example misc_9 but couldn't find a way to solve it. When the script runs, it doesn't do anything, but I did check the logs and it basically converts `y` to `'+y+'` but it doens't seem to convert it to a number.

**Comment by kensoh** [comment]
There are a couple of issues on how to pass variables to dom (https://github.com/kelaberetiv/TagUI/issues/55 and https://github.com/kelaberetiv/TagUI/issues/125), and details in readme for dom step (https://github.com/kelaberetiv/TagUI#steps-description), and also the 9_misc sample flow (https://github.com/kelaberetiv/TagUI/blob/master/src/samples/9_misc) has examples on passing 1 or more variables to dom.

DOM environment exists within the web browser and is separate from TagUI environment. If you put y as variable, there is no way for web browser or TagUI to know whether the y variable is a variable in Chrome, or a variable in TagUI. To resolve that, the dom_json variable is introduced. In your example, below code will pass variable y from TagUI into browser DOM as dom_json variable to be used.

More details on DOM (https://www.w3schools.com/js/js_htmldom.asp), for security and practical reasons TagUI's operating environment will not be directly in the same environment as the web browser. Otherwise variables will write over one another and there can't be deterministic and reliable behavior when automating webpages.

```
for y from 1 to 3
{
    dom_json = y 
    dom alert(document.querySelectorAll('#blah')[dom_json].querySelector('#foo').innerHTML)
}
```

**Comment by jean-philippe-bousselin** [comment]
We just tried that with @Scipionh and it works. Thanks a lot @kensoh for your help and the swift answer!

**Comment by CJohnDesign** [comment]
I needed to add `` to my dom_json variable to get it to work. ei:

for y from 1 to 3
{
    dom_json = y 
    dom alert(document.querySelectorAll('#blah')[`dom_json`].querySelector('#foo').innerHTML)
}

**Comment by kensoh** [comment]
That's interesting, maybe dependent on use cases. What I'm aware is dom_json would already be a variable injected into the webpage DOM, so it is natively accessible by the JS code executed there.
