### ISSUE TITLE
Using web locator when calling the web browser manually, using TagUI with Firefox

### ISSUE THREAD

**Issue by LZF07** [kelaberetiv/TagUI#344]
I'm having trouble using slimerjs with firefox, with this I'm calling firefox manually.
If I open the browser without using the chrome or firefox commands can I reference their web fields?
The way i call the web browser: 
vision type(Key.WIN)
type page.png as firefox[enter]

The trouble with slimerjs is 
"SLIMERJSLAUNCHER is set to C:\PROGRAM FILES\MOZILLA FIREFOX\firefox.exe"
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=

**Comment by LZF07** [comment]
Used the xpath copy and the result was:
//*[@id="login_field"]

i used but doesn't worked
enter //*[@id="txt_user_login"] as 1234

**Comment by LZF07** [comment]
the website I want to access does not work well with google chrome, if there is any way to use firefox or internet explorer it will make it easier

**Comment by kensoh** [comment]
Thanks for raising this, since Firefox v60, due to the architecture overhaul, SlimerJS (which TagUI uses to control Firefox) has not been able to support Firefox browser. Details here - https://github.com/laurentj/slimerjs/issues/694

An alternative I can think of is running in the default PhantomJS mode (without chrome or headless or firefox option). You can use the `live` step to try debugging and building your script even though you can't see the browser.

Alternatively, try using the visual automation method through Sikuli, and treat it as if you automating the browse like a desktop app. In this, case the webpage DOM would not be accessible to TagUI and thus you can't reference elements using locators. Images of elements are used instead to reference them. Details here - https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by kensoh** [comment]
Oh, of course, if really want to use Firefox, another option is try downloading and using an older version of Firefox, eg v59 - https://ftp.mozilla.org/pub/firefox/releases/59.0/

**Comment by LZF07** [comment]
Already tried to use firefox v54 but doesn't worked.
My system works better with IE, and if we could work with web locator on IE would be perfect.
There´s any way to use with internet explorer?

Thank you for the support!

**Comment by kensoh** [comment]
I see, I guess that website works for IE as you suggested. I'm afraid TagUI doesn't automate IE directly. You can try the above suggestion on visual automation or PhantomJS mode.

If that doesn't work, can explore other automation solutions such as open-source Selenium, or even commercial ones like UiPath. Those tools have spent big engineering efforts to automate IE.

**Comment by LZF07** [comment]
I´m actually using visual automation and will try Selenium in the future.
nice job with TAG UI and thank you, Kensoh!
