### ISSUE TITLE
Using datatable with test option for batch test automation

### ISSUE THREAD

**Issue by kurawadiprasanna** [kelaberetiv/TagUI#348]
After the completion of chrome based test execution, it is not terminating the execution flow. It hangs off. Please advise.

**Comment by kensoh** [comment]
Have you tried the flow sample 6 on datatables to see if they work for you? Running both commands below in src/samples/6_datatables folders work as expected, quitting after 3 iterations.

`tagui 6A_datatables page_data.csv`
`tagui 6A_datatables page_data.csv chrome`

Link to the datatable and other flow samples - https://github.com/kelaberetiv/TagUI#flow-samples

**Comment by kensoh** [comment]
Adding on to above, below has more useful info on using TagUI for test automation - https://github.com/kelaberetiv/TagUI#testing

Although it can be used for test automation, there are way better frameworks and tools designed specifically for test automation. Recommend to check out those specialized tools.

**Comment by kurawadiprasanna** [comment]
tried with both 6A and 6B datatables. it is still not working. PFA for the link below for screenshot.
https://drive.google.com/file/d/1eOrSuZAnKBuwdGiYA_Yzg-no--AQmRtu/view?usp=sharing

**Comment by kensoh** [comment]
Thanks Prasanna, I get it now, you mean running in test mode. I made PR https://github.com/kelaberetiv/TagUI/pull/352 with below comments -

---

details of issue here - kelaberetiv#348

when datatable is used with test option, execution hangs after the first iteration. this is because casperjs test mode treats every parameter as in input file to test. when the datatable parameter is passed to casperjs it hangs because it is not a valid test js file. modified tagui and tagui.cmd to not pass parameters to casperjs in test mode.

technical details here - http://docs.casperjs.org/en/latest/testing.html#arguments

`The casperjs test command will treat every passed argument as file or directory paths containing tests. It will recursively scan any passed directory to search for *.js or *.coffee files and add them to the stack.`

---

Prior to merging, you can download from below repo, unzip, and replace contents under src folder. The files changed are tagui and tagui.cmd under src folder. Do a backup if you have made your local modifications to code.

https://github.com/tebelorg/TagUI/tree/datatable_test_mode

**Comment by kurawadiprasanna** [comment]
it is working fine with the fix provided. Thanks @kensoh

**Comment by kensoh** [comment]
no probs Prasanna 👍, i keep the issue open until the PR is merged into TagUI master by @ryzalk

**Comment by kurawadiprasanna** [comment]
sure @ Kensoh

**Comment by kensoh** [comment]
Committed to master and closing the issue. Users can download the cutting edge version to overwrite their package installation to use this feature - https://github.com/kelaberetiv/TagUI#set-up
