### ISSUE TITLE
Headless mode not working for some clients' laptops but working for some others

### ISSUE THREAD

**Issue by v-akos** [kelaberetiv/TagUI#357]
Hi,

I've experienced that headless mode doesn't work on some computers. However chrome mode works fine. No alert messages, only blinking cursor in cmd...

Please let me know how I could debug the problem, or what further information you need.

These problematic PCs are not mine but my clients' so it would be nice if you could tell me several options or questions that I could try with them or ask them about.

Thanks for your support in advance!

Regards,
Akos

**Comment by kensoh** [comment]
That's interesting I can't think of what can be done because this needs live troubleshooting to find out.

- You can try comparing the tagui_chrome.log when running chrome mode and headless mode on the laptop with problems to see what difference is there and if there is any error messages.

- You can also try checking the Chrome versions on the working laptops and the laptops not working with headless mode. I think only Chrome newer releases after mid 2017 supports headless mode.

- You can try comparing the working laptops and not working laptops to see the difference in their systems setup, operating system versions and other environment settings, hardware ram, installation locations etc.

**Comment by kensoh** [comment]
Closing for the time being, pending further inputs.

**Comment by sandeep14897** [comment]
Hello Kensoh

I was facing the same issue. Could you help us solve this?

Below mentioned are my Hardware details:
My local machine: Chrome version-81.0.4044.129, Operating system-windows 10 Home, RAM-4GB
VM: Chrome Version-81.0.4044.138, Operating system-windows server 2016 Datacenter,RAM-2GB

Thanks in Advance,

**Comment by kensoh** [comment]
Hi @sandeep14897 you can try the first step here to see if there are more clues in the run log. tagui_chrome.log is found in tagui\src folder and tracks the messages btw TagUI and Chrome.

https://github.com/kelaberetiv/TagUI/issues/357#issuecomment-474389173

Adding on, you can try running normal Chrome mode first to see if it works, before running headless mode. It could be the first run require running visible mode to accept Google T&C.

**Comment by HarshithaSarvisetti** [comment]
Hello @kensoh  I am also facing the same issue.And,i am able to run the tagui flow in normal chrome mode but not in Chrome Headless mode.Can you tell me,what is the reason?

**Comment by kensoh** [comment]
Hi @HarshithaSarvisetti , my part-time contract with AI Singapore is ending and my team-mate @siowyisheng will be helping with supporting TagUI users queries on GitHub.
