### ISSUE TITLE
I got an issue (potential error in my TagUI script)

### ISSUE THREAD

**Issue by Hassan-Ali123** [kelaberetiv/TagUI#367]
SyntaxError: Unexpected token '}'---- phantomjs://code/write_data_to_excel.js:1344 in injectJs   phantomjs://code/bootstrap.js:456 in tagui. Can someone please guide me why this issue occurring in tagui??

**Comment by kensoh** [comment]
There may be some errors in the script that lets TagUI not convert to proper JavaScript execution. You can try writing a simple script and add on new lines to test where is the line causing error. Or you can paste the minimum script that replicates this error here.

**Comment by kensoh** [comment]
Hi Hassan, closing issue until further inputs but do ping here if you have any questions!

**Comment by Trionx** [comment]
Hi @kensoh I'm getting the same error as TS and can't figure out why. I've narrowed it down to a py_step as below,
py_step('cinfo2 = ' + `cinfo2`)
where cinfo2 is in tagui_local. any ideas?

**Comment by kensoh** [comment]
Hi @Trionx assuming you are sending over a string, the syntax should be as follows (without backticks here) -

```
py_step('cinfo2 = "' + cinfo2 + '"')
```

Another example here showing for sending string over and sending number over -
https://tagui.readthedocs.io/en/latest/advanced.html#writing-python-within-flows

Also, in tagui_local.js, you probably should not define it with `var` but just the variable. Otherwise it is out of scope during run-time.

**Comment by Trionx** [comment]
Hi @kensoh, I'm actually using tagui_local.csv not js. Yes it's a string(a path to be exact), but Ive tried with the additional " and with and without backticks but it still doesn't work. the tag flow can echo the variable but when I try to use py_step it errs.

**Comment by kensoh** [comment]
Following works for me, you can try getting latest version of TagUI here https://tagui.readthedocs.io/en/latest/setup.html

There was some enhancement in the last couple of months to let object repository variables be usable in the JS code.

Other areas to check would be the object name, whether it is variable JS variable name and also whether you can using double backslash. Because in Python, you need `\\` to mean `\` in the path for Windows.

demo.tag
```
py_step('info = "' + path + '"')
py print(info)
echo `py_result`
```
tagui_local.csv
```
object,value
path,some_path
```

**Comment by kensoh** [comment]
CC @ruthtxh too
