### ISSUE TITLE
Every script gives error (for Ubuntu, PHP needs to be installed first)

### ISSUE THREAD

**Issue by kemelzaidan** [kelaberetiv/TagUI#413]
I don't know what is wrong, but every script gives me an error. I even tried running the samples, but they also give me errors:

```
~/src/tagui/src$ ./tagui samples/1_yahoo chrome
./tagui: linha 256: php: comando não encontrado
Unable to open file: /home/kemel/src/tagui/src/samples/1_yahoo.js

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script /home/kemel/src/tagui/src/samples/1_yahoo.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die
```

What's wrong? I'm trying using it on Linux Ubuntu 18.10

**Comment by kensoh** [comment]
You have probably not gone through the usage section, there is a part on potential issues. For Ubuntu, it is a Linux distribution that does not come with PHP, thus PHP needs to be installed first -

https://github.com/kelaberetiv/TagUI/blob/master/README.md#command-line

**Comment by kemelzaidan** [comment]
Sorry, I guess I was mistaken for the text that says that php was for Windows manual installation setup only. It's in number 6 of the README part below:

![image](https://user-images.githubusercontent.com/897436/57051680-f7b0ed00-6c58-11e9-8450-f6008d6c262d.png)

Maybe those dependencies can be made more clear on README, specially when downloading the zip package as it's possible to see that there is a bunch of dependencies bundled. Installing php worked fine with the zip bundle.

But I also had problems when trying to install it as a global package with npm (`npm i -g tagui`) but it also seems to be lacking dependencies. After installing `casperjs` also as a global, it started to lack `phantomjs` (`ERROR - Fatal: No such file or directory; did you install phantomjs?`). Installing it as a global package didn't solve the problem. Improving the instructions to install through npm would be nice too.

Thanks a lot.

**Comment by kensoh** [comment]
For npm when I previously tried npm install tagui it works, CasperJS and PhantomJS is in its dependencies already. Nevertheless TagUI is not a Node module, as is PhantomJS. It's more for distribution convenience.

**Comment by kemelzaidan** [comment]
The installation runs without errors, but when trying to use tagui, it gives an error:

```sh
tagui teste.tagui
/home/kemel/.nvm/versions/node/v10.15.1/bin/tagui: line 327: /usr/local/bin/casperjs: No such file or directory
```

**Comment by kensoh** [comment]
Running the following works on Node v6.4. Can you try installing using below method instead of global, and then use symbolic link to make tagui command accessible globally.

```
npm install tagui
cd node_modules/tagui/
./tagui samples/1_yahoo
```

To run tagui from anywhere -

For MacOS/Linux, use ln -sf /full_path/tagui/src/tagui /usr/local/bin/tagui to create symbolic link
For Windows, add tagui/src folder to path, then tagui will be accessible from any folder

If there is an intrinsic incompatibility with installing TagUI with npm newer versions, then I'll remove npm as distribution method and stick to using downloading of zip files. Which can also be use automated installation with curl and shell commands.
