### ISSUE TITLE
"\" and "\\" slash problem in variable (JS & Python syntax - use \\ to mean \)

### ISSUE THREAD

**Issue by muratcim** [kelaberetiv/TagUI#420]
Hello to everyone

I have 2 problems.

First problem

There is a "\\" character in the variable.
"\\"  character is deleted when I send this variable to python code block

```
filePath = "C:\temp\sample.txt"
py_step('p_filePath = "' + filePath + '"')

py begin
print(p_filePath)
py finish

echo py_result
```
`
**Output** : C:	  empsample.txt

Second Problem

I get the following result when I send a "\\\\" character

**Output** : C:	  emp\sample.txt

**Comment by kensoh** [comment]
Try the following -

```
filePath = "C:\\\\temp\\\\sample.txt"
py_step('p_filePath = "' + filePath + '"')

py begin
print(p_filePath)
py finish

echo py_result
```

And you'll get the following output -
```
START - automation started - Tue May 07 2019 21:55:29 GMT+0800 (+08)

py print(p_filePath)
C:\temp\sample.txt

FINISH - automation finished - 0.5s
```

\\ character is a special character used by JavaScript and Python to escape and support special characters such as \\t to mean tab and \\n to mean enter. In above, within JavaScript py_step will convert \\\\\\\\ to \\\\ and then within Python, the \\\\ will be converted to \\.

This is standard programming language syntax to support special characters, so TagUI follows the syntax for JavaScript and Python instead of automatically escaping them. If TagUI auto-escapes them, then users will lose ability to use these special characters in JavaScript and Python code in TagUI.
