### ISSUE TITLE
Change timeout from default 10 seconds for SikuliX visual automation

### ISSUE THREAD

**Issue by kishorer1290** [kelaberetiv/TagUI#431]
Hi Ken,
I am using visible() , present() with the check condition. Is there any option of adding a kind of timeout for these functions. 
The issue becomes when there is a verification step on the next step. Even before waiting the next page to load, it checks for the condition and fails it 
Thank much in Advance 
Kishore

**Comment by kensoh** [comment]
Hi Kishore, to change the default timeout (10 seconds) for visual automation steps, you can modify the following file  tagui/'src/tagui.sikuli/tagui.py. Change line 4 to some other longer timing, for eg 60 for 60 seconds before getting error that UI element cannot be found -

```
wait_timeout = 10
```

**Comment by ShwetaChahan** [comment]
Hi Ken, 

I did the change, but it does not apply in tagUI script . 
Ex I used :
check present('name') | "Name Present" |"Name not present"
It seems to always fail. There is only one option which is giving a wait which i was avoiding.

**Comment by kishorer1290** [comment]
Hi Ken,

Me and my teammate tried this. The above timeout does not help when we use present() /visible() with check() condition 
Ex 
check('present') |"pass"|"fail" 
So we have to use wait, other the scripts fail

Please suggest

**Comment by kensoh** [comment]
Hi Kishore, that is expected behaviour, for present() and visible() helper functions, they only return the condition in real-time whether the UI element is present at the moment. The 2 functions are designed not to wait for timeout to happen before returning true or false.

You can do a wait for some time before checking, or do something like `hover element` on some element which you know will be loaded and appears before what you are checking appears. After that step, then check present() or visible().

**Comment by kishorer1290** [comment]
Thank you. It works
