### ISSUE TITLE
dom_result always returns null (using dom document.querySelector in frame)

### ISSUE THREAD

**Issue by grahamlin** [kelaberetiv/TagUI#440]
I tried using TagUI to capture HTML data at Salesforce.com. Right now I can show element text but cannot use dom steps to save the outerHTML via the same selector. The dom_result always returns null.

`https://c.eu9.visual.force.com/apex/star_report?expand=yes
if present('#Login')
{
type username as abc@acme.com
type password as xxxxxxxx
click #Login
}
wait 30

frame contentPane
{
  show #RBU_star
  dom_json = '#RBU_star'
  dom return document.querySelector(dom_json).outerHTML
  echo 'dom_result=' dom_result
  var fs = require('fs'); fs.write("star_table.html", dom_result + "\n", 'w');
  wait 5
}
snap page
`

**Comment by kensoh** [comment]
I don't think doing a `document.querySelector` within a dom step can work within a frame step. Because doing `document.querySelector` already hard-codes the context to be `document`, which is the main parent frame of the webpage.

Some ideas to try -

- You can try using dom return chrome_context.querySelector(dom_json).outerHTML in your code above to see if it works for you. chrome_context is an internal TagUI variable to track the current selected frame.

- You can try if using read step in combination with XPath to retrieve the attribute outerHTML works. For eg here in getting href attribute - https://github.com/kelaberetiv/TagUI/issues/427

**Comment by grahamlin** [comment]
The ideas you offered didn't work.  I end up using Read to a text variable and use JS code to process that text variable.
BTW, the above can work on visible Chrome but not headless. I would get ERROR - cannot find RBU_star. Is it because of the frame?

**Comment by kensoh** [comment]
Cool! Can you paste your working code here for future reference by other users? This is a password protected page, so others can't test. But can be useful reference to try.

Yes, from your description, it is likely due to the way Chrome visible and Chrome headless handles the frame.
