### ISSUE TITLE
Need an examples for vision_step() helper function

### ISSUE THREAD

**Issue by mazhilnan** [kelaberetiv/TagUI#446]
vision_step() is mentioned in the documentation but no examples available for the usage. Also let me know if there are any other options available for passing tagui params into sikuli commands

Thanks in advance !

**Comment by kensoh** [comment]
Hi @mazhilnan try the following, from below link, choose pro steps. You will see below example of how to use vision_step() and the other helper functions to pass data to TagUI's integrations.

https://github.com/kelaberetiv/TagUI#cheat-sheet

```
phone = 1234567
name = 'donald duck'
py_step('phone = ' + phone)
py_step('name = "' + name + '"')

py print(name)
echo py_result
py print(phone)
echo py_result
```

The reason for such a roundabout implementation is because when you use vision or py step, what follows are text string that will be sent to the integrations. So it is not possible for TagUI to know whether variables are intended to be in SikuliX context or TagUI context. Above will explicitly make sure what gets sent through to SikuliX will be exactly what user wants.

**Comment by kensoh** [comment]
Adding on, for visual automation, the backend engine is SikuliX, which is processing scripts base on Jython. Thus the syntax of commands that you send using vision step would follow normal syntax for Python programming language.

**Comment by mazhilnan** [comment]
Hi @kensoh, 
Thanks for your reply !
Now I understood clearly about vision_step() usage. 
Below is an working example code for vision_step(), please include it in your documentation, if you find it is useful. 

About TagUI, it is really useful framework. Lot of thanks to you for such wonderful contribution !

<cars = ["Santro","Alto 800","SWIFT Desire"];
len = cars.length
for (i = 0; i < len ; i++) 
{
carName = cars[i];
vision_step('carName = "' + carName +'"')
vision Do.popup(carName, 3)
}>
