### ISSUE TITLE
Windows zip file seems to not have tagui.cmd command

### ISSUE THREAD

**Issue by hemanthsavasere** [kelaberetiv/TagUI#449]
There has been an interchange of Zip folder under headings. The windows folder is put under Linux and vice- versa. Can I fix this issue?

**Comment by kensoh** [comment]
@hemanthsavasere thanks for flagging out, the zip files at below link looks correct, I just checked. Maybe that's why you are getting the tee and grep error in https://github.com/kelaberetiv/TagUI/issues/450. Because the Windows zip file will have those commands under tagui\src\unx folder.

https://github.com/kelaberetiv/TagUI#set-up

![Screenshot 2019-06-12 at 12 53 41 AM](https://user-images.githubusercontent.com/10379601/59291051-91ce7100-8cac-11e9-9ba4-e342cb4233e0.png)

**Comment by hemanthsavasere** [comment]
Another observation,

In TagUI_Linux/src zip file there are .cmd files while it is not found in TagUI_Windows/src zip file. 

![image](https://user-images.githubusercontent.com/11555217/59403012-84a1a700-8dbe-11e9-82e7-304538978c48.png)

**Comment by kensoh** [comment]
Thanks @hemanthsavasere for telling me about your observation! Let me check and see what's going on.

**Comment by kensoh** [comment]
Hi @hemanthsavasere I tried 3 times downloading from this link and choose the Windows unzip and run link. https://github.com/kelaberetiv/TagUI#set-up

After unzipping, I can see see tagui and tagui.cmd inside tagui/src folder. Can you try again to see if it works? Not sure why your download does not have the tagui.cmd file.

![Screenshot 2019-06-13 at 3 36 23 PM](https://user-images.githubusercontent.com/10379601/59413352-f515eb80-8df1-11e9-9def-b5721213512c.png)

**Comment by hemanthsavasere** [comment]
Hi @kensoh,

Thanks, magically now it is working.

Thanks & Regards.

**Comment by kensoh** [comment]
Oh great @hemanthsavasere thanks for verifying! I didn't make any change, maybe it is some temporary problem with the web host. Appreciate that you raise the issue so that we can check it together 👍
