### ISSUE TITLE
'tee' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by hemanthsavasere** [kelaberetiv/TagUI#450]
Hi,

When executing the tagui command, I am getting the 'tee' is not recognized as an internal or external command, operable program or batch file. I am attaching screen-shot below for reference.

 
![image](https://user-images.githubusercontent.com/11555217/59264562-fb289280-8c60-11e9-8d5c-461400b86e31.png)

**Comment by aazzim** [comment]
i got the same issue too

**Comment by aazzim** [comment]
i fixed it by download tee.exe file from here [ http://ss64.net/westlake/nt/]  and copy the tee.exe file at the same src/ directory . it worked and error wasn't appeared again . However, i got another error 'casperjs' is not recognized as an internal or external command  , it seems i have to install casperjs

**Comment by hemanthsavasere** [comment]
I followed the procedure as mentioned above by @aazzim. I am getting a different error, grep is not 
 as an internal or external command.

![image](https://user-images.githubusercontent.com/11555217/59290236-b539f180-8c95-11e9-93e5-60b1c44f2681.png)

**Comment by kensoh** [comment]
@hemanthsavasere and @aazzim thanks for flagging out, the zip files at below link looks correct, I just checked. The [Windows zip file](https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Windows.zip) will have those commands under tagui\src\unx folder. To use TagUI, need to download and unzip the file for your OS so that dependencies are all packaged in.

https://github.com/kelaberetiv/TagUI#set-up

![Screenshot 2019-06-12 at 12 53 41 AM](https://user-images.githubusercontent.com/10379601/59291051-91ce7100-8cac-11e9-9ba4-e342cb4233e0.png)

**Comment by aazzim** [comment]
@kensoh thanks a lot for your fast reply. i tried the zip file you gave us and problem solved :)

**Comment by kensoh** [comment]
Welcome @aazzim, closing this issue here and following up with @hemanthsavasere at issue #449

**Comment by sengsanlim** [comment]
Hi, I am facing the same problem with v6.
'tee' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kensoh** [comment]
If you have downloaded from https://tagui.readthedocs.io/en/latest/setup.html

And get this error, most likely it is because of company IT policy or anti-virus auto-deleting the tee.exe file after you unzip the zip file. Try on your personal computer to see if the same happens.

**Comment by samax-hawk** [comment]
how install tee.exe in windows 10 ?
