### ISSUE TITLE
是否有开发的例子 (any development / integration examples?)

### ISSUE THREAD

**Issue by JayenLee** [kelaberetiv/TagUI#451]
我想electron+nodejs进行开发一个自动化操作网页的程序，能否集成你的程序？有没有什么例子可以告诉我该如何去使用这个？

**Comment by kensoh** [comment]
你好, for browser automation that is based on Electron, have you taken a look at Nightmare? It is a mature browser automation framework already based on Electron -

https://github.com/segmentio/nightmare

If you want to develop your own engine for Electron and you hope to have TagUI natural language syntax, then there are 2 things you need to solve. For first problem, you can take a look at [tagui_header.js](https://github.com/kelaberetiv/TagUI/blob/master/src/tagui_header.js) to see the natural language conversion and get idea how to do. For second problem, there is no reference of automating Electron in this project, so you probably can look at above Nightmare project to see how they control the Electron browser.

If you are thinking of integrating TagUI to an Electron + NodeJS framework, can you tell me more what are the benefits to do that? Because now TagUI can control Chrome visible and Chrome headless, there is no need to control Electron which is also based on Chromium. But the gain may be access to NodeJS packages because TagUI's engine is based on PhantomJS JavaScript.

**Comment by JayenLee** [comment]
如何使用web api 来控制TAGUI 自动化？这个有点不太明白，文档的例子很少。

**Comment by kensoh** [comment]
I'm afraid TagUI does not have web API to let other applications control it. It is designed to be self-contained to run automation scripts written in human languages. It has an API for running scripts if you are hosting it as a service on a server, but the API is only for calling what script to run, not to send step by step instructions via another app - https://github.com/kelaberetiv/TagUI#api

If you are thinking of writing a new NodeJS application that directly controls TagUI to automate Chrome browser, you can take a look at below project on how I do that in Python. It uses TagUI live mode to control and make it into API available in Python. The same thing can be done for NodeJS if you follow the logic in [tagui.py](https://github.com/tebelorg/TagUI-Python/blob/master/tagui.py) and try to implement that logic in Node.

https://github.com/tebelorg/TagUI-Python

**Comment by JayenLee** [comment]
你好，我测试的时候发现，很多情况下，打开的网页不是稳定的时间加载完成，导致经常自动化失败，是否能够有什么设置可以等待网页加载完成后，再触发后续的操作的？

**Comment by kensoh** [comment]
You can try the timeout step to set default timeout value to higher. For eg, timeout 60

**Comment by kensoh** [comment]
The default is 10 seconds, so if UI element has not appeared by then, will assume missing and show error.
