### ISSUE TITLE
live mode escape characters - eg using apostrophe ' in keyboard step

### ISSUE THREAD

**Issue by ck81** [kelaberetiv/TagUI#465]
@kensoh, Thanks for the tips in #259 How do I use apostrophe ' when echoing a message?

The following works when run in script:
```javascript
str = "it's TagUI"
echo str
keyboard '+str+'
LIVE
```

But once in LIVE mode, try the following:
```javascript
echo str
keyboard '+str+'
```

The first echo will produce the correct string.

But the keyboard will produce the Error Message:
> ERROR - expected token ')'

**Comment by adamkendall1** [comment]
I noticed in their "1_yahoo" sample script, the following line:

`type search_form_input_homepage as The search engine that doesn\'t track you.`

Notice the backslash before the apostrophe. Maybe try that?
I'm not a contributor and haven't tested this theory. I just stumbled across your question and thought I'd reply since the question was asked recently.

**Comment by ck81** [comment]
@adamkendall1:
> I noticed in their "1_yahoo" sample script, the following line:
> 
> `type search_form_input_homepage as The search engine that doesn\'t track you.`
> 
> Notice the backslash before the apostrophe. Maybe try that?

Just tried the following as you've suggested:
```javascript
str = "it\'s TagUI"
echo str
keyboard '+str+'
```

The result is the same i.e. it runs ok direct in script. But in LIVE mode, when you type in:
```
keyboard '+str+'
```

The same error message occurs:
> ERROR - expected token ')'

**Comment by kensoh** [comment]
Hi CK, this is a good question.

It is a limitation with live mode, I think it was a tradeoff to support dynamic variables in live mode.

Try the following and it will type `it's working`. I have not opted for automatic conversion of detected ' to the string below as it might cause more things to break in order to support keying in ' in live mode.

In most situations, eg XPath double quotes can be used, and ' is not part of CSS or other parameters.

```
keyboard it`"\'"`s working
```

**Comment by ck81** [comment]
> keyboard it`"\'"`s working

This is interesting. Learn something new today!

Thanks!

**Comment by kensoh** [comment]
No probs CK! I hope there'll be a better elegant fix but this is the workaround now as a tradeoff.

**Comment by kensoh** [comment]
Hi CK! Made a commit with following comments. Found solution, using similar solution for a problem encountered when I was developing TagUI for Python. Prior to packaged installation release, feature available from cutting edge version here - https://github.com/kelaberetiv/TagUI#set-up

>This change adds support for escape characters in live mode, for eg when using keyboard step ' will give error and requires creative syntax to type a '.
>
>Idea for solution is from solving a similar problem during recent development of personal side project - Tagui for Python. More details in issue #465.

**Comment by kensoh** [comment]
Above change is causing a bug with dynamic variables identifiers in live mode. More at #549.

---

The cause of the bug is due to changes made in #465 where various special characters are escaped in order for them to usable in live mode. However, as single ' is now escaped, it is not working as originally intended to process the dynamic variables correctly.

To figure out if there is a way to have both features working. This was missed as there is limited resource for the project, and automated test is focused on translation to correct positive test cases of TagUI steps (in src/test folder positive_test and positive_test.signature).

And live mode does not have such tests developed.
