### ISSUE TITLE
calling a variable flow filename in tagui step - technical limitation / tradeoff

### ISSUE THREAD

**Issue by ck81** [kelaberetiv/TagUI#467]
@kensoh, the *tagui* command is very useful in code reuse.

Have the following codes:

```javascript
if (dept=='Finance')
{
    tagui module_finance
}
eles if (dept=='HR')
{
    tagui module_HR
}
else if (dept=='Sales')
{
    tagui module_Sales
}

```

Imagine there are 10 different departments. Instead of writing 10 if-else-if, I tried the following:

```javascript
dept = 'Sales'
tagui module '+dept+'
```

It gives the following Error Message:
> ERROR - file not found for step tagui module '+dept+'

Based on the error message, I think your current version of TagUI does not support variables in the *tagui* command.

Hope that you can add this feature in the later release as it will greatly facilitate code reuse with less codes.

**Comment by kensoh** [comment]
Hi CK, this is a good use case. But I'm afraid after thinking through for some time, I couldn't find a way to implement it technically. The crux is tagui step expands the flow file before parsing even happens, in order to extract the TagUI steps to be parsed into JS code, and then running them.

But in this case, as TagUI default environment is JavaScript, a JS variable is being defined and attempted to be used even before parsing to JS code and execution in JS environment happens. Thus the error message appears.

I cannot think of any workaround that is simpler than what you already did above with the if else statements. It looks like a technical limitation / tradeoff in order to have the way natural language, JavaScript, TagUI language is mashed together into a seamless script file.

The tagui step allows variables to be defined before it to be used within the flow it calls. That may be helpful if most of the steps in the sub flows are similar and the same flow can be used by leveraging on the variables before it is called. But if each sub flow has drastically different steps, then I can't think of any more elegant solution than what you did above.

**Comment by ck81** [comment]
@kensoh, thanks for the detailed explanation.

Yes, totally understand where you are coming from. Actually like the simplicity and stability TagUI has now.  Can still achieve what I want with additional codes. Just trying to stretch your TagUI...!

**Comment by kensoh** [comment]
No probs CK, thanks for raising the question! I have to relook to come to the conclusion that there isn't a technically feasible way to implement that without retaining the robustness and reliability of TagUI.

In theory, with enough resources, someone can write a PHP interpreter to understand variables declared and then use that during parsing, even before JS execution. But that is likely to introduce compatibility problems with existing user scripts (eg scripts used to work but no longer work with the change), or need unreasonable amount of test cases, testing and development time that really should be invested into bringing other features with significant impact vs something that can be done now.

For example, I think Murat from Turkey is working on something very exciting now on TagUI - https://github.com/kelaberetiv/TagUI/issues/470

**Comment by kensoh** [comment]
Adding on a workaround using a batch file. This way, in your script just use tagui step on the flow file module_department. This works because the file is changed to the one you want before the actual parsing by TagUI happens. User can just change the config from 2nd line of batch file below -

```
@echo off
set department=Finance
copy /Y "module_%department%" "module_department" > nul
tagui script option1 option2 ...
```
