### ISSUE TITLE
Downloading file in Linux - possible w/o Chrome if known URL

### ISSUE THREAD

**Issue by claireyoungmin** [kelaberetiv/TagUI#483]
Hi @kensoh !
I am new to TagUI! 
Trying to use TagUI to automate download and upload of files to a web browser. I am still on the download part. Currently running TagUI from a linux workstation and am encountering issues with downloading files.

phantom.setProxy('IP', 'PORT', 'manual', '', '');
URL

type user_id as userid
type password as password
click xpath

When clicking xpath above, in windows with chrome (visual automation), I am able to download the file. I am able to login and snap the pages correctly (so I can confirm tagUI is working properly) but just when I try to download that file, I don't find the file anywhere. 

Can you please help me?

**Comment by kensoh** [comment]
Hi @claireyoungmin that's an interesting use scenario! Where you explicitly use a proxy server in order to access the target website and also use visual automation to control the workflow. One thing to point out is the setting proxy only affects PhantomJS browser mode (no option used when running tagui command). If chrome option is used, the proxy settings does not get effected into Chrome browser.

The default download folder is the same folder where your TagUI flow file is. Check if there is a file there. It is also possible to set another download location using the following code in your script -

```js
chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'download_path'});
```

Another option is to try capturing an image of the download button or link, and use visual automation to click on it, for eg `click download_button.png`. This may work in some cases where clicking XPath directly cannot work. Because it simulates an actual user mouse movement and click on the web browser layer, instead of using JavaScript code to tell Chrome to click through DOM layer.

Let me know if you still can't get the download working!

**Comment by claireyoungmin** [comment]
Hi @kensoh!
Thank you for replying! Appreciate the promptness. I am still a newbie on this, so apologies if I get some of the stuff below wrongly. So I was thinking of running tagui without the chrome option (that would mean default on PhantomJS) so I don't have to install Chrome as a dependency in our linux server and since we would like to run this application in the background via a cron in our servers. Thus, visual automation is not necessary. But that would mean I can't use this one below right? 

chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'download_path'});

I checked the tagui folder like you said, but could not find the file there. 
It seems to be able to find the element and click but nothing is happening. Otherwise, it would throw an error. I tried what you asked but it seems like the download_button is not an image itself but input type="button"

**Comment by kensoh** [comment]
Ok I get it now, I was mistaken that you are automating on Chrome when you say clicking XPath on Windows with Chrome.

For the default PhantomJS mode, there are 2 ways. It doesn't support downloading by clicking. Need some additional work.

1. First way is finding out the URL of the file to be downloaded and using download step to do it.

2. Second way is finding out the URL of the file and use receive step, followed by clicking the download link.

More details on these 2 commands in the readme, under cheat sheet --> pro steps. Give a try to see if that works!

**Comment by claireyoungmin** [comment]
I see. I understand. 
Seems like it would be difficult for our case since the website provided to us to work with has masked URLs :( Guess we'd have to result with visual web automation.

**Comment by kensoh** [comment]
I see... Got it.. The next best option with TagUI is running with headless option for Chrome. But if Chrome is strictly not allowable in scope, then yeah have to look at other solutions or alternatives.
