### ISSUE TITLE
How to close Chrome browser on Ubuntu...

### ISSUE THREAD

**Issue by manbannur** [kelaberetiv/TagUI#484]
I am connecting Linux Ubuntu via VNC Viewer and am executing 1_yahoo sample tagui script.  Script executes but does not close the browser.

Can you please suggest what could be wrong.?

**Comment by kensoh** [comment]
Hi @manbannur I have tried running TagUI on Ubuntu before and it is able to launch and close Chrome browser.

Can you confirm what happens is TagUI launches Chrome browser, perform the automation and TagUI exits, but the browser is still open?

If yes, can you check if you are running an updated version of TagUI (download v5.0 packaged installation and then download the cutting edge release to overwrite the core files) - https://github.com/kelaberetiv/TagUI#set-up

You can also check if your other colleagues' Ubuntu laptop is having the same problem.

This issue may take some time to troubleshoot because I can't replicate on my side. The below line of code is executed from shell after TagUI exits. You can try running it after automation is completed and Chrome browser is still open. To see if there is a valid process ID returned to kill the browser process. If there is no ID, you can try gradually removing the last part of below command to see at which step the result becomes empty.

```
ps x | grep remote-debugging-port=9222 | grep tagui_user_profile | sed -e 's/^[ ]*//' | cut -d' ' -f 1 | sort -nur | head -n 1
```

**Comment by kensoh** [comment]
Closing issue for now but do post here if there is any new inputs!
