### ISSUE TITLE
Allowing chrome:// as valid URL - pending more use scenarios

### ISSUE THREAD

**Issue by ck81** [kelaberetiv/TagUI#487]
Hi @kensoh, have recently encountered the following situation in one of my corporate websites. 

Every now and then, after running the TagUI automating some corporate web pages for some time, it will encounter "400 Bad Service - Request Header or Cookie Too Large" error. (Note: the error is not due to TagUI.  It's our corporate websites.)  The only way to fix this is to clear the cache of the chrome browser and re-run the robot.

I tried minimizing visual automation and found that I can bring up the chrome "clear browser data" menu with the url: 
```chrome://settings/clearBrowserData```

Problem is: TagUI only allows http:// and https://

Tentatively I have edited tagui_parse.php Line 420 to:
```php
if ((substr($lc_raw_intent,0,7)=="http://") or 
(substr($lc_raw_intent,0,8)=="https://") or 
(substr($lc_raw_intent,0,9)=="chrome://") or 
(substr($lc_raw_intent,0,11)=="about:blank")) 
return "url"; // 
```

Sharing this here in case some users also need to access `chrome://`

**Comment by kensoh** [comment]
Thanks CK for raising this use scenario and sharing! I'll recommend using below for now. Or use tagui step to call a flow file with below line, eg tagui clear_browser_cache

**clear_browser_cache**
```js
chrome_step('Page.navigate',{url: 'chrome://settings/clearBrowserData'});
```

This is because accessing Chrome settings is not a typical use case. There is also no harm to make it officially supported, but will look out for more use cases with non-http(s) URLs to implement an revision for the URL step. Thanks for pointing this out!

**Comment by ck81** [comment]
> ```js
> chrome_step('Page.navigate',{url: 'chrome://settings/clearBrowserData'});
> ```

Yes, the above works!  Thanks!

**Comment by kensoh** [comment]
No probs! Will look out for more use scenarios and maybe walk through with you to make a PR 👍 (pull request to commit your code change into the project and visible as code contributor)
