### ISSUE TITLE
URL with JavaScript prompt at the start - use dom or visual automation

### ISSUE THREAD

**Issue by HemilModi03** [kelaberetiv/TagUI#491]
Hello,

I am trying to open an URL which prompts me to enter username & password. For entering username & password into prompt box I am using sikulix. But tagui does not execute next line until the URL is loaded and the script is just stuck on the first line of execution.

Can you please look into it and suggest a work around for it.

thanks

**Comment by kensoh** [comment]
This is an interesting scenario and yes SikuliX is the solution because the JS popup dialog box cant be controlled through the DOM directly.

TagUI will wait for webpage to load and retrieve its title, before continuing the next step. You can try below 2 ideas and let me know if it works for your use case.

1. don't load webpage with the URL. use dom step to run window.location.href = "some url" directly and see if that is still blocking

2. use SikuliX directly to type URL into browser. eg visually click on Chrome icon, and use type step visually on the address bar by specifying an image of the address bar. [enter] will simulate the enter key.

**Comment by HemilModi03** [comment]
I already tried the 2nd solution, opened chrome, entered url and logged in using sikulix but after that tagui is not able to find web elements.

**Comment by kensoh** [comment]
Oh need to launch TagUI with chrome option so that TagUI has access to the Chrome browser web elements. But start the script with clicking on the chrome icon, so that window is in foreground.

```
click chrome_icon.png
type address_bar.png as https://abc.com
type username_box.png as sonic
type password_box.png as tails
```

**Comment by HemilModi03** [comment]
This is exactly what I did but after I am logged in I am not able to access the web elements after logging in using sikulix.

**Comment by kensoh** [comment]
I'm afraid I can't replicate the issue you are facing. Following TagUI script works for me when run with chrome option. It opens up browser and type in URL using visual automation. Then proceeds to interact with the web elements directly. ```tagui sample_script chrome``` to run -

**sample_script**
```
click chrome_icon.png
click address_bar.png
keyboard [cmd]a
keyboard [delete]
keyboard https://ca.yahoo.com[enter]
type search-box as github
click search-button
wait 6.6
snap page
snap logo
```

**chrome_icon.png**

![chrome_icon](https://user-images.githubusercontent.com/10379601/60896662-4dc59080-a299-11e9-9e61-970d3b04cb33.png)

**address_bar.png**

![address_bar](https://user-images.githubusercontent.com/10379601/60896672-51f1ae00-a299-11e9-8813-1a7fb3c2d502.png)

Above are images from my macOS, you will need to capture the icons from your laptop because it may look different across different operating systems or screen resolution.

**Comment by kensoh** [comment]
The web elements are correctly accessed using web identifiers and output images are created -

![snap2](https://user-images.githubusercontent.com/10379601/60896873-aeed6400-a299-11e9-8369-e952e3797476.png)

![snap1](https://user-images.githubusercontent.com/10379601/60896884-b280eb00-a299-11e9-9c0b-4ded4d12046a.png)
