### ISSUE TITLE
Detect when download finishes before closing Chrome - loop to check

### ISSUE THREAD

**Issue by Puayny** [kelaberetiv/TagUI#492]
Hi, can tagui detect when a file has finished downloading in Chrome before ending the script (and hence closing the browser)?
In this scenario, the download is initiated by clicking a button, and the download url is unknown.

If the browser closes before the file has finished downloading, the file doesn't complete the download. 'Wait' works, but the file size is dynamic, and the length to wait is uncertain.

Thanks!

**Comment by kensoh** [comment]
Hi @Puayny thanks for providing the detailed information of your use scenario. I assume that the file size if pretty big, otherwise a wait step would do the trick without losing too much time.

I can think of 3 ways that you can try and let me know which one works best for your setup. The main idea is to loop until the file download is completed. But how to check it is completed, there are a few ways -

1. use run step to run the corresponding OS command to check if the downloaded file with the name is there already. eg `run ls filename` for macOS / Linux and `run cmd /c dir filename` for Windows. After that check the run_result variable for the command output.
```
run xxx
if (run_result ...)
break
```

2. use JavaScript code to check for the file, eg
```
var fs = require('fs')
if (fs.exists(filename))
break
```

3. use the visual automation capability to look visually for an image that is expected when download completes. Maybe a snapshot of the download completed rectangle or something.
```
if present('image.png')
break
```

The loop will look something like this

```
for loop from 1 to infinity
{
// code block 1 or 2 or 3 above to check if download completes

// wait for some time before checking again
wait 1 second
}

**Comment by kensoh** [comment]
There's also a 4th way to try, run the automation with speed option so that Chrome won't be killed.

Then use end_processes or end_processes.cmd to periodically kill the Chrome sessions - 

https://github.com/kelaberetiv/TagUI/blob/master/src/end_processes
https://github.com/kelaberetiv/TagUI/blob/master/src/end_processes.cmd

**Comment by Puayny** [comment]
Thanks for the help @kensoh ! 

I went with the fourth option - I'm calling the tagui script from another program, so that program waits for download completion, then runs end_processes.

**Comment by kensoh** [comment]
Sounds great! That'll be a nice implementation 👍
