### ISSUE TITLE
Usage Errors: Ubuntu 18.04 - possibly not downloaded from packaged zip

### ISSUE THREAD

**Issue by gfleetwood** [kelaberetiv/TagUI#501]
Hi,

I'm having problems getting Tag UI to work on Ubuntu 18.04. I downloaded and extracted the program and tried to run the yahoo example: ` ./tagui samples/1_yahoo`. First I got a php which said I didn't have casperjs installed. (Isn't the program self-contained?) I installed it and then got another php error which now asked for a phantomjs installation which I already had. (Both casperjs and phantomjs are in my usr/bin.) The error is below:

```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/gordon/tagui/src/tagui_parse.php on line 31
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/gordon/tagui/src/tagui_parse.php on line 32
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/gordon/tagui/src/tagui_parse.php on line 34
ERROR - Fatal: No such file or directory; did you install phantomjs?
```

**Comment by kensoh** [comment]
Hi @gfleetwood the error looks like downloading the repository and using it directly. Can you check if you have downloaded the packaged zip file for Linux to unzip and run it?

https://github.com/kelaberetiv/TagUI#set-up

Only the packaged zip file contains the dependencies. The repository does not because it would bloat up with the dependencies for all the 3 operating systems.

**Comment by kensoh** [comment]
Adding on, I saw that your background is in data science and versed in Python and R. In that case, maybe you can try this project instead - https://github.com/tebelorg/TagUI-Python

It's a wrapper I made around TagUI and can be installed using `pip install tagui`. The main benefit would be ability to code directly in Python instead of the human languages.

**Comment by gfleetwood** [comment]
Thanks for the heads up on the Python package. Tag UI is working now. Turns out that I had downloaded the v5.0.0 assets the first time around. Thanks!

**Comment by kensoh** [comment]
You're welcome @gfleetwood, have fun using the tool! 👍
