### ISSUE TITLE
Error with visual automation looking for an UI element

### ISSUE THREAD

**Issue by rubber12** [kelaberetiv/TagUI#505]
ERROR - cannot find C:/TAGUI/tagui/src/tagui.sikuli/start-menu.png on screen

**Comment by kensoh** [comment]
Try checking the things here and let me know which one of them can help solve the issue!
Checklist from homepage - https://github.com/kelaberetiv/TagUI#visual-automation

  1. Check that [Java JDK (64-bit)](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) is installed (entering `java -version` returns your Java version)
  2. After Java is installed, you will have to restart your command prompt or terminal to use it
  3. On Windows, set display magnification to recommended %, if it doesn't work then 100%
  4. On Windows, if TagUI just hangs there, see if it's due to [this issue and try the solution](https://github.com/kelaberetiv/TagUI/issues/229)
  5. On macOS, if can't find image on screen, may be due to [how the image was captured](https://github.com/kelaberetiv/TagUI/issues/240#issuecomment-405030276)
  6. On Linux, requires installing and setting up dependencies by following [this guide](https://sikulix-2014.readthedocs.io/en/latest/newslinux.html#version-1-1-4-special-for-linux-people)

**Comment by rubber12** [comment]
thank you, sir. I  got the answer.
