### ISSUE TITLE
How to extract PDF text using TagUI and SikuliX

### ISSUE THREAD

**Issue by rubber12** [kelaberetiv/TagUI#506]

**Comment by kensoh** [comment]
There are a few ways -

1. using visual automation to open the PDF, using `keyboard [ctrl]a` and `keyboard [ctrl]c`, then paste into Notepad with `keyboard [ctrl]v`

2. if PDF is image text, can use visual automation to open the PDF, and using read step to apply OCR to PDF window (make an image of the PDF window, but make the contents transparent. this will be troublesome if multiple pages, because you need to also tell automation to click to go to next page and keep repeating until done.

3. If PDF is text format and not an image, then using some other way to convert directly will be better to retain accuracy. For eg using Python integration with the [Python package PyPDF2](https://github.com/mstamy2/PyPDF2)

**Comment by rubber12** [comment]
Sir.. plz can you show us how to do that.. ??

**Comment by kensoh** [comment]
How is your PDF like, do you have a sample? Need to see if it is pure text PDF or image PDF.

**Comment by rubber12** [comment]
yaa sure. Plzzz Check this out
[cns_mod1.pdf](https://github.com/kelaberetiv/TagUI/files/3396761/cns_mod1.pdf)

**Comment by rubber12** [comment]
Sir, please answer me.

**Comment by ryzalk** [comment]
Hi @rubber12 . Ken, as well as other users, have kindly replied to issues and queries submitted for this tool/repo on their own time and expense so it would be nice if you do not rush them, as they do not have any obligation to answer you with this being an open source offering.

Anyway I have taken a look at the PDF file and it seems like it is an image PDF. This adds complexity to your problem as it is not easy to extract handwritings from images. My personal opinion is that TagUI/SikuliX won't be the best tool for this job and you would have to resort to smarter solutions that utilises deep learning capabilities.

**Comment by rubber12** [comment]
Hi @ryzalk. I need to know how can I extract the pdf using TagUI and SikuliX

**Comment by rubber12** [comment]
Is that possible to extract text pdf data? using TagUI and SikuliX

**Comment by kensoh** [comment]
Thanks @ryzalk !

Hi @rubber12 yes what @ryzalk said is correct. Below are 2 sample pages from your PDF. They are handwritten text, combined with faded ink, lines, and background image. TagUI, even with Tesseract OCR, will not be able to convert such format into text.

You can explore other OCR tools or commercial RPA software to try to do this, though I feel that chance of success is low in getting acceptable accuracy. As it is not just hand-written numbers but different text in a heavily accented hand-writing style.

Even if there is a possible advance OCR or deep learning solution, the price you have to pay to use that solution will be so expensive that it may be better to hire some freelancer to help you transcribe these PDFs to text. Closing issue for now as this can't be done with TagUI.

![Screenshot 2019-07-17 at 4 40 00 PM](https://user-images.githubusercontent.com/10379601/61366738-bf669580-a8bc-11e9-913b-a478b1f46020.png)

![Screenshot 2019-07-17 at 4 40 17 PM](https://user-images.githubusercontent.com/10379601/61366746-c1c8ef80-a8bc-11e9-975f-e417a68d4466.png)

**Comment by raghmk** [comment]
Is it possible to extract data from a pdf which doesnt have hand written text but has typed text along with tables. I tried with tesseract, but it doesn't extract data if pdf has tables.

**Comment by kensoh** [comment]
I don't think it will work reliably because tesseract extraction does not extract tables. So the extracted text will be in a mess without context which column and row it belongs to. I think Microsoft has created some technology for converting image of table into Excel.

But tesseract alone can't do that. You probably have to combine with your own computer vision algorithm in Python to detect lines of the table and then segment text accordingly for extraction. So not something that can be done out of the box for TagUI.

**Comment by rubber12** [comment]
Thank You for your kind information, sir, @kensoh

**Comment by kensoh** [comment]
Good luck for your project work! - saw from your profile that you are studying.

So probably trying to find a way to digitise for project work or for own studying.
