### ISSUE TITLE
Unable to check two variables using check step - use indexOf()

### ISSUE THREAD

**Issue by ShwetaChahan** [kelaberetiv/TagUI#510]
I am reading two values from ui
Ex : 
read h2 to var1 
read h2 to var2
Using the following syntax to check, but it always fails
check var1 contains "`var2`" | "pass"| "fail"

Please suggest

**Comment by kensoh** [comment]
Hi @ShwetaChahan for the check step, when using natural language for the condition contains, I have to check for quotes in order to parse the meaning. Thus only checking text string is possible.

For checking if variable 1 contains variable 2, you can do it the JavaScript way with indexOf() -

```
a = 'xyz'
b = 'y'
check a.indexOf(b) > -1 | 'pass' | 'fail'
```

For JavaScript, indexOf() will return -1 if the string is not found,
and position of the string b in a if found (integer 0 or more).

**Comment by kensoh** [comment]
Closing for now until further inputs
