### ISSUE TITLE
Headless file upload Linux - use upload step, if fail try dom step

### ISSUE THREAD

**Issue by sachin1004** [kelaberetiv/TagUI#513]
Hi Kensoh,

I'm having issues while trying to upload file in headless chrome in linux. I'm using CSS selector for uploading ex upload 'cssSelector' as 'fileUrl'. I can see the file name being displayed near the file field, however when i click on upload button nothing happens. Can you please help me. Thanks in advance.

**Comment by kensoh** [comment]
Hi @sachin1004 as you already know in headless mode, normal clicking of choosing file will not work.

Using upload step with CSS is correct. If it does not work, there is unlikely any easy workaround that can be done, because TagUI is already using the standard DevTools protocol's `DOM.setFileInputFiles` to natively set the file to be uploaded.

One thing you can try to experiment, is see if you can use dom step to execute custom JavaScript code to do the file selection and upload. If you can do that in Chrome visible mode, then likely it will work for headless mode.

**Comment by sachin1004** [comment]
Thanks Kensoh. Will check the js implementation and post the result here

**Comment by sachin1004** [comment]
Hi Kensoh,
I was exploring the js implementation, simple document.querySelector("#file").value ="filePath" is restricted because of security issues. So i don't think we can replicate upload in js. 

The formData solution could have been used if it were api test, unfortunately I'm working on UI test.

I suppose we can try autoIT script using run step. Any advice?

**Comment by kensoh** [comment]
Thanks for your update @sachin1004 ! I see.. Yes Chrome has strict limitations on security for good reasons. The only other alternative I can think of is using TagUI in default mode (without chrome or headless option). In that mode, PhantomJS can also let you use the upload step to specify CSS of the file to be uploaded. However, it may not work because PhantomJS is an older browser and many applications may not work correctly as they are tested to work in Chrome.

If PhantomJS mode does not work, I'll recommend trying out some other solutions (perhaps commercial RPA software or other test automation frameworks). Not recommended to use run step with AutoIT because your use case is a special situation in headless mode, there isn't a Chrome browser to combine workflow with TagUI. So it is unlikely to work.

**Comment by sachin1004** [comment]
Thanks @kensoh. Will check with default mode once and update.

**Comment by sachin1004** [comment]
@kensoh do you think we can use Page.setInterceptFileChooserDialog set to true and then Page.handleFileChoose, params: {"action":"accept","files":["logger.log"]} in chrome protocol?

**Comment by kensoh** [comment]
That's a great idea to try.

**From the documentation of this experimental feature, following should work in TagUI script**
```js
chrome_step('Page.setInterceptFileChooserDialog', {enabled: true});
click Choose Photo/Video
chrome_step('Page.handleFileChooser', {action: 'accept', files: ['/tmp/abc.txt']});
```

**References from website of maintainer of Puppeteer**
https://vanilla.aslushnikov.com/?Page.setInterceptFileChooserDialog
https://vanilla.aslushnikov.com/?Page.handleFileChooser

However, most likely because this is an experimental feature, it is not working on my Chrome. You can experiment if it works in newer versions of Chrome for your use case.

But this would not be a feature to be implemented yet in TagUI codebase as it is experimental stage in DevTools Protocol and not yet working.

**error response from my Chrome at v75 (latest for macOS)**
```
[tagui] INPUT  -
[63] {"id":63,"method":"Page.setInterceptFileChooserDialog","params":{"enabled":true}}
[tagui] OUTPUT -
[63] {"error":{"code":-32601,"message":"'Page.setInterceptFileChooserDialog' wasn't found"},"id":63}
```

**Comment by kensoh** [comment]
Closing issue for now until further inputs! Due to above response from Chrome, this technically is not implementable until it reaches stable state in DevTools Protocol.
