### ISSUE TITLE
TagUI snap page with Chrome not capturing full screen.

### ISSUE THREAD

**Issue by RobinTYK** [kelaberetiv/TagUI#515]
Hi,

I tried the command tagui samples\1_yahoo chrome 
The snap page command is not able to capture full page as oppose to without the chrome option. 

Is this expected?
Thanks.
![snap1](https://user-images.githubusercontent.com/53131599/61586137-8752a180-ab9f-11e9-8522-a9b60aca8ed2.png)

**Comment by kensoh** [comment]
Hi @RobinTYK yes that is expected. The goal of TagUI is to replicate user action on applications frontend. Thus a normal print-screen would also only capture the visible area of the webpage and not the entire webpage.

Without Chrome option, TagUI runs in the default PhantomJS mode. Since it was designed originally for test automation, it captures the full length of the webpage whether it is in the visible area or not.

Some alternatives if still want to use TagUI -

1. using dom step with JavaScript code to scroll down and capture separate images (eg `dom window.scrollTo(500, 0)`)

2. use default mode in PhantomJS to capture the fullscreen image, but PhantomJS is an older browser engine, so it may not work correctly for websites designed and tested on Chrome

3. use [visual automation mode](https://github.com/kelaberetiv/TagUI#visual-automation) to tell Chrome to export webpage as a PDF

Otherwise, there should also be other automation tools that can capture fullscreen of webpage.

**Comment by RobinTYK** [comment]
Thanks for the tips!

**Comment by dannyzuo** [comment]
> hi, may i know how to tell chrome to export webpage as a pdf? for snap command, not a full page, but only visiable page, I want to snap a full page. thanks.

use [visual automation mode](https://github.com/kelaberetiv/TagUI#visual-automation) to tell Chrome to export webpage as a PDF
