### ISSUE TITLE
How to dump array data into .csv file and how to connect with Oracle DB

### ISSUE THREAD

**Issue by hasanmahamud31** [kelaberetiv/TagUI#519]
How to dump array data into .txt and .csv file and also how to connect with oracle DB using tagui

**Comment by kensoh** [comment]
Hi Hasan, to access database you can use run step. You will have to find the correct SQL commands to use to do the writing, and also the correct Oracle command line command to run queries.

Below is an example using MySQL. For Oracle SQL, there should be something similar to do reads and writes. Be sure that the Oracle SQL command line command is available before trying to call it in a temporary script. The temporary script is required in order to capture the different quotation marks in the command to run query. https://github.com/kelaberetiv/TagUI/issues/112

To dump array into .csv you can make use of csv_row() and write step. More on csv_row() here at helper functions - https://github.com/kelaberetiv/TagUI#helper-functions

**Sample TagUI script**
```
// declare dummy array
forex_rates = []
forex_rates[0] = ['USDSGD','1.370']
forex_rates[1] = ['USDJPY','108.7']
forex_rates[2] = ['EURUSD','1.110']

// create csv header
dump 'Currency,Exchange Rate\r\n' to result.csv

// write to csv file
for record from 0 to 2
write csv_row(forex_rates[record]) to result.csv
```

**Output result.csv**

Currency|Exchange Rate
:--------|:--------------
USDSGD|1.370
USDJPY|108.7
EURUSD|1.110
