### ISSUE TITLE
Use Safari instead of Chrome (headless) - how about Firefox?

### ISSUE THREAD

**Issue by cevangelio** [kelaberetiv/TagUI#521]
Is it possible to use Safari instead of Chrome in headless mode?

**Comment by kensoh** [comment]
Hi @cevangelio Safari browser is not supported natively by TagUI, as TagUI uses DevTools Protocol to talk directly to Chrome. Also, since TagUI is meant for process automation, Chrome would be the browser that most apps would be tested to work properly on and should fit the scope of process automation. Thus, no plans to extend to Safari browser. Firefox browser v59.0 or earlier is supported using the firefox option - https://ftp.mozilla.org/pub/firefox/releases/59.0

If you really need to use Safari browser and with TagUI, you can visual automation method to interact and extract info using images / OCR / keyboard shortcuts - https://github.com/kelaberetiv/TagUI#visual-automation

You can also check out Selenium, there might be a solution there that interacts with Safari browser.

**Comment by cevangelio** [comment]
Hi Ken, using Safari is required by internal company websites that I use, thus the request. I currently use TagUI using visual automation which is great but want some of the tasks I want to be able to run in the background. I've used Selenium before so I would check that again, thanks for the answer @kensoh!

**Comment by kensoh** [comment]
Oh I see.. Great! Hopefully selenium works for you (don't think there is headless Safari though). Closing issue for now but feel free to add on anything here!
