### ISSUE TITLE
click visually is not working in ubuntu 18.04 - SikuliX need special setup

### ISSUE THREAD

**Issue by rubber12** [kelaberetiv/TagUI#523]
At first it is working on my system after reinstalling ubuntu its not working it is not processing the image.. So plzz help

**Comment by rubber12** [comment]
![a](https://user-images.githubusercontent.com/47210737/62022321-69152300-b1e9-11e9-9b02-56480dd8c069.png)
see this it will stop here.

**Comment by rubber12** [comment]
![b](https://user-images.githubusercontent.com/47210737/62022556-88f91680-b1ea-11e9-8aa4-1cf1cc67d99b.png)

**Comment by kensoh** [comment]
For Ubuntu, I assume you already install php with apt-get command because Ubuntu does not come with PHP. TagUI uses PHP to do the translation from human language to JS code to do the automation. For visual automation on Linux systems (Ubuntu is Linux), you have to follow the special setup instructions mentioned in

Visual automation section of readme -
https://github.com/kelaberetiv/TagUI#visual-automation

Direct link on special setup on Linux -
https://sikulix-2014.readthedocs.io/en/latest/newslinux.html#version-1-1-4-special-for-linux-people

**Comment by kensoh** [comment]
Also, make sure that you have downloaded the packaged installation for Linux, it already comes with Jython interpreter packaged in for use with SikuliX - https://github.com/kelaberetiv/TagUI#set-up

**Comment by rubber12** [comment]
![a](https://user-images.githubusercontent.com/47210737/62022321-69152300-b1e9-11e9-9b02-56480dd8c069.png)
see this it will stop here.

**Comment by rubber12** [comment]
Sir , first of all i don't want Sikulix_ide , i need sikulix to work with tagui....

**Comment by kensoh** [comment]
TagUI uses SikuliX and SikuliX is SikuliX IDE run in command line mode.

So above setup steps are needed to use visual automation mode with TagUI.

**Comment by rubber12** [comment]
Thank you sir it's worked..
