### ISSUE TITLE
 chromeStep does not work to change download folder - use \\ ?

### ISSUE THREAD

**Issue by Donko123** [kelaberetiv/TagUI#528]
Hi Ken Soh,

I am trying to change the chrome download path in a chrome step, but I cannot make the download where I indicated, as additional data, I access a page and from it I get a token to access another page, in the second web page when I download the file simply TagUI saves it in downloads.

chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'C:\DownloadTagUI'});

Greetings.

**Comment by kensoh** [comment]
Hi Donko, thanks for raising this issue, can you try if using double backslash works? This is because in JavaScript backslash \\ is an escape character and \\\\ is needed to represent \\ in path names on the operating system. And need to make sure user has write access to that folder.

chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'C:\\\\DownloadTagUI'});

**Comment by Donko123** [comment]
Hi Ken Soh,

I tried it with // and it does not work, I have noticed that at the time of downloading the page opens a new tab ... generates the file to download and closes the new tab, this causes tagUi to "lose" the connection and It is waiting infinitely, I think that is why the Chromestep does not work since it performs a test by downloading from another page and if the chromeStep works, does it help?

**Comment by kensoh** [comment]
I see.. It looks like it might be a unique download behaviour for this webpage. To try to isolate the problem, can you try -

1. if the sample 3 which downloads from GitHub works -
https://github.com/kelaberetiv/TagUI/blob/master/src/samples/3_github

2. if above works when you use chrome_step to change folder before `click Download ZIP` step

If 1 works and 2 fails, it could be some write permissions issue with the folder or maybe a space in the path name. Try changing to another folder to see if that works.

If both 1 and 2 above works, it could be something specific for your website, can you share your replication steps? And also share the log in tagui/src/tagui_chrome.log to see what is the response from Chrome when chrome_step is used.

What the chrome_step command above does is tell Chrome where to store the downloaded file and whether to accept downloads. By default, TagUI will run this step to set to the same folder as the TagUI script. Also try running without using the step to see if it downloads correctly to default TagUI script folder path.

**Comment by Donko123** [comment]
Hello,
It works 1 and 2 changing the route successfully with chrome Step, I can share the steps but it is a company page that has username and password ... attached tagui chrome.log.

[tagui_chrome.log](https://github.com/kelaberetiv/TagUI/files/3452812/tagui_chrome.log)
[steps.txt](https://github.com/kelaberetiv/TagUI/files/3452835/steps.txt)

Greetings.

**Comment by kensoh** [comment]
Thanks Donko, I haven't something like this before. If you see the tagui_chrome.log file, below first block is the working one called by TagUI. For some reason, the Chrome browser is saying that string value must be provided instead of what you gave - error `string value expected`.

Not sure if it is due to some special character set that Chrome does not recognise or what. Do you have clues on similar problems in the past? Or do you have a colleague or friend with a different laptop using English to see if the same error happens? Not seen this before.

**called by TagUI when you provide an URL**
```
[tagui] INPUT  - 
[1] {"id":1,"method":"Page.setDownloadBehavior","params":{"behavior":"allow","downloadPath":"C:\\tagui\\src\\fijo"}}
[tagui] OUTPUT - 
[1] {"id":1,"result":{}}
```

**called by you as a step in TagUI script**
```
[tagui] INPUT  - 
[63] {"id":63,"method":"Page.setDownloadBehavior","params":{"behaviour":"allow","downloadPath":"C:\\descargasTagUI\\Fija"}}
[tagui] OUTPUT - 
[63] {"error":{"code":-32602,"message":"Invalid parameters","data":"behavior: string value expected"},"id":63}
```

**Comment by Donko123** [comment]
Thanks Ken Soh,

I will set up a virtual machine to perform the test in an English OS and I will tell you the results.

**Comment by kensoh** [comment]
Sure Donko, adding on, the only similar error I found on Chrome is a Ruby open-source project. Their solution is converting the parameter to a string. I'll share their solution here, although I don't understand how that will work and whether it will work for your use case -

**reference** - https://github.com/machinio/cuprite/issues/47#issuecomment-460054081
```
chrome_step ('Page.setDownloadBehavior', {behaviour: 'allow', downloadPath: 'C:\\descargasTagUI\\Fija'.toString()});
```

**Comment by kensoh** [comment]
Closing the issue for now until further inputs or comments from other users!
