### ISSUE TITLE
how can I handle new tabs of popup windows with python?

### ISSUE THREAD

**Issue by abirkorched** [kelaberetiv/TagUI#530]

**Comment by kensoh** [comment]
To automate on popup new tabs, use the popup step.

Check pro steps here - https://github.com/kelaberetiv/TagUI#steps-description
And sample 9 - https://github.com/kelaberetiv/TagUI/blob/master/src/samples/9_misc

For Python integration use the py step. You can also use `py begin` and `py finish`. But I'm not sure what you mean by using Python to handle new tabs. The Python integration for TagUI is to perform Python code, eg calling ML models etc. If you want to write script in Python, then you can use the TagUI for Python package - https://github.com/tebelorg/TagUI-Python

However it does not support popup tabs because TagUI live mode does not support popup step. The package runs TagUI in live mode to communicate with and perform the automations.
