### ISSUE TITLE
Support for use of other OCR integration instead of Sikuli 

### ISSUE THREAD

**Issue by hemanthsavasere** [kelaberetiv/TagUI#531]
Hi @kensoh,

I wanted to know if I can integrate my own OCR based on deep learning model like tesseract OCR instead of SilkuliX, as accuracy is better in case of tesseract OCR compared to Sikuli.

Thanks & Regards,
Hemanth Savasere

**Comment by kensoh** [comment]
Hi Hemanth, oh SikuliX is using Tesseract 3.0.5 as the OCR engine. See here - https://sikulix-2014.readthedocs.io/en/latest/news.html

But yes you can use your own engine or model. There are a few ways you can try. First will be using the py step to call Python code and run them directly before collecting back result. Details -

https://github.com/kelaberetiv/TagUI#python-integration

Second may be using run step to run some command for OCR and get result.

**Comment by hemanthsavasere** [comment]
Hi @kensoh,

I think in this way I have to provide screenshots, after each stage. Ex. After login, we need to again pass the screenshot of the next page to the OCR. Is there any way that I can make sure that TAGUI does it automatically rather than the explicit call of snap and then the OCR recognition.

**Comment by kensoh** [comment]
If your steps are the same but repeated, you can see if using tagui step to call a combination of a few steps work for your use case - 

https://github.com/kelaberetiv/TagUI/blob/master/README.md#modules

If not, maybe you can use the Python package instead and hack the tagui.py to do something special after each step. Because TagUI has no option to take screenshots automatically after each step.

**Comment by hemanthsavasere** [comment]
Thanks, @kensoh.
