### ISSUE TITLE
Keyboard typing is slow - pending replication details or hack TagUI

### ISSUE THREAD

**Issue by sandeep14897** [kelaberetiv/TagUI#536]
Hello,

I was trying to open run and want to type the complete path of the file i need to open. In this case the typing getting very slow. Can you please suggest me on this how to overcome the issue.

**Comment by vrudhay** [comment]
I also have faced this issue most of the times
![image](https://user-images.githubusercontent.com/6286626/63343650-1fdd6c80-c36c-11e9-8741-32c8f73bd71a.png)
Just typing some 20-25 chars it takes 3 secs - wont it just splash by default.

**Comment by sandeep14897** [comment]
@vrudhay For you it is taking at least 3 secs. but in my case it is taking a lot time. for every letter it is taking 1 sec delay don't know why?

**Comment by vrudhay** [comment]
@sandeep14897 can you show that line which is used to type something - is it vision type or just type?

**Comment by sandeep14897** [comment]
@vrudhay it is type <IMG> as <path of doc>

**Comment by sandeep14897** [comment]
@vrudhay I have used vision type also. But it is also not working.

**Comment by kensoh** [comment]
Thanks @vrudhay for sharing your inputs!

@sandeep14897 what @vrudhay said is the correct behaviour. The type step simulates normal user keypresses one by one so it does not happen instantly. This is so that application thinks that the automation behaves like a normal human user.

Expected behaviour is a few seconds for 20+ characters, like what @vrudhay said. Your computer seems to be working differently at 1 character per second. Can you try the code at your friend or colleague's laptop? Can you also share more details your code to replicate the issue? 

When I checked TagUI source code, it will call SikuliX `type()` function directly without doing special processing. Thus the delay looks like not possible to be caused at the TagUI's area but somehow SikuliX is behaving unusually on your computer.

---

Lastly, if for whatever unknown reason SikuliX type() is working very slowly on your computer and the root cause cannot be found, one way is to explore hacking TagUI. This is not recommended, when you upgrade to future release of TagUI, this hack will be gone and you have to repeat this change.

In file `src\tagui.sikuli\tagui.py`, under function `def type_intent ( raw_intent ):`, change all the `type(` to `paste(`. This will change the default behaviour of typing character by character to simply instantly pasting the text you want to type.

**Comment by sandeep14897** [comment]
@kensoh Thank you. The issue got resolved. I have changed the **def type_intent ( raw_intent ):** to paste( in python file. 

That worked fine. Thank you for the immediate response.
