### ISSUE TITLE
Upload with function - using custom functions

### ISSUE THREAD

**Issue by Fry115** [kelaberetiv/TagUI#538]
Hello, 

I am trying to upload images automatically to a business page, the images change their name 4 times a day with a timestamp and a correlative, create a function that if I echo it generates the string I want to upload but at the time of concatenating the timestamp and the correlative to the upload option when uploading the image does not detect as a timestamp or correlative function:

upload #scv_file_file_provider as "upload_master" + timestamp () + "-" + run + ". csv"

Thanks.

**Comment by kensoh** [comment]
Hi @Fry115 yes you can create custom functions. More details and example below -

https://github.com/kelaberetiv/TagUI#helper-functions
https://github.com/kelaberetiv/TagUI/issues/236#issuecomment-403188526

After you create the custom function `generate_filename()`, you can call it using below -
```
upload #scv_file_file_provider as `generate_filename()`
```

Your above line may be is not working because you use quotation marks. There is no need for quotation marks in the text parameter for upload. The backtick ` is used to denote variables and functions as TagUI default context for many steps is text and not variable, to make the usage more like natural human language.

**Comment by Fry115** [comment]
Hi,

I'll try what you tell me, thanks.
