### ISSUE TITLE
location to use variables outside the vision step - custom SikuliX code

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#539]
how to use location to use variables outside the vision step
![image](https://user-images.githubusercontent.com/6286626/63405023-fa4f7200-c402-11e9-94b3-67a66042d18f.png)

y = y + 60
click (`x`,`y`)
vision_step('x = "' + x + '"')
vision_step('y = "' + y + '"')
vision dragDrop(Location(x,y), Location(500,250))

where could be the prob.  x and y goes exactly the same.  Is there any .value?

**Comment by kensoh** [comment]
If relative coordinates is needed, I showed you an example link from the other issue -

https://github.com/kelaberetiv/TagUI/issues/535#issuecomment-522890904
https://github.com/kelaberetiv/TagUI/issues/537#issuecomment-523069703

So there is no need to use custom SikuliX commands by using vision step.

The above code is SikuliX Python code. I think your error is making x and y a string when it should be numbers. You can try something like below or explore more on SikuliX documentation. But there is no need to use this method because you can do it directly using above examples.

```
vision_step('x = ' + x)
vision_step('y = ' + y)
```

**Comment by vrudhay** [comment]
Gotcha! worked!!

**Comment by vrudhay** [comment]
![image](https://user-images.githubusercontent.com/6286626/64245952-85635880-cf29-11e9-839b-678899aa423d.png)

Am sorry... Actually this didnt work.  Line 24 vision_step is not getting the values into the variables.  What could be the problem.
I am yet to master the knack.  Pls. suggest.

**Comment by kensoh** [comment]
For drag and drop you don't have to use vision step. You can do a mouse down -> hover to some x,y coordinates, then mouse up. Make sure to have the cutting edge release (check setup section).

If you still want to use above logic, once variables go to SikuliX, you can reference directly with `Location(sd1_x, sd1_y)` don't have to use ` symbol to replace variables anymore. That is only used in TagUI because TagUI a lot of steps assume text as text and not variable names.

**Comment by vrudhay** [comment]
dragDrop is working nice if I give Location(100,200) - some location.  Would like to know only how to use variables.
![image](https://user-images.githubusercontent.com/6286626/64247083-b6dd2380-cf2b-11e9-9562-a7eaac4ace57.png)
In the image - I removed that back tick and still not substituting - LIne 17.
Advice?

**Comment by vrudhay** [comment]
![image](https://user-images.githubusercontent.com/6286626/64248272-5a2f3800-cf2e-11e9-98e2-6866658130b5.png)
I am able to change to hover and even the coordinates are coming - still some where there is challenge.  Why does it say cannot find a location?

**Comment by vrudhay** [comment]
****
![image](https://user-images.githubusercontent.com/6286626/64248802-c52d3e80-cf2f-11e9-82f1-d0cb708caefb.png)
Something strange is happening - if I hardcode, it works and if it is getting substituted from variable - it says cannot find - is this a bug?

**Comment by kensoh** [comment]
Your screen shot shows that for the second Location you are using using backticks `

**Comment by vrudhay** [comment]
if I dont use back ticks - in the previous snapshot you can see that it substitutes the right values.  We have to use or just leave it?

**Comment by kensoh** [comment]
Use backticks for variables in TagUI steps. For vision step in SikuliX, don't use backticks.

**Comment by kensoh** [comment]
Also, make sure you are using the latest cutting edge version -
https://github.com/kelaberetiv/TagUI#set-up

**Comment by kensoh** [comment]
Adding on, below is an example using the cutting edge version (typing tagui command with no parameters will show v5.5).

**script**
```
hover (100,200)
x = 100
y = 200
hover (`x`,`y`)
```

**result**
```
START - automation started - Thu Sep 05 2019 20:57:21 GMT+0800 (+08)

hover (100,200)
hover (100,200)

FINISH - automation finished - 14.8s
```
