### ISSUE TITLE
how to send arguments to modules with tagui step

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#540]
![image](https://user-images.githubusercontent.com/6286626/63411500-4b676200-c413-11e9-82eb-a2981a40f393.png)
How to send arguments (e.g. x and y coordinates) in the above file and making use in the another

////--------dragDrop
y = y + 60
tagui a_dragdrop.tagui

**Comment by kensoh** [comment]
`tagui` step expands the code in your file a_dragdrop.tagui at the same spot where you call it. 

Thus the variables that you define in the main program can directly be used in the code in a_dragdrop.tagui. When you modify variables inside the call, the variables will also change in your main program. This design was chosen so that it is easy to pass variables without users having to declare formal module parameters headers and take longer time for developing scripts.

**Comment by hemanthsavasere** [comment]
Hi @kensoh,

If I want to pass an argument to a python file from TAGUI, then how should I do it. Like we have command-line arguments in python

**Comment by kensoh** [comment]
There isn't a way to pass command-line arguments to Python in TagUI's Python integration. Unless you use the run step to run python command on the Python script.

For sending parameters to Python from TagUI, you can do the following (more details in https://github.com/kelaberetiv/TagUI#steps-description under pro steps details)

```
phone = 1234567
name = 'donald duck'
py_step('phone = ' + phone)
py_step('name = "' + name + '"')

py print(name)
echo py_result
py print(phone)
echo py_result
```

**Comment by hemanthsavasere** [comment]
Thanks @kensoh.

**Comment by vrudhay** [comment]
Very nice!  Working!!
As ever, we are struggling with more comprehensive cheat sheet.
