### ISSUE TITLE
How to run desktop automation on VM without display - not supported

### ISSUE THREAD

**Issue by RuturajD** [kelaberetiv/TagUI#542]

**Comment by RuturajD** [comment]
Hello Ken Soh,

Hope you are doing well.

I am trying to automate the download of files from outlook and save it into a desired folder using tagui python library. I have used images for the automation. I have deployed it on a VM. The problem I'm facing is the flow fails if it doesn't detect any image. I have used click command for automation. Is there any other command which doesn't require the screen to appear and run the flow on VM? Please do suggest.

Thanks,
Ruturaj.

**Comment by kensoh** [comment]
Hi Ruturaj, good day to you. I've heard of users running TagUI on Windows VM and using visual automation features. Can you tell me more about the type of VM you are using and how are you using it?

When a VM is spinned up, there should be a virtual display that is accessible for TagUI visual automation, but from your experience above, it sounds like the VM display is not accessible. For desktop outlook, only visual automation method can work. If you are using Outlook web application, then the normal web identifiers can work.

Other info that you can provide which can help to troubleshoot - are you using TagUI for Python, or this TagUI project directly, with some Python integration using py step? Any replication steps or sample script you can share to show how the issue can happen?

**Comment by RuturajD** [comment]
Hello Ken Soh,


[All_in_one.zip](https://github.com/kelaberetiv/TagUI/files/3540075/All_in_one.zip)
1. The VM I'm using is a VM Ware. When I'm running the script I have to keep the VM logged in or else the script execution fails. I want to know whether we can execute the script without screen appearance.
2. I'm using TagUI for Python. I'm using desktop outlook for automation.
3. There is new tool in market called Techforce.AI which allows to perform the flow without any screen appearance. Do we have any feature like it into TAGUI for python?

**Comment by kensoh** [comment]
I see.. For TagUI for Python, you can raise the issue next time there - https://github.com/tebelorg/TagUI-Python/issues

Both TagUI and TagUI for Python uses SikuliX for the visual automation engine. That engine requires a display in order to automate using computer vision of the UI elements. So, unless the VM instance has a display enabled, SikuliX will not be able to work. Thus for your use case to automate visually without a display, it will not be a suitable tool.

I heard that TechForce.ai underlying engine is TagUI. But they may have perhaps added another visual automation engine maybe using Python UI automation frameworks, or maybe their implementation uses VM ware / Linux image configuration that is configured to have virtual display such as Xvfb (virtual framebuffer).

**Comment by kensoh** [comment]
Closing issue for now until further inputs
