### ISSUE TITLE
TagUI desktop application support - how to interact with desktop apps?

### ISSUE THREAD

**Issue by shravanvh** [kelaberetiv/TagUI#550]
Hi @kensoh 

Thanks for keeping something like tagUI open source :). I am fairly new to tagUI, could you please help me out with some queries related to it:

- The browser doesn't end clean after the automation is over, whenever I try to run a different new script it throws the "Restore/Close tabs" pop up in the browser, in my case I have used Google Chrome.

- How to identify the address of the local windows applications elements other than visual image option to automate? Other than image as a reference to pass the data is there something we can use? 
Suppose, for example: If I am searching for a particular person in "Microsoft Teams", after the search I would like to click on the exact person in order to chat or send him some content.

- How to always click the latest unread mail from outlook of specific subject. 

That's all for now. I'll get back and update if I have something new.

Regards,
Shravan

**Comment by kensoh** [comment]
- Hi Shravan, I see, yes that is a known side-effect because there is no other way of terminating Chrome other than killing its process through the operating system level.

- Your understanding is correct, only visual automation is able to interact with the desktop applications. Besides using images, you can try to see if using keyboard combinations can do what you need. Most open-source tools can't interact with desktop applications directly, but you can google for some other tools which can do so to see if it fits your use case better.

- Besides recognising by image, you can do x,y coordinates offset or specify x,y coordinates to click. For example, `click (400, 600)` if you know the latest email is always at the top and the location is always the same. You can use `echo mouse_xy()` in live mode to check the current mouse position.

**Comment by shravanvh** [comment]
Hi Kensoh, Thank you so much for the update. I will try and see how to work out with it.

**Comment by kensoh** [comment]
Sure @shravanvh I'll close the issue for now but do shout out here or reopen if you have more questions!
