### ISSUE TITLE
Command prompt not closing after execution - pending replication details

### ISSUE THREAD

**Issue by sandeep14897** [kelaberetiv/TagUI#551]
Hi @kensoh ,

After the execution of the all the steps in the code my command prompt was getting closed. After that there were no other steps for execution even, do not know why that was happening. Can you help in resolving this issue.

Thanks in advance.

**Comment by kensoh** [comment]
Hi @sandeep14897 can you provide replication step by step how to create this? If you run TagUI script by typing `tagui script_name`, after execution your command prompt should still remain open. If you set up TagUI to run by double-clicking a batch file to run the script, after execution Windows will auto-close the batch file and TagUI.

**Comment by kensoh** [comment]
And do you mean command prompt not closing (issue title) or closing (issue description)?

**Comment by sandeep14897** [comment]
@kensoh The I am running TagUi script as tagui file_name chrome. After executing all steps in the code the execution was not stopping, and there were no activities to execute further.

**Comment by kensoh** [comment]
I see.. I have not encounter this problem before. Can you try if the same problem happen on another laptop or computer? Maybe your colleague computer, and see if the issue happens?

Without details to replicate the issue, it is hard to troubleshoot the problem from my computer.

**Comment by kensoh** [comment]
Some other things you can try is run simple script like below and see if it works. But the best will be try your script on another colleague's laptop to see if the same issue happens. If another laptop works, then find the difference between the 2 laptops to see if it is due to some environment settings or security / firewall / virus scanner issues.

Run `tagui demo_script` on the command prompt.

**demo_script**
```
echo '123'
```

**Comment by sandeep14897** [comment]
@kensoh to use  `tagui demo_script` i should do automation in chrome. if i run like that i was not able to open chrome. I have also tried in my collegue system it was also having the same issue.

These are the cmd's those are open in back ground can you please refer these.

![Capture](https://user-images.githubusercontent.com/37222769/64177702-063d2a00-ce2e-11e9-8826-c58677f24ce6.PNG)
![Capture1](https://user-images.githubusercontent.com/37222769/64177709-0a694780-ce2e-11e9-9a9e-d6d6c2be34df.PNG)
![Capture2](https://user-images.githubusercontent.com/37222769/64177716-0d643800-ce2e-11e9-99fc-c62034395b22.PNG)

**Comment by kensoh** [comment]
From your SikuliX log file, it looks like there may be some admin issue. When I try to run a simple script on my laptop (macOS), there is no error message like your one saying mouse actions are blocked.


**script**
```
click pc.png
```

**pc.png**

![pc](https://user-images.githubusercontent.com/10379601/64190021-0843cf00-cea8-11e9-84b9-81de4e8ecf3d.png)

It will be difficult to troubleshoot as I don't have your laptop environment config to test. Instead of using clicking on the close-file-explorer image, are you able to use keyboard combinations to do what you need? For example, `keyboard [esc]` will simulate an escape key, `keyboard [alt][f4]` will simulate Alt + F4. Also make sure that you are running the latest TagUI version - 

https://github.com/kelaberetiv/TagUI#set-up

**Comment by kensoh** [comment]
Let me know if you try to run a simple script like above example works? For eg click on the Windows start menu button. If the simple example does not work, then most likely it is due to the error message in your SikuliX log above, saying that the automation was launched without appropriate user permissions

**Comment by kensoh** [comment]
Let me know if you try to run a simple script like above example works?

For eg click on the Windows start menu button. If the simple example does not work, then most likely it is due to the error message in your SikuliX log above, saying that the automation was launched without appropriate user permissions

**Comment by sandeep14897** [comment]
Hello @kensoh 
Sorry for the late response, Actually i have tried with a simple script and that works fine. but when i iterate the sequence of steps by placing it in a loop. I was facing the issue. 

And also can I know if TagUI can work in the VM (background automation) if we schedule it in Windows task scheduler.  If Yes, can i know the VM requirements. Please, let me know.

Thanks

**Comment by kensoh** [comment]
I see.. Can you try to create a minimal replication script with the loop and a simple click to see where could the problem happen? After you create the most basic script with loop and click image that has this problem, share with me the script so I can try to replicate the behaviour.

I see.. I know some enterprise users of TagUI run it on Windows VM, but I don't know the details of their implementation because it is done directly by their IT team and I have no visibility. You can try it out to see if that works.

For VM requirements, TagUI just need a basic computer specs to work. It can run on macOS, Windows, Linux. But I have not tested how far back in Windows versions will it run properly.

**Comment by sandeep14897** [comment]
Hi @kensoh . My problem was similar to #417. In the background my tagui cmds are still open. Can i know where should i use the helper scripts. I was trying to write a batch file, for scheduling my bot and can i write helper scripts in batch file? after `tagui filename chrome` can i use helper script to shut down background processes? Can you please let me know.

Thank you

**Comment by kensoh** [comment]
Hi @sandeep14897 I see.. Yes you can try that using batch files. The helper scripts to kill all TagUI processes is in src folder. For Windows it is `end_processes.cmd`.

However, if your environment does not let TagUI to terminate and return control back to the batch file, then when you put `end_processes.cmd` after the `tagui filename chrome` the helper script may not have a chance to run. In any case, try and see if your idea works.

**Comment by kensoh** [comment]
Another way to implement is call these helper script at the start of your batch file, or have it scheduled in task manager. So that the open windows are terminated when you run the next time, or when user need to use the laptop.

**Comment by sandeep14897** [comment]
@kenosh Will I be able to run tagui in Windows workspace with 2GB RAM and 1
core ? Because we want to schedule our not in that VM and the schedule is
not running when VM got disconnected. Can you please help me on this.

Thank you

**Comment by kensoh** [comment]
I have not done testing of TagUI for VM, but I will think 2GB is enough. From my understanding of VM, if the VM is not online, there it only exist as an image and does not do anything at all.

**Comment by kensoh** [comment]
I have not done testing of TagUI for VM, but I will think 2GB is enough. From my understanding of VM, if the VM is not online, then it only exists as an image and does not do anything at all.

**Comment by sandeep14897** [comment]
@Kenosh I see. Means now my bot will not run if I log out of the VM right?

Is there any alternative for that?

Thank you

**Comment by sandeep14897** [comment]
@Kenosh but in 2GB the process is going slow. The CPU utilisation is
exceeding more than 80% while bot is running.

Why?

**Comment by kensoh** [comment]
The main processes that are running are PhantomJS, Chrome and if visual automation is used, SikuliX (which is based on Java).

Performance testing was never done in breadth for different types of computer specifications for TagUI, as it wasn't designed to be run on VM, so there is no data on minimum requirements.

**Comment by sandeep14897** [comment]
@ken soh


Thank you for the very quick response.

It is really helpful .

**Comment by kensoh** [comment]
Closing this issue to follow-up at #560 on using helper script to kill processes.

**Comment by sandeep14897** [comment]
Hi @kensoh 

`Mouse actions are blocked generally or by the frontmost application.
You might try to run the SikuliX stuff as admin.`

I was getting this message in console and end_process also not executing as it was not getting to next step in batch file. If i should run as admin how can i do that?

Thank you in advance.

**Comment by kensoh** [comment]
Hi @sandeep14897 when you click to run command prompt, try to right-click and see if there is a menu to run as admin. See if that helps.

Interesting, I have not yet heard feedback on the end_processes.cmd not working. Can you share more what is your Windows system version and what folder you install TagUI?
