### ISSUE TITLE
TagUI for dealing with complex / random web identifiers - visual automation

### ISSUE THREAD

**Issue by Lion666** [kelaberetiv/TagUI#566]
Hi Ken, 

sorry to bother you again. 
I am trying to automate data retrieval from a platform. I use the TagUI extension of Chrome to give some indication of what to code should be but I refine it using "Copy XPATH" functionality from Chrome (inspect element). 

I am slowly but surely tackling login, inputting fields. 
I then have to click on a link that will run the report for my choices. This link is a javascript:void(null). 

`<a href="javascript:void(null)" onclick="return DashboardReportLink('saw.dll?Go&amp;Path=%2fshared%2fMAH%20Pharmacovigilance%20Query%20Library%2fReport%2felectronic%20Reaction%20Monitoring%20Report%20%e2%80%93%20ad-hoc%20reference%20period&amp;Action=PromptStart&amp;Style=ema&amp;Options=frd', 'd:dashboard~p:dbr6behhuvpukevu~r:7ckco2goaa80j3nn','Dashboard&amp;PortalPath=%2fshared%2fMAH%20Pharmacovigilance%20Query%20Library%2f_portal%2fMAH%20Pharmacovigilance%20Queries&amp;Page=electronic%20Reaction%20Monitoring%20Report%20-%20eRMR', true)" name="SectionElements">electronic Reaction Monitoring Report – ad-hoc reference period</a>`

the xpath inspection provides this xpath: `//*@id="d:dashboard~p:dbr6behhuvpukevu~r:7ckco2goaa80j3nnResult"]/a`

it provides the following error in the log (using click as function)

> ERROR - cannot find //*@id="d:dashboard~p:dbr6behhuvpukevu~r:7ckco2goaa80j3nnResult"]/a

I also tried the code providing by the tagUI extension: 
`click .PageTable:nth-child(4) tr:nth-child(11) td`

it provides no error in the log (just copy pasting the instructions) but the expected outcome which is the opening of a new tab containing the requested data does not happen as it happen when manually clicking on the link

Do you have any idea on how I could code this step of launching JavaScript instructions (equivalent of manually clicking on the link)? 

Thanks in advance, 

Lionel

**Comment by kensoh** [comment]
Hi Lionel, no problem, I think one of the strengths of TagUI is there is always very fast replies to issues and questions by users. This helps them get what they or their company or their clients want fast without being blocked by some technical challenge. Furthermore, the person replying is the person who created the tool, so you'll get the best answer lol.

Above looks like an id that is randomly generated and probably not a good idea to use it as it can change with time. But if you want to use it, for some reason your XPath above looks wrong (it is missing a left square bracket).

It should be `//*[@id="d:dashboard~p:dbr6behhuvpukevu~r:7ckco2goaa80j3nnResult"]/a`

You can try if that works. Also, if you use live step, you can interactively test your steps to figure out what works, instead of rerunning automation many times to test.

Next, for this example, it may not be easy to figure out the JavaScript code to run (using dom step). You can try the visual automation method where you provide an image to click on, it should work better than trying to find ways to deal with this complicated web element -

https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by Lion666** [comment]
Hi, 
this message to let you know that sikuli solved my issues and allowed me to move much faster and complete the proof-of-concept. That's so elegant to be able to use snips to guide the RPA. The only downside is that it will probably require some maintenance of the snips across chrome/MS upgrades but that's ok for me. 
Thanks a lot for all your work & support! 
It's impressive and much respect for letting it open source!
Lionel

**Comment by kensoh** [comment]
That's great, thanks for sharing your feedback! Yes what you said is correct, if the webpage frontend changes, then the image snapshots have to be updated to work.

You're welcome! While the foundation work was done by me over 2016-2017 full-time, it is AI Singapore (and Mr Laurence Liew) who took on the baton and bring the tool to its current state.

There would be more interesting developments to come in 2020, where someone with frontend experience would be groomed to take over the project and extend it in ways which I can't.
