### ISSUE TITLE
TagUI desktop not working - pending going through setup steps and checks

### ISSUE THREAD

**Issue by mandar-bhambure** [kelaberetiv/TagUI#571]
Hi Ken,
This is Mandar. I am exploring TagUI for desktop automation (on Windows 8).
I have TagUI+Sikuli installed on my computer as per the instructions. 
I tried a few simple scripts, for ex: double click on chrome icon on desktop, or click on windows icon  on left bottom. This is not getting automated. Can you please help?
Attached is a screenshot of my command prompt.
![Capture](https://user-images.githubusercontent.com/14823299/65040899-1cd99a00-d973-11e9-88b0-421efe23bde1.PNG)

**Comment by kensoh** [comment]
Hi Mandar, this problem is usually with unable to load SikuliX with Java. You can check 2 things -

1. Have you tried to use the packaged installation here for Windows?
https://github.com/kelaberetiv/TagUI#set-up

2. Have you tried going through the steps 1 to 4 here for visual automation?
(especially step 1 to check if java -version returns valid response and step 4 on a known Java issue)
https://github.com/kelaberetiv/TagUI#visual-automation

3. do your user account have read and write access to c:\tagui folder and the folder you install tagui?

If you have tried above, then you can drag the logs for SikuliX in tagui\src\tagui.sikuli folder here so that I can take a look.

**Comment by kensoh** [comment]
Lastly, just in case this is the reason, try to wait around 30 seconds before trying to terminate the execution. SikuliX engine is not small as it contains OpenCV for computer vision and Tesseract for OCR, thus it will take some time to load before TagUI can connect to it to automate visually.

**Comment by mandar-bhambure** [comment]
Hi Ken,
Thanks much for the help. It worked well.
I changed java installation on my machine.

Thanks!
Regards,
Mandar.

**Comment by kensoh** [comment]
Welcome Mandar, glad that it's working for you now!
