### ISSUE TITLE
Invocation of R unsuccesful - Rscript path not added to env variables

### ISSUE THREAD

**Issue by Lion666** [kelaberetiv/TagUI#576]
Hi Ken,
 
I continue to use automation with tagui. The first example was a success last week. Next phase for me is to repeat this success at a larger scale. That involves using a loop. 
As I am using R/Rstudio, I decided to use the R integration aspect of tagui. I consequently tried the most simple example to make sure it works fine: 

`r a=1;b=2
r c=a+b
r cat(c)
echo r_result`

I saved the file under samples folder under the name Rintegration.txt and I call it using the following command line: `tagui samples\Rintegration.txt` 

The DOS window stays unresponsible and displays only this.. 
```
START - automation started - Mon Sep 23 2019 15:03:42 GMT+0200 (Romance Daylight Time)

r a=1;b=2
```

I suspect my installation of R (under Windows 10) does not meet your criteria 

> Make sure that Rscript command is accessible from your command prompt (added to path or symbolically linked)

Any idea of how I could make my machine understand to run R ?

**Comment by kensoh** [comment]
Hi @Lion666 from you command prompt, can you try to type Rscript and see whether this command is accessible? TagUI relies on Rscript command being available in order to use R.

If the Rscript command is not available, make sure the folder is added to path. If it is available, check the log file in tagui\src\tagui_r to see if there is any clue of error messages from R.

Lastly, following are 2 ways of sending commands to R (using begin and finish)

```
r a=1;b=2
r c=a+b
r cat(c)
echo r_result
```

```
r begin
a=1;b=2
c=a+b
cat(c)
r finish
echo r_result
```

**Comment by Lion666** [comment]
Hi, 
Rscript command is not available except if I go into the right directory where the file is located meaning running first the command 
`cd c:\Program Files\R\R-3.5.0\bin`

Should I use some code before to mention where to find rscript.exe so that the command r begin can be understood?

**Comment by kensoh** [comment]
I see, you can add this folder c:\Program Files\R\R-3.5.0\bin to your path in your Windows system environment variables. You can google and will see some step by step examples how to add that.

After adding to path, Rscript command will be available for TagUI to call in its script.

**Comment by Lion666** [comment]
That's what I was afraid of :( To be honest, I don't have the admin rights on my corporate machine to edit the environment variables. 

The nice thing with tagui, sikuli etc was that I could use it without installation (meaning even if I don't have the admin rights). 

Do you have any suggestion on how I could programatically make undesrtand tagui where is the location of the Rscript file on my machine so that it can understand the R command?

**Comment by kensoh** [comment]
Oh I see.. If you can't edit environment variables. In that case, the only alternative is to hack TagUI.

Since it is designed for systems where Rscript command is made available through the environment, but your PC you can't do that, you can do the following -

1. Edit src\tagui.cmd file
2. Search for Rscript
3. Add the full path in front of the Rscript command

For example below -
```
start /min cmd /c c:\progra~1\R\R-3.5.0\bin\Rscript tagui_r\tagui_r.R 2^>^&1 ^| tee -a tagui_r\tagui_r.log
```

You have to check to verify that c:\progra~1\R\R-3.5.0\bin\Rscript can run your R command first. Normally progra~1 should map to Program Files. If not you can try progra~2.

**Comment by Lion666** [comment]
Thanks a lot! That does the job :)
