### ISSUE TITLE
R integration for looping - possible but recommend using datatables feature

### ISSUE THREAD

**Issue by Lion666** [kelaberetiv/TagUI#580]
Hi Ken, 

I am kind of stuck at the next steps where I want to automate some access for multiple values. 
Let's say the original code is the following: 

```
https://TheWebsiteIWantToAccessTo
click username
type username as MyUserName
click password 
type password as MyPassWord
click //*[@id="submit"]
click //*[@id="dashboard_page_1_tab"]/tbody/tr/td[2]/span
type //*[@class="promptTextField textFieldHelper"][1] as VALUE1[enter] 
click //*[@id="dashboard_page_1_tab"]/tbody/tr/td[2]/span
click //*[@id="d:dashboard~p:dbr6behhuvpukevu~r:7ckco2goaa80j3nnResult"]/a
vision type(Key.F11)
vision type(Key.END, Key.CTRL)
click Export.PNG
click Data2.PNG
click CSV.PNG
vision type(Key.DELETE)
vision type("VALUE1")
vision type(Key.ENTER)
```

Now I want to iterate and do the same not only for VALUE1 but for VALUE1 to VALUE29. 

I consequently used R integration: 

```
r library(sqldf)
r dico<-read.csv(file="C:\\Users\\U058685\\Downloads\\ListOfValues.csv",header=TRUE,sep=",")
r names(dico)<-gsub("[^A-z]", "", names(dico))
r ntot<-sqldf('SELECT count(distinct Values) FROM dico')
r lst<-sqldf('SELECT distinct Values FROM dico')
r lst2<-as.character(lst[,1])
```

Now I am like ok I have the "VALUE1" is now in a R list called "lst2". Let's not even try to do a loop directly but try replacing the typing of "VALUE1" by the value of first element of R list lst2. 

I tried the echo function but when put as such: 
```
r cat(lst2[1])
type //*[@class="promptTextField textFieldHelper"][1] as echo r_result [enter] 
```
but it is typing the 'echo r_result [enter]' instead of the value

I also tried the variable assignment as such: 

```
r cat(lst2[1])
product=r_result
type //*[@class="promptTextField textFieldHelper"][1] as product [enter] 
```
but again it is typing product and not its value. 

Is there a tagui function extracting the value of a variable? Or do you know of straightforward of using values extracted from R within the tagui code? 

Thanks for your attention, 

Lionel

**Comment by kensoh** [comment]
Hi Lionel, the syntax for denoting variables where text is expected in TagUI is the backticks, for eg `r_result`. It's covered in samples and documentation but is easy to miss because a lot of info.

What you are looking for is something like below, if you are using R -
```
type //*[@class="promptTextField textFieldHelper"][1] as r_result` [enter] 
```

However, the recommended way to do batch automation with different rows of data is using the built-in feature called datatables. See below section, with this feature, you can provide a CSV file as input.

https://github.com/kelaberetiv/TagUI#datatables

In your example above, because it requires login, you would want to do the login only on the first iteration -

```
if `[iteration]` equals to 1
{
// login sequence of steps
}

// set URL of the starting state for subsequent iterations
// some URL
```

Also, you will want to run TagUI with `speed chrome` option, so that it does not restart the browser every time, and the logged in state would be preserved.

**Comment by Lion666** [comment]
Database works like a charm! Very elegant...
