### ISSUE TITLE
How to get the HTML source code with Java and CSS rendered

### ISSUE THREAD

**Issue by alakaiobito** [kelaberetiv/TagUI#585]
Hi Ken,

I would like to know how I can get the entire HTML source (Java and CSS rendered) while executing TagUI using Python library.

Thanks in advance.

Kind regards,
Alakai

**Comment by kensoh** [comment]
Hi Alakai,

TagUI for Python is a separate project that I maintain in my personal time, raise issues there instead so that the question can benefit other users using the Python package.

I've posted the solution there - https://github.com/tebelorg/TagUI-Python/issues/65

PS - for users using this original TagUI project, the syntax is

```
read page to page_html
```
