### ISSUE TITLE
Visual automation, Java JDK >= v8 (64-bit) - use Amazon Corretto OpenJDK

### ISSUE THREAD

**Issue by saketlopes** [kelaberetiv/TagUI#589]
Hello Kensoh,

About  Java JDK, Oracle announced that starting January 1st of 2019, changes to Java licensing and support would go into effect, which would require paying substantial licensing fees for software.

Due to this we are looking for other options . 

Can TAGUI run on other option like Amazon Corretto?

Thanks & Regards
Saket Lopes

**Comment by kensoh** [comment]
Hi @saketlopes thanks for telling me, can you share with me the official announcement or link that best describes this change?

TagUI uses SikuliX for its visual automation engine, covering functions such as computer vision to interact with UI elements, OCR, keyboard and mouse automation. SikuliX is built to run on Java.

http://sikulix.com/quickstart/

>Beginning with version 11, there will not be functional differences between Oracle JDK and OpenJDK anymore. I will use the OpenJDK from now on, since it has an Open Source license.

From SikuliX official documentation above, it looks like it is already supporting OpenJDK, an open-source version of Java JDK. Can you try if OpenJDK works for you in place of Oracle's Java?

**Comment by saketlopes** [comment]
Hello Ken

Thanks for sharing link on OPEN JDK.
I uninstall JAVA and install  Amazon Corretto 8. Check below link.
https://d3pxv6yz143wms.cloudfront.net/8.232.09.1/amazon-corretto-8.232.09.1-windows-x64.msi
 
![image](https://user-images.githubusercontent.com/54308957/67177299-97229180-f3eb-11e9-8455-debebccd03d4.png)

Then tried Sikuli command with below example , it is working. Do I have to test any other tagui functionality , with open JDK ?  

example.
vision type('m', Key.WIN)
wait 1
click outlook-icon.png

About JAVA licence information ,check below link 
https://upperedge.com/oracle/using-java-heres-how-oracles-new-2019-java-se-licensing-affects-you/

Regards
Saket Lopes

**Comment by kensoh** [comment]
Oh great, thanks Saket!

Above test is sufficient. Amazon Corretto is a distribution of OpenJDK, since it works you can continue to use it instead of installing OpenJDK, which is officially supported by SikuliX.

I'm not familiar enough with both tools to recommend which one users should use going forward, though I'll prefer a vendor-agnostic version (OpenJDK) versus Amazon Corretto.

**Comment by kensoh** [comment]
Have updated readme and tutorial to point Java JDK v8 (64-bit) or later to [Amazon Corretto OpenJDK website](https://aws.amazon.com/corretto/). Have tried the plain vanilla OpenJDK. I don't think the ease of setup meets the needs of most TagUI users. Thus opting for Amazon Corretto's distribution of OpenJDK.

The driver for this change is Oracle now requires Java JDK to be paid for commercial use, only for private and non-commercial use it is free. Amazon Corretto is a distribution of OpenJDK which can be used without restrictions and available on Windows, macOS, Linux.

**Comment by kensoh** [comment]
Added a further commit to change reference to Java JDK to OpenJDK, firstly to avoid confusion for users, and secondly, it is better to err on side of caution and advise users to use Amazon Corretto distribution of OpenJDK, instead of pointing to Oracle's Java JDK. Otherwise, if users are using for commercial purpose, they would be flouting Oracle's usage restriction guidelines.

**Comment by kensoh** [comment]
Thanks Saket for highlighting this important info to me! No other users have mentioned this before.
