### ISSUE TITLE
Query regarding TAGUI, why write and execute instead of record

### ISSUE THREAD

**Issue by alakaiobito** [kelaberetiv/TagUI#595]
Hi Ken, 

Is there a provision for record and execute in TagUI?
Why have you chosen to "Write and Execute" when record and replay tools are there.
Also where do you think TAGUI will work better?

Kind regards,
Alex

**Comment by kensoh** [comment]
Hi Alex,

There is a Chrome extension recorder https://chrome.google.com/webstore/detail/tagui-web-automation/egdllmehgfgjebhlkjmcnhiocfcidnjk but I prefer to write automation script myself instead of using recorder.

I develop TagUI for the goal of making it easiest to develop, deploy and maintain. For myself, I find it easiest to write the script and make it work the first time (try using the `live` step to develop your script interactively). Using recorders will waste a lot of time trying to fix mistakes and non-ideal element identifiers decided by the recorder.

Since I developed the tool for me to use myself, I'll of course develop it in the way that makes sense for me which I think is the fastest way to develop and maintain automation scripts.

**Comment by kensoh** [comment]
Adding on, Blue Prism, one of the earliest commercial RPA software and the only publicly listed one, shares this view and also do not have a recorder. For strengths and weaknesses, check below link and click to expand to show comparison between this tool and commercial RPA tools.

https://github.com/kelaberetiv/TagUI#why-this

**Comment by kensoh** [comment]
Lastly, for a new personal project that I created a few months back, a Python package base on TagUI, I don't think there is anything open-source and free that is comparable to it that can do what it do.

https://github.com/tebelorg/TagUI-Python/
