### ISSUE TITLE
Unable to run tagUI on MacOS - csv bug after macOS Catalina upgrade - fixed

### ISSUE THREAD

**Issue by jerrymannel** [kelaberetiv/TagUI#597]
OS: **macOS Catalina**
Nodejs: **v10.13.0**
Python: **2.7.16**
Java: **1.8.0_172**

I tried running the samples by, _unzip and run_ and _npm install_, both cases i get the following error.

```
Warning: count(): Parameter must be an array or an object that implements Countable in /Users/jerry/workspace/rpa/tagui/src/tagui_parse.php on line 31
Warning: count(): Parameter must be an array or an object that implements Countable in /Users/jerry/workspace/rpa/tagui/src/tagui_parse.php on line 32
Warning: count(): Parameter must be an array or an object that implements Countable in /Users/jerry/workspace/rpa/tagui/src/tagui_parse.php on line 34
ERROR - automation aborted due to above
```

**Comment by kool601** [comment]
I'm having the same issue on Catalina. Hopefully there's a fix.

**Comment by JackyChuang74** [comment]
same here. encountering error with the file tagui_parse.php (line 31, 32, 34).
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /Users/jacky/tagui/src/tagui_parse.php on line 31
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /Users/jacky/tagui/src/tagui_parse.php on line 32

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/jacky/tagui/src/tagui_parse.php on line 31

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/jacky/tagui/src/tagui_parse.php on line 32
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /Users/jacky/tagui/src/tagui_parse.php on line 34

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/jacky/tagui/src/tagui_parse.php on line 34
ERROR - automation aborted due to above

I was just trying out with my own test script of just one line to go to "http://www.google.com".

Running on:
OS Catalina
Server version: Apache/2.4.41 (Unix) with PHP 7.3

**Comment by JackyChuang74** [comment]
ok guys, after doing some research, I realised that the above error is due to PHP7.3 (or rather from v7.2 onwards).

So my work around is to install another older version (7.1 in my case) and it is now working fine.

------
$ ./tagui samples/1_yahoo

START - automation started - Fri Oct 25 2019 10:40:38 GMT+0800 (+08)
https://ca.yahoo.com - Yahoo

NOTE - this sample may not work for EU users due to website changes for GDPR
EU users may have to modify script to first click on announcement OK button

type search-box as github
show search-box
github
click search-button
wait 6.6
snap page
snap logo
snap page to results.png
snap logo to logo.png
https://duckduckgo.com - DuckDuckGo — Privacy, simplified.
type search_form_input_homepage as The search engine that doesn't track you.
snap page to duckduckgo.png
wait 4.4 seconds

https://duckduckgo.com/ - DuckDuckGo — Privacy, simplified.
FINISH - automation finished - 22.7s
----------------------------

you can refer to this link on how to do multiple php version in Catalina.
https://getgrav.org/blog/macos-catalina-apache-multiple-php-versions

**Comment by kensoh** [comment]
Thanks for raising this! I can replicate, and confirm that this issue happens after macOS applies the update to a new release to Catalina.

Thanks @JackyChuang74! Let me see if I can change something to fix this, so users do not need to do their own installation to use TagUI.

```
Tebel:samples kensoh$ tagui 1_yahoo chrome

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/kensoh/Cloud Drive/Marketing/Website/api/tagui/src/tagui_parse.php on line 37

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/kensoh/Cloud Drive/Marketing/Website/api/tagui/src/tagui_parse.php on line 38

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/kensoh/Cloud Drive/Marketing/Website/api/tagui/src/tagui_parse.php on line 40
ERROR - automation aborted due to above
```

**Comment by kensoh** [comment]
In the interim, remove tagui_local.csv from the samples folder when you are running the samples and the error should disappear.

The issue is with a backward-incompatible change in the PHP count() function, which comes with the upgraded PHP v7.3 in macOS Catalina.

**Comment by jerrymannel** [comment]
+1 
I tested by removing `tagui_local.csv` and it is working.

**Comment by kensoh** [comment]
Fix implemented in TagUI cutting edge release (v5.9). To use it, follow the steps in setup section for overwriting existing packaged installation with the cutting edge release codebase -

https://github.com/kelaberetiv/TagUI#set-up

**Comment by kensoh** [comment]
This issue impacts Windows users as well, updated issue title so that it's easier to search by users. The solution is using the fix implemented in TagUI cutting edge version. To use it, follow the steps in setup section for overwriting existing packaged installation with the cutting edge release codebase -

https://github.com/kelaberetiv/TagUI#set-up

This fix will be an upcoming packaged release later this month. And in a future planned v7, PHP issues would be removed permanently as the execution engine switches purely to NodeJS. Copying @siowyisheng fyi too!

**Comment by kensoh** [comment]
Implemented today in packaged release with @siowyisheng - fresh downloads of the packaged installations should not have this problem anymore! https://github.com/kelaberetiv/TagUI#set-up
