### ISSUE TITLE
Is there any sample to deal with Google spreadsheet? - use API or visual

### ISSUE THREAD

**Issue by tan-z-tan** [kelaberetiv/TagUI#599]
I'm trying to create a TagUi script that helps my daily routines.
The task is
- First, login to my Google account.
- Open a spreadsheet (URL is fixed. Only login user can see).
- Append a row (e.g. 2019-10-25)

Is there any sample script?

**Comment by kensoh** [comment]
Hi @tan-z-tan there isn't any sample script for that. I tried taking a look, it appears that the cells are rendered in a canvas, which is not accessible through using web element identifiers such as XPath or CSS or HTML attributes (correct me if you manage to locate using XPath).

So that remains 3 ways to do that.

1. First is programmatically using API calls to Sheets API with api step -
Google Sheets API - https://developers.google.com/sheets/api
TagUI `api` step guide - https://github.com/kelaberetiv/TagUI#api

2. Second is programmatically using the Google Python package -
https://developers.google.com/sheets/api/quickstart/python
and use TagUI Python integration - https://github.com/kelaberetiv/TagUI#python-integration
or use TagUI for Python tool - https://github.com/tebelorg/TagUI-Python
or use vanilla Python (this should work if workflow only involves Google Sheets)

3. Third is the easiest way to get start in my opinion, using visual automation and replication of keyboard combinations and keystrokes to do that. For eg using `click` step visually the image of the column header A, then using `keyboard` step to move to the correct cell to update. However, this method requires the automation to be done visibly on the computer, unlike method 1 and 2 which can be done 'headlessly' without seeing web browser at all. More details here -
https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by tan-z-tan** [comment]
Thank you @kensoh for quick reply 😄

The third way you mentioned above would be cool but it requires image recognition to edit cells at arbitrary positions.
I'll try using Google Sheets API.

**Comment by kensoh** [comment]
You're welcome 😄  What you said is correct. API is always the best method if a user is familiar with programming and API is available to interface with an application. Going through UI is too much overheads and has a higher risk of running into exception issues versus API.
