### ISSUE TITLE
Visual automation image is not recognized - pending checks and replication

### ISSUE THREAD

**Issue by saketlopes** [kelaberetiv/TagUI#603]
Hello ken,

I am doing  TAGUI setup on windows server has OS windows server 2012 R2.
While testing visual automation I used following script.

vision type('m',Key.WIN)
wait 1
vision click('img/icon-google.png')

It ran successfully but image was not recognized.
When I ran with C:\tagui\src\tagui.sikuli\runsikulix same image is working.

Regards
Saket Lopes

**Comment by kensoh** [comment]
Hi Saket,

For visual automation, there is no need to use `vision` step, because you can do click `img/icon-google.png` directly. `vision` step is for situations when you want to do something special that existing TagUI commands cannot, so you want to send custom SikuliX code to do it.

More details on visual automation usage -https://github.com/kelaberetiv/TagUI#visual-automation

For above error, it should be because when you run vision step, the active directory is inside tagui\src\tagui.sikuli folder and not the folder where the script is. So SikuliX cannot find the file.

**Comment by kensoh** [comment]
Use the latest cutting edge version (see here for setup details - https://github.com/kelaberetiv/TagUI#set-up)

Then try below code. Put image in same folder as script.

```
keyboard [win]m
wait 1
click icon-google.png
```

If you still run into error, check in tagui\src\tagui.sikuli folder. There is a log file of what happens when the click image action is done. Check to see if the log contains some clues on what's wrong with clicking.

**Comment by kensoh** [comment]
Hi Saket, it looks like the SikuliX engine is unable to check if the image you provided exists. The only idea I can think of is try putting your c:\tagui folder on your desktop to see if it helps. It might be some companies IT policies having issues with TagUI writing data to c:\tagui folder.

Other than this suggestion, you can try running on your friend's laptop or your personal laptop instead of office laptop to see if that works. Once you find another laptop that works, try to compare and check what is the different in the environment and setup that cause the problem.

I'm afraid no other users have encounter this problem and I can't replicate this issue to assist further from my side.

**Comment by saketlopes** [comment]
Hello kensoh

Thanks for your help & suggestion.

I have TAGUI installed on my laptop running on windows 10 OS. I created few automations with TAGUI on my laptop now I want to deploy them on server machine. 

On server machine I have OS windows server 2012 R2. To setup TAGUI I downloaded zip from website https://github.com/kelaberetiv/TagUI#set-up and installed on C:\tagui folder. For JAVA I am using Amazon Corretto 8. Check below link.
https://d3pxv6yz143wms.cloudfront.net/8.232.09.1/amazon-corretto-8.232.09.1-windows-x64.msi

 I followed same steps which I have done on laptop. but on server TAGUI visual automation is not working.

Then on server machine I done sikulix setup, ran command file runsikulix.cmd which is running successfully. 

Do you feel I have to check any other options?  Any possibilities to debug code?

I found some difference in my laptop & server machine is that, on laptop visual automation running without sikulix setup.
  
 
Regards
Saket Lopes

**Comment by saketlopes** [comment]
Hello Kensoh

Issue resolved ,  Problem with **C:\tagui\src\sikulix\sikulix.jar** , I replace this file with C:\tagui\src\tagui.sikuli\sikulix.jar ( this file created from sikulix setup https://www.rpa-sg.org/TagUI/setting-up-sikuli-to-work-with-tagui-on-windows.php)

My investigation as below:
While investigating I found when ever we run C:\tagui\src\tagui.sikuli\runsikulix.cmd  it creating files in folder C:\Users\sl49638\AppData\Roaming\Sikulix and it is referring  C:\tagui\src\tagui.sikuli\sikulix.jar.

When I deleted  folder C:\Users\sl49638\AppData\Roaming\Sikulix ,and ran tagui script  it was showing message as below
> Neither Jython nor JRuby available
> IDE not yet useable with JavaScript only
> Please consult the docs for a solution.

TagUI script is below:
keyboard [win]m
wait 1
click icon-google.png

After copying file, automation is working without error.

Thanks for your help.

Regards
Saket Lopes

**Comment by kensoh** [comment]
Thanks Saket for sharing your troubleshooting and fixing details!

TagUI is using SikuliX v1.1.4. What you did above is replace with v1.1.3. I don't have enough knowledge to explain why the older SikuliX version works on your server instead of the newer one. But I'm glad you found the solution. Have fun automating stuffs!

**Comment by shanyu-e** [comment]
> 

this can help in windows server 2012 r2

**Comment by iamB0rgy** [comment]
I am getting this error

Neither Jython nor JRuby available
IDE not yet useable with JavaScript only
Please consult the docs for a solution.

**Comment by kensoh** [comment]
TagUI comes with the Jython package, but it gets moved to another folder after run first. Check that you install TagUI and download from the home page, not copy and paste the entire folder from a PC with existing TagUI installed.

**Comment by kensoh** [comment]
Tagging @iamB0rgy on above reply
