### ISSUE TITLE
Incorrect python code crash problem - fixed in cutting edge release

### ISSUE THREAD

**Issue by muratcim** [kelaberetiv/TagUI#606]
Hi Ken

Application be locked when there is an error in a Python block.

```
py begin
a= 4/0
py finish

```
Is there a method of terminating when an error is thrown with a python block?

I'm applying a method like this for

```
py begin
import traceback
try:
    print(4/0)
except Exception:
    print('PYTHON ERROR ' + traceback.format_exc())
py finish


if ( py_result.indexOf('ERROR') !=  -1 )
{
  js begin
  	throw new Error(py_result)
  js finish
  
}

echo 'anything'
```

**Comment by kensoh** [comment]
Hi Murat, I'm afraid not. The assumption is valid Python code is sent to the Python integration.

If you really want to explore this, you can try modifying `tagui\src\tagui_py\tagui_py.py` file. Inside there is this line `exec(params,globals())` which executed the Python instruction sent from TagUI. You can try modifying to catch exception and return some error message.

**Comment by muratcim** [comment]
Thank you Ken
I'll examine and try to find a solution.Closing issue
when i find a solution i will be sharing here

**Comment by kensoh** [comment]
Ok Murat, I will also see if there is something that can be changed in below file which can be committed to the codebase without affecting backward compatibility - `tagui\src\tagui_py\tagui_py.py`

**Comment by kensoh** [comment]
Going to make a commit that works with Python 2 and 3, and also the following test -

```
py begin
a = 1
b = 2
print(a+b)
py finish
echo py_result

py begin
a = 1
b = 2
print(ava+b)
py finish
echo py_result
```

**Comment by kensoh** [comment]
This is now available in the cutting edge release. With above commit, when invalid Python code is called by user, TagUI continues operation and the error message is stored in py_result. Before this change, TagUI hangs as the Python process does not return response. Works for Python 2 & 3 and the test case above. Thanks Murat for raising this feedback!

---

https://github.com/kelaberetiv/TagUI#set-up

To try [cutting edge version](https://github.com/kelaberetiv/TagUI/compare/v5.0.0...master) with the latest features, [download master.zip](https://github.com/kelaberetiv/TagUI/archive/master.zip) to overwrite your existing packaged installation (be sure to manually select and move the folders & files inside master.zip's TagUI-master/src folder to replace your existing tagui/src folder, some OSes will delete existing target folders that are missing from source folder)

**Comment by kensoh** [comment]
Adding a further commit so that when error happens running the Python code from user, there is an 'ERROR - ' in front of the error message. Without this, py_result is ambiguous.

This is both for consistency in TagUI error messages and also for user to be able to validate without ambiguity whether the response returned is due to error running the code. 

Thus running `py a = 4/0` will return py_result as `ERROR - integer division or modulo by zero`

---

Available in cutting edge version - https://github.com/kelaberetiv/TagUI#set-up

To try [cutting edge version](https://github.com/kelaberetiv/TagUI/compare/v5.0.0...master) with the latest features, [download master.zip](https://github.com/kelaberetiv/TagUI/archive/master.zip) to overwrite your existing packaged installation (be sure to manually select and move the folders & files inside master.zip's TagUI-master/src folder to replace your existing tagui/src folder, some OSes will delete existing target folders that are missing from source folder)
