### ISSUE TITLE
Wait 60 seconds hangs script - run with chrome or headless option

### ISSUE THREAD

**Issue by idiogolima** [kelaberetiv/TagUI#615]
Tried:

https://www.energisa.com.br/
wait 4 seconds
select ddlEstado as TO
wait 3 seconds
select ddlCidade as 8;91

click //a[@id="lnkEnviar"]
snap page to energisa1.png
wait 60 seconds
snap page to energisa2.png

snap energisa1.png works.
snap energisa2.png never works, stop in wait 60 seconds

**Comment by idiogolima** [comment]
![stop](https://user-images.githubusercontent.com/11023107/68242196-de657080-ffee-11e9-8712-6b5a51e877f6.PNG)

**Comment by kensoh** [comment]
Hi @idiogolima, when I run with `tagui script_name chrome` (Chrome visible mode), it runs successfully and after 60 seconds the webpage screenshot is saved to energisa2.png. When I run with `tagui script_name headless` (Chrome invisible mode), it runs successfully and after 60 seconds the webpage screenshot is saved to energisa2.png.

However, when I run with `tagui script_name` (default PhantomJS mode), it runs successfully sometimes but sometime it hangs there. When I try with `tagui script_name debug` I get the following. It looks like sometimes the website will invoke Google Recaptcha when run in PhantomJS mode and hangs the automation. I think its because the website recognise that you are using automated browser and tries to block access -

>[debug] [phantom] Navigation requested: url=https://www.google.com/recaptcha/api2/anchor?ar=1&k=6Ld6qKoUAAAAAEPM3AoxrglDi4HsoNdIax9REygE&co=aHR0cHM6Ly93d3cuZW5lcmdpc2EuY29tLmJyOjQ0Mw..&hl=en&v=66WEle60vY1w2WveBS-1ZMFs&size=invisible&cb=pb82zbf3chk2, type=Other, willNavigate=true, isMainFrame=false

The solution is to run with headless option if you really need the automation to be invisible, or run with chrome option. If all else fails, writing the automation to make use of visual automation will be the failsafe method, as it mimics user actual mouse movements and keyboard entries to lower the chance of being detected as automated browsing. More details here -

https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by idiogolima** [comment]
Thanks!

I liked visual mode!
I tried the example: https://github.com/kelaberetiv/TagUI/issues/113

click outlook-icon.png
click new-email.png
enter mail-body.png as Hi Whoever,\n\nAttached are the M1 numbers.\n\nRegards,\nKen
enter subject-field.png as M1 Lucky Numbers
enter to-field.png as ksoh@aisingapore.org
click attach-button.png
click numbers-icon.png
click choose-button.png
click send-button.png


tried image:
![visual](https://user-images.githubusercontent.com/11023107/68316316-03fa8480-0098-11ea-9a44-eef10b91ce47.PNG)

am i doing something wrong?

**Comment by kensoh** [comment]
For visual automation mode, first check if the pre-requisites are there -
https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by kensoh** [comment]
Closing issue for now until further inputs!

**Comment by WhyNotPal** [comment]
Hey Ken, 
Thanks for developing TagUI. 
May I ask, for me the script here above does not work in headless mode. Chrome mode runs fine, but headless mode stops at the first select. 

My machine runs Ubuntu18.04, Tagui 6.0.0, Chrome 85.0.4183.83 (Official Build) (64-bit)

For me, the ability to run such scripts in headless mode would be essential. Could you point me to some ideas as to why it doesn't seem to work? thanks a lot

**Comment by kensoh** [comment]
Sorry @WhyNotPal I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

If you are referring to running the script above that uses image snapshots, then it can't work in headless mode - https://github.com/kelaberetiv/TagUI/issues/615#issuecomment-550385799

This is because visual automation uses computer vision to interact with UI elements and in headless mode for Chrome, there is no window for the computer vision to interact. Also, for Linux, you'll need to install OpenCV and Tesseract manually using the steps here - https://sikulix-2014.readthedocs.io/en/latest/newslinux.html

**Comment by kensoh** [comment]
If you are referring to normal automation without using visual automation, you can check the Chrome log in tagui/src/tagui_chrome.log to see what error messages are showing up, besides any error message that shows up during running the script.
