### ISSUE TITLE
Running TagUI in Git Bash in Windows fails

### ISSUE THREAD

**Issue by siowyisheng** [kelaberetiv/TagUI#623]
Various errors occur as Git Bash runs as if it's in linux but it's actually on windows. 

So TagUI should not be used in Git Bash on windows.

Maybe the error msg could highlight this possibility.

**Comment by siowyisheng** [comment]
But how we would tell that they are running on git bash on windows? For me, I errored here:
```
chrome_command="google-chrome"
if ! type "$chrome_command" > /dev/null; then
  echo "ERROR - cannot find Chrome command \"$chrome_command\""
  echo "update chrome_command setting in tagui/src/tagui and make sure symlink to command is created"; exit 1; fi
```

Does it make sense to warn them about the possibility of them using git bash on windows here? or is there a better way to check and error out?

**Comment by kensoh** [comment]
Yes this is the expected behaviour by design. For Windows users, run TagUI directly from the command prompt or power shell. Git Bash is not a real Linux environment, it is only a bash shell running in Windows. Thus running TagUI in it will not work.

For now it's sufficient that they search issues and see this issue for solution. Also, from the to use section and the tutorial, there is explicit step to open command prompt. So users who using alternative environments if they follow the steps there they'll be fine.
https://github.com/kelaberetiv/TagUI#to-use

There should be technically possible solution, but not recommend to handle via error handling, because will be opening up a can of worms. To handle this error means we should also handle the situation where Windows users trying to run other Linux shells or VMs on Windows, which may not work as expected.

But it is hard to try to address all those cases. As TagUI already tries to make any new feature or change work for macOS, Linux and Windows, further addressing the sub-cases would make the project much harder to maintain at the gain of making it easier for the minority of users who happen to be using alternative shell in Windows and also never follow the step by step guide in To Use and Tutorial section.

**Comment by kensoh** [comment]
Eg maintaining software across multiple OSes is so challenging that even for unicorn commercial RPA software, they are only supporting Windows OS. None of them has releases for macOS / Linux.

**Comment by kensoh** [comment]
But cross-platform solutions such as Electron, NodeJS, Python etc, is changing this old paradigm, and make it more accessible to develop cross-platform apps that work with minimal localisation.
