### ISSUE TITLE
Accessing UI elements on log-in page - pending checks & replication

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#625]
user query

---

Recently i started to use TagUI. I am playing around writing hello world programs.

One difficulty i am facing is i am unable to access the log in page(also the elements). Later i found out that the page is a Windows Authentication Page coming from the server through HTTP request. Because  this is a secured page i am thinking i am unable to access this.

Question is using Sikuli can i access the log-in pop up and enter the user name, pwd and click login ?

I tried to in the internet no sample code or direction, hence reaching out to you to see if this is possible in using Sikuli?
 
Alternatively iprovide the username and pwd as a parameter to the url (https://username:pwd@url) which should work but it is not working as i am trying to access the elements as given below it says unable to find element.

```
https://username:pwd@url  
wait 4
name = "test\emp-temp"
pwd = "pwd"
enter //input[@Name="Username"] as `name`
enter //input[@Name="Password"] as `pwd`
```

**Comment by kensoh** [comment]
Some ideas to try is using live step to test whether the element identifier you are interacting with is correct, verifying if in Chrome inspector that XPath works, and checking in Chrome inspector if the elements are inside a web frame. If web frame, the steps need to be enclosed within a frame step and brackets. SikuliX visual automation can also be used.

However, if you mean a popup message box asking for login, then TagUI can't work with that using web element identifiers. Because Chrome does not return control to TagUI until after user keys in the login information.

The only way if you are using TagUI is use visual automation entirely to start Chrome, type in the address and login and every step, using visual automation. In that way, TagUI does not require Chrome to return control to it before running the next step. Eg here - https://github.com/kelaberetiv/TagUI/issues/491

**Comment by Yaazh-Inidhu** [comment]
Hello, Kensoh -

Thank you !

The main issue i was facing with the Log-In page (windows authentication), as mentioned by you "**Because Chrome does not return control to TagUI until after user keys in the login information**"

So i tried the SikuliX visual automation approach, for some reason the image that i am capturing with snipping tool is not getting recognized for the username, pwd and the login button. Not sure as what the specific issue is.

Alternatively i tried the approach you had mentioned in the the example link and it worked.
Now i have a working solution. 
Still i need to figure out as why sikuli is not recognizing any of the png files that i capture using snipping tool in windows.

`keyboard [ctrl]a
keyboard [delete]
keyboard https://website.com[enter]

username = "test\\lala"
pwd = "halwaWala"
type (507,161) as `username`
type (512,204) as `pwd`
click (737,262)
`

**Comment by kensoh** [comment]
You're welcome! Try changing your Windows display zoom % to 100% or the recommended % to see if that works. Sometimes the zoom % is not at the level which the SikuliX visual automation engine recognises, so it cant find the matching images on the screen.

**Comment by Yaazh-Inidhu** [comment]
Was struggling for sometime as the **png files were not getting recognized**, the moment i changed from Snipping Tool to sikulix-2.0.0(Take Screenshot) to capture the images, it started to work fine immediately.
Something new i learned today.

**Comment by kensoh** [comment]
Oh great! Thanks for sharing the solution that works for you here. There is a similar issue for one of the Windows users. Somehow the snipping tool by Windows capture screenshots that did not accurately reflect what is shown on the screen and did not work with SikuliX computer vision engine.
