### ISSUE TITLE
Can tagui support the use of two-dimensional array arrangements?

### ISSUE THREAD

**Issue by jcarriv** [kelaberetiv/TagUI#629]
I need to be able to sort a table using a two-dimensional array, but I have not seen that the use of these structures is supported by Tagui, any suggestions?

//loading test.csv to datatable
echo 'start test.csv to table'
load test.csv to datatable
table2 = datatable.split('\n')
echo 'Processing table on a cell level

	array_test = [][]
//loading table2 into array array_test
	for n from 0 to table2.length-1
	{
		row = table2[n].split(',')
		for m from 0 to row.length-1
		{
			array_test[n][m] = row[m].trim()
		}
	}			
//pivot to sort: array_test[n][34]
	n = table2.length
	i = 1
	ordenado = 0
	while ((i < n) && (ordenado == 0))
	{
		i = i + 1
		ordenado = 1
		for j from 0 to n-1
		{
			if (array_test[j][34] > array_test[j+1][34])
			{
				ordenado = 0
				aux = array_test[j][34]
				array_test[j][34] = array_test[j+1][34]
				array_test[j+1][34] = aux
			}
		}
	}
	
	for n from 0 to table2.length-1
	{
		for m from 0 to row.length-1
		{
			echo '[' + `n` + ',' + `m` + ']=' + array_test[n][m] 
		}
	}

**Comment by kensoh** [comment]
Hi @jcarriv if you mean if TagUI can work with 2-dimensional arrays, yes. The underlying programming language is JavaScript, so that is doable. For sorting that is also doable, but you'll have to figure out the JS code needed to do the sorting according to your requirements.

If you are familiar with Python, you may consider using a Python package I created recently that's base on TagUI. The numerous libraries such as numpy or pandas makes it very easy to work with data. Link to the Python package - https://github.com/tebelorg/TagUI-Python

**Comment by jcarriv** [comment]
I appreciate your quick response, I will try to add a while loop inside the reading of the first array loop.

**Comment by kensoh** [comment]
Welcome @jcarriv replied you in your new issue on while loop - https://github.com/kelaberetiv/TagUI/issues/630
