### ISSUE TITLE
How to select monitor in multi-monitor environment? - use vision step

### ISSUE THREAD

**Issue by lchojnowski** [kelaberetiv/TagUI#631]
If there is a many monitors, it simply fails and never founds an element.

**Comment by kensoh** [comment]
This is not supported as SikuliX can't set this via a configuration setting. Thus to support such a feature requires rewrite of the TagUI-SikuliX integration. Workaround would be setting up workstation to use a single display, or use `vision` step to run SikuliX commands directly. 

More details at SikuliX documentation. First define the screen to be used, then use that screen variable for every action function. This may not be straightforward unless someone is already familiar with SikuliX. Copying @siowyisheng fyi.

https://sikulix-2014.readthedocs.io/en/latest/screen.html#multi-monitor-environments

**Comment by kensoh** [comment]
Closing issue for now because SikuliX can't easily support this by changing a flag or config, will require rewrite of the TagUI-SikuliX integration engine. Can keep this in view for time being until there is substantial interest from users for such use cases.

Rewriting takes effort but it is only part of the challenge, the other part is it is not easy to ensure 100% backward compatibility from existing users' scripts if the integration engine is re-written.
