### ISSUE TITLE
How to load child TagUI file dynamically - try using variables instead

### ISSUE THREAD

**Issue by Yaazh-Inidhu** [kelaberetiv/TagUI#633]
Hello, All 

I have encountered an interesting situation where i need to load the child tagui file dynamically
(**_like lazy loading_**).
Would like to know if this is possible?
I have three files as given below, one.txt, two.txt and and empty three.txt.
The content in three.txt is dynamically written and saved. 

_But when i run the three.txt does nothing_(since it was initially empty). **How to overcome this?**

**one.txt**
```
https://www.google.com/
tagui two.txt
tagui three.txt
```

**two.txt**
```
keyboard [win]s
vision type('cmd')
keyboard [enter]
vision type('cd C:\sample\temp.exe')
```

**three.txt**
``

In three.txt there is no code initially, two.txt while processing writes the below lines to three.txt at run time() and saves. Once can notice a windows exe does this in this case.

https://www.bookdepository.com/
read //div[@class="block-wrap  "][1]//h2 to booklist
echo "booklist = " + booklist

Now the file has the below content after two.txt runs
**three.txt**
```
https://www.bookdepository.com/
read //div[@class="block-wrap  "][1]//h2 to booklist
echo "booklist = " + booklist
```

**Comment by kensoh** [comment]
Hi @Yaazh-Inidhu I'm afraid that the `tagui` step can only load a TagUI script that already exists at the time when the parent script is executed. This is because each sub-script is 'compiled' before the whole script runs. Trying to call a script that is empty but only has contents halfway through is not supported. Following is another issue with a similar setup - https://github.com/kelaberetiv/TagUI/issues/467

Can you tell me more what is the variable content in three.txt? For certain use cases, it might be possible to set a variable in one.txt and two.txt so that in three.txt it is usable. For eg, below is three.txt which will access the \`some_variable\` value that can be generated in one.txt or two.txt.

The benefit of `tagui` step is variables defined in the parent script or other sub-scripts can be usable and accessible to each other.

```
https://www.bookdepository.com/
read //div[@class="block-wrap  "][`some_variable`]//h2 to booklist
echo "booklist = " + booklist
```

**Comment by Yaazh-Inidhu** [comment]
Hello, Ken Soh 

Thank you for the suggestion. Using variable and capturing it in step 2 is a good idea.
This could be applied for certain usecase i have, which is good.

For the rest of the use case the three.txt would be receiving dynamic statements of type, write and click. Say we point to a website and read these statements. The catch is the owner of the website can change the statements (add/modify/delete statements) which causes the dynamic nature.

I am thinking of using a headless version to read the content and save it, followed by calling the TagUIi one.txt in command prompt in the same TagUIi script (not too sure, but i remember receiving error saying already another process is running, not sure if its ok and safe to take this approach).  

Also i might explore on the batch workaround after the headless version runs.
Will post my results soon.

Again good ideas, thank you !

**Comment by kensoh** [comment]
I see, that might work. You can try putting the different scripts together using a Windows batch file or macOS / Linux bash script. In that way, script3 will be running using the correct dynamic steps. For eg below, a Windows batch file. In one.txt you can put the steps you want to do to generate three.txt contents.

```
@echo off
tagui one.txt
tagui two.txt
tagui three.txt
```

**Comment by Yaazh-Inidhu** [comment]
Perfect the above code works very well.

Once catch here : once the one.txt file executes, it opens a separate command prompt, executes the script and then stays in the same child command prompt until we type exit or close the window manually. The bat file is expecting the child command window to close so that the two.txt can start executing.

Is there a way we can close the the child command window once one.txt completes ?

**Comment by kensoh** [comment]
This seems like an issue with your Windows environment, though I don't have a Windows computer to test. Normal batch file execution after a command is executed it will exit automatically to continue with the next command. Some things you can try to figure out what is wrong -

1. check if you are running a normal command prompt instead of some special shell
2. try running below with some other commands to see if the problem happens -
```
@echo off
some command 1
some command 2
some command 3
```
3. Try running on your personal laptop or another work laptop to see if the same happens

**Comment by Yaazh-Inidhu** [comment]
Finally in windows below approach worked out....


```
@echo off
rem This is a test
set root=C:\test
pushd %root%
CALL tagui one.txt chrome
CALL tagui two.txt
CALL tagui three.txt chrome
```



Good to close. Thank You KenSoh !

**Comment by kensoh** [comment]
Thanks for sharing your solution! Adding on below reference, it looks like for control to be returned if a batch file is called, the call command must be used. TagUI on Windows is invoked through a batch file src\tagui.cmd, thus the call command must be used.

https://stackoverflow.com/questions/14731877/to-call-or-not-to-call-a-batch-file
