### ISSUE TITLE
unable to read element text if the text contains double quotes - test "

### ISSUE THREAD

**Issue by Yaazh-Inidhu** [kelaberetiv/TagUI#638]
Hello, All :

Wondering if anyone has encountered this issue, unable to read element text if the text contains double quotes :
wanted to read text under a div tag an it has a p tag like : div/p
And below is the actual text.

`<div><p>To proceed Please click on the box "Next" </p></div>`

Also what i noticed, for the elements which does not have double quotes, i am able to read the text.

Any idea as how to overcome this?

**Comment by kensoh** [comment]
Hi @Yaazh-Inidhu it seems like it could be your XPath or identifier used is incorrect, or some problem with the website. For example, I updated the issue title for this issue to have double quotes " (see above). Then I run below replication script -

```
https://github.com/kelaberetiv/TagUI/issues/638
show js-issue-title
```

And it shows the correct output with double quotes -

```
unable to read element text if the text contains double quotes - test "
```

Try running TagUI with the `live` step so that you can test which identifier works for the webpage.

**Comment by Yaazh-Inidhu** [comment]
Hello, KenSoh

Yes you are right, in the current page i am able to capture the double quotes with the below code.
I am thinking of some issue with the website i am trying. Since the same identifier is used in a loop in certain iteration it works, and in the other iterations which has these double quotes, it skips.

https://github.com/kelaberetiv/TagUI/issues/638
read //*[@id="issue-531729045"]/div/div[2]/task-lists/table/tbody/tr/td/p[3]/code to sometext
echo sometext

Alternatively i have made the web-site to have single quote instead of double and quote and now it starts to work.

good to close this query.
