### ISSUE TITLE
Use indentation instead of curly braces {} for if blocks and loops

### ISSUE THREAD

**Issue by siowyisheng** [kelaberetiv/TagUI#655]
so instead of:
```
for n from 1 to 5
{
    some instructions
    some more instructions
}
```

it would be:
```
for n from 1 to 5
    some instructions
    some more instructions

some instructions outside of the loop
```

ie. python-style indentation for blocks.

Benefits: 
1. business users don't need to use alien `{}` symbols.
2. fewer lines

**Comment by kensoh** [comment]
Actually I prefer this rather than {}. The benefits are clear, the cons are -

1. this is risky inconsistent style because TagUI's programming language is JavaScript. Users will be writing JavaScript code in TagUI scripts, which uses {}. To use a code block style from Python to bring into a JavaScript environment will be good for business users but may be super confusing for JavaScript users.

2. There are issues like calculating the tabs or spaces correctly, some editors will be 4 spaces or more while some are tabs. This has to be done accurately and robustly in order to work, otherwise {} is more 'deterministic' and unambiguous compared to indentation. Also, current design will trim empty spaces in front and back, need to make adjustments to handle that correctly if implementing this.

Though above cons are huge, but there are workarounds and careful engineering should be able to handle them. If the feature is designed such that users can use both {} or indentation then it'll be great. Otherwise it will mean breaking a lot of compatibility for many existing user scripts where {} is used. If upgrading TagUI may mean they have to rewrite their scripts to change style, I think it will be too unreliable for users to invest into writing scripts using TagUI.

If retaining backward compatibility it'll be ok. But will be technically more challenging to implement.

**Comment by kensoh** [comment]
Adding on, in situations where there is a major major gain for users in the long run and breaking backward compatibility of their scripts is required, and it requires them to update manually a lot of scripts, 1 way will be including some migration helper that can auto-convert old-styled scripts to the new style. That'll minimise user friction while still moving forward.

**Comment by siowyisheng** [comment]
> this is risky inconsistent style because TagUI's programming language is JavaScript. Users will be writing JavaScript code in TagUI scripts, which uses {}. To use a code block style from Python to bring into a JavaScript environment will be good for business users but may be super confusing for JavaScript users.
There are issues like calculating the tabs or spaces correctly, some editors will be 4 spaces or more while some are tabs. This has to be done accurately and robustly in order to work, otherwise {} is more 'deterministic' and unambiguous compared to indentation. Also, current design will trim empty spaces in front and back, need to make adjustments to handle that correctly if implementing this.

I have some ideas to implement with backward compatibility. Python actually allows an arbitrary number of spaces/tabs, but it just needs to be consistent. Will probably try to follow python rules.

**Comment by kensoh** [comment]
Yes if retain backward compatibility and gives user options to use {} or indentation this should be a win for users in terms of readability and ease of development. Only thing is may be confusing when writing JavaScript code and using space / tab as indentation.

**Comment by siowyisheng** [comment]
They can always use `js begin` if they really want to type javascript. We should push tagui language as much as possible imo.

**Comment by mbsryu** [comment]
Does this topic also entail some assumptions about the editor that the user is using? Some are good at making sense of syntactical rules (like closing the brackets) but not all.

**Comment by kensoh** [comment]
For first statement, js begin it won't work. Because the { and } is supposed to be parsed by TagUI into the matching CasperJS code block structures. So following should fail.

```js
js {
step 1..
step 2..
js }
```

The following will not work either, because the TagUI step 1 and step 2 will miss the parsing and not be converted from TagUI syntax into working JS code.

```js
js begin
step 1..
step 2..
js finish
```

For second statement, that is only true if TagUI is no longer dependent on JavaScript as its programming language - eg users wanting to perform some string manipulation on a variable. Otherwise, we will risk trying to come up with 'TagUI' versions of JavaScript functions and syntax and it can be very challenging while still not be able to fully get rid of JS.

---

For the editor, we should not make assumptions on the editor because we can't control that, but make the design work across different editors. In a future release, when TagUI has its own IDE then this problem will be mitigated because the editing and dev env is within TagUI's domain.

**Comment by kensoh** [comment]
(@siowyisheng I adjusted discussion label from e8 to e3 for the green component. the original green is a little too bring from the existing colour palette used for issues labels)

**Comment by kensoh** [comment]
(and for the newly added `needs more info`, I change from aaaaaa to c4c4c4 for readability. the grey is too dark to read the black text easily)

**Comment by kensoh** [comment]
Adding on, assuming that there's function that can read a text file line by line, and able to return at which block level that line is. And another function that compares the block level of a line with a previous line, and add { or } or do nothing accordingly.

If these 2 functions parse the .raw file generated, I think it can be a potentially quick-to-implement solution that still preserves backward compatibility. Of course, there must first be a general check to see if the .raw file uses the Python indentation style or the JS {} indentation style, before calling those functions.

Because the underlying code is still in JS and same for CasperJS JS code blocks, I think the implementation would likely be parsing Python indentations to JS {} code blocks instead of parsing JS {} code blocks into Python indentations to be then parsed again to CasperJS code blocks.

**Comment by kensoh** [comment]
Closing issue as this is done in v6
