### ISSUE TITLE
ERROR - Unable to open file 'tagui_chrome.out' - pending testing

### ISSUE THREAD

**Issue by saketlopes** [kelaberetiv/TagUI#661]
Hello 

I have setup a automation , which runs hourly bases . But some time it gets fail with below error.

**ERROR - Unable to open file 'tagui_chrome.out'**

for this error i found some previous issues links
https://github.com/kelaberetiv/TagUI/issues/560

Can you please suggest How to make use of end_processes.cmd ?

Currently I have set automation in window task scheduler with batch file.
Automation script combine with tagui command and python script therefore I have activated python virtual environment before calling tagui script.

Batch file as below 
_echo off
cd C:\tagui\Projects\Ariba_invoice_prod
cmd /k "C:\Python\Projects\reports\Scripts\activate.bat & tagui main_flow.txt chrome report & C:\Python\Projects\reports\Scripts\deactivate.bat & exit"_

Regards
Saket Lopes

**Comment by kensoh** [comment]
Hi Saket, your setup is a bit more complex than the usual usage, because I don't know what is happening in your activate.bat and deactivate.bat. You can try adding the following line in your batch file to see if that helps. The end_processes script will kill all TagUI and integrations processes.

```batch
@echo off
c:\full_path_to_tagui_src\endprocesses
```

The error happens when the file is somehow locked and it could be previous processes not exiting cleanly, or maybe when you run hourly, the previous process has not completed. Hopefully above will work for you, as all processes will be killed before running TagUI in your batch file.

**Comment by saketlopes** [comment]
Hello Kensoh

Thanks for your help.

I will try , But I have a question ? currently I have setup multiple automation on a central server and these automation are running hourly VIA task scheduler for multiple users .

endprocesses file will kill only Tagui task belongs to my user or other too?
 
Regards
Saket Lopes

Will

**Comment by kensoh** [comment]
I think that is the root cause of the issue. It could be different automation jobs from different users not completed yet and new jobs start.

TagUI was not designed and tested to run in parallel with multiple sessions at the same time on the same computer. Thus this use case is not supported and not expected to work properly.

The end_professes script will kill all TagUI processes that the user has access to. If a user can see other user processes on the server then it will try to kill them too. Because the tool is designed with having only 1 active process at one time.

**Comment by kensoh** [comment]
Under the developer reference section, there is a part on API and API Service files. It implements a queue system to make sure only 1 job is running at 1 time. But the code is for Linux / macOS. You can use as idea if you want to modify your implementation into a  queue-based system.

https://github.com/kelaberetiv/TagUI#developers-reference

Alternatively, you can consider installing TagUI into seperate directories with each directory to be used by 1 user, to see if that helps. I think there'll still be issues if user processes are not hidden from each other by the OS (eg Chrome processes, TagUI main running process etc).

**Comment by saketlopes** [comment]
Thanks Kensoh for your help,I will identify cases  as you suggested.

**Comment by saketlopes** [comment]
Hello Kensoh

Suppose I have multiple automation separated by folder name example
C:\Automation 1
C:\Automation 2

If I setup tagui under each folder like.
C:\Automation 1\Tagui\src
C:\Automation 2\Tagui\src

Can this idea will resolved my issue or there will be other issues ?

Regard
Saket Lopes

**Comment by kensoh** [comment]
You can try and test to see if it works. It has to be done under different user accounts, and can only work if the user has no access to the processes running in other user accounts. I have not tested something like that to know if that works, but it may work in theory.

**Comment by saketlopes** [comment]
Hello Ken

With regards to this issue below are  my analysis .
I found running parallel processing are creating challenges to mange automation.

I tried above option , with it error frequency reduced.
But issue not resolved. 

Whenever automation gets terminated i saw following task process were remain in memory.

conhost.exe
casperjs.exe
cmd.exe
phantomjs.exe
php.exe
python.exe

As I have several other automation running parallel, so I avoided to use endprocessess.cmd.
I have implemented a python script which will check if any process active belongs to my automation folder then i am closing those task . This check runs before i start automation.
It works as endprocessess.cmd but only for my automation folder.
Do you suggest, to check any process before starting automation?

I am planning to implement queue to handle parallel processing.
Can you suggest any tool or python library which will help to handle queue on windows platform.

Regards
Saket Lopes

**Comment by kensoh** [comment]
Hi Saket, I see.. What you observe makes sense as TagUI isn't designed for parallel runs.

I'm afraid I don't know which tools are good for managing queues. It should not be too difficult to develop your own queue management system by combining with batch files and Task Manager.

**Comment by githubcyc** [comment]
@saketlopes I recommend that [celery/celery: Distributed Task Queue ](https://github.com/celery/celery) will will help to handle queue.

**Comment by kensoh** [comment]
CC @siowyisheng fyi on celery. New to me.
