### ISSUE TITLE
Why Chrome gets closed but command line keeps on waiting?

### ISSUE THREAD

**Issue by amitsavani** [kelaberetiv/TagUI#664]
I am trying to scrap about 500 mp3 uploaded on google drive from a page. Below is the script I had written.

```
https://gujaratistorytellingforchildren99.blogspot.com/2019/06/415.html

total_stories = count('//ol/li')
echo "total_stories = " + total_stories

for (n=; n<=total_stories; n++)
{
	read (//ol/li['+n+']//a/@href) to mp3_url
	echo "mp3_url = " + mp3_url
	click (//ol/li['+n+']//a)
	wait 5
	keyboard [ctrl][s]
	echo 'Saved'
	wait 3
	echo "current URL > "+url()
	if text() contains "Sorry"
	{
		echo 'Download failed...closing window'
		keyboard [ctrl][w]
		wait 2
	}
	echo 'go back to index'
	chrome.back();
	wait 3
}
```

The problem is when on successfully download, it closes the chrome which ideally shouldn't? Would anybody please suggest what is wrong with it and how can be fixed?

**Update**
Suddenly I realised that those TagUI processes still working in background even if nothing is running and consuming all of the CPU.

![Screenshot from 2019-12-24 10-30-11](https://user-images.githubusercontent.com/1183144/71394761-fc3b7300-2638-11ea-939d-cf0bad461be8.png)

**Comment by kensoh** [comment]
The problem looks like below block of code. 2 things you can check. First, you try to close if download fail, is it because there is a new window opened on failed download? If there is no new window, trying to close the current window will lead to TagUI losing connection to Chrome browser, thus there is dead process still in memory.

```
if text() contains "Sorry"
	{
		echo 'Download failed...closing window'
		keyboard [ctrl][w]
		wait 2
	}
```

Second, I suspect that the condition above may be true whether download successful or not. There can be HTML text on the page with string 'Sorry' but it is not visible. You can try using TagUI live mode (add a `live` step) to try verify if the condition you are checking is correct or not. You may need to refine the condition to something more specific to match correctly.

Also, if you have the n value which will lead to error download, you can post here. That will also help troubleshooting. Attaching the logs here will also help, but first check above two ideas.

**Comment by AmitPatel-BoTreeConsulting** [comment]
Thanks @kensoh for quick reply. Actually it doesn't reach to the condition after file downloaded successfully. Here is the log

```
total_stories = 500
read (//ol/li[500]//a/@href) to mp3_url
mp3_url = https://drive.google.com/open?id=1cZnj5OohMdQr5SaGWLyXx6e0YHzfgLYx
click (//ol/li[500]//a)
wait 5
keyboard [ctrl][s]
Saved
wait 3
```

The first link shows error always so I reverse the loop. When we press Ctr + S, google drive opens new tab and starts downloading. It immediately closes the tab once download starts. There after `wait 3` gets printed and then chrome itself gets closed.

**Comment by kensoh** [comment]
Above doesn't look straightforward to replicate as the n value is not provided. I recommend you break the automation into 2 parts. First part try to get the URLs of all the links. After that, format into a .csv file and use datatable method (try with speed option and without speed option) -

https://github.com/kelaberetiv/TagUI#datatables

**Comment by kensoh** [comment]
That way the automation can be made straightforward, to process each link 1 by 1. Your second automation script can be made easy by something like below, where url is the field in datatable.

```
`url`
keyboard [ctrl][s]
```

**Comment by kensoh** [comment]
Let me know if breaking the automation into 2 parts works for you, closing issue for now until further inputs!
