### ISSUE TITLE
How to make TagUI work with Chrome window which is already running?

### ISSUE THREAD

**Issue by mapofthe** [kelaberetiv/TagUI#666]
Hello! I'm very noob. Could you help me? How to make TagUI work with Chrome window which is already running? I don't want TagUI to run a new Chrome window

**Comment by siowyisheng** [comment]
Hi @mapofthe ! What is your use case that you are trying to automate the current open chrome window?

The best way to do that is to use [visual automation](https://github.com/kelaberetiv/TagUI#visual-automation), but the manipulation is more limited than you can usually do with web automation, since you don't have direct access to the dom.

**Comment by siowyisheng** [comment]
I'll close this issue for now and you can reopen if necessary.

**Comment by kensoh** [comment]
Adding a reply to a newer issue on the few alternative ideas to do that -

https://github.com/kelaberetiv/TagUI/issues/1043#issuecomment-850774922
