### ISSUE TITLE
Can't upload video file to Facebook - try visual automation method

### ISSUE THREAD

**Issue by mapofthe** [kelaberetiv/TagUI#670]
Hello!
I tried different selectors, trying to attach video file to Facebook post, but it still doesn't work. What am I doing wrong?
I use this command:
`upload #js_5 as a.mp4`

![New Project](https://user-images.githubusercontent.com/35805764/71542911-6deb2800-297d-11ea-82d9-9df48b2138e9.png)

**Comment by kensoh** [comment]
Hi @mapofthe your code looks correct, it could be due to a number of reasons. Perhaps Facebook has detected automation and blocking, perhaps the upload popup window is a frame which requires frame step to set the context, or perhaps the locator may be randomly generated..

Though I think most likely is because the upload mode is not supported. The upload step is usually meant for situations when there is a filename input which the filename shows up after selecting the file, not something like this Facebook upload method.

First suggestion is you can try the live mode by putting a live step in your script, then test different combinations to see if the upload step works. Unlikely, because not the type of upload method the step is designed for.

Second suggestion is use the visual automation mode. That mode replicates user actions and keystrokes visually. It should solve most of the problems above to allow the upload to work. See https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by kensoh** [comment]
Fyi adding on, I was try to test on imgur.com which the upload step was tested during development. It looks that the step also does not work now for the beta upload page on imgur with this new style of uploading files - https://imgur.com/upload?beta

**Comment by kensoh** [comment]
Closing issue for the time being until further inputs!
