### ISSUE TITLE
Workarounds for Websites Discouraging Automation - depends on website

### ISSUE THREAD

**Issue by mbsryu** [kelaberetiv/TagUI#680]
I've been following the thread [#660 ](https://github.com/kelaberetiv/TagUI/issues/660) with some interest. Although #660 is specific to Google (Gmail?), I was wondering how common it was for websites to implement features to prevent/discourage browser automation?

In one flow that I use, I noticed that (a click step) on a button on the website recently stopped working when using the default (PhantomJS) mode. It works however when using the visible Chrome option. I've not tried Headless mode yet. 

I'm unable to show this here as the website is a closed members only site... but it "feels" as though the website is determining the browser type (via user agent) and modifying its behaviour. (Then again I can't rule out the possibility that there are other reasons.)

If this (prevention of automated browsers) is a common occurrence, I was wondering whether it would be helpful to have a list of similar issues, possible causes, and workarounds.

In my particular case, switching to visible Chrome mode was a workaround of sorts but it slowed down the operation of the flow significantly. (I would imagine the Visual Automation method would slow it down even more.) As frequent and automated checking of the information on the website is one of the requirements being addressed in this particular flow, this is somewhat undesirable.

**Comment by siowyisheng** [comment]
Some automations not working in default PhantomJS mode may be due to the fact it doesn't read the most modern javascript. It may not be due to user agents/headers/etc. 

You can try using the `headless` option which runs chrome headlessly to see if those same automations work.

**Comment by mbsryu** [comment]
Thank you for your ultra fast response!!

Trying it in headless mode brought up the same error. My step is as follows:

**TagUI step**
click .menuItem.recentItem.recentProject .recentItemText:nth-child(1)

**Error**
ERROR - cannot find .menuItem.recentItem.recentProject .recentItemText:nth-child(1)

In both Phantom.JS and Headless Chrome, I get the same error in the log. The step works without a problem in visible Chrome mode.

**Comment by siowyisheng** [comment]
Thanks for your report. We are monitoring this issue as well.

**Comment by kensoh** [comment]
Adding on, websites are mostly developed and tested to work on Chrome. Thus running using PhantomJS or headless Chrome can lead to unintended effects that sometimes is not due to the website trying to prevent automated browsing.

There are some stuffs that websites do to prevent automated browsing, for eg checking UserAgent which denotes to the webserver what browser user is using, using randomly generated element attributes so that user can't code in the same XPath or CSS which will fail on each new run, and others like Captcha. All these have solutions, but most solutions are not permanent because once users start to find a loophole, the website will also add new logic to block in other ways.

You can try headless Chrome and use the live step to try live debugging. You can do something like below to see the HTML code or save it somewhere to troubleshoot why in headless mode it is not showing up - `html_content = chrome.getHTML()`

Can you tell more details why using visible Chrome slow down operation of the flow significantly? There should be negligible impact on the total execution time for visible Chrome and PhantomJS. If there is datatable iteration, using speed option will speed things up without restarting Chrome. Or maybe the flow has many small steps with negligible lag time from the webserver, then it might be much slower on Chrome. Otherwise normal bottleneck in automation is the delay in the website responding to an action.

Lastly, in `tagui\src\tagui_chrome.php` there is `$scan_period = 100000;` which means a polling time of 0.1 seconds from TagUI to Chrome. You can try reducing this to 10000 or 1000 or lesser to speed up the communications between TagUI and Chrome to see if that helps. Usually lag time is website responding, so I set it as 0.1 sec for a good balance between being responsive and wasting too much CPU cycles on checking Chrome response.

**Comment by mbsryu** [comment]
Once again, thank you for your informative responses. 

Something rather curious is happening.

For the last few days, our production flow had been  using the visible Chrome mode since the Phantom and Headless Chrome had stopped working.  

This morning however, we found that the visible Chrome no longer works, but Phantom and Headless modes are working again. 

It does feel as though the website devs are tweaking their site in response our robotic efforts.

**Comment by mbsryu** [comment]
As for differences in speed between Phantom.JS and visible Chrome modes, we're finding that when running in visible mode, more wait steps are required for certain activities. 

Am not sure about the exact cause/effect  but wait steps are necessary when the elements that need clicking are always available on the page but will behave different depending on the (table) data being displayed which takes a while to refresh after the previous step.

I cannot explain why this is not the case when in invisible modes., but our tests have shown that in visible modes, more wait steps in between helps to make the flow more robust.

**Comment by kensoh** [comment]
Oh yes, that sounds like some active tweaking (manual or automated) from the website to reject automated activities.

I see.. Yes that sounds strange, visible mode consumes more CPU time and uses the graphics card, but I don't think it slow down a normal computer significantly.

Lastly, as TagUI has auto-wait build in, if the selector you use are uniquely present in the updated page or the website, then it will wait until the element identifier appears before continuing the next step. Default timeout is 10 seconds but can be changed to longer or shorter with timeout step. The key will be looking out for what is it that will appear when the webpage is ready, and use that with hover step for example, to wait until that signal element before continuing.

**Comment by mbsryu** [comment]
Re web dev tweaking...  Is it possible for the website to determine that automation is in use when its running in **_visible_** Chrome mode?

Your comment about the Hover step use to wait/test for the appearance of an element was helpful. I've been able to replace most of the wait steps in favour of hover.

**Comment by kensoh** [comment]
Yes it's possible, website could also run JS code to detect mouse movements. In automated browsers there isn't the human-like mouse movements around a page. Thanks for feedback!

@siowyisheng it looks like hover step to 'wait' for something to appear is not intuitive. Do you think this should be addressed from samples and tutorials, or we could look at something enhancement to wait step?

Eg now it's `wait 3 seconds`, `wait 12.3` but it might be able to modify to support `wait identifier` until the default timeout of 10 seconds happens.

**Comment by kensoh** [comment]
Closing issue for now till further inputs
