### ISSUE TITLE
Error: A network error occurred in synchronous requests - URL inactive

### ISSUE THREAD

**Issue by joglomedia** [kelaberetiv/TagUI#683]
Hi there,

i am trying the github flow example from https://github.com/kelaberetiv/TagUI/blob/master/src/samples/3_github

and got this error

```ERROR - NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.```

**Comment by kensoh** [comment]
Hi @joglomedia thanks for flagging this out! Yes below api step tries to use a free API to test calling API, but below free service is now no longer active. Visiting below URL from the browser will get the same error message. Copying @siowyisheng who is revising the sample and docs, so that a new working API example can be used instead.

```
api http://services.groupkt.com/country/get/iso2code/SG
ERROR - NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.
```

**Comment by kensoh** [comment]
Closing issue for now as this example will be excluded in the new samples.
