### ISSUE TITLE
How does TagUI Interpreter translate code block into Javascript?

### ISSUE THREAD

**Issue by githubcyc** [kelaberetiv/TagUI#706]
* How can i parse condition or loop syntax ? 

```js
a = 1
if a equals to 1
{
      snap page1
}
else if a equals to 2
{
      snap page2
}
else
{
      snap page3
}

for n from 1 to 3
{
       echo n
}
```

* How can i translate TagUI script as above to python script like followings?

```python
a = 1
if a == 1:
  snap page1
elif a == 2:
  snap page2
else:
  snap page3
 
for n in range(1, 3):
  print(n)
```

**Comment by kensoh** [comment]
Hi @githubcyc this sounds like you are trying to do something special for some special applications, because the output Python script above is not something that is runnable by Python.

The short answer is a lot of string manipulation and detection. The code to do this is for JavaScript in src\tagui_parse.php --> parse_condition() function. It is not easy and straightforward to do this correctly and will take a lot of trial and errors to be able to handle the edge cases if you try to do that in Python.

**Comment by kensoh** [comment]
CC @siowyisheng and closing for now till further inputs, as this is not a question related to TagUI.

Adding on, if you want the automation code to be in Python, you can use RPA for Python, a personal project I created that is built on TagUI, to do RPA stuffs. Then you can write Python code directly without doing all these translations. https://github.com/tebelorg/RPA-Python
