### ISSUE TITLE
Wrong Output for Automation script in Hindi - check locale and chcp

### ISSUE THREAD

**Issue by joginderrohilla** [kelaberetiv/TagUI#718]
Output written on command prompt should use hindi keyword after execution.

Please find below screenshot. Let me know if more information is required.

![image](https://user-images.githubusercontent.com/60636357/73828416-377bb500-4827-11ea-9ae9-5ff02fc84aea.png)
![image](https://user-images.githubusercontent.com/60636357/73828468-4cf0df00-4827-11ea-9ac5-10f5dd8c43a2.png)
![image](https://user-images.githubusercontent.com/60636357/73828510-6003af00-4827-11ea-86dc-92f297667baf.png)

**Comment by kensoh** [comment]
The code seems to be running correctly but the output shows garbage. This is likely due to Windows command prompt not able to render the Hindi text correctly. See the tip at Native Languages section - https://github.com/kelaberetiv/TagUI#native-languages

>Tip - as Windows Unicode support isn't as straightforward as macOS/Linux, doing this in Windows may require changing system locale, using chcp command, and selecting a font to display native language correctly - http://www.walkernews.net/2013/05/19/how-to-get-windows-command-prompt-displays-chinese-characters/

After changing system locale or using the chcp command to change the code page correctly for the command prompt this should hopefully work. Let me know how it goes!

**Comment by kensoh** [comment]
Closing issue for time being until further inputs, let me know how it goes @joginderrohilla !
