### ISSUE TITLE
Passing parameters to tagui file from another file - variables are shared

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#720]
![image](https://user-images.githubusercontent.com/6286626/73907219-79f6cd80-48cb-11ea-8025-4abd23e70a5c.png)

![image](https://user-images.githubusercontent.com/6286626/73907233-8713bc80-48cb-11ea-8272-f5826eac4f54.png)

When I use parameter to call another tagui file from one tagui file I get file not found error.  This is 2 simply 2 steps of clipbard and keyboard Ctrl+v to enter value in a shot.

**Comment by kensoh** [comment]
The syntax above is invalid. The tagui step only has 1 parameter which is the filename of the child script that you want to call. So `type.tagui abc` is invalid because there is no such file.

The variables in the parent script will all be accessible in child scripts. If the variable is changed in the child script, it will be updated in the parent script. For eg, below should print 1, 1, 2.

**parent script**
```
a = 1
echo a
tagui child
echo a
```

**child script**
```
echo a
a = 2
```

**Comment by kensoh** [comment]
This should be straightforward to work, closing for now until further inputs!
