### ISSUE TITLE
Trigger TagUI from RasaNLU - try RPA for Python, ask RasaNLU forum

### ISSUE THREAD

**Issue by alketshabani** [kelaberetiv/TagUI#727]
Hello,

i want to integrate RasaNLU with TagUI. I know that in Rasa i can have custom actions in python and from there i can run TagUI automation. My concern is how can i do this in 2 separate machines. 

Thanks in advance

**Comment by kensoh** [comment]
Hi @alketshabani to invoke TagUI from RasaNLU you can use the Python os.system('tagui flowfile options') to call TagUI to run a pre-defined script or a script generated dynamically in your Python program. Above assumes you already added tagui to path, otherwise you have to provide the full path.

Also, I've created a personal project based on TagUI which brings TagUI RPA capabilities to Python. Most likely, if you use that rpa package instead, it will be easier to do, as you can have fine-tune control of the automation step by step, instead of running a full script all at once. See more at https://github.com/tebelorg/RPA-Python

For 2 separate machines, I assume you mean if run RasaNLU as a webserver / webapp, how can the user be able to call TagUI on his computer from the web browser actions correct? For this, you'll have to check with RasaNLU community forum to ask how people implement running local programs through the RasaNLU web frontend. From what I understand, it is not straightforward as web browsers are designed not able to run local programs for security reasons.

You'll probably have to implement some background agent on user local machine that pings some web-hosted REST API or data to repeatedly keep checking if there is a command to run from your web frontend. Try posting in the RasaNLU, someone should have a similar challenge and solution there. I won't be able to advise more because this requires in-depth understanding of RasaNLU, its capabilities and limitations.

**Comment by kensoh** [comment]
CC @siowyisheng

**Comment by alketshabani** [comment]
Thank you for you answer, i will follow your suggestion.
