### ISSUE TITLE
Chrome dom_result problem - use .toString() to return array object as string

### ISSUE THREAD

**Issue by muratcim** [kelaberetiv/TagUI#729]
Hi @kensoh 

i have a dom block that captures all urls on a page.Null returns when the dom_result object runs in chrome visible mode.When I run it with phantomJs or firefox, I can get the result I want

```
https://www.google.com
dom begin
var links = []
for (index = 0; index < document.links.length;index++)
{
  links.push(document.links[index].href)
}
return links
dom finish

echo dom_result
```

I researched it before I wrote it, but I couldn't find any results.

**Comment by kensoh** [comment]
Hi @muratcim this is a usage issue, you are trying to build an array called links and return the error to TagUI. However, you can only return string to TagUI instead of links which is a JavaScript array object. You can do it by using below instead to return as a string to process with dom_result.split(',')

```
return links.toString()
```

**Comment by kensoh** [comment]
Closing this issue but ping here if anything! CC @siowyisheng
