### ISSUE TITLE
Important folder path suggestions in the script by default - to review

### ISSUE THREAD

**Issue by muratcim** [kelaberetiv/TagUI#730]
Hi @kensoh 

Desktop, home and temp folder paths may be required in RPA projects.
For this I made the following changes in the tagui_parse.php file.

```
$marker_for_home_path = "var home_path = '" . str_replace("\\","/", drush_server_home()) . "';\n\n";
fwrite($output_file,$marker_for_home_path);

$marker_for_desktop_path = "var desktop_path = '" . str_replace("\\","/", drush_server_home()."/Desktop") . "';\n\n";
fwrite($output_file,$marker_for_desktop_path);

$marker_for_temp_path = "var temp_path = '" . str_replace("\\","/", sys_get_temp_dir()) . "';\n\n";
fwrite($output_file,$marker_for_temp_path);
```

I can now access desktop_path in my project.Maybe it can be added to the tagui project by default.

**Comment by kensoh** [comment]
Thanks @muratcim for sharing your inputs! Passing on to @siowyisheng to review to see if this is something to add into future release of TagUI in v6/v7. I added below my inputs.

Hi Yi Sheng, for your assessment. Few points -

1. Above `marker_for_syntax` is not relevant as it is only for flow_path, if this is added, it can be added with more meaningful temporary variables

2. the drush_server_home() stuffs are nothing to do with TagUI or macOS or Linux, but looks like a Drupal project called Drush. If implemented, this has to be done using normal PHP functions

3. Home folder has no meaning I think on Windows, also Desktop folder may not have meaning on Linux. This is not easy to implement in consistent way across all OSes

Overall, I'll think that it would not be a common use case for users to have to access temp folder or home folder, or the desktop folder, since folder location can already be by context of where the script is located. I'm leaning not to add this new global variables due to hard to implement consistently and not a common use case, but will leave it to you to decide.

**Comment by kensoh** [comment]
Bumping my colleague @siowyisheng for inputs

**Comment by kensoh** [comment]
Closing issue for now until further similar suggestions from users!
