### ISSUE TITLE
Extended ASCII chars - SikuliX doesn't support extended chars, try this hack

### ISSUE THREAD

**Issue by JoseLuisTeixeira** [kelaberetiv/TagUI#742]
Hello Ken,

Thank you for this great tool.
Making first trial steps (using the new mail example).

Whenever I insert an extended ASCII, tagui is not able to finish the script.
This works perfect:
`enter 03_mail-body.png as Ola teste,\n\nEm anexo os numeros do Euromilhoes. \n\nAtentamente,\nJose Luis`

This does not work:
`enter 03_mail-body.png as Olá teste,\n\nEm anexo os números do Euromilhões. \n\nAtentamente,\nJosé Luís`

It seems that the problem is on the _console_ as either the js or the log file are ok. 
![Image of tagui console](https://i.imgur.com/UnjNqfk.png)

![Image of tagui newmail.txt.js](https://i.imgur.com/XBzay57.png)

![Image of tagui newmail.txt.log](https://i.imgur.com/jX3EqhA.png)

**Comment by kensoh** [comment]
Hi Jose, TagUI should work with UTF-8 characters. But as Windows Unicode support isn't as straightforward as macOS/Linux, doing this in Windows may require changing system locale, using chcp command, and selecting a font to display native language correctly.

See if the info here helps - http://www.walkernews.net/2013/05/19/how-to-get-windows-command-prompt-displays-chinese-characters/

Alternatively, try running TagUI with the quiet option to see if not printing the output to screen helps. Lastly, can you attach the log file here and tell me more what is the error message or problem when running the script?

**Comment by kensoh** [comment]
Closing issue for now until further inputs, feel free to add on and reopen

**Comment by JoseLuisTeixeira** [comment]
Using `Quiet` option didn't work.
Trying to change `codepage` to _Portuguese_ [chcp 860] either on Command prompt, either inside tagui.cmd also didn't sort effect.

As matter of experience, could you try to make a trial on your side and on the "New Outlook email example", try to insert the word "Olá José" in the email body.

**Comment by kensoh** [comment]
Hi Jose, can you attach you log files in src\tagui.sikuli folder for reference? I don't have a Windows laptop and passing this issue to my colleague to see if there are any workaround ideas to try.

Hi @siowyisheng, it looks like SikuliX can't work with UTF-8 characters. Whether it is by typing (https://answers.launchpad.net/sikuli/+question/246217) or by pasting (https://answers.launchpad.net/sikuli/+question/254595).

Verified that below does not work, some normal English text gets typed and SikuliX terminates with error -

```
keyboard [cmd][space]
keyboard Olá José[enter]
```

```
[tagui] INPUT  - [2] keyboard Olá José[enter]
[tagui] ACTION - keyboard Olá José[enter]
[error] script [ tagui ] stopped with error in line 582
[error] UnicodeDecodeError ( 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128) )
[error] --- Traceback --- error source first
line: module ( function ) statement
82: main (  keyboard_map )     input_keys = input_keys.replace('[esc]',u'\u001b').replace('[ESC]',u'\u001b')
425: main (  keyboard_intent )     params = keyboard_map(params)
528: main (  parse_intent )     return keyboard_intent(script_line)
[error] --- Traceback --- end --------------
IDE terminated: returned: 1
```

Tried using the paste method but the text does not paste correctly either.
```
keyboard [cmd][space]
some_text = "Olá José"
clipboard(some_text);
keyboard [cmd]v
wait
```

Copying you to see if you have any other ideas for such use case, since both typing and pasting does not seem to be supported by SikuliX.

**Comment by kensoh** [comment]
Hi @JoseLuisTeixeira sorry for the long delay, my colleague hasn't looked at this yet. I did some research and found a workaround that I want you to see if it works for you.

Although SikuliX does not support typing out extended characters as part of the automation, there is a workaround by using vision step to run custom SikuliX to paste unicode text.

You can click on the UI element using normal TagUI step, after that use something like below to paste the unicode text. It works for me on macOS and I paste this string to search box.

```
vision paste(ucode("Olá José"))
```

**Comment by kensoh** [comment]
I'll close this issue for now, but keep adding your inputs and questions here if any!

The above method should work by using vision step to paste things. You can also pass in variables from TagUI to SikuliX using this example code below -

```
email_message = 'Hi John, I'm Ken writing to you from Singapore'
vision_step('email_message = "' + email_message + '"')
vision paste(ucode(email_message))
```

For typing, SikuliX (https://answers.launchpad.net/sikuli/+question/246217) still can't support typing extended characters so above workaround I hope works for you.

**Comment by Raul-M-P** [comment]
Hi Ken,

Congratulations for this great software.

This is my code: 

```
keyboard [ctrl] c
mensaje = clipboard()
echo [`mensaje`]
row =[]
row[0] = get_text(mensaje, 'Nombre: ','Primer' ) //Nombre
row[1] = get_text(mensaje, 'Primer Apellido: ','Segundo' ) //Primer apellido
row[2] = get_text(mensaje, 'Segundo Apellido: ','Entidad' ) //Segundo apellido
row[3] = get_text(mensaje, 'Entidad: ','Cargo' ) //Entidad
row[4] = get_text(mensaje, 'Cargo:: ','Dirección' ) //Cargo
row[5] = get_text(mensaje, 'Dirección: ','Localidad' ) //Dirección
row[6] = get_text(mensaje, 'Localidad: ','Provincia' ) // Localidad
row[7] = get_text(mensaje, 'Provincia: ','Código' ) // Provincia
row[8] = get_text(mensaje, 'Postal: ','País' ) // Código Postal
row[9] = get_text(mensaje, 'País: ','Email' ) // País
row[10] = get_text(mensaje, 'Email: ','Observaciones' ) // Email
```


This is what echo [`mensaje`] throws:

Nombre: Vicente
Primer Apellido: Rojo
Segundo Apellido: Monte
Entidad: Hierros Blanco
Cargo: ├ürea de Formaci├│n
Direcci├│n: Calle del Pez , 136
Localidad: Madrid
Provincia: Madrid
C├│digo Postal: 28003
Pa├¡s: Espa├▒a
Email: V.rojo@hierrosblanco.es
Observaciones:


And this is the array row: **[Vicente,Rojo,Monte,Hierros Blanco,,Calle del Pez , 136,Madrid,Madrid,28003,Espa├▒a,V.rojo@hierrosblanco.es]**


As you can see, Cargo is missing ("Área de Formación") and the España word is damaged.
I'm only worried about the array (not the echo[mensaje]) because is the data I need to paste into another application.

I haven't been able to use your workaround here. Could you suggest any other tip, please?
