### ISSUE TITLE
Publish v6 to npm - to publish v5.11 and v6 to npm after wrapping up

### ISSUE THREAD

**Issue by gauravgandhi15** [kelaberetiv/TagUI#755]
@kensoh When are you publishing v6 to npm?

**Comment by kensoh** [comment]
Hi @gauravgandhi15 we are still wrapping up loose ends for v6, after that my colleague @siowyisheng will be looking to publish both v5.11 and v6 to npm.

**Comment by kensoh** [comment]
Hi @gauravgandhi15! there is some bug we found in v6. Will try to fix before publishing on npm

In the meantime, can you tell us your use case for TagUI using npm? Note that it is not really a npm package to use in Node.js, it's there for easier installation only.

Also, because npm can't provision PHP automatically as a dependency, the npm package only works for macOS and Linux as they have PHP by default (except Ubuntu).

**Comment by kensoh** [comment]
Also, visual automation will not work from npm distribution, because there isn't an up-to-date SikuliX package on npm that can be auto-installed. The latest on was 3 years ago -

https://www.npmjs.com/package/sikuli

**Comment by kensoh** [comment]
@gauravgandhi15 will hear more from you the use case, to figure out if we should deprecate it.

It does seem like given the developments and increased usage of visual automation, maintaining an npm package for distribution for TagUI does not make sense. It will confuse users when visual automation is not available, and it does not work on Windows and Ubuntu due to no npm PHP package.

**Comment by kensoh** [comment]
Of course, in a future v7 release, where TagUI is planned for migration to NodeJS, then distribution as a npm package other than a direct zip makes perfect sense.

**Comment by kensoh** [comment]
Hi @gauravgandhi15, closing issue for now until further inputs
