### ISSUE TITLE
Get excel data using python error - syntax issue, check TagUI v6

### ISSUE THREAD

**Issue by joginderrohilla** [kelaberetiv/TagUI#762]
Please look into below issue...

![image](https://user-images.githubusercontent.com/60636357/77232932-13ebae80-6bca-11ea-9c07-40a999b6103d.png)

**Comment by kensoh** [comment]
Hi @joginderrohilla it looks like you are using v6 syntax where variables for `echo` has backticks.

Can you check if you downloaded TagUI v6 here - https://github.com/kelaberetiv/TagUI#tagui

For the pre-v6 release which I think you are using, the echo for variables is echo variable_name

More info on this change and why - https://github.com/kelaberetiv/TagUI#echo-dump-write-steps

**Comment by kensoh** [comment]
Adding on, if the workflow deals a lot with Python packages or Python code, consider writing directly in Python using RPA for Python - https://github.com/tebelorg/RPA-Python

It is built on TagUI so it has similar functionalities for UI automation, and you can get started right away because you are already familiar with TagUI. But it can only code in Python language, not the other human languages like Hindi or Chinese.

**Comment by joginderrohilla** [comment]
> Hi @joginderrohilla it looks like you are using v6 syntax where variables for `echo` has backticks.
> 
> Can you check if you downloaded TagUI v6 here - https://github.com/kelaberetiv/TagUI#tagui
> 
> For the pre-v6 release which I think you are using, the echo for variables is echo variable_name
> 
> More info on this change and why - https://github.com/kelaberetiv/TagUI#echo-dump-write-steps

Hi Ken, I am usinng tagUI v6

**Comment by joginderrohilla** [comment]
> Adding on, if the workflow deals a lot with Python packages or Python code, consider writing directly in Python using RPA for Python - https://github.com/tebelorg/RPA-Python
> 
> It is built on TagUI so it has similar functionalities for UI automation, and you can get started right away because you are already familiar with TagUI. But it can only code in Python language, not the other human languages like Hindi or Chinese.

adding to it, I tried all my python code on Anaconda jupyter, it working fine. but when i run with tagUI v6, it shows me above error

**Comment by kensoh** [comment]
From your screenshot, I assume that the error message happens after the echo step correct?

If yes, try running below workflow - 

```
py begin
a = 1
b = 2
c = a + b
print(c)
py finish
echo `py_result`
```

It works for me on v6 and should print the following output - 

```
START - automation started - Sun Mar 22 2020 10:44:12 GMT+0800 (+08)

py a = 1
b = 2
c = a + b
print(c)
3

FINISH - automation finished - 2.1s
```

**Comment by joginderrohilla** [comment]
Hi Ken, Above additon program is also working for me on v6. YEs i am getting error on echo step. But issue is with python code block, which is not returning anything. how eevr code is working fine on Anaconda jupyter

**Comment by kensoh** [comment]
I see.. There is a log file in tagui\src\tagui_py. Can you attach here to see the error message?

**Comment by joginderrohilla** [comment]
Hi Ken, thanks for your continuous feedback.  It worked after updating my python package openpyxl using below command:
 pip3 install openpyxl

**Comment by kensoh** [comment]
Oh great! I see, I think I can guess why. The Python available in your Anaconda is probably a different environment from the Python in your command line that is available to TagUI. Because of that, what works in Anaconda may not work I have to TagUI. And you saw some log above to install the package to fix it.
