### ISSUE TITLE
TagUI does not accept comma (,) in repository file - CSV format issue

### ISSUE THREAD

**Issue by joginderrohilla** [kelaberetiv/TagUI#770]
Hi Ken, Xpath does not accept comma(,) in repository file

Doesnt work for me:
click link_financial

tagui_local:
link_financial,//a[contains(text(),"Financials")]

Error:
![image](https://user-images.githubusercontent.com/60636357/77831976-9808dd80-7158-11ea-89af-5503efa4c201.png)

---> Looks like it splits with comma in repository file and xpath is getting break

Works for me:
click //a[contains(text(),"Financials")]

**Comment by kensoh** [comment]
Hi Joginder, the reason is because the CSV file is incorrect. In CSV, if there is a comma , in the string, the whole string has to be enclosed in double quotes. Also, after whole string is enclosed in double quotes, the double quotes around Financials has to be escaped with 2X double quotes. Below is the standard CSV formatting that will work for above example -

**tagui_local.csv**
object,value
link_financial,"//a[contains(text(),""Financials"")]"

echo \`link_financial\` shows `//a[contains(text(),"Financials")]`

**Comment by kensoh** [comment]
CC @siowyisheng

**Comment by joginderrohilla** [comment]
Thanks Ken, It worked
