### ISSUE TITLE
Where to add useragent for headless chrome - hack tagui / tagui.cmd

### ISSUE THREAD

**Issue by bhuvanesh15** [kelaberetiv/TagUI#771]
Cuz it throw an error of 403 in headless mode for a site, to overcome it in selenium folks will add useragent in chrome option,is it possible  in Tagui ?

**Comment by kensoh** [comment]
Hi @bhuvanesh15 TagUI is not designed by default to change user agent because for RPA use case the browser should be the default user agent for Chrome. To do this, you have to hack `tagui\src\tagui` file for macOS/Linux or `tagui\src\tagui.cmd` for Windows.

Search for `chrome_switches` variable and add your user agent string according -
`--user-agent=YOUR USER AGENT STRING TO USE`

**Comment by bhuvanesh15** [comment]
Thanks Ken, it works!
can we add --pop-blocker in the same way?

**Comment by kensoh** [comment]
I have not tried that option before but yes you can try it to see if that works. Chrome options which normally can be invoked from the command line should be able to work using this hack 👍
