### ISSUE TITLE
TagUI not working in Linux system - pending user logs and details

### ISSUE THREAD

**Issue by jereff** [kelaberetiv/TagUI#780]
Hi,

I download V6 version for linux and follow the instruction to install tagui, but when I try to run tagui sample script(1_google.tag) with command, the whole terminal will be hangs there, don't have any output in terminal.
first I suspect it is caused by chrome(maybe I didn't install chrome correctly), so I changed the script to very simple one,which has only one command(wait 3),the result looks the same, also hangs there. and one more thing I noticed is: all generated log files are 0 kb, so I couldn't find reason through log files.

my steps are:
1. download TagUI_Linux.zip from website,and unzip it to /home/userid/tagui folder.

2.install openJDK and chrome.

3. ln -sf /your_tagui_path/tagui/src/tagui /usr/local/bin/tagui

4.tagui your_tagui_path/tagui/flows/samples/1_google.tag

and then the terminal hangs there forever, all log files are generated with 0 kb., have to use ctrl+z in terminal to stop running.

do you have any advice? thanks a lot mate

**Comment by kensoh** [comment]
Hi @jereff, TagUI requires Chrome to be installed in order to work. If the Chrome program is missing from the system, there should be an error message. Can you attach the file tagui/src/tagui_chrome.log here?

That file can detect if a successful connection to Chrome happened. After running the command and it hangs forever, is there any output on your screen or there is nothing printed on the screen?

Also, did your Chrome browser launched after you run the command?

**Comment by jereff** [comment]
thanks kensoh,
1.tagui/src/tagui_chrome.log  file I found it is 0 kb.
2.it hangs forever, and no output on my screen, nothing is there.
3. chrome is not launched.

BTW, I changed the script, which has only one line(wait 3), the tagui still not working, the same result,So it may not caused by chrome. all the log files are 0 kb, that wired, so I cound't find any error information

**Comment by jereff** [comment]
Hi kensoh,
I figure out the command is stuck in below code in tagui:

while true; do
ws_url="$(curl -s localhost:9222/json | grep -A 1 '"url": "about:blank"' | grep webSocketDebuggerUrl | cut -d'"' -f 4)"
if [ -n "$ws_url" ]; then break; fi; done

do you have any idea how to fix it?

**Comment by kensoh** [comment]
Great, will need your help to figure out this one, as it requires testing on your system step by step.

1. edit tagui/src/tagui file
2. look for the following line, change the line from 
```
$chrome_command $chrome_switches $window_size $headless_switch > /dev/null 2>&1 &
```
to
```
echo "$chrome_command $chrome_switches $window_size $headless_switch"
```

3. Try running and this will show the exact command that Chrome is run on your system. It will hang as your situation, just kill it. Then run that exact command that Chrome is run on your system. Include the & behind so that it runs in the background.

4. for the ws_url code you type above, try doing it step by step to see where the problem happens.
try below to see if there is some output
```
curl -s localhost:9222/json
```
then try
```
curl -s localhost:9222/json | grep -A 1 '"url": "about:blank"'
```
then try
```
curl -s localhost:9222/json | grep -A 1 '"url": "about:blank"' | grep webSocketDebuggerUrl
```
then try
```
curl -s localhost:9222/json | grep -A 1 '"url": "about:blank"' | grep webSocketDebuggerUrl | cut -d'"' -f 4
```

What should happen is above code should return a websocket URL for TagUI to connect to your Chrome browser so that it can control it and read data from it. if it hangs there, that means for some reason the valid websocket URL cannot be returned using above filter. It could be some issue starting Chrome or some other reason.

**Comment by kensoh** [comment]
If you are using TagUI v6, by default it will launch Chrome browser and using visible mode. Unless -n or -nobrowser option is used, then it will not launch the browser.

**Comment by jereff** [comment]
Thanks kensoh,
I did what you have asked me to do, the result are:
1.echo "$chrome_command $chrome_switches $window_size $headless_switch", output is:
"google-chrome --user-data-dir=chrome/tagui_user_profile --remote-debugging-port=9222 about:blank --window-size=1366,842"

2. then I run the chrome command with "&" behind:"google-chrome --user-data-dir=chrome/tagui_user_profile --remote-debugging-port=9222 about:blank --window-size=1366,842 > /dev/null 2>&1 &"
output: a chrome tab is opened, and the  output in terminal is [19] 10461
3.run "curl -s localhost:9222/json", output:
[19]   Done            google-chrome --user-data-dir=chrome/tagui_user_profile --remote-debugging-port=9222 about:blank --window-size=1366,842 > /dev/null 2>&1

4.the other "curl" command you have mentioned, all of them don't have any output.

**Comment by jereff** [comment]
some update, I found why I couldn't get the websocket url, it is because I used "sudo" when execute tagui script, it will cause error in chrome so couldn't get the url. after I remove "sudo", now I can get url and tagui command won't stuck there.

but if I remove "sudo", there are a lot of error that mention doesn't have enough permission to use "chmod" command for some log files, it looks like some code in script used chmod.

for such case, do you have any advice to resolve permission issue without cause other issue?

**Comment by jereff** [comment]
new update....
I resolved the permission issue with changing whole folder to chmod 777, and also changed tagui script, make all of the chmod command to 777. now it doesn't report permission issue, instead a new error coming:
"Auto configuration failed
139717715680896:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so"

there errors come from:
integrations are active
if [ "$tagui_test_mode" == false ]; then "$CASPERJS_EXECUTABLE" "$1".js $params$api | tee -a "$1".log
else export tagui_test_mode=true; "$CASPERJS_EXECUTABLE" test "$1".js $api --xunit="$1".xml | tee -a "$1".log; fi

**Comment by jereff** [comment]
with "export OPENSSL_CONF=/etc/ssl/", the issue fixed, thanks a lot kensoh!

**Comment by kensoh** [comment]
Hi Jeff, just saw your replies, glad that it works for you now and thanks for sharing these info!
