### ISSUE TITLE
Python script integration documentation/samples - check these docs

### ISSUE THREAD

**Issue by mazhar-webonise** [kelaberetiv/TagUI#784]
Hello!
We're facing an issue with integrating/calling a python script and unable to get past this for a few days. Could you please share some documentation or a sample for this?

**Comment by kensoh** [comment]
Hi @mazhar-webonise! Sure,  

This is the doc for Python integration -
https://tagui.readthedocs.io/en/latest/advanced.html#writing-python-within-flows

This is the old doc with slightly more details for developers -
https://github.com/kelaberetiv/TagUI/tree/pre_v6#python-integration

Main thing is make sure that the `python` command is accessible from the command prompt that you run `tagui` command. So that TagUI can invoke the Python process in the background to run your Python code. If you run into further issues, share your execution log in tagui\src\tagui_py and also your TagUI script that can reproduce this issue so I can check more.
