### ISSUE TITLE
tagui' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by verghese1996** [kelaberetiv/TagUI#786]
Hi there, I have tried to install this tagUI based on the youtube video. 

I have installed the tagUI, Unzipped to my C drive. I have installed OpenJDK for Windows. I have run both commands. Yet it still says that not recognised as an internal or external command. 

I then found on stackoverflow the manual way of adding it. I have done so. Yet still no luck. Do advice. 
![333](https://user-images.githubusercontent.com/63459581/79493915-ba559300-8054-11ea-8750-55c194717341.JPG)

**Comment by verghese1996** [comment]
Managed to fix it. Sorry for wasting your time. New to this. Not sure how to delete it so I will close.

**Comment by kensoh** [comment]
No probs @verghese1996 ! Yes issues can't be deleted. I think what might have happened, is you have not restated the command prompt after changing the path environment variable, or the command prompt is a different user from the env variable that was changed.

In the v6 documentation, there's an easier way to use setx so that you can update the path directly to include the tagui folder - https://tagui.readthedocs.io/en/latest/setup.html
