### ISSUE TITLE
Loop and wait order problem - while loop not supported, use for loop

### ISSUE THREAD

**Issue by puchalakd** [kelaberetiv/TagUI#793]
**Code**:
I=0
while I < 5
  wait 3
  I = I + 1
  echo `I`

**Expected result:**
START - automation started - Wed Apr 22 2020 00:37:51 GMT+0200 (CEST)

wait 3
1
wait 3
2
wait 3
3
wait 3
4
wait 3
5

FINISH - automation finished - 17.0s

Actual Result:
START - automation started - Wed Apr 22 2020 00:37:51 GMT+0200 (CEST)

1
2
3
4
5
wait 3
wait 3
wait 3
wait 3
wait 3

FINISH - automation finished - 17.0s

**Comment by kensoh** [comment]
Hi @puchalakd, the while loop is not supported for TagUI workflows due to technical limitations of the architecture involving CasperJS + auto-wait for element to appear. This is covered in the docs for new doc and old doc to use for loops instead -

https://tagui.readthedocs.io/en/latest/main_concepts.html#loops
https://github.com/kelaberetiv/TagUI/tree/pre_v6#conditions-examples

Below example using for loop will achieve the expected result you want above -

```
for i from 1 to 5
    wait 3
    echo `i`
```

**Comment by kensoh** [comment]
Closing issue until further inputs
