### ISSUE TITLE
Browsers apart from chrome for web automation - use visual automation

### ISSUE THREAD

**Issue by Yogesh2906** [kelaberetiv/TagUI#798]
Hi @kensoh 
Can I use TagUI for web automations on all supported browsers like IE/Edge/Firefox/Safari?

Thanks in advance for your reply!

**Comment by kensoh** [comment]
Hi @Yogesh2906 only Google Chrome is natively supported, because TagUI uses DevTools protocol on websocket connection to communicate and control Google Chrome.

For other browsers, you can automate only by using visual automation method and keyboard shortcuts (eg providing image of elements to interact with).

**Comment by kensoh** [comment]
Closing for now till further inputs
