### ISSUE TITLE
Maximum limit in the for loop? - probably depends on computer RAM

### ISSUE THREAD

**Issue by Robertsson** [kelaberetiv/TagUI#802]
Tagui seems to have a limit of the maximum number in the for loop.
Hard to say exact number but seems to be more then 40000 for me. 

```
for n from 1 to 40000
    echo loop `n`
```

(I think this worked in 5.x. Have only tried it on Windows 10 so far.)

**Comment by kensoh** [comment]
Underneath TagUI is CasperJS. In order to implement on CasperJS, there is always a stack structure of steps before a loop runs. Thus there is a limit and time delay for large loop counts, because the stack data structure will be built first by CasperJS.

I've not tried testing the limit, and it may be different on different computer with different RAM.
