### ISSUE TITLE
How to open a local html page in tagui script - need to hack this way

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#805]
How to open a local html page in tagui script?

Like c:/temp/sample.html.
I tried with file://
I gave just the file name

Everything.... this is to check on my local

**Comment by kensoh** [comment]
Hi @vrudhay TagUI is not designed to do that, because normal users will not be opening local HTML files on their browsers to use a web application. If you really need to do this, you can try hacking tagui\src\tagui_parse.php.

Search for this line -

```
if ((substr($lc_raw_intent,0,7)=="http://") or (substr($lc_raw_intent,0,8)=="https://") or (substr($lc_raw_intent,0,11)=="about:blank")) return "url"; // recognizing about:blank as valid URL as it is part of HTML5 standard
```

And modify to below -
```
if ((substr($lc_raw_intent,0,7)=="file://") or (substr($lc_raw_intent,0,7)=="http://") or (substr($lc_raw_intent,0,8)=="https://") or (substr($lc_raw_intent,0,11)=="about:blank")) return "url"; // recognizing about:blank as valid URL as it is part of HTML5 standard
```

This will accept file:// as a valid URL to open. For Windows, not sure if double backslash is needed to open file in browser you can try file://c:/temp/sample.html or file://c:\temp\sample.html or file://c:\\temp\\sample.html to see which one works for Chrome on Windows.

Also, as this is not a use case TagUI is designed for, you may encounter unexpected behaviour when trying to automate on that local HTML web page.

**Comment by vrudhay** [comment]
That works!

Actually we have a concept for Behavior driven where we create wireframes and write behavior and automate before getting developed.  After development, they execute this scenario and if the result is pass, we 'ACCEPT'.

In fact this is the concept of Behavior driven development.

**Comment by owenttttt01** [comment]
Hi, @kensoh I tried using your suggestion and the script managed to work. Thank you very much!
