### ISSUE TITLE
Many times the Chrome fails close properly - pending replication details from user

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#811]
Many times the Chrome fails close properly - and closes abrupty.  Hence, when it opens for 2nd time, we see the old tabs and windows in the new session of Chrome.

How do we resolve this?  I dont see this in typical automation tools like WebdriverIO or Puppeteer.  Pls. help.

**Comment by kensoh** [comment]
Sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Do you have a minimal replication workflow that can recreate the problem? And what typo of parameters and OS are you running to create the crash?

Normally the browser will be closed after the last line of TagUI instruction is executed. I haven't come across Chrome browser closing abruptly.

If you are using visual automation to launch Chrome visually, you will need to close the tabs manually using keyboard step just like a normal user session. Otherwise when Chrome is reopened again, it will have the previously opened tabs.

**Comment by kensoh** [comment]
(closing issue for now till further inputs)
