### ISSUE TITLE
visual automation type fails on Norwegian chars - added ability to 'type' in non-English

### ISSUE THREAD

**Issue by olvd** [kelaberetiv/TagUI#812]
Hi and thanks for this RPA tools :)

I'm experiencing what looks like an encoding issue with Norwegian characters.
Given the following:
```
task_name = "Skjæring"
type img/task-filter-input.png as `task_name`
```

The input typing is not performed and the output console reads:
type C:/dev/RPA/img/task-filter-input.png as Skj├ªring

If I remove the offending **æ** character, all works as expected.
Is it a bug or do I need to take extra step for these characters to be supported?

Thanks.
Cheers, Olivier

**Comment by kensoh** [comment]
Sorry Olivier, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

As Windows Unicode support isn't as straightforward as macOS/Linux, doing this in Windows may require changing system locale, using chcp command, and selecting a font to display native language correctly. More info on this - http://www.walkernews.net/2013/05/19/how-to-get-windows-command-prompt-displays-chinese-characters/

For my macOS, running below works as expected, showing correct output on the terminal prompt and Google search page.
```
https://google.com
task_name = "Skjæring"
type q as `task_name`
wait
```

Please lemme know if that works, or if you run into any issue or question.

**Comment by kensoh** [comment]
Checking further, noticed you are using visual automation from your example. If I recall, SikuliX (the computer vision engine used by TagUI) has issues with non-English characters. I'll look into it.

**Comment by kensoh** [comment]
Found, indeed, there's an issue with typing non-English characters, due to SikuliX's US keyboard layout.

https://answers.launchpad.net/sikuli/+faq/933
https://answers.launchpad.net/sikuli/+question/260734

There's a solution from above, is to override the default typing behaviour by pasting text as unicode text.

Following code works ok on Google search page. By copying the text to clipboard, then pasting instead of typing it.
```
https://google.com
task_name = "Skjæring"
clipboard(task_name)
click search_bar.png
keyboard [cmd]v
wait
```

It requires above code commit which forces text copied to clipboard to be unicode, to let the paste method work. To use it, you can download the latest copy of the code from here and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files. Thanks for raising this issue!

**Comment by kensoh** [comment]
Closing issue since the latest packaged release TagUI v6.14 is out.

**Release notes** - https://github.com/kelaberetiv/TagUI/releases/tag/v6.14.0
**To download v6.14** - https://tagui.readthedocs.io/en/latest/setup.html
**Documentation** - https://tagui.readthedocs.io/en/latest/index.html
