### ISSUE TITLE
tagui step with datatable.csv

### ISSUE THREAD

**Issue by olvd** [kelaberetiv/TagUI#814]
The invocation of a sub-flow in combination with a datatable csv to iterate over yields:

ERROR - file not found for step tagui mySubFlow.tag data.csv
ERROR - automation aborted due to above

Note that my flows are not in the same directory as tagui.cmd
I have tried with absolute path for both the sub-flow and the csv file but still get the 'file not found' error. 

Is this not supported?

**Comment by kensoh** [comment]
Hi Olivier, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

That's correct, using datatable this way as part of tagui step is not supported. What the tagui step does is it expands a TagUI flow into the same position in the parent flow.

Datatables and variables inside can still be used iteratively, but the datatable has to be specified from the initial tagui command from the command line.

In other words, you can't do a nested loops of 2 different datatables. You might be able to use run step to run the tagui command as a separate process with its own datatable.

But most likely you will run into issues unless you create separate TagUI installations and Chrome user directories so that the 2 tagui processes don't overwrite into each other.

Closing issue for now, but please lemme know if you have any questions on this topic.
