### ISSUE TITLE
tagui table function takes a long time

### ISSUE THREAD

**Issue by yewkay** [kelaberetiv/TagUI#815]
the table to csv function seem to take a long time even for small tables I tested with wiki
```
ubuntu@ubuntu:~/tagui/flows$ time tagui testtable.tag -h

START - automation started - Sat Jun 06 2020 09:21:52 GMT+0800 (+08)
https://en.wikipedia.org/wiki/V%C3%ADctor_Rivero - Víctor Rivero - Wikipedia

table /html/body/div[3]/div[3]/div[4]/div/table to wiki.csv

https://en.wikipedia.org/wiki/V%C3%ADctor_Rivero - Víctor Rivero - Wikipedia
FINISH - automation finished - 23.5s


real	0m36.550s
user	0m22.880s
sys	0m4.502s
```
It takes just over half a minute for tagui to get a small table, bulk of the time went into the _table_ command.

Is there any other way to get the tables into CSV faster? 

System specs if needed.
I'm running TagUI 6 on Ubuntu 20.04 LTS server in a VM with 4 cores (1.6GHz) and 4Gb ram

**Comment by kensoh** [comment]
Hi @yewkay sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Yes the table step is designed to be slow to mimic human user speed. It actually reads the table values cell by cell.

Here are some ideas to speed up data extraction -

1) Try using this hack to make TagUI run at superhuman speed. Not recommended because websites are not tested and designed for super-human speed users and will likely lead to errors in automation - 
https://github.com/tebelorg/RPA-Python/issues/120#issuecomment-610532082

2) Consider using other tools for datascraping which are designed to be fast and not TagUI which is designed to mimic human user speed for RPA purpose and maximise robustness of the automation

3) Perhaps using the visual automation method and keyboard step to select the table to copy out and then paste using clipboard() function or using visual automation to open up Excel to paste the copied data

Closing the issue for now, but lemme know if you have any questions
