### ISSUE TITLE
Unable to find element on MacOS desktop

### ISSUE THREAD

**Issue by natngmk** [kelaberetiv/TagUI#818]
Hi Ken, thanks for developing this tool. It's simple and straightforward and easy to get started.

I'm facing a little problem at the moment. I've installed and setup the following below. But somehow it's not able to find element on desktop screen, the output always returning False. I was trying to get the Calendar app icon.

But it works on Chrome browser and able to find visual elements like logos or buttons.

Did I miss something else?

**Install and setup**
Install RPA package from pip
Installed JDK 11 from Amazon
Allowed Java and Terminal in accessibility (in Security and Privacy control panel)
r.Init() first time setup successful

**Code run**
import rpa as r
r.init(visual_automation = True, chrome_browser = False)
r.exist('cal.PNG') # if true = found

**The log output below didn't seem to throw any error.**
LIVE MODE - type done to quit
 [RPA][STARTED]
[RPA][0] - listening for inputs
[RPA][1] - exist_result = exist('cal.PNG').toString()
[RPA][1] - listening for inputs
[RPA][2] - dump exist_result to rpa_python.txt
[RPA][2] - listening for inputs

I'm on Mac Catalina 10.15.4 (early 2015)
display default scale at 1280 x 800

**Comment by natngmk** [comment]
After some time on google, suspect that Retina display could be the cause of problem. So I went to connect my MacBook to an external display and set it at 1920 x 1080. It works!

I also had a Windows setup but it didn't give me this problem. Will use this workaround for the time being :)

**Comment by kensoh** [comment]
Hi @natngmk, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Yes, your suspicion is correct. I think I saw an open issue regarding Retina display. Will see if I can get more details from there to put this info in docs. From what I remember, the gist of the issue is on Retina display, when a screenshot is taken, it is actually a different resolution and size from the actual screen. So, using that image as an input will lead to it not being found on the screen. Because the image is quite different in size from the actual screen.
