### ISSUE TITLE
How to Download Embed PDF file in Chrome browser

### ISSUE THREAD

**Issue by manojpokhare** [kelaberetiv/TagUI#819]
Let me know what is best way to download embed PDF File . I am using  t.keyboard('[ctrl]s') command but it saves in current working directory. I want to download the file in different directory. Please let me know how to do this.

**Comment by kensoh** [comment]
Hi @manojpokhare sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

After you use keyboard step and if the save dialog box opens up, you can visually click on the folder file textbox, and then use keyboard step again to type out the full path and file name to save the file.

Alternatively, below hack will set the file download location. There is no official step or function for this because a normal user workflow will not programmatically set the file download location. It'll be configured or selected manually.

`r.send("chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'flow_path'});")`

Closing issue for now but lemme know if you have any questions.
