### ISSUE TITLE
Exist is not working on element

### ISSUE THREAD

**Issue by manojpokhare** [kelaberetiv/TagUI#820]
Currently working on the automation of report download from website. After passing parameters when click on the Run report, it opens the new tab and generate the PDF embed report. During the report generation process trying to find out element //html/body/embed element exits or not so that I can do the downloading process. But it is not showing it element is exists even its present.  if I open the developer tool and find the element using XPath , it is showing but not in tagui.

Can you please help me ? I already raised another issue related to this, to download embed PDF file.

Thanks is advance.

**Comment by kensoh** [comment]
Sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I've replied to your other issue https://github.com/kelaberetiv/TagUI/issues/819

From the description, it sounds like you are trying to interact with a popup tab. In that case, the step popup is required - https://tagui.readthedocs.io/en/latest/reference.html#popup

Otherwise TagUI will not know which tab you are referring to when providing the identifier. 2 different tabs can have the same identifier and thus it will not be unique. By using popup step, you can set which tab to automate.

Alternatively, using visual automation and keyboard step would be easier to do these download and save PDF workflow.

Closing issue for now, but please lemme know if you have any questions.
