### ISSUE TITLE
How to read a png file into csv file for tagui

### ISSUE THREAD

**Issue by Sora1433** [kelaberetiv/TagUI#821]
Hi this is my first time using Github and I am thinking of extracting the first column called currency of a table in this website:
https://www.dbs.com.sg/personal/rates-online/foreign-currency-foreign-exchange.page
__________________________________________________________________________________________________________
Here are my codes so far:

https://www.dbs.com.sg/personal/rates-online/foreign-currency-foreign-exchange.page

dom window.scrollTo(0, 200);

snap //*[@id="sgfx"]/div/div[2]/table[31]/tbody to webpage.png
__________________________________________________________________________________________________________
After that, I am not sure how to convert the png file into a csv, not to mention only the first column.

Thank you for reading, any help would be much appreciated as I am a complete beginner :)

**Comment by kensoh** [comment]
Sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

For this webpage, this is a good example to see how to get data from the table -
https://github.com/aimakerspace/TagUI-Bricks/tree/master/DBS-Forex-Gmail#tagui-workflow

The idea is save it directly to CSV using write step instead of saving to PNG and converting it.

Closing issue for now but please lemme know if you have any questions. I'll also reply to your other issue #822
