### ISSUE TITLE
goto or exit script

### ISSUE THREAD

**Issue by yewkay** [kelaberetiv/TagUI#823]
Couldn't find any mention of this in the documentation.

Is there any way to jump/goto a portion of the flow script and also any way to terminate the flow inside the script?

**Comment by kensoh** [comment]
Sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

goto is generally considered a bad way to structure programs, thus this was never added to list of TagUI steps. While it is very powerful, it can lead to more headaches later in trying to debug issues by using this method to jump through code.

For exit, there isn't a step for that, but you can use `this.exit();`. This kills the automation flow abruptly and come back to command prompt. Can you tell me more about the scenario that you are planning to use exit? Please let me know as much details as possible, so that I can see if there is an existing way of doing the same actions, or if there's a need to figure out how to implement an exit step in TagUI. Thanks!

Closing issue for now but please lemme know if any inputs or questions.
