### ISSUE TITLE
Web execution documentation

### ISSUE THREAD

**Issue by yewkay** [kelaberetiv/TagUI#825]
I am looking to deploy TagUI for execution from the browser over the net. 
The only documentation I manage to find is at [https://github.com/kelaberetiv/TagUI/tree/pre_v6#api](https://github.com/kelaberetiv/TagUI/tree/pre_v6#api)

Is there a more detailed write up on the deployment of TagUI for web use?

**Comment by kensoh** [comment]
Sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I'm afraid that is the only documentation. There aren't more details because there are many ways to create a webpage service around TagUI, depending on the programming language and the desired goal.

The main idea is to take in parameters from a webpage or API URL, then convert that into TagUI script or parameters, then run tagui command with the parameters, then decide what to do with the result (eg displaying back to the webpage).

However, note that TagUI is designed to be single instance. If you try to run multiple processes of TagUI at the same time on the same machine using the same using ID, most likely problems will happen. Because each process can overwrite into each other's temporary files like the Chrome I/O buffer.

Closing issue for now but please lemme know if you have any input or question.
