### ISSUE TITLE
Unable to interact from Service-Now website using XPath - perhaps frame

### ISSUE THREAD

**Issue by adityak64** [kelaberetiv/TagUI#827]
I have to automate several user activities like click, type, choose from drop-down box, etc. on Service-Now website (incident form). I am using XPath to locate element on web page and use it with click or type function. To find XPath of an element, I am using Chrome developer tool.
On running the .tag file the ServiceNow web page is opening but its not able to find the element to perform click or type
type //*[@id="activity-stream-work_notes-textarea"] as [clear]test work notes[enter]
ERROR - cannot find //*[@id="activity-stream-work_notes-textarea"]
I am not using Chrome Extension for recording any steps in ServiceNow web page.

**Comment by kensoh** [comment]
Sorry Aditya, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

When an element can be found from Chrome developer console but not found during automation, the most likely reason is because the webpage has frames. Frames is when a webpage is embedded in another webpage. To access elements in a frame, the frame step is required - https://tagui.readthedocs.io/en/latest/reference.html#frame

This is to let TagUI know which webpage to find an element. Otherwise there can be different elements on the same website that exist in different frames and parent page, and an identifier provided will not be unique.

Closing issue for now but please lemme know if any inputs or questions.
