### ISSUE TITLE
The speed for table function

### ISSUE THREAD

**Issue by xiaoxu727** [kelaberetiv/TagUI#829]
i have a table 13(cols)*40 (rows) to save use table(), but it will take 2mins, How can spedd, tks!

**Comment by kensoh** [comment]
Hi @xiaoxu727 sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

The table step is designed to be slow to mimic human user speed. It actually reads the table values cell by cell.

Here are some ideas to speed up data extraction -

1) Try using this hack to make TagUI run at superhuman speed. Not recommended because websites are not tested and designed for super-human speed users and will likely lead to errors in automation - 
https://github.com/tebelorg/RPA-Python/issues/120#issuecomment-610532082

2) Consider using other tools for datascraping which are designed to be fast and not TagUI which is designed to mimic human user speed for RPA purpose and maximise robustness of the automation

3) Perhaps using the visual automation method and keyboard step to select the table to copy out and then paste using clipboard() function or using visual automation to open up Excel to paste the copied data

Closing the issue for now, but lemme know if you have any questions
