### ISSUE TITLE
Weixin (WeChat) demo failed - pending user checks and visual automation logs

### ISSUE THREAD

**Issue by riverbuilding** [kelaberetiv/TagUI#831]
[wxdemo.zip](https://github.com/kelaberetiv/TagUI/files/4794653/wxdemo.zip)
I was trying to make a simple demo: open WeChat app window which is in dock and then search someone, then click the search result in WeChat app and input a word in chat box. but in the very first step, it failed.
not sure what went wrong

**Comment by kensoh** [comment]
Sorry @riverbuilding, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Can I check if you have followed the installation instructions here - https://tagui.readthedocs.io/en/latest/setup.html

Make sure OpenJDK is installed so that the visual automation engine can run. Your automation script looks correct.

Can you also share the contents of the log file tagui/src/tagui.sikuli/tagui_windows.log or tagui.log (macOS/Linux)?

**Comment by kensoh** [comment]
(closing issue for now till further inputs)
