### ISSUE TITLE
How to config TagUI's OCR to recognize the Chinese characters

### ISSUE THREAD

**Issue by yiouyou** [kelaberetiv/TagUI#832]
Is it possible to do it? I assume the OCR function could be customized somehow to support more languages besides English.

Thanks for your attention and help!

**Comment by kensoh** [comment]
Sorry Zack, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

1. download chi_sim.traineddata (simplified chinese) from Tesseract GitHub page -
https://github.com/tesseract-ocr/tessdata

2. put the language file in the Sikulix Tesseract tessdata folder for your OS, see here -
https://sikulix-2014.readthedocs.io/en/latest/basicinfo.html#sikulix-on-windows

3. in your TagUI automation script, add the following line at the top, or before using OCR function -
`vision TextOCR.start().setLanguage('chi_sim')`

Simple test, have a webpage visible with some chinese text, and run the following to save the OCR text -
```
save page.png to chinese_text.txt
```

However, I don't think the OCR function to click using text is working well, for eg below.

```
click 详细信息 using ocr
```

For such case, will still need to rely on an image snapshot of the text to click on in order to automate that step.

Closing issue for now but please lemme know if you run into any issue or question.
