### ISSUE TITLE
Why some commands are working in 'tagui live' mode, but not in 'tagui *.tag' mode

### ISSUE THREAD

**Issue by yiouyou** [kelaberetiv/TagUI#837]
HTML looks as below:
![image](https://user-images.githubusercontent.com/14249712/85696228-53ff8780-b70b-11ea-92a4-f387f9f3c21c.png)

when running
```
n = count('//div[@id="answer_lab"]/div[@class="answer-list"]')
for i from 1 to n
  read (//div[@class="answer-list"])[`i`]/@id to id
  echo `id`
```
Under 'tagui live' mode, l get 355625324 as it should be, however under 'tagui *.tag' mode, I get the error as below:
```
ERROR - cannot find (//div[@class="answer-list"])[1]/@id
```
Moreover, under 'tagui live' mode, l get n equals 20 as it should be, however under 'tagui *.tag' mode, I get n equals 0.

Anyone can help here? Thanks.

**Comment by Robertsson** [comment]
Have you tried adding "wait 2 seconds" after load?
Guessing the page is not fully loaded.

**Comment by yiouyou** [comment]
I've waited 10 seconds to get page ready. Have no idea why is it. Sad...

**Comment by kensoh** [comment]
Sorry Zack, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Thanks Robert, what you said is correct, most likely it is because the page has not been loaded yet.

Hi Zack, TagUI steps will auto-wait for default 10 seconds before showing not found error. count() function will not auto-wait, if something is not yet loaded it will return 0. You can try adding below to the start of the script, to wait up to 60 seconds. The hover step will auto-wait for the element to appear before continuing to rest of steps.

```
timeout 60 seconds
hover answer-list
```

Alternatively, you can add a step `live` in your script to debug live during execution to find out what's wrong. I assume that you are running .tag mode with no options. If you run with -n option, the headless PhantomJS browser may give unusual errors because it is an old browser engine. If you have a minimal script that can recreate the problem you can share here too so I can try to see if it happens on my computer.

**example code using this idea, on github page**
```
https://github.com/kelaberetiv/TagUI/issues?q=is%3Aissue+is%3Aclosed
timeout 60 seconds
hover //*[contains(@id,"_link")]
total_on_page = count('//*[contains(@id,"_link")]')
for n from 1 to total_on_page
    show (//*[contains(@id,"_link")]/text())[`n`]
```

Closing issue for now but please lemme know if you have any input or question
