### ISSUE TITLE
py_step doesn't work

### ISSUE THREAD

**Issue by yiouyou** [kelaberetiv/TagUI#838]
```
phone = 1234567
name = 'donald duck'
py_step('phone = ' + phone)
py_step('name = "' + name + '"')
py print(name)
echo `py_result`
py print(phone)
echo `py_result`
```
results:
```
py print(name)
donald duck
py print(phone)
1234567
````

Shown as up, py_step doesn't work, and have no idea how to pass variables to Python

If run example code:
```
phone = 1234567
py 'phone = ' + phone
py print(phone)
echo `py_result`
```
return:
```
py 'phone = ' + phone
py print(phone)
ERROR - name 'phone' is not defined
```
Still doesn't work.

**Comment by kensoh** [comment]
Sorry Zack, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Your first block of code using py_step() is correct and the result is correct.

Your second block of code is wrong, because the docs have a typo. I have corrected the typo now -
https://tagui.readthedocs.io/en/latest/advanced.html#writing-python-within-flows

The solution to pass variables is already in your first block of code, by doing this way -
```
phone = 1234567
py_step('phone = ' + phone)
py print(phone)
echo `py_result`
```

**Comment by kensoh** [comment]
Closing issue for now but please lemme know if any input or question
