### ISSUE TITLE
Error when using csv_row() - not designed for number inputs, updated to support now

### ISSUE THREAD

**Issue by ronisc** [kelaberetiv/TagUI#841]
When trying to run the following:

```
name = "dog"
price = 10 
details = "small dog"
write `csv_row([name, price, details])` to product_list.csv
```

Getting an error of:
ERROR - undefined is not a constructor (evaluating 'cell_data.replace(/"/g, '\"\"')')

**Comment by ronisc** [comment]
In the meantime, I have managed to make it work by avoiding the use of csv_row().

```
name = "dog"
price = 10 
details = "small dog"
tempArray = [name, price, details]

write `tempArray` to product_list.csv
```

Given the above, I am not sure:
1. What does the csv_row() do, and how it is helping?
2. Why it is not working on my original questions. I am using it exactly the way it is present in the documentation.

**Comment by kensoh** [comment]
Sorry @ronisc I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I see, csv_row() helps to handle special situations (for eg single quotes in inputs, double quotes in inputs), and formats an array of variables into a string, to be ready to write to a text file. It is not working in your examples above because it is not designed to take in numbers as inputs. The documentation examples are reading text inputs from a webpage. Any data read from a webpage using read step is a string, even though it may be a string representing a number.

I'm considering this original design to not handle number inputs as a bug and have updated code to fix this. You can download the latest copy of the code from here and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files. Thanks for raising this!

Closing issue for now but please lemme know if you have any input or question.

**Comment by kensoh** [comment]
Closing issue since the latest packaged release TagUI v6.14 is out.

**Release notes** - https://github.com/kelaberetiv/TagUI/releases/tag/v6.14.0
**To download v6.14** - https://tagui.readthedocs.io/en/latest/setup.html
**Documentation** - https://tagui.readthedocs.io/en/latest/index.html
