### ISSUE TITLE
Not able to extract information from PDF

### ISSUE THREAD

**Issue by prashanthtv** [kelaberetiv/TagUI#848]
Hello,
I have just started exploring TAGUI and it must say that it is really a cool tool and can do wonders. 
I have got stuck with a small issue and it will be great if you can help me out with that.
This is regarding extracting data from a PDF File. I tried doing that, But was not successful. It is not opening up the PDF file.

Below is the code I used:
dclick samplepdffile.pdf using ocr
wait 4
read page.png to text_on_screen
echo text_on_screen

[samplepdffile.pdf](https://github.com/kelaberetiv/TagUI/files/4964079/samplepdffile.pdf)

Note: Also, When i run the .tag file from my command prompt, It opens up a chrome browser always though there is no mention of an url in the flow file.

Regards
Prashanth

**Comment by kensoh** [comment]
Sorry  Prashant, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I see.. If you want to doubleclick on the PDF icon, the syntax is below, where sample_pdf_icon.png is an image snapshot of the icon for this PDF file, together with the file name so that it is unique (there can be many PDF icons on the desktop).
```
dclick sample_pdf_icon.png
```

Yes, TagUI will assume user is automating web browser by default. If you don't need browser, run with -n or -nobrowser option `tagui sample.tag -n`. Closing issue for now but please lemme know if you have any input or question.
