### ISSUE TITLE
Can we write RPA recorder as a standalone application? (Mostly, I have only seen browser extensions)

### ISSUE THREAD

**Issue by jagrati639** [kelaberetiv/TagUI#857]
Hi Ken Soh and Team,
 I need to build an RPA browser recorder. Most of the recorders like selenium IDE, Katalon recorder, sideex and even Tagui are chrome extensions.  Even Tagui browser recorder is an extension, though the player is a standalone application, which is able to pIay the recorded script or manually written script. I need urgent help with understanding the implementation of RPA recorder. Is it not technically possible to implement the recorder as a standalone application (reason being that I also need to implement desktop recorder and I was wondering if I can have a common UI for these 2) ?.  From my research, these recorders call chrome APIs. Are these APIs not exposed to external application?. Is there a workaround?.

I have also sent you request on Linkedin?. Would greatly appreciate help on this. Thanks a lot!.

Best,

**Comment by kensoh** [comment]
Sorry @jagrati639, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

That's correct, in order to access the web element details inside Chrome, it can only be implemented as a web browser extension. There are 2 ideas which can overcome this. First idea is you can try implementing a recorder which captures image snapshots of the UI elements. This way you do not need to use Chrome extension.

2nd idea is you design a Chrome extension which integrates with your RPA recorder to send data back and forth. So that it feels to user it is a standalone RPA recorder. However, the backend is a Chrome extension. I think the 2nd method is how UiPath does it.

Closing issue for now but please lemme know if you have any input or question
