### ISSUE TITLE
python-rpa can't find Xpath

### ISSUE THREAD

**Issue by oulufeng** [kelaberetiv/TagUI#859]
I was reading the school's grades, so I copied the XPath on the web page, but I couldn't find the copied XPath using Python's RPA module, so that I couldn't read / HTML / body / table / tbody / TR [3] / TD [1]

**Comment by kensoh** [comment]
Sorry @oulufeng I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

RPA for Python is a personal side project, please raise the issue here - https://github.com/tebelorg/RPA-Python/issues

However, I most likely won't have time to work on it for now. Catching up with issues raised here past few months. Closing the issue here.

You can find XPath this way https://tagui.readthedocs.io/en/latest/faq.html#how-do-i-find-the-xpath-of-a-web-element

However, if the web element exists within a web frame (embedded webpages), you will need to use [frame()](https://github.com/tebelorg/RPA-Python#pro-functions) first.
