### ISSUE TITLE
TAGUI does not copy all data from csv cell

### ISSUE THREAD

**Issue by mshoa** [kelaberetiv/TagUI#860]
Hi,

I am trying to automate an application using vision, once I move into application I use mouse coordinates to click and type data to application fields. But there seems to be a glitch, not all data is written correctly all the time. 

Some runs it writes the data correctly, some runs it excludes the first character while writing the data.

For eg.
Type (35,158) or field.PNG as `field`
field in csv has "[c]"

Type (66,275) or number.PNG as number
number in csv has C200100481

Sometimes it fills all, sometimes it does not fill all, 

It leaves out the first character and fills "c]" and "200100481". 

I tried to slow down the steps by giving wait 10 even then it does a mistake..I also tried with all .PNG files instead of coordinates.

Anything which I am missing here??

Thanks
Mohammed

**Comment by kensoh** [comment]
Sorry Mohammed, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I see, the above TagUI commands are sent directly as type(target, text) to SikuliX engine. This will let SikuliX click on the target and type the text. If some characters are missing, it could be for some reason, the computer or Chrome browser running on the computer is too slow to respond to the click by SikuliX.

This behaviour can't be hacked because it is controlled in the SikuliX engine. You can try below to break up the 1 TagUI step into 2 steps to slow it down and see if that works to type the variable field correctly.

```
click (35,158)
keyboard `field`
```
```
click field.PNG
keyboard `field`
```

If that is still too fast and the app you are automating responds too slowly, you can try adding a wait this way -
```
click (35,158)
wait 2 seconds
keyboard `field`
```
```
click field.PNG
wait 2 seconds
keyboard `field`
```

Closing issue for now but please lemme know if you have any input or question
