### ISSUE TITLE
ERROR - number of step { does not tally with with }

### ISSUE THREAD

**Issue by sandymehta2014** [kelaberetiv/TagUI#861]
Hi, I am using TagUi 6.0 and I got the following error on the console. I am using Lubutu as an operating system.
ERROR - number of step { does not tally with with }
ERROR - automation aborted due to above

Here is the code that I a using:

`http://www.someurl.com
wait 2

if present('//*[@id="react-root"]/section/main/div/div/ul/li[1]/a')
{
	click //*[@id="react-root"]/section/main/div/div/ul/li[1]/a[@class="-qQT3"]
	wait 5
	dom window.scrollTo(0, 500);
}
for r from 1 to 50
{
  row = r
  if r>=12
	{
   	row=10
  	dom window.scrollBy(0, 300);
	}
}`

**Comment by kelvinl22** [comment]
Hi,

I don't have Lubutu but tested in MS Windows, and [1] does not have the error messages:
_ERROR - number of step { does not tally with with }
ERROR - automation aborted due to above_

My output as shown below:
![image](https://user-images.githubusercontent.com/71938711/95151548-81090f00-07bd-11eb-8639-08bfffc96dd4.png)

[2] By the way, which screen element of **_http://www.someurl.com_**, were you trying to access via the XPath? **_id="react-root"_** does not seem to exist.

**Comment by kensoh** [comment]
Sorry Sandy, thanks Kelvin, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I can replicate the issue, it looks like your blocks of code have different types of indentation -

![indent](https://user-images.githubusercontent.com/10379601/100448592-7e57d580-30ed-11eb-8195-cfaab1df4f53.png)

In TagUI v6, indentation is treated as code blocks. Non-matching indentation will lead to errors like above. Below is the same code with indentation corrected. The {} are now optional and could be removed and still work -

```
http://www.someurl.com
wait 2

if present('//*[@id="react-root"]/section/main/div/div/ul/li[1]/a')
    click //*[@id="react-root"]/section/main/div/div/ul/li[1]/a[@class="-qQT3"]
    wait 5
    dom window.scrollTo(0, 500);
for r from 1 to 50
    row = r
    if r>=12
        row=10
        dom window.scrollBy(0, 300);
```

Closing issue for now but please lemme know if you have any input or question
