### ISSUE TITLE
JS Script not working in headless - pending more info and user replication steps

### ISSUE THREAD

**Issue by sivakmurali** [kelaberetiv/TagUI#862]
While trying to call a service using ajax No action takes place but supposedly it must do the action and redirect to next page . When I snap the page It remains in the same page

**Comment by kensoh** [comment]
Sorry @sivakmurali, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I have not come across this error raised by any user. Can you share a minimum replication script that can trigger this error?

Try running it with -h / -headless option instead of -n / -nobrowser option. -h uses headless Chrome which works better with modern websites than -n which uses headless PhantomJS.

**Comment by kensoh** [comment]
(closing issue for now till further inputs)
