### ISSUE TITLE
Start tagUI on a preloaded page in Chrome or Firefox?

### ISSUE THREAD

**Issue by Stwissel** [kelaberetiv/TagUI#865]
I'd like to create a script that fills in an online form (Intranet) from CSV. The process seems pretty straight forward. However we use 2FA, so initial login and navigation buck automation.

Is there a way where I navigate to the given page (including the login) manually and once there start (or resume?) the TagUI script on the current loaded page?

#question

**Comment by kensoh** [comment]
Sorry Stephan, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Yes your scenario can be done. There are a few ways to do that -

1. you can do a `wait 300 seconds` for example at the start, so that after user manually login the automation starts
2. you can also do something like below. it sets the timeout to be long enough for 2FA login, when user is done and the button that only appears after login appears, TagUI automatically continues and timeout is set back to default 10 seconds

```
timeout 300 seconds
hover some_button
timeout 10 seconds
```

3. some other ways but not user friendly is do a `live` step. after user has log in, user can type done to continue automation

This automation workflow shows an example of method 2 - https://github.com/aimakerspace/TagUI-Bricks/tree/master/IMDA-ICMS-CITREP#tagui-workflow

Closing issue for now but please lemme know if you have any input or question
