### ISSUE TITLE
Ids not working in TagUI

### ISSUE THREAD

**Issue by agrawal27aditi** [kelaberetiv/TagUI#866]
![taguioutut](https://user-images.githubusercontent.com/21997549/92771214-52fbff00-f3b8-11ea-8475-365b3a2e7cd9.PNG)
Hi  Ken,

I am doing web recording using TagUI  RPA web Recorder, I record steps and export it. The scripts which are generated, I am pasting it  in tagUI > src> samples> new file
Below I am sending some parts of my script.
This is a part of the script. In which when the page encounters id, it starts giving me errors, so how do we pass ids in TagUI to get output. I tried using XPath as well but it gives me a similar error.

click _s2d3v > .w-pml-icon.aw7_w-pml-icon
click _rn5dcd > b
click //a[@id="_5m8ha"]
click _gh2l3d
click _nje4wc > span

These steps are directly taken from the TagUI RPA web Recorder.

I have these steps to execute. but getting error as cannot find _s2d3v > .w-pml-icon.aw7_w-pml-icon

**Comment by joginderrohilla** [comment]
TagUI supports ID locator, Below example

https://www.facebook.com/
type email as Aditi
click u_0_b
wait 5


Try putting some wait for page load or Share your URL, you are working on if possible

**Comment by kensoh** [comment]
Sorry @agrawal27aditi I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

A common reason is the web elements are on a web frame. The recorder has a limitation with web frame.

If it is due to web frame, you can use frame step - https://tagui.readthedocs.io/en/latest/reference.html#frame

But alternatively, consider using visual automation by using image snapshots to do the automation, it's easier.

Closing the issue but please let me or @joginderrohilla know if any issue or question.
