### ISSUE TITLE
How to take screenshot and open it afterwards.

### ISSUE THREAD

**Issue by agalino91** [kelaberetiv/TagUI#867]
I basically have the screenshot code ready but I don't know how to open the image after. I wanted to show it as a notification in the latter part of my program. Thank you.

**Comment by kensoh** [comment]
Sorry Anna, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I'm afraid TagUI doesn't have a way to show a popup window with a specified image as notification.

After capturing image, you can try using the Windows start command or the macOS open command to open the image.

```
snap page to result.png
run start c:/full_path/result.png
```

```
snap page to result.png
run open /full_path/result.png
```

Note to use the full path, because the run step will run the command in tagui\src directory, not in the same directory as the automation flow and the image file saved. If your automation involve the web browser, you can using the following line to show a popup message -

```
dom window.alert("Message to user")
```

If your automation involves visual automation or only desktop apps, you can use the following line to show popup -

```
vision popup('Message to user')
```

Closing the issue for now but please lemme know if any input or question.
