### ISSUE TITLE
init(visual_automation = True) is not working

### ISSUE THREAD

**Issue by dharam1804** [kelaberetiv/TagUI#871]
Below is the script I have been trying to run on Windows 10 via Jupyter notebook.
I have installed OpenJDK 8 from Amazon Coretto.

import rpa as t
t.init(visual_automation = True)
t.url('https://google.com')

After running t.init(visual_automation = True), I am getting a windows popup with the below message:
[tagui] START  - listening for inputs

init function is not running successfully.

Please help with a solution.

**Comment by kensoh** [comment]
Sorry @dharam1804 I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

RPA for Python is a personal side project, please raise the issue here - https://github.com/tebelorg/RPA-Python/issues

However, I most likely won't have time to work on it for now. Catching up with issues raised here past few months.

A common cause of error is company network blocking automated installation of TagUI. Otherwise you can try below to check which folder TagUI is installed. After that you go to the tagui\src folder and run `tagui live` from command prompt, to see what error messages appear that could have caused this. Closing the issue here.
```
import os
print(os.environ['APPDATA'])
```
