### ISSUE TITLE
CLICK step not working

### ISSUE THREAD

**Issue by kelvinl22** [kelaberetiv/TagUI#873]
Hi,

Wrote a simple (7 lines) script to test out CLICK step and it seem to fail - pls see below.

1. https://github.com/join
2. wait 5 seconds;
3. type user_email as ABC
4. type //input[@id="user_email"] as 123
5. click //input[@id="user_email"]
6. keyboard [ctrl]a
7. wait 10 seconds;

![image](https://user-images.githubusercontent.com/71938711/94995348-3eceaa80-05d0-11eb-89c2-689185d0ce80.png)

If CLICK works, keyboard statement would have (Ctrl-A) select/highlight the text in email address field. BUT nothing happens. I had ran the script multiple times and when I manually use my mouse to click on the email field prior to KEYBOARD step, the KEYBOARD with Ctrl-A works.

If CLICK fails due to wrong XPATH provided, then why would TYPE (at line 4) works. See screenshot.

**Comment by kensoh** [comment]
Sorry @kelvinl22 I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Oh, the type and click (steps 4 and 5) will talk to Chrome directly to perform the actions. But they do not make Chrome browser in the foreground and in focus. That means any keyboard keystrokes will not be received by the browser, just like a normal human user interaction. If you do [ctrl]a when the browser is not the active window it will not work.

The solution for above is to add 1 more step, for eg `click chrome_icon.png` to make the browser the active window. Or `click user_email.png` to click on an image of the textbox to make the browser window active. This extra steps can be done at the start of the automation or just before the keyboard step. Most impt is make browser active in foreground.

Closing issue for now but please lemme know if any input or question.

**Comment by kelvinl22** [comment]
Hi Ken,

Thanks for your reply.

So there are inconsistencies in the implementation of CLICK?

When click on input box element (such as **_click //input[@id="user_email"]_** ) of webpage, browser window would not be activated (active).

But when click on picture element (such as an image **_click user_email.png_** ) on same webpage, browser would be selected and active.

... because if seen from perspective of normal human user interaction, both above actions would require or have activated browser window.

**Comment by kelvinl22** [comment]
> Sorry @kelvinl22 I was away the past few months - [tebelorg/RPA-Python#144](https://github.com/tebelorg/RPA-Python/issues/144)
> 
> Oh, the type and click (steps 4 and 5) will talk to Chrome directly to perform the actions. But they do not make Chrome browser in the foreground and in focus. That means any keyboard keystrokes will not be received by the browser, just like a normal human user interaction. If you do [ctrl]a when the browser is not the active window it will not work.
> 
> The solution for above is to add 1 more step, for eg `click chrome_icon.png` to make the browser the active window. Or `click user_email.png` to click on an image of the textbox to make the browser window active. This extra steps can be done at the start of the automation or just before the keyboard step. Most impt is make browser active in foreground.
> 
> Closing issue for now but please lemme know if any input or question.

**Comment by kelvinl22** [comment]
> Sorry @kelvinl22 I was away the past few months - [tebelorg/RPA-Python#144](https://github.com/tebelorg/RPA-Python/issues/144)
> 
> Oh, the type and click (steps 4 and 5) will talk to Chrome directly to perform the actions. But they do not make Chrome browser in the foreground and in focus. That means any keyboard keystrokes will not be received by the browser, just like a normal human user interaction. If you do [ctrl]a when the browser is not the active window it will not work.
> 
> The solution for above is to add 1 more step, for eg `click chrome_icon.png` to make the browser the active window. Or `click user_email.png` to click on an image of the textbox to make the browser window active. This extra steps can be done at the start of the automation or just before the keyboard step. Most impt is make browser active in foreground.
> 
> Closing issue for now but please lemme know if any input or question.


Hi Ken,

Thanks for your reply.

So there are inconsistencies in the implementation of CLICK?

When click on input box element (such as click //input[@id="user_email"] ) of webpage, browser window would not be activated (active).

But when click on picture element (such as an image click user_email.png ) on same webpage, browser would be selected and active.

... because if seen from perspective of normal human user interaction, both above actions would require or have activated browser window.

**Comment by kensoh** [comment]
Hi Kelvin, that's correct. The click step actually has 3 different implementations combined into 1. First is using web identifiers, next is using image snapshots, 3rd is using screen coordinates. For web identifiers, it is done using direct communications to Chrome browser, which Chrome will not allow instructions to make it active. That's the reference standard for web-browser automation, like any other automation tools.

For image snapshots and coordinates, they are doing using visual automation to replicate actual mouse movements and keyboard keystrokes. So doing a click on the Chrome browser will make it active like a normal user would.

The alternative of not combining all 3 into 1 step is having 3 separate steps `click_web`, `click_image`, `click_coordinates` instead of `click`. This way, all 3 steps are separate and there won't be inconsistency, but it comes at expense of making it harder for users to use, having to remember 3 steps instead of 1 step for click. And multiply that by the many other TagUI steps like read, snap, dclick and so on.

It is also a bad design if TagUI always use visual automation to click on Chrome browser to make it active at the start. Partly because it is hard to do that consistently on Windows, Linux and macOS and within each OS different screen resolutions. Also, using visual automation slows down the automation due to the requirement to load computer vision and OCR data into memory during starting. This will make all automation slower for all users even when visual automation is not needed.

So it's up to user to do an initial click using visual automation on the browser if they want to make it an active window.

**Comment by kelvinl22** [comment]
> Hi Kelvin, that's correct. The click step actually has 3 different implementations combined into 1. First is using web identifiers, next is using image snapshots, 3rd is using screen coordinates. For web identifiers, it is done using direct communications to Chrome browser, which Chrome will not allow instructions to make it active. That's the reference standard for web-browser automation, like any other automation tools.
> 
> For image snapshots and coordinates, they are doing using visual automation to replicate actual mouse movements and keyboard keystrokes. So doing a click on the Chrome browser will make it active like a normal user would.
> 
> The alternative of not combining all 3 into 1 step is having 3 separate steps `click_web`, `click_image`, `click_coordinates` instead of `click`. This way, all 3 steps are separate and there won't be inconsistency, but it comes at expense of making it harder for users to use, having to remember 3 steps instead of 1 step for click. And multiply that by the many other TagUI steps like read, snap, dclick and so on.
> 
> It is also a bad design if TagUI always use visual automation to click on Chrome browser to make it active at the start. Partly because it is hard to do that consistently on Windows, Linux and macOS and within each OS different screen resolutions. Also, using visual automation slows down the automation due to the requirement to load computer vision and OCR data into memory during starting. This will make all automation slower for all users even when visual automation is not needed.
> 
> So it's up to user to do an initial click using visual automation on the browser if they want to make it an active window.


Thanks for providing clarity. Totally understand the intention of combining 3 steps for better usability by user/developer - just like in many other scripting/coding languages, some are more explicit, while others a lot easier.

**Comment by kensoh** [comment]
I guess there might be another reason why web automation standard does not bring browser to focus or find a way to make browser the active window before automating.

Traditionally, in a setup where computers used to be expensive, allowing automation to run on the web browser in background means a user can continue doing other work on the laptop while automation is running. If finding and implementing a solution to make it always active window, the laptop can't be used for the whole duration of the automation.

**Comment by kelvinl22** [comment]
> I guess there might be another reason why web automation standard does not bring browser to focus or find a way to make browser the active window before automating.
> 
> Traditionally, in a setup where computers used to be expensive, allowing automation to run on the web browser in background means a user can continue doing other work on the laptop while automation is running. If finding and implementing a solution to make it always active window, the laptop can't be used for the whole duration of the automation.


Hi Ken,

In the case where where input form field needs to be cleared prior to text entry, and KEYBOARD not appropriate (since it's not for background processing), what technique can we use?

**Comment by kensoh** [comment]
Hi Kelvin, first way is using web automation `type identifier as [clear]` to clear the field. 2nd way is use visual automation method to first click on the textbox, then do something like `keyboard [ctrl]a`, `keyboard [delete]` to clear the field.

You can use image editor to make centre of textbox transparent so that no matter what text is inside it can be clicked visually. Alternatively, find some anchor label to do an offset to click. Example of getting (x,y) coordinates and adding offset - https://github.com/kelaberetiv/TagUI/issues/879#issuecomment-734014871
