### ISSUE TITLE
How to use variables in datatable in if-statement?

### ISSUE THREAD

**Issue by gem3** [kelaberetiv/TagUI#874]
Hello,

I'm trying to use variables in datatable in if-statement.

Ex."size" in datatable.('S'=small, 'L'=large )

What I want to do is

```
if size equals to "S"
	echo This is SMALL
else
	echo This is LARGE
```

I have tried various ways, but not worked.

If anyone know solutions, please share your solutions.

Thank you.

**Comment by gem3** [comment]
Hello,

After checking a log of js file. I found a solution.

```
if "`size`" equals to "S"
	echo This is SMALL
else
	echo This is LARGE
```


I hope this help somebody in future.

kensoh, My prayers with you and family.

**Comment by sheneeb** [comment]
Thank you for that gem3

**Comment by kensoh** [comment]
Thank you @gem3... Sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Yes that's the syntax for comparing a variable as a string in conditions.

**Comment by kensoh** [comment]
Adding on, you can use double or single quotes in TagUI - 
```
size = 'S'
  
if '`size`' equals to 'S'
    echo This is SMALL
else
    echo This is LARGE
```

I personally prefer single quote because I don't need to press shift key each time I type the quote. This tiny time-saving each time a quote is typed will be compounded info significant time savings over a long period of time.

**Comment by gem3** [comment]
Helloo kensoh,

I have to press shift key to type double or single quotes with a keybord in my language.
this is a keybord layout problem with my language.

btw are you ok now?
I don't know whole your story, but I'm glad to know you are back.

**Comment by kensoh** [comment]
Oh I see.. Then there is no difference using double or single quotes, I understand now...

Thank you..... My mum has just been discharged to go home, after 6 months in hospital. Condition is still bad but we are trying to do what we can to help her recover and not be dependent on oxygen supply through a hole in her throat. It looks like going to be a long journey ahead.

Plan to send 18-month old baby to childcare failed. On first day got a couple of accidents already. Now trying to hire a helper to help with housework, cooking and taking care of baby. So that I can start work again. It's tough being sandwiched with the demands of taking care of a young baby and my mum's illness. But there's no other option than facing it and marching on.

**Comment by gem3** [comment]
Hello kensoh,

It's hard to find words for you.
But I like the story of "塞翁失马，焉知非福".

"There is no unstoppable rain."

**Comment by kensoh** [comment]
Thank you @gem3 I appreciate your kind words of encouragement in these dark times 🤞
