### ISSUE TITLE
cannot find xpath to type

### ISSUE THREAD

**Issue by coolmonster** [kelaberetiv/TagUI#875]
Hi i couldn't find a solution to this problem 

i am trying to type name and email address in the field but i am unable to do so. it say it couldn't find the path. please spare few minute to look into my problem i adding the script. thank you in advance

[webex.zip](https://github.com/kelaberetiv/TagUI/files/5346028/webex.zip)

**Comment by kelvinl22** [comment]
Hi coolmonster,

Instead of using XPath, the script below works:
1. http://meetingsapac50.webex.com/meet/pr1651191506
2. wait 3 seconds;
3. keyboard [esc]
4. wait 1 seconds;
5. keyboard [tab][tab][tab]
6. wait 1 seconds;
7. keyboard [enter]
8. wait 3 seconds;
9. keyboard My Full Name[tab]
10. keyboard me@email.com

Seems kind of challenging to construct XPath, your path seems ok but I encounter issue too:

> _ERROR - cannot find //*[@id="meetingSimpleContainer"]/div[2]/div[3]/input_ 

... had tried and failed with the following too:
- type //input[@placeholder="Email address"] as me@email.com
- type //input[contains(@placeholder,"Email address")] as me@email.com

Truly painful to get XPath to work.

**Comment by kelvinl22** [comment]
... by the way, at script line 3, sending [Esc] key is to rid the Chrome pop-up ('Open Cisco Webex Meeting' - see screenshot below), so that subsequent 3 tabs would position cursor to the 'Join from your browser'.

![Open link with Webex app](https://user-images.githubusercontent.com/71938711/95563101-8e3d2c80-0a4f-11eb-83bb-fb8205607dc2.png)

**Comment by coolmonster** [comment]
Thank you for the solution truly greatful

**Comment by kensoh** [comment]
Hi @coolmonster and @kelvinl22, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Yes, using XPath is powerful but there are still tricky situations, eg in frames, and popup box like above.

Such dialog boxes can block execution of TagUI, thus control is not returned to TagUI until user manually clicks.

What @kelvinl22 shared is a workaround. If 9 and 10 types into the terminal, then just add a step before that to click on the browser to set it in the foreground. Some actions may cause browser to be away from foreground, try to replicate the same steps as a normal user manual actions.
