### ISSUE TITLE
Extracting specific data from pdf

### ISSUE THREAD

**Issue by supu4u** [kelaberetiv/TagUI#877]
Hi,
Please let me know if we can extract specific data from pdf (eg: invoice details such as invoice no. , date of invoice and few other data but not all data) using Tagui? I tried opening pdf and extracting data, but its not coming proper, some data are weirdly coming. Eg: if Invoice no. is 12345 then its coming as "12$%5". This is happening for other data as well. Please let me know if we can use Tagui to extract specific information from pdf. Also, if I need to open multiple pdf using tagui, how i can do it?

**Comment by kensoh** [comment]
Sorry @supu4u I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Yes it is possible, there are a few ways of doing it. First way is copying all PDF contents and use `pdf_contents = clipboard()` to get raw text of PDF. Then use JavaScript code to extract using string processing. For eg this workflow - https://github.com/aimakerspace/TagUI-Bricks/tree/master/WHO-Report

Another way is to use visual automation with read step to do OCR by providing a region to extract the info (if the position of the text is always in the same position). You can also use an anchor image to do `hover` step, then `mouse_x()` and `mouse_y()` to get the coordinates, before you calculate another region relative to this anchor image match.

Other ideas can be after finding anchor image, use `hover` to move mouse to certain position, `mouse down` then `hover` to the right then `mouse up` then `keyboard [ctrl]c`, then get the value from `clipboard()`. This is mimicking how a human user manually sees and copy out the data.

For accuracy, it depends on font type and font size. You can try zooming into the PDF so that a larger text can be processed by the OCR. TagUI uses Tesseract v3 OCR as part of SikuliX engine. If further accuracy is required for OCR, most likely you'll need to involve other online OCR services using api step, or consider other software solutions specially designed for data extraction from PDF.

Closing issue for now but please lemme know if you have any input or question.
