### ISSUE TITLE
TagUI chrome extension does not capture the input to aliyun.com for username and password

### ISSUE THREAD

**Issue by Alibner** [kelaberetiv/TagUI#880]
I can't login to aliyun.com using tagui, it always prompts me that I cannot find the elements on the page, as follows:

```
type //*[@id="fm-login-id"] as [clear]username
ERROR - cannot find //*[@id="fm-login-id"]
```

```
https://account.aliyun.com/login/login.htm?oauth_callback=https://usercenter2.aliyun.com/home

// click //div[@data-spm-click="gostr=/aliyun\;locaid=login"]

type //*[@id="fm-login-id"] as [clear]username
type //*[@id="fm-login-password"] as [clear]password

click button

wait 5

snap page to results.png
```

And I found that the TagUI chrome extension does not capture the input to aliyun.com for username and password

**Comment by kensoh** [comment]
Hi @Alibner sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

This is because the webpage uses frames. Some websites uses frames to embed webpages into parent webpage. In order to access frames, you will need to use the frame step - https://tagui.readthedocs.io/en/latest/reference.html

![frame](https://user-images.githubusercontent.com/10379601/100303999-cb965300-2fd8-11eb-8c87-623e7a9ac637.png)

The Chrome extension is built on another open-source project and has a limitation of not able to record frames information. Also, this webpage uses quite complex frame structure. I recommend using visual automation instead for this scenario, that will be easier to write the automation and make changes later on if needed.

In visual automation, you provide image snapshots of UI elements for TagUI to click and type on, instead of relying on web identifiers. See this example - https://github.com/aimakerspace/TagUI-Bricks/tree/master/IRAS-Notice-OCR

Closing issue for now but please lemme know if any input or question.

**Comment by kensoh** [comment]
Adding on, if you know any open-source web recorder that is good at capturing frames information and is much better than the TagUI chrome extension, lemme know. So that I can review to see if it can be modified to record TagUI scripts.

TagUI chrome recorder is originally based on this open-source project - https://github.com/ebrehault/resurrectio

**Comment by Alibner** [comment]
hi @kensoh , thank you very much. After reading, I think what you said is very good. The frame webpage is beyond my expectation, So I will try it. In addition, I wish you and your family good health.

**Comment by kensoh** [comment]
Thank you @Alibner for your reply and good wishes. I appreciate it!
