### ISSUE TITLE
PaddleOCR+tagUI

### ISSUE THREAD

**Issue by roughsoft** [kelaberetiv/TagUI#881]
PaddleOCR is very popular our solution.
If we could integrate PaddleOCR and tagUI,it would increase the accuracy of OCR,special the chinese language.
https://github.com/PaddlePaddle/PaddleOCR

**Comment by kensoh** [comment]
Sorry @roughsoft, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Thanks for sharing with me about PaddleOCR! I'll give a miss for now because it involves adding Python dependency.

There's some OCR support for Chinese now - https://github.com/kelaberetiv/TagUI/issues/832. Closing issue for now, to visit the idea again in future.
