### ISSUE TITLE
Many execution Instances - might be possible by separating into different users

### ISSUE THREAD

**Issue by fuzaro** [kelaberetiv/TagUI#891]
Hi @kensoh

I hope you are doing well.

Can you help me ?

Is possible execute more than one instance of TagUI simultaneously on a linux server? I use xvfb to create many desktop enviroments, and this works well and I need to scale up.

I think if doing this the logs and execution controls maybe not create for this.
If so, I can duplicate a source directory and call different executable or they will create problem in executors level like sikulix and other executors?

Thanks in advance

**Comment by kensoh** [comment]
Thanks for asking Luiz.. Situation with my mum's health condition is still cloudy, but I've gone back to work at AI Singapore.

I have not tried that before but it should work in theory. To be sure, create separate folders for tagui under different user accounts so that different threads will not accidentally write into each other, and that a user scription completion will not accidentally kill a Chrome process for another user. For SikuliX, the internal TagUI logs are kept within tagui\src\tagui.sikulix folder, but I'm not sure if it can do multiple XVBF screens concurrently.

You can try out and ping me here with errors that you are facing, if you run into any problems.

**Comment by kensoh** [comment]
Closing issue for now, but please ping me if you run into any issue or question!

**Comment by kensoh** [comment]
Hi Luiz @fuzaro, I've sent you a message on LinkedIn on discussion on TagUI Foundation.

Sending a note here in case you are not regularly using LinkedIn. And Happy 2022 !
