### ISSUE TITLE
Cannot find image on screen - image snapshot provided doesn't match screen

### ISSUE THREAD

**Issue by tlm2c09** [kelaberetiv/TagUI#896]
Hi Ken,
Firstly, I want to thank you for developing this useful tool. It is simple and easy to begin with.

I am working with TagUI integrating with Sikuli on my Mac 2014 to click on some images. I tried to click on the outlook icon in the dock but it showed the message 'ERROR - cannot find /Users/tuongle/PycharmProjects/tag_ui_python/src/test/lib/outlook.png on screen'
I already put the .tag file and the .png files into the same folder but still no luck.
Also I tried with the absolute path to the image but the same error displays.
<img width="1056" alt="Screen Shot 2020-12-23 at 07 19 56" src="https://user-images.githubusercontent.com/52133495/102945428-424b4100-44f0-11eb-869f-926bcdd2f5a6.png">
<img width="869" alt="Screen Shot 2020-12-23 at 07 19 34" src="https://user-images.githubusercontent.com/52133495/102945438-47a88b80-44f0-11eb-809d-f1b3e8df0a5f.png">
Could you please help me on this?
Thank you

**Comment by kensoh** [comment]
Hi Tim, thanks for your appreciation. From your screenshot, it looks like the outlook icon looks different from what is in the dock. The dock has some red numbers showing number of emails but not your image snapshot. In order to find a match, the given image must match the target UI element closely.

Can you try doing `[cmd][shift]4` to capture an image of the outlook icon on the dock, but you capture without including the red circle and number? If you have an image editor, you can also clip away the red number part and make it transparent. That can also be used as a match as transparent parts of a .png file will be ignored during matching.

Let me know how that goes!

**Comment by tlm2c09** [comment]
Hi Ken,

After I cleared all the red numbers on the outlook icon (as in the screenshot below), it still showed the error message that 'cannot find image on screen'.
I also tried with other images as well but no luck. Below are others I tried with:
<img width="913" alt="Screen Shot 2020-12-24 at 06 37 53" src="https://user-images.githubusercontent.com/52133495/103044301-a20a2080-45b2-11eb-9592-29cf7dee76c4.png">
<img width="840" alt="Screen Shot 2020-12-24 at 06 35 55" src="https://user-images.githubusercontent.com/52133495/103044312-a6363e00-45b2-11eb-9895-b6dc20b0a682.png">
<img width="60" alt="Screen Shot 2020-12-24 at 06 37 58" src="https://user-images.githubusercontent.com/52133495/103044314-a8000180-45b2-11eb-9361-e593176f0232.png">

**Comment by tlm2c09** [comment]
In addition, when I opened Sikuli, took screenshots and run, clicking on images worked.

**Comment by kensoh** [comment]
I'm guessing could it be due to MacBook Pro Retina display? I have encountered users having problems when using the screenshot capture. If it is retina display, the image captured will be at much higher resolution than it actually is and won't match. Can you see if the solutions / workarounds at below issue works for you?

https://github.com/tebelorg/RPA-Python/issues/170#issuecomment-715421460

**Comment by tlm2c09** [comment]
> I'm guessing could it be due to MacBook Pro Retina display? I have encountered users having problems when using the screenshot capture. If it is retina display, the image captured will be at much higher resolution than it actually is and won't match. Can you see if the solutions / workarounds at below issue works for you?
> 
> [tebelorg/RPA-Python#170 (comment)](https://github.com/tebelorg/RPA-Python/issues/170#issuecomment-715421460)

@kensoh thank you very much. After changing the PPI from 144 to 72, it worked for me now.

**Comment by kensoh** [comment]
Thanks @tlm2c09! In future when I learn of better solution I'll implement it into the tool. Have fun!

**Comment by marcelocecin** [comment]
for me the solution to reduce the PPI to 72 did not work

**Comment by kensoh** [comment]
Hi Marcelo, I think somehow I missed your message. Can you tell me more if this is working now?

**Comment by marcelocecin** [comment]
hi Ken, sorry for the delay
I believe that there was an error related to the background of the image and not to the resolution
the problem was solved, thank you

**Comment by kensoh** [comment]
Hi Marcelo, I see.. ok got it! For background, some image editing tool can let you select and remove background to become transparent. That way it can make an icon work better when the background colour changes.
