### ISSUE TITLE
Excel Automation, updating specific cell in Excel file - 2 ways to do it

### ISSUE THREAD

**Issue by Barunbari777** [kelaberetiv/TagUI#904]
Hi,

Please let me know if Excel automation is feasible?
I am trying to update specific cell data in Excel file from PDF, but unable to mention in code. (using Python integration)

Please let me know if Tagui has all the capability of Uipath? (Like entering multiple data in Excel file) 

Thanks,
Barun

**Comment by kensoh** [comment]
Hi @Barunbari777 yes it is feasible. There are 2 ways to do it. The first way is you mentally convert your thinking process just like how you do it manually in Excel, opening the file, choosing the cell, typing into it etc. For eg, below for macOS Excel -

```
cell = 'b2'
value = 'some value'
run open /Users/kensoh/Desktop/transactions.xlsx
wait 3 seconds
keyboard [ctrl]g
click reference.png
keyboard [cmd]a
keyboard [delete]
keyboard `cell`[enter]
keyboard `some_value`[enter]
```

**reference.png**

![reference](https://user-images.githubusercontent.com/10379601/103789156-a5a1ab00-507a-11eb-800d-ec37389d668e.png)

**Comment by kensoh** [comment]
The first way is good for users who are familiar with Excel but not good at programming. The second way is make use of TagUI Python integration to do it. You can write Python code directly in TagUI script -
https://tagui.readthedocs.io/en/latest/advanced.html#writing-python-within-flows

By using this method, you can make use of Python packages like https://openpyxl.readthedocs.io/en/stable/ to read and write Excel files programmatically. Users who ok to do Python programming can consider using this way.

Python users can also choose to directly use RPA for Python to do it.
That's a wrapper for TagUI - https://github.com/tebelorg/RPA-Python

**Comment by kensoh** [comment]
TagUI of course does not have all capabilities of UiPath, it is a mature enterprise RPA tool.

But TagUI has enough flexibility and ease-of-use to automate many scenarios, and could be much faster than UiPath in developing and updating the automation. For eg of ease-of-use - https://github.com/kelaberetiv/TagUI/issues/898#issuecomment-754177698

Also, UiPath Community Edition users, I heard that using the free community forum is not a good channel to get answers. Because other users also do not know the answers to the specific automation scenarios you have.

If you are using TagUI, you can ask any implementation questions here and where possible we'll try to answer within 24 hours. And people answering are directly the people who created the tool. [Here's a slide deck](https://drive.google.com/file/d/1pltAMzr0MZsttgg1w2ORH3ontR6Q51W9/view?usp=sharing) on some other useful info on TagUI.

**Comment by kensoh** [comment]
Adding on, below is an example of using method 1, I was giving training to some users, but it is not viable to do using method 2 programming because it is an SME firm that does not have strategic need to hire people with programming experience. And most SMEs do not have staff with programming experience or have the business need to learn programming.

[**Video of below example on LinkedIn**](https://www.linkedin.com/posts/kensoh_merging-data-from-2-excel-spreadsheets-using-activity-6752663085305229312-W6yR). This may look long, to have to map the manual process of merging spreadsheets into step by step actions. But it is doable for someone without any programming background, and not want to explore other software options for merging Excel spreadsheets. Also, after the initial template is done, users can use the modular design to break up the different sections into reusable components. And also make use of [object repositories csv](https://tagui.readthedocs.io/en/latest/advanced.html#object-repositories) to store settings.

```
// open file using run step and open command (for macOS)
// for Windows, should be run start C:\XXX\YYY.xlsx
// you can also use dclick on the desktop file icon,
// or use keystrokes to search for file to open
run open /Users/kensoh/Desktop/MYOB.xlsx
rclick excel.png
keyboard MYOB[enter]

// use keystrokes to go to cell
echo [ use keystrokes to go to cell ]
keyboard [ctrl]g
click reference.png
keyboard [cmd]a
keyboard [delete]
keyboard b2[enter]

// select and copy cells data
echo [ select and copy cells data ]
keyboard [cmd][shift][right]
keyboard [cmd][shift][down]
keyboard [cmd]c

// open Template spreadsheet and paste data
echo [ open Template spreadsheet and paste data ]
run open /Users/kensoh/Desktop/Template.xlsx
rclick excel.png
keyboard Template[enter]
keyboard [ctrl]g
click reference.png
keyboard [cmd]a
keyboard [delete]
keyboard b2[enter]
keyboard [cmd]v

// go to next row to prep for pasting
echo [ go to next row to prep for pasting ]
keyboard [cmd][down]
keyboard [down]

// copy data from the XERO spreadsheet
echo [ copy data from the XERO spreadsheet ]
run open /Users/kensoh/Desktop/XERO.xlsx
rclick excel.png
keyboard XERO[enter]
keyboard [ctrl]g
click reference.png
keyboard [cmd]a
keyboard [delete]
keyboard b2[enter]
keyboard [cmd][shift][right]
keyboard [cmd][shift][down]
keyboard [cmd]c

// paste and save Template spreadsheet
echo [ paste and save Template spreadsheet ]
run open /Users/kensoh/Desktop/Template.xlsx
rclick excel.png
keyboard Template[enter]
keyboard [cmd]v
keyboard [cmd]s

// copy row count to clipboard
echo [ copy row count to clipboard ]
keyboard [cmd][down]
keyboard [down]
keyboard =row()[enter]
keyboard [up]
keyboard [cmd]c

// get row count text from clipboard()
// and convert to number for use
total_rows = parseInt(clipboard())

// delete the dummy row count value
echo [ delete the dummy row count value ]
keyboard [delete]

// minus 1 to exclude header row
// minus 1 to exclude extra blank row
total_rows = total_rows - 2

// go to starting cell to enter running number
echo [ go to starting cell to enter running number ]
keyboard [ctrl]g
click reference.png
keyboard [cmd]a
keyboard [delete]
keyboard a2[enter]

// loop to auto-enter some running number
echo [ loop to auto-enter some running number ]
for row from 1 to total_rows
    keyboard T0000`row`[enter]

// save the Template spreadsheet
echo [ save the Template spreadsheet ]
keyboard [cmd]s
```

**Images used for the automation**
excel.png
![excel](https://user-images.githubusercontent.com/10379601/103835588-9265fe00-50c1-11eb-920c-c9fea43df39c.png)

reference.png
![reference](https://user-images.githubusercontent.com/10379601/103835592-96921b80-50c1-11eb-82c2-495eb46cc9d6.png)

**Sample Excel spreadsheets used**
[Template.xlsx](https://github.com/kelaberetiv/TagUI/files/5778832/Template.xlsx), [MYOB.xlsx](https://github.com/kelaberetiv/TagUI/files/5778852/MYOB.xlsx), [XERO.xlsx](https://github.com/kelaberetiv/TagUI/files/5778853/XERO.xlsx)

**Comment by kensoh** [comment]
Closing issue for now, until chancing on the same question again, then do something polished for TagUI-Bricks demos
