### ISSUE TITLE
If statements base on whether an image is present on the screen - yes doable

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#915]
Hi there !
is it possible to create some way to check if the image is on the screen, and if not, execute another command?
example:
```javascript
if !exist(some-element.png)
      https://tagui.readthedocs.io/ 
```

**Comment by kensoh** [comment]
Hi Marcelo, thanks for raising this question! Yes this is doable, for example the following will open Google page if some Zoom window is not present on the screen. Do note that `exist()` will check until the default timeout of 10 seconds before returning whether something is found. `present()` will right away return result if something is not already there.

And, most likely, what your example didn't work is because of the indentation. In TagUI v6 onwards, you can use tab or a fixed number of spaces (eg 2, or 4), to let it know that you are having an indented block of code. Let us know if you have further questions around this topic :)

```
if !exist('zoom_window.png')
    https://www.google.com
else
    http://yahoo.com
```

PS - below is the zoom_window.png I used to detect whether the Zoom window is visible on my screen
![zoom_window](https://user-images.githubusercontent.com/10379601/105971281-4e18bd00-60c5-11eb-81a3-63f35f4d14df.png)

**Comment by kensoh** [comment]
Adding on, more on how this solution is found on this YouTube video - https://youtu.be/M4JbL-Mr93Y

**Comment by marcelocecin** [comment]
thanks @kensoh !
