### ISSUE TITLE
How to speed up multiple flows automation time involving computer vision?

### ISSUE THREAD

**Issue by NeneBen** [kelaberetiv/TagUI#917]
I  have created scripts for a Point of Sale device. I went ahead and created a batch file to run all the scripts i created.
Now the my problem is the there a too much wait time for each line in the batch file to run.  Tagui takes too much time to begin each individual script. The screen sometimes times out as there is no action or click.
Below is a sample script. It takes tremendous amount of time before the scripts starts clicking on the UI elements. More than about 30-45 seconds before each scripts runs

Is there a way i can speed up  my automation?

repo = 'c:/POSAutomation/FOH/repos/'
click `repo`regularBeer.png
click `repo`checkIdOk.png
click `repo`regularBeer.png

click `repo`premiumBeer.png
click `repo`dineIn.png

click `repo`orderPaneRegularBeer.PNG

click `repo`payExact.png

**Comment by kensoh** [comment]
Hi @NeneBen the delay is due to loading of computer vision engine into memory. Likely your computer is not a very new model, because my 2014 macOS takes under 20 seconds to load, and on newer computers it takes a few seconds.

The slowness happens also because each time you run a script, the computer vision engine will be loaded fresh into memory. You can try the following way by using the `tagui` step to run all your scripts at one go. So the loading only happens once instead of 10 times. Each flowx.tag below is a workflow like your example above.

So doing `tagui run_all.tag` will run all the 10 flows with only loading of computer vision engine once. Doing this will speed up total run time considerably. There are also some internal design by default to slow down each individual step to mimic human user speed. That can be changed but not recommended. Because if automation happens faster than a normal human user, some apps might detect this and suspect that the user is a robot and block the IP or account.

**run_all.tag**
```
tagui flow1.tag
tagui flow2.tag
tagui flow3.tag
tagui flow4.tag
tagui flow5.tag
tagui flow6.tag
tagui flow7.tag
tagui flow8.tag
tagui flow9.tag
tagui flow10.tag
```

**Comment by kensoh** [comment]
Adding, this video shows more details on the solution - https://youtu.be/zKKiepeBJLc

**Comment by NeneBen** [comment]
CMD /C tagui C:\POSAutomation\FOH\Tests\Other\3Pointer.txt report
CMD /C tagui C:\POSAutomation\FOH\Tests\Other\quesarito.txt report

here is two lines from my batch file.

How do i write it in the format you showed above. FYI am using the old version of tagui

**Comment by kensoh** [comment]
The format is create a new file run_all.tag with following lines. Then rename the existing text scripts to .tag extensions.

```
tagui 3Pointer.tag
tagui quesarito.tag
```

After that you can try running with `tagui run_all.tag report`.

For the new version it is running with `tagui run_all.tag -report`

If the old version you have doesn't support the tagui step yet, you can get the latest from the Download v6.14 link on the main page. On the same page you will also see some differences for v6. https://github.com/kelaberetiv/TagUI

Lemme know if you run into any problems!

**Comment by kensoh** [comment]
Adding on, more details on this solution and the train of thoughts https://www.youtube.com/watch?v=zKKiepeBJLc

**Comment by kensoh** [comment]
Closing issue for now but do ping us if anything!
