### ISSUE TITLE
Automation hangs after Chrome is launched - company IT network policy issue

### ISSUE THREAD

**Issue by joginderrohilla** [kelaberetiv/TagUI#921]
Issue Description: When I try to hit the flow file using CLI, it just launches the chrome and stops after that.

I am just tries to launch the website, It did not work. My old flows are also not working.

Flow file:
![image](https://user-images.githubusercontent.com/60636357/106231825-95fc2900-6218-11eb-95c1-9979813bf5e5.png)

![image](https://user-images.githubusercontent.com/60636357/106231650-2dad4780-6218-11eb-84bd-dae6e1283cbb.png)

It might be some system issue, could you please let me know how to debug this?

**Comment by ruthtxh** [comment]
Hello @joginderrohilla 

Just to check, previously you have ran TagUI before and it works fine? Since your last successful run, did you change any dependencies from the source codes or ran any major system upgrade?

If you are available in about 30mins time at 4PM (SGT) today, you can join this week's live Q&A session where we can attempt to troubleshoot over screen sharing. Zoom Meeting URL - https://nus-sg.zoom.us/j/82049782250?pwd=WTRZcmRIWXU2OWJEYmt1UWR1MUVYUT09

Thanks!

**Comment by kensoh** [comment]
Hi @joginderrohilla thanks for joining the call earlier. To summarise, from controlling your laptop earlier on the Zoom meeting and directly tracing the root cause, we found that somehow your company IT network policy perhaps has a new change in proxy access. That's why the `curl` command cannot return response from both external and localhost endpoint.

This access is required in order for TagUI to connect to Chrome browser through a direct Web Socket connection. The next steps as you have rightly said is contacting your IT team to open up certain proxy access, at least to localhost. Loop us in on the outcome!

**Comment by kensoh** [comment]
Adding on, this is the video recording for reference - https://youtu.be/rgDUu0D3Ws4

**Comment by joginderrohilla** [comment]
Thanks Ken for Debugging this. I worked with IT team to resolve this, But unfortunately the policy cant be rolled back since TagUI is my personal interest. Seems like I have to plan to buy a new laptop :). Closing the issue.

**Comment by kensoh** [comment]
No probs @joginderrohilla ! Fyi am working on a cloud-based RPA, see this POC v1. You can run TagUI on this Colab notebook on your computer or phone. But this only runs on Linux due to Colab only offering Linux servers. Will be doing a POC for GitHub Actions which can provision Windows and macOS servers in addition to Linux.

**Comment by kensoh** [comment]
This is the Colab notebook URL and details - https://github.com/kelaberetiv/TagUI/issues/913
