### ISSUE TITLE
Fatal: No such file or directory; did you install phantomjs? - resolved now

### ISSUE THREAD

**Issue by TJ-888** [kelaberetiv/TagUI#922]
Getting that phantomjs error when trying to run the samples flow tag. Has followed the suggestion mentioned on the following link also but still got that error:

https://github.com/kelaberetiv/TagUI/issues/601

**Comment by kensoh** [comment]
Hi @TJ-888 the issue #601 deals with macOS security policy. The error message you seen above is more of the PhantomJS component not found. For TagUI, I package all the required components into a zip file so that you can unzip and run.

Can you try downloading using the steps here instead from the GitHub homepage Code -> Download zip link? (that one only downloads TagUI source code without any of the components required for it to run).

https://tagui.readthedocs.io/en/latest/setup.html

If that still does not work, can you try on your personal laptop to see if it helps? Some company IT anti-virus policy may accidentally mistake PhantomJS as some unrecognised app and blocks it from running as if the file is missing. Let me know how it goes!

**Comment by kensoh** [comment]
More context on the train of thoughts at this video - https://www.youtube.com/watch?v=D9sjpSHLD3Q

**Comment by TJ-888** [comment]
Hi @kensoh ,
Thanks for the quick reply. I should have given you more context about my environment for this issue:
1. It is on my personal Mac book actually, still on **High Sierra** though
2. I did follow the steps mentioned in the github but not just downloading the code as you said:
https://tagui.readthedocs.io/en/latest/setup.html
3. I could see the phantomjs package as part of the tagui package
4. When I searched around for this issue, I came across issue #601 that mentioned about Mac didn't trust to open any application unless we are ok with it. I meant for the following steps:
_

> From macOS Finder, go to the folder where you unzipped and installed TagUI.
> 
> Go to src --> phantomjs --> bin folder. Right-click phantomjs icon and click Open.
> 
> If a macOS prompt appears to ask whether to open the application because it is untrusted and downloaded from the internet, click Open to add the app to list of trusted apps.
-
Hence,  I thought that  I should have given a try and see if it could fix my issue but it didn't.

 FYI, I did try to uninstall and reinstall again today but I still get the same error.
Any other thoughts?

Thanks,

**Comment by kensoh** [comment]
Hi @TJ-888, thanks for sharing these details! I haven't come across such a situation reported by other users.

Can I check with you if you have some time at 3pm Singapore time this Thursday? There's a weekly Live Q&A session where we could look deeper into what's going on in your Mac environment. I can't think of any possible cause and there also isn't any log that I could get from you now because TagUI didn't even got started.

Here's the link to the Zoom meeting invite - https://github.com/kelaberetiv/TagUI/issues/914#issuecomment-770161061

Copying my team-mate @ruthtxh

**Comment by lookang** [comment]
I managed to install and run tagUI on a MacOS
[https://weelookang.blogspot.com/2020/12/managed-to-get-tagui-work-on-mac.html](https://weelookang.blogspot.com/2020/12/managed-to-get-tagui-work-on-mac.html)
please check tagUI is on your desktop, i tried to copy to another folder and it didn't work.

**Comment by TJ-888** [comment]
Hi @kensoh , thanks for the reply and offer to have live session. However, the time difference could be a challenge for me :). Let me try the suggestion from lookang first. I will keep you posted about the result.

**Comment by kensoh** [comment]
Sure @TJ-888, in the meantime, can you tell us where you unzip the tagui folder? I don't think this could have any impact why PhantomJS cannot be found, but checking just in case it is some unusual folder which no other users have tried before.

**Comment by TJ-888** [comment]
Hi @kensoh ,  finally, I was able to manage and resolve it. I looked at the notes from @lookang  too and redid the installation. 
What puzzled me is I think I did the same steps before unless I missed something.
In any case,  I was able to pass the phantom.js error but got the Library error. 

I did manage to overcome this also after **disabling** the **SIP** and then install openssl and do the link as follow:
1. brew install rbenv/tap/openssl@1.0
2. ln -sfn /usr/local/Cellar/openssl@1.0/1.0.2t /usr/local/opt/openssl

Thanks for the support and thanks to @lookang also!
