### ISSUE TITLE
No reaction after running tag file several times if kill it halfway - some ideas

### ISSUE THREAD

**Issue by kan-cjis** [kelaberetiv/TagUI#929]
Hi 
I was trying to run tag file in pycharm by python code
`os.system("tagui /Users/kkkkaaa/PycharmProjects/pj1/test.tag ")`
The tag file inside is opening a url and some web automation. 

But I forgot to add other s code in python, so I stop the execution , add back the code and close all cmd file. And run it again, and then the tagui become no reaction, cmd opened, START to listen input, but it become no input. The cmd file is keep opening ,but chrome opened.

This can happens randomly, the workaround is restart the windows

**Comment by kensoh** [comment]
Hi @kan-cjis, when you try to kill the process halfway it might not exit cleanly. To do that, you can add in this step -

```
os.system('path_to_tagui_folder/src/end_processes')
```

The end_processes command on macOS/Linux, and the end_processes.cmd batch file on Windows, will help to clean up any remnant processes in memory, if you try to kill TagUI halfway during running.

Also, I've created this personal side project called RPA for Python, it is a wrapper around TagUI that exposes the RPA capabilities to the Python user. To install it, simple `pip install rpa`. That might be easier for you, since your starting point is in Python already, instead of trying to call `tagui` command from Python environment.

More info - https://github.com/tebelorg/RPA-Python

**Comment by kensoh** [comment]
Adding on for more context and details, here's a video - https://www.youtube.com/watch?v=5JBpzarYBco

**Comment by kensoh** [comment]
Backfilled with a remake video for completeness - https://www.youtube.com/watch?v=lT8oyXZX58U

**Comment by kensoh** [comment]
Closing issue for now, but do ping us if anything!
