### ISSUE TITLE
Save Chrome user profile for subsequent automations - some checks and ideas

### ISSUE THREAD

**Issue by gilgoldman** [kelaberetiv/TagUI#930]
It seems that TagUI opens a new instance of Chrome on Windows 10, which requires a login and changing language (in my case, google defaults to Czech).
This results in all flows breaking unless I manually (and very quickly) log in to my Google account while the flow waits... which kind of beats the purpose, no?

Any way to settle this? Did I mess up the installation?

**Comment by kensoh** [comment]
Hi @gilgoldman, TagUI will always run Chrome with a special user profile just used by TagUI. The specific user profile directory is tagui/src/chrome/tagui_user_profile. So login settings to websites and other user information for the TagUI automations will be saved here.

Some ideas to try - 
1. Look through the setup steps here to reinstall to see if it helps - https://tagui.readthedocs.io/en/latest/setup.html
2. For above step, try installing to another folder. Usually c:\tagui works, but you could also try putting it on your desktop
3. Try open command prompt as administrator to make sure the reason is not due to insufficient folder write permissions

Let me know how it goes! If there is still no progress, see if you can join us at the weekly live Q&A call coming Thursday?
The Zoom meeting link can be found here at this Q&A index page - https://github.com/kelaberetiv/TagUI/issues/914

**Comment by kensoh** [comment]
This is a video recording of more contextual details on above ideas and some tips - https://youtu.be/SIL8Atm_-vo

**Comment by gilgoldman** [comment]
Hi Ken,

Thanks for the video and the recommended steps! 
Turns out it was a weird write permissions issue. All fixed now - thanks again!

**Comment by kensoh** [comment]
Oh great, thanks @gilgoldman for updating back that it works now! Have fun using the tool :)
