### ISSUE TITLE
Weird behavior: cannot click on an element - centre of that element is not clickable

### ISSUE THREAD

**Issue by Kenneth-tangjw** [kelaberetiv/TagUI#931]
Hi Tagui team, 

Just want to say that I am a huge fan of Tagui and its ease of use. It has helped me in collating data required for my projects. 

Issue:
I was trying to collate the list and addresses of libraries in Singapore (via URL: https://www.nlb.gov.sg/visitus.aspx ) 
when I encountered a strange issue for this particular entry: 
**"National Library / Lee Kong Chian Reference Library"** 

I am unable to get tagui to click this on this particular entry so that it could be redirected to its respective library page (https://www.nlb.gov.sg/VisitUs/BranchDetails/tabid/140/bid/329/Default.aspx?branch=National+Library+%2f+Lee+Kong+Chian+Reference+Library)  
All other entries works flawlessly with the Xpath method. 

I have tried trouble shooting with the following codes: 

`click (//*[@class="nestedBranchList"])[18]//a`
`click //*[@id="float_left"]/ul/li[18]/a`  (Xpath)
`click /html/body/form/div[4]/div/div[2]/div/div[3]/div[1]/div/div/div/ul/li[18]/a` (Full Xpath)  

Might there be something wrong with the site or in the manner I am doing? 

Thanks in advance! 

Best regards
Kenneth

**Comment by kensoh** [comment]
Hi Kenneth, thanks for your encouragement!

Indeed this is a very rare issue. Whenever you ask TagUI to click on something, as a form of best practice to simulate user's clicking action, it will form the rectangle boundary of the item and click directly at the centre. However, in this case, clicking directly in between the 2 lines of text for that link actually clicks nothing.

![nlb](https://user-images.githubusercontent.com/10379601/107154247-db54ef00-69ac-11eb-8a2f-f010d4e924d3.png)

One workaround is to use computer vision method, by capturing a snapshot of the link and use `click link_image.png`. That will work. However, it will add an additional few seconds of start-up time to load the computer vision engine. Thus, below would be another way to do this without using computer vision.

```
https://www.nlb.gov.sg/visitus.aspx
total_branches = count('//*[@class="nestedBranchList"]')

for branch from 1 to total_branches

    // special handling for the unique branch
    if branch equals to 18
        hover (//*[@class="nestedBranchList"])[`branch`]
        dom document.evaluate('(//*[@class="nestedBranchList"]/a)[18]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click()
    else
        click (//*[@class="nestedBranchList"])[`branch`]

    // do what is needed for the branch info page
    show librarytitle

    // go back to the starting page to do the next item
    https://www.nlb.gov.sg/visitus.aspx
```

What happens is above falls back on the older way TagUI clicks on something, which is initiating the click() method directly on the web element. This is usually not the best way because JavaScript events won't catch it and websites may behave differently compared to when a normal user clicks on the item.

This is a video of the troubleshooting process fyi with more contextual details -
https://www.youtube.com/watch?v=tRMxpHHt7Kk

Have fun!

**Comment by ruthtxh** [comment]
Hello @Kenneth-tangjw 

To add on, noticed there's a "Decrease font size" button at the top of the page. A workaround for what @kensoh mentioned above would be to first decrease the font size so the text is a single line

![image](https://user-images.githubusercontent.com/40910744/107169363-a1113f00-69f8-11eb-85c8-0930fe7d0af3.png)

click decreaseFont
click decreaseFont
click decreaseFont
click //*[@id="float_left"]/ul/li[18]/a

**Comment by kensoh** [comment]
Omg @ruthtxh, that's a brilliant idea!

That is the official solution for this scenario I would think. No need hacks, and easy to understand 👏🏻👏🏻

**Comment by Kenneth-tangjw** [comment]
Cool! Thanks both @kensoh @ruthtxh .. 
Will it work for all instances without the zoom in and out options?
[ctrl][-]

**Comment by kensoh** [comment]
Oh you might have seen some of the examples here - https://github.com/aimakerspace/TagUI-Bricks

If the Chrome zoom % is not at 100%, what happens is when TagUI tries to click on (400,200), the click will land on some other random UI element that is not where you are planning to click on.

For eg when I tried below, at 50%, the typing works but the clicking to search does not work. It probably landed elsewhere.
```
https://google.com
type q as rpa
click Google Search
wait
```

![50_percent](https://user-images.githubusercontent.com/10379601/107193373-be123600-6a29-11eb-8804-91d87953533c.png)

**Comment by Kenneth-tangjw** [comment]
I see! Thank you Ken!
