### ISSUE TITLE
How to declare a global variable? - by design all variables accessible anywhere

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#938]
hello
is it possible to declare a global variable where when executing another .tag within another, the second .tag accesses that variable?
thank you !

**Comment by kensoh** [comment]
Hi Marcelo, of course! As part of the focus on reusability and modularity, you can do something like below -

**master_flow.tag**
```
a = 1
tagui flow1.tag
echo `b`
tagui flow2.tag
echo `c`
```

**flow1.tag**
```
echo `a`
b = 2
```

**flow2.tag**
```
c = b + 1
```

**output of tagui master_flow.tag -nobrowser**
```
1
2
3
```

Note - I know for programmers this may not be the best design because they may prefer having local and global variables separated. But for the fastest development speed for the general user, I opted for this design where variables are shared. Also, within a sub flow you can further call other flows.

**Comment by marcelocecin** [comment]
hi @kensoh 
I was in doubt and before testing I preferred to open the ticket
very good !
will save some lines of programming all these features !
thank you very much !

**Comment by kensoh** [comment]
Adding on Marcelo, a video with demo of above flows for other users to refer -

https://www.youtube.com/watch?v=9FvOLnob6j8

**Comment by kensoh** [comment]
Adding on, this design optimises for most users' usage patterns where global and local scope doesn't matter. So, implementing this way makes it the shortest time to get a RPA workflow up and running.

If for some reason, a power user or hardcore programmer wants to strictly force the separation of global and local scope, he or she can do so by naming the variables accordingly. For eg in the parent flow, he might put a `global_` prefix to all variables used, and in subflows he might put a `local_` prefix to the variables used. This way there is a clean separation.

With above design, most users are not burdened with extra work of being worried about scope every time a variable is used, while power users can still have scope separation if they wish to, by naming variables accordingly.
