### ISSUE TITLE
Combine excel files from different subfolders - can but hard for now, use macros?

### ISSUE THREAD

**Issue by zulradi** [kelaberetiv/TagUI#952]
Hi, I'm very new to Tagui and just picking things up from scratch. So one of my daily tasks is to combine excel files from different subfolders into a single spreadsheet. Can I use Tagui to automate this task? If so, can you show me how its done. Thanks in advance

**Comment by kensoh** [comment]
Hi @zulradi, I see.. I believe this should be something doable directly using Excel macros. And that should be the easiest fastest solution since everything happens within Excel spreadsheets. However, if you choose to still use RPA for this task,

It can be done in 2 ways in TagUI. First way is doing the traditional RPA way where you simulate opening the file to copy and paste into 1 final spreadsheet. It is doable but takes a long time to map out all the actions. The second way is if you are familiar with Python, you can use TagUI's Python integration to use Python package do it. More in below link -

https://github.com/kelaberetiv/TagUI/issues/904#issuecomment-755798861

There is a third way, but it is not released yet. We are adding Excel integration and a new step to work with Excel files. This would be very useful to do what you are trying to do. Should be out sometime in Q2. Now we are working on other features like MS Word Add-in, Excel Add-in, Google Docs plugin, to do RPA using those familiar software.

**Comment by zulradi** [comment]
Hi Ken, Thanks for the reply. I am going to try out with the traditional RPA method for now. Looking forward to the Tagui excel integration !

**Comment by kensoh** [comment]
Sure @zulradi ! When I met an accounting firm a couple of months ago, I also recommended the traditional RPA way. Because their team does not have Python user. Otherwise after you create automation, no one else in the company can use or edit it.
