### ISSUE TITLE
API call with authentication - try Python requests package cuz can't replicate

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#967]
I am trying to include basic authentication, but the call is not recognizing
```
api_config = {method:'POST', header:{'Authorization': 'Basic somecredential='}, body:{'id': 12345}};
api https://some.url
echo `api_result`
```
the result:
`Invalid User`

**Comment by kensoh** [comment]
Hi Marcelo, syntax from https://github.com/kelaberetiv/TagUI/tree/pre_v6#api is like below (square brackets for header).

```js
api_config = {method:'PUT', header:['Header1: value1','Header2: value2'], body:{'id':123,'pwd':'abc'}};
```

Can you try the following ideas?
1. Change your api_config to use [] for header
2. If it doesn't work, try some other API calls to see if they work
3. If you can't try other calls, see your API call works with https://www.postman.com

**Comment by marcelocecin** [comment]
hello Ken, the request on Postman is working normally
I changed the api_config, but the following error occurred:
```
SyntaxError: Expected token ']'

  phantomjs://code/apireq.tag.js:1499 in injectJs
  phantomjs://code/bootstrap.js:456
```

**Comment by kensoh** [comment]
Hi Marcelo, I try below dummy call with dummy header it seems to not throw error.

```
api_config = {method:'PUT', header:['Header1: value1','Header2: value2'], body:{'id':123,'pwd':'abc'}};
api https://reqres.in/api/users/2
echo `api_result`
```
```
{"updatedAt":"2021-03-14T12:52:04.946Z"}
```

I assume you cannot share the actual API call here correct?

Would be hard for me to troubleshoot because I don't have a way to replicate.

An alternative will be using the Python `requests` package. It's a popular package to do API calls - 
https://requests.readthedocs.io/en/master/

By using TagUI's Python integration you can access this package from TagUI script -
https://tagui.readthedocs.io/en/latest/advanced.html#writing-python-within-flows

**Comment by marcelocecin** [comment]
hi Ken
I ended up using python
thanks

**Comment by kensoh** [comment]
Thanks Marcelo, I'll look out for other users to report issue on api step and see if it is a case which I can get the full code to replicate and test.
