### ISSUE TITLE
Qt platform plugin "xcb" not found? - raised issue to PhantomJS and its creator

### ISSUE THREAD

**Issue by babintheuns** [kelaberetiv/TagUI#969]
I was logged into my Babin account to maintain my son's school website when I posted this;

I posted below as TetraGenius (just disclosure in case of confusion); So the original issue was resolved; see below. Thanks Ken for the quick response.

Executing the sample file 1_google.tag used to work fine but after some updates on Fedora:
tagui /home/theuns/TagUI_Linux/tagui/flows/samples/1_google.tag
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Available platform plugins are: phantom.

Reinstalling the application may fix this problem.
PhantomJS has crashed. Please read the bug reporting guide at
http://phantomjs.org/bug-reporting.html and file a bug report.

PhantonJS crashes on Fedora:
Operating System: Fedora 33 (Workstation Edition)
CPE OS Name: cpe:/o:fedoraproject:fedora:33
Kernel: Linux 5.10.22-200.fc33.x86_64
Architecture: x86-64

Already tried this:
I downloaded the newest version v6.14 of tagUI 
I tried various things such as creating symlinks etc and also replaced phantomjs as suggested here:
Troubleshooting macOS/Linux
If you see dyld: Library not loaded: overwrite tagui/src/phantomjs with contents of this zip

tagUi is stille not working on your examples in samples (or my scripts)

Any workarounds?

**Comment by TetraGenius** [comment]
It may have something to do with:
Building Qt for Static Linking: To use static linking, Qt must be built with the -static configuration option?
This message was displayed in QT_DEBUG_PLUGINS:
QFactoryLoader::QFactoryLoader() ignoring "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3" since plugins are disabled in static builds
This application failed to start because it could not find or load the Qt platform plugin "xcb".

**Comment by TetraGenius** [comment]
Also, maybe this approach will be better in the long run: https://bigbinary.com/blog/replacing-phantomjs-with-headless-chrome

**Comment by kensoh** [comment]
Hi @babintheuns thanks for raising this issue! Hi @TetraGenius thanks for adding on your inputs!

I've raised below issue to PhantomJS project and its creator to find out more - https://github.com/ariya/phantomjs/issues/15454

PS - Oh PJS has resumed active maintenance. For the time being, it is hard to pluck PJS out of TagUI because it uses PJS as the JavaScript execution engine behind all the UI automation capabilities. Although over time I write my own Chrome engine using WebDocket and DevTools protocol, and integrated with SikuliX, Python etc, the foundation is still PJS. At the point of creation, PJS offers a stable JS engine to run on various OSes. And users can unzip and run directly or do that programmatically, without having to install other programming languages such as NodeJS or Python etc.

---

Hi Ariya (@ariya), first off, I'm super excited to hear the news that you've joined @metabase as Chief Architect!!

We exchanged on emails a couple of years back (ken@tebel.org or ken@tebel.sg), and I've built my career since 2016 on the foundation of your contribution to the open-source community - PhantomJS. I've always put credit back to you and PJS (https://github.com/kelaberetiv/TagUI#credits / https://github.com/tebelorg/RPA-Python#about--credits)

I have a user @babintheuns who seems to have run into some problems after some updates in Fedora Linux.

May I check with you if you have heard of other PJS users experiencing this issue? Below are details of the error.

https://github.com/kelaberetiv/TagUI/issues/969

```
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Available platform plugins are: phantom.

Reinstalling the application may fix this problem.
PhantomJS has crashed. Please read the bug reporting guide at
http://phantomjs.org/bug-reporting.html and file a bug report.
```

**TagUI free and open-source RPA bustling ecosystem (possible because of you and PJS)**
![roadmap](https://user-images.githubusercontent.com/10379601/111152994-591fa200-85cc-11eb-8f3b-507bd4c565bb.png)

**Comment by kensoh** [comment]
In the meantime, want to add that searching for the error messages shows up some 'solutions', but I'm not the subject matter expert to advise whether they are suitable, because my Linux is not Fedora distribution to replicate / validate the issue.

**Comment by TetraGenius** [comment]
So I don't know if something else changed, but the error has resolved after I moved the tagui folder to my documents and restarted fedora. Maybe it was some issue with tagui running from a directory with limited permissions. 

Other users in other software who experienced the same error could resolve by creating symlinks or  setting: export QT_DEBUG_PLUGINS=1 
and running the script to see more detail. None of these seemed to work yesterday, but this morning after moving the tagui directory and a restart the issue resolved...

Sorry I don't have a clear idea of what transpired and thanks if  someone fixed it.

**Comment by kensoh** [comment]
Oh I see.. No probs! I'll just send a note over at PJS issue, and continue to look out if other users experience this :)
