### ISSUE TITLE
'type' command does not clear all selected text - for this case use keyboard step

### ISSUE THREAD

**Issue by tlm2c09** [kelaberetiv/TagUI#971]
Hi Ken,

So I am trying to create a script which is same with the [MS Word Letter](https://github.com/aimakerspace/TagUI-Bricks/blob/master/MS-Word-Letter/letter_flow.tag). However, in my case, when the script double-clicked on the word, and type texts, the original texts are not cleared.
I did try to add [clear] or [delete] but still the same.
![Capture](https://user-images.githubusercontent.com/52133495/111331898-eaae1300-86a3-11eb-8832-2f9f8829f385.PNG)
![Capture2](https://user-images.githubusercontent.com/52133495/111331905-ec77d680-86a3-11eb-8ee1-fa534fd54430.PNG)
Could you help on this?
Thanks!

**Comment by kensoh** [comment]
Hi @tlm2c09 thanks for raising this! Can you check 2 things -

1. If you have made Microsoft Word the app in the foreground first? By doing a click on the MS Word app or something? It could be you are trying to do a `dclick`, the first click ends up making MS Word in the foreground and the 2nd click ends up becoming a normal click instead. For MS Word, double-clicking on a word will select it entirely.

2. This is probably the real reason. From the example given it is doing a type page.png which types into the screen, versus above you are typing into the word --> which will just do a single click and type and void the selection in the previous dclick step. Try the following 2 ways which should be both work -

```
dclick first_name.png
type page.png as `first_name`
```

```
dclick first_name.png
keyboard `first_name`
```

PS - I've updated the MS Word example to use keyboard step instead so that it is not confusing

**Comment by kensoh** [comment]
Hi Tim, closing issue for now until further inputs!
