### ISSUE TITLE
SyntaxError: Unexpected token '/'

### ISSUE THREAD

**Issue by TetraGenius** [kelaberetiv/TagUI#973]
**// I run these two lines with no error:**
csv_file = 'search.csv'
echo csv_file
**// When I add this third line:**
load '+csv_file+' to lines

I get the error:
SyntaxError: Unexpected token '/'

  phantomjs://code/snap4.tag.js:1481 in injectJs
  phantomjs://code/bootstrap.js:456

The os is Fedora 33 and the examples of Ken work as it should.
The search.csv contains: 
s1,innovation
s2,judo
s3,gymnastics
and is attached as .txt file since github does not accept .csv
[search.txt](https://github.com/kelaberetiv/TagUI/files/6157100/search.txt)

**Comment by TetraGenius** [comment]
This code works:
csv_file = 'search.csv'
echo csv_file
load `csv_file` to lines
echo `lines`

**Comment by TetraGenius** [comment]
Expanding the code above also works:
array_1 = []
array_2 = []
csv_file = 'search.csv'
echo csv_file
load \`csv_file\` to lines
echo \`lines\`
array_lines = lines.split('\n')
for (n=0; n<array_lines.length; n++) 
 {
  items = array_lines[n].split(',')
  array_1[n] = items[0].trim()
  array_2[n] = items[1].trim()
  echo \`array_2[n]\`
  // r dir.create(`array_1[n]`) \\commented out for now
  echo \`array_1[n]\`
 }

**Comment by kensoh** [comment]
Hi Theuns Dirkse, oh I see! This is because the tutorial example in the rpa-sg.org website is based on v5 syntax.

In v6, there is a shift from using '+variable_name+' to `variable_name` for some of the TagUI steps, that may be the cause.

There is still 1 area of TagUI which isn't fully consistent yet. In conditions and for loops, variables are referred without backticks. But if I change it to use backticks and for text to be without quotation marks, it is not easy to get it right to map the condition accurately to JavaScript code to run. So that part is still a stale-mate.

**Comment by TetraGenius** [comment]
In github we need to escape the \` on the same key as ~ with \' else it becomes `formatting`

**Comment by kensoh** [comment]
Thanks for pointing out! I miss that. Do you have a way of handling putting a backtick in below string enclosed in backticks?

I don't think I found a way to escape in below case.

`some text`
