### ISSUE TITLE
Moving files from one folder to another, no error but files are not moved - try this

### ISSUE THREAD

**Issue by sheneeb** [kelaberetiv/TagUI#982]
Hi @kensoh ,
I am trying to move a batch file of files using cmd command using the below code tagui does not give me any error, but the files are not moved

```
run cmd /c dir c:\temp\new\ /b
file_list = run_result.split('\n')
echo `file_list.length`
// file length equals to 1 means there is no files inside the folder
if file_list.length equals to 1
    run cmd /c for /r c:\Temp\old\ %f in (*.whl) do move /y "%f" C:\Temp\new
echo `run_result`
```
and this is the output 

```
START - automation started - Mon Mar 22 2021 09:52:12 GMT+0400 (Arabian Standard Time)

run cmd /c dir c:\temp\new\ /b
1
run cmd /c for /r c:\Temp\old\ %f in (*.whl) do move /y "%f" C:\Temp\new
C:\tagui>move /y \"c:\Temp\old\pandas-1.2.3-cp37-cp37m-win_amd64.whl\" C:\Temp\new

FINISH - automation finished - 0.5s
```

, also appreciate if you can help with limiting the number of files to be moved to 50 files at a time, is that possible ?

**Comment by kensoh** [comment]
Hi @sheneeb, one way to ensure everything runs correctly without any issue due to quotation marks or other reason is you can put your DOS commands into a Windows batch file and name it with .bat or .cmd extension. Then from TagUI do the run step on that batch file. Alternatively, for very fine control you can consider using the `fs module` that is already part of TagUI. And write JavaScript code to read the directory using fs.list() and do many things with full control.

See more on the API here - https://phantomjs.org/api/fs

**Comment by sheneeb** [comment]
@kensoh 
thank you for that, i'll explore the fs library , mostly like i'll end up using pathlib to do this, i wanted to get hold of cmd commands as well.
