### ISSUE TITLE
SyntaxError: Expected token ')' - workflow calling invalid datatable field name

### ISSUE THREAD

**Issue by dhruthi-t** [kelaberetiv/TagUI#983]
Hi Ken

I am trying to automate a webpage with multiple dropdowns and checkboxes.

I am trying to use datatable as I need to create mutiple data but i am getting this error when i run it with my data table

SyntaxError: Expected token ')'
 phantomjs://code/LaunchingBrowser.tag.js:1691 in injectJs
  phantomjs://code/bootstrap.js:456

I have checked for the bracket closures.

Please find the attached tag file and datatable file for reference.

Could you please help me with this.

Thank you
[ParnterPage.txt](https://github.com/kelaberetiv/TagUI/files/6190266/ParnterPage.txt)
[TestData.xlsx](https://github.com/kelaberetiv/TagUI/files/6190274/TestData.xlsx)
[tagui_local.xlsx](https://github.com/kelaberetiv/TagUI/files/6190278/tagui_local.xlsx)

**Comment by kensoh** [comment]
Hi @dhruthi-t oh in your workflow file, you are making references `field url`, `New field url`, `Resource url`. However in your datatable, there is no such columns, there is only `fieldurl`, `Newfieldurl`, `Resourceurl`. You can change your workflow to call `fieldurl` (no space) or change your datatable to `field url` (with space) so that TagUI can find a match.

```
//**********************************Uploading the Field URL File************************************
type `Title` as `Title`
upload `FieldURLFileUpload` as `field url`
click `FieldURLFileUploadButton`
//**************************************************************************************************
wait 7
//**********************************Uploading the New Field URL File********************************
upload `NewFieldURLFileUpload` as `New field url`
click `NewFieldURLFileUploadButton`
//**************************************************************************************************
wait 7
//**********************************Updating the Value for Resource URL*****************************
type `ResourceURL` as `Resource url`
```

Normally in this situation TagUI will give an error missing variable, but the `field url` becomes invalid JavaScript code that is why it throws up this unknown error when the JavaScript compilation fail.

In addition, in your object repository, it is not necessary to have double quotation marks on the definition. This will not cause error, but just a tip that this is not needed. For example below, no need " before and after.

"input[id=edit-field-resource-type-indusrty-und-41]"

---

**PS - below additional notes for my team-mate**

@ruthtxh I solve this by enabling tagui_logging, then see which line in the generate .js file the error happens. Then by trial and error to isolate the workflow line that causes the error, I can see that it is invalid JavaScript code. For eg below, the `field url` variable makes the whole line invalid JS code.

```js
casper.then(function() {{techo('upload input[id="edit-field-field-url-und-0-upload"] as '+field url+'');
```

**Comment by kensoh** [comment]
Adding on @dhruthi-t you are doing advance usage of TagUI! 👏

**Comment by dhruthi-t** [comment]
Hi Ken,

I have tried to use the Object Identification without the  double quotes but it does not identify the object. I noticed that it happens specifically for checkbox.  Other object identification is working fine.

Also, I tried to modularize the code by adding the if condition in a sperate file and calling it as a part of the flow file but does not seem to be working.

> Adding on @dhruthi-t you are doing advance usage of TagUI! 👏 ---- Thank you.

**Comment by kensoh** [comment]
Hi @dhruthi-t oh for object repository, because it is a CSV file, if there are commas in the field, then double quotes are needed at the start and end for CSV standard to work. Maybe it is due to that. If this is not, let me know more or if there is some website I can replicate the issue to test.

For the condition and modular flow, there is a bug which is now fixed. Can you try if using the latest version of TagUI works for you? You can get it from the instructions here - https://github.com/kelaberetiv/TagUI/issues/961#issuecomment-795334166

**Comment by dhruthi-t** [comment]
Thanks Ken.. Will try the suggestion

**Comment by dhruthi-t** [comment]
Hi Ken,

In the workflow file 
//**********************************Selecting the value of Resource Type from Dropdown**************
echo `ResourceTypeRepo`
select `ResourceTypeRepo` as `resourceTypeValue`
//**************************************************************************************************
In the above block of code I am trying to reference `ResourceTypeRepo`  from Object repository and `resourceTypeValue` from DataTable csv.

But the css from object repo is not being identified.

could you please propose a solution for this?
[ParnterPage.txt](https://github.com/kelaberetiv/TagUI/files/6228611/ParnterPage.txt)

**Comment by dhruthi-t** [comment]
> Hi @dhruthi-t pls check - in your tagui_local file there is no `ResourceTypeRepo` but only `ResourceTypeDropDown`.

Hi Ken I had modified the object repo, had not attached the uploaded the recent one. 

But I have resolved that issue.

Thank you
