### ISSUE TITLE
Time taken for processing missing UI element - you can change default timeout 10s

### ISSUE THREAD

**Issue by NS-27** [kelaberetiv/TagUI#984]
Just a query. I am using the python package and created a function where I am looping through search terms and reading an xpath text (if available) with a try-except statement.

I noticed that if the intended xpath is available, TagUI quickly executes and moves on to the next command. However, it tends to get stuck for a few seconds processing and returning the error when the xpath cannot be found, before moving on to the next line of code.

While it is not an issue (other than time taken), I am just curious if this is something that is normal, or if I should be doing something else other than a try-except statement.

Thank you!

**Comment by kensoh** [comment]
Hi @NS-27 for RPA for Python, it's a personal project, normally you can raise the issue at below URL -

https://github.com/tebelorg/RPA-Python/issues

But your question is actually common to TagUI. It is a feature by design. There is a default timeout of 10 seconds. This is to let your RPA auto-wait for some UI element to appear before throwing error. If error is immediately shown when something is not found, then you will get a lot of errors from a UI element have not be loaded on the screen yet.

To cut down this timing less than 10 seconds, you can use `timeout` step in TagUI or `r.timeout()` in RPA for Python.

**Comment by NS-27** [comment]
Thank you Ken.
