### ISSUE TITLE
作者你好，不知道可不可以用汉语交流 (can discuss in Chinese?) - pending more info

### ISSUE THREAD

**Issue by GCwithH2O** [kelaberetiv/TagUI#985]
如题

**Comment by kensoh** [comment]
Hi @GCwithH2O thanks for creating issue! I can read Chinese, but I can write in English better. Is it ok I type in English?

**Comment by GCwithH2O** [comment]
> 如题



> Hi @GCwithH2O thanks for creating issue! I can read Chinese, but I can write in English better. Is it ok I type in English?

of course,i'll try my best  LoL
let me describe this issue later
thanks

**Comment by GCwithH2O** [comment]
​	

OS:windows 10

my two scripts:

1:

```
http://58.56.94.34:21880
type userCode as test
type password as 123456
click enter
wait 3
if exist('sidebar-mini')
    click //*[@id="panelbar"]/div[1]/div/i
click //*[@id="panelbar"]/div[2]/ul/li[1]/span/span[2]
click //*[@id="panelbar"]/div[2]/ul/li[1]/div[2]/ul/li[1]/span/span[2]
click //*[@id="panelbar"]/div[2]/ul/li[1]/div[2]/ul/li[1]/div[2]/ul/li[1]/span/span[2]
wait 5
frame iframe_0df0280e2f2b4a14831c6d8bfb8a263c
    read //*[@id="gblmstatus"]/tr[2]/td[2] to itemsPerSec
    js console.log(itemsPerSec)
```

2:

```
http://58.56.94.34:21880
type userCode as test
type password as 123456
click enter
wait 3
if exist('sidebar-mini')
    click //*[@id="panelbar"]/div[1]/div/i
click //*[@id="panelbar"]/div[2]/ul/li[1]/span/span[2]
click //*[@id="panelbar"]/div[2]/ul/li[1]/div[2]/ul/li[1]/span/span[2]
click //*[@id="panelbar"]/div[2]/ul/li[1]/div[2]/ul/li[1]/div[2]/ul/li[1]/span/span[2]
wait 5
frame //*[@id="iframe_0df0280e2f2b4a14831c6d8bfb8a263c"]
    read //*[@id="gblmstatus"]/tr[2]/td[2] to itemsPerSec
    js console.log(itemsPerSec)
```

so,this two scripts only has one diffence on line 12, in the 1 script,i use DOM and in the 2 script , i use XPath

the first try , i use the 1 script , and the command in CMD is : 

```
tagui tag.tag
```

everything is ok , and the log is :

```
C:\Users\gc\Desktop\tagui>tagui tag.tag

START - automation started - Fri Mar 26 2021 10:05:41 GMT+0800 (不重要的汉字乱码)
http://58.56.94.34:21880 - 不重要的汉字乱码

type userCode as test
type password as 123456
click enter
wait 3
click //*[@id="panelbar"]/div[1]/div/i
click //*[@id="panelbar"]/div[2]/ul/li[1]/span/span[2]
click //*[@id="panelbar"]/div[2]/ul/li[1]/div[2]/ul/li[1]/span/span[2]
click //*[@id="panelbar"]/div[2]/ul/li[1]/div[2]/ul/li[1]/div[2]/ul/li[1]/span/span[2]
wait 5
frame iframe_0df0280e2f2b4a14831c6d8bfb8a263c
read //*[@id="gblmstatus"]/tr[2]/td[2] to itemsPerSec
25.91

http://58.56.94.34:21880/sys/index - 不重要的汉字乱码
FINISH - automation finished - 24.0s
```



the second try , i use the 2 script , and the command in CMD is : 

```
tagui tag.tag -n
```

something is wrong , and the log is :

```
C:\Users\gc\Desktop\tagui>tagui tag.tag -n

START - automation started - Fri Mar 26 2021 10:08:26 GMT+0800 (不重要的汉字乱码)
http://58.56.94.34:21880 - 不重要的汉字乱码

type userCode as test
type password as 123456
click enter
wait 3
click //*[@id="panelbar"]/div[2]/ul/li[1]/span/span[2]
ERROR - cannot find //*[@id="panelbar"]/div[2]/ul/li[1]/span/span[2]
```

it seems that the program can not find the frame whose id is iframe_0df0280e2f2b4a14831c6d8bfb8a263c



the third try , i run the 1 scrip in CentOS Linux release 7.9.2009 , a mini OS without desktop , and the command in shell terminal is :

```
 tagui tagui_test.tag -n
```

something is wrong two , and the log is :

```
[root@localhost scripts]# tagui tagui_test.tag -n

START - automation started - Fri Mar 26 2021 10:12:56 GMT+0800 (CST)
http://58.56.94.34:21880 - 智能运维平台

type userCode as test
type password as 123456
click enter
wait 3
click //*[@id="panelbar"]/div[1]/div/i
ERROR - cannot find //*[@id="panelbar"]/div[1]/div/i
```

i did not try the 2 script in CentOS



where am i wrong ?



thanks

**Comment by kensoh** [comment]
Hi @GCwithH2O oh I mean you can type in Chinese I can understand, but I type in English so I can explain better. Chinese for me I can read no problem!

Oh for the frame step, the input is the name of the frame for -nobrowser (-n) mode. For Chrome's it can take name or id of frame. So your example 1 works because it is a name of the frame.

Example 2 fails because the input has to be a name, not XPath. So when the frame cannot be found, robot cannot click the element inside the frame.

For example 3, it could be the website detects the OS is CentOS and renders the webpage in a different way from when you run on your Windows computer. You can insert a `live` step like below, then program will pause for you to debug. You can do things like `snap page` to take a screenshot, or `save page to web.html` to see the HTML code and see why the thing you want to click on is missing.

```
http://58.56.94.34:21880
type userCode as test
type password as 123456
click enter
wait 3
live
click //*[@id="panelbar"]/div[1]/div/i
```

**Comment by kensoh** [comment]
(copying my team-mate @ruthtxh for info)

**Comment by GCwithH2O** [comment]
我用命令tagui tag.tag -n 去执行脚本1 的时候，控制台会提示这些：
`
C:\Users\gc\Desktop\tagui>tagui tag.tag -n

START - automation started - Fri Mar 26 2021 11:17:49 GMT+0800 (涓浗鏍囧噯鏃堕棿)
http://58.56.94.34:21880 - 鏅鸿兘杩愮淮骞冲彴

type userCode as test
type password as 123456
click enter
wait 3
click //*[@id="panelbar"]/div[2]/ul/li[1]/span/span[2]
click //*[@id="panelbar"]/div[2]/ul/li[1]/div[2]/ul/li[1]/span/span[2]
click //*[@id="panelbar"]/div[2]/ul/li[1]/div[2]/ul/li[1]/div[2]/ul/li[1]/span/span[2]
wait 5
frame iframe_0df0280e2f2b4a14831c6d8bfb8a263c
ERROR - no element matching selector found: xpath selector: (//frame|//iframe)[@name="iframe_0df0280e2f2b4a14831c6d8bfb8a263c"]

`
从log看程序好像是按照frame的name属性找的，但实际上这个"iframe_0df0280e2f2b4a14831c6d8bfb8a263c"是frame的id

**Comment by GCwithH2O** [comment]
我又尝试使用命令tagui tag.tag -n执行了脚本1，结果在click enter这一步就已经出了问题，tagui并没有找到这个enter
但是奇怪的是，昨天我在尝试的时候tagui是能找到这个enter的，这是为什么啊？

**Comment by kensoh** [comment]
Oh when you use -n it means not using Chrome and only using the PhantomJS invisible browser. For that mode, the search for frame is only by frame name. You can try waiting for longer time, instead of wait 5 you do wait 30, before the frame step. Maybe the webpage taking long time to load so sometimes the frame can be found sometimes cannot.

For the click enter step, it may also be website taking long time to load. You can try changing the default timeout from 10 seconds to longer to see if that can help. For example below will make the timeout value 30 seconds. If the enter button cannot be found after 30 seconds then there will be error.

```
timeout  30
```

Lastly, another tip is you can try using headless Chrome with -h or -headless option. Chrome in most cases will be able to work better with modern websites compared to PhantomJS headless browser.

**Comment by GCwithH2O** [comment]
@kensoh 
我尝试加上-headless选项，结果在windows10下是正常的，能找到那个frame了，
但是在centos中，
![image](https://user-images.githubusercontent.com/37324999/112584335-a1438d80-8e32-11eb-8c75-d3435e504c7c.png)
程序卡在这一步不动了，也没有提示产生

**Comment by GCwithH2O** [comment]
我重新在虚拟机中安装了一个带有桌面的centos7系统，运行tagui脚本时发现无法自动打开chrome浏览器
![image](https://user-images.githubusercontent.com/37324999/112598897-2dad7a80-8e4a-11eb-86be-cfc06dcb9691.png)
程序卡在这一步不动了，也没有提示产生

**Comment by kensoh** [comment]
For headless Chrome mode, use only -h, no use -n. `tagui abc.tag -h`

Also, make sure you have installed Chrome already on your CentOS. You can double check this by typing `google-chrome` command from your terminal window.

If the command to run Chrome is some other command, you can change it in tagui/src/tagui file at the start of that file.

Lastly, which version is your CentOS? I know version v6 cannot run Chrome anymore. v7 not sure. v8 should be ok.

**Comment by GCwithH2O** [comment]
> For headless Chrome mode, use only -h, no use -n. `tagui abc.tag -h`
> 
> Also, make sure you have installed Chrome already on your CentOS. You can double check this by typing `google-chrome` command from your terminal window.
> 
> If the command to run Chrome is some other command, you can change it in tagui/src/tagui file at the start of that file.
> 
> Lastly, which version is your CentOS? I know version v6 cannot run Chrome anymore. v7 not sure. v8 should be ok.


搞定了！
因为CentOS 7下root用户使用```google-chrome```必须加上 --no-sandbox参数，所以导致无法运行tagui，即便在```tagui/src/tagui```里加上--no-sandbox也不行。
解决办法就是不要使用root用户运行，切换成普通用户执行```tagui test.tag -h```，一切正常了

**Comment by kensoh** [comment]
Thank you @GCwithH2O, hope you enjoy using the tool! :)

For your friends who are familiar with Python, they can also try the Python version with pip install rpa -
https://github.com/tebelorg/RPA-Python
