### ISSUE TITLE
Fail to get HTML source inside popup step - limitation with attaching to popup target

### ISSUE THREAD

**Issue by queyintik** [kelaberetiv/TagUI#988]
I'm trying to get the HTML source of a page inside popup steps, but it is not successful. For example, I have two files "without_popup.tag" and "with_popup.tag" with content as follows:

without_popup.tag:
```
http://tebel.org/gist/about_tebel
read page to html
echo `html`
```

with_popup.tag:
```
http://tebel.org
click ABOUT
wait

popup about_tebel
 read page to html
 echo `html`
```

It turns out that

- `tagui without_popup.tag -h` can display the HTML source, but
- `tagui with_popup.tag -h` shows nothing.

Not sure is there any workaround to get the HTML source inside popup? Thanks for help in advance.

**Comment by kensoh** [comment]
Hi @queyintik, the issue is due to complication in JSON parsing for retrieving the HTML source in the popup tab. The contents will be parsed and then stringified on the websocket level before being consumed by TagUI, in order to access data on a separate tab through attaching and detaching from target tab. But this leads to the following error.

```
jSON Parse error: Expected '}'
```

Can you tell me more about your use case? A workaround is get the URL of the popup window, and access it directly. Here's another issue with example on visiting URL dynamically (https://github.com/kelaberetiv/TagUI/issues/936) and a related issue on creating a macro visit (https://github.com/kelaberetiv/TagUI/issues/960).

If you are able to access the popup page directly, then `read page to html` would work.

**Comment by queyintik** [comment]
Got it. Thanks for the explanation.
