### ISSUE TITLE
TagUI from docker container error launching Chrome - pending root cause details

### ISSUE THREAD

**Issue by agustin-tecso** [kelaberetiv/TagUI#992]
Hi! I'm trying to mount a dockerized enviroment for a possible use in production of Tagui. In my local linux machine everything works fine, but in the container I'm stuck with an error of google-chrome. When I excecute tagui with the command:

**$ tagui flows/samples/1_google.tag -h**

I got this error:

/usr/local/bin/tagui: line 329: 107643 Illegal instruction     (core dumped) $chrome_command --user-data-dir="$TAGUI_DIR/chrome/tagui_user_profile" $chrome_switches $window_size $headless_switch > /dev/null 2>&1

I dont understand the cause of that error.

This is my DockerFile:
[Dockerfile.txt](https://github.com/kelaberetiv/TagUI/files/6222962/Dockerfile.txt)

Thanks for help in advance.

**Comment by kensoh** [comment]
Hi @agustin-tecso ! Can you tell me if you are running this as normal user or root user? Can you try editing tagui/src/tagui file, change the first line to `#!/usr/bin/env bash -x` by adding `-x` at the end. Then you run again. This will let you see exactly the command that is run that triggers the error.

For example on my macOS, it will be the following line -
```
+ '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' '--user-data-dir=/Users/kensoh/Cloud Drive/Marketing/Website/api/tagui/src/chrome/tagui_user_profile' --remote-debugging-port=9222 about:blank --window-size=1366,842
```
\
With this info, you can copy that line and run it manually to know what exactly are the parameters that cause the error when launching Chrome in the docker image. Let me know how it goes! Both me and my team-mate we don't use Docker so we can't test directly and immediately from our side, but if Docker usage is common and we have more demand, we may have to do that in order to replicate.

**Comment by kensoh** [comment]
Oh I see, this is totally new to me this solution, because I have no experience with Docker. Thanks for sharing back!!

**Comment by kensoh** [comment]
I'll close the issue now but feel free to ping back if anything.

**Comment by EvanYiLi** [comment]
> Hi! Thanks for the quick reply @kensoh! I was running tagui with non-root user, because chrome doesn't allow you to excecute whitout UI and root privileges. I was able to solve the problem. It was an issue with chrome and docker container. I had to run the container with **--cap-add** option in docker and export enviroment variable before execute tagui **export OPENSSL_CONF=/etc/ssl**
> 
> Thanks alot!

Hello tecso, I also encountered this problem. Can you tell me how you solved it? Thanks alot!

**Comment by kensoh** [comment]
Tagging @agustin-tecso
